force-app/main/default/objects/Co_Op__c/Co_Op__c.object-meta.xml
<CustomObject>
    <label>Co Op</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Ops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Op__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Co-Ops</relationshipLabel>
    <relationshipName>Co_Ops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Op__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Co-Ops</relationshipLabel>
    <relationshipName>Co_Ops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Op__c/fields/Interact_Tools_Email__c.field-meta.xml
<CustomField>
    <fullName>Interact_Tools_Email__c</fullName>
    <description>To store Email address of Interact_Tools_Email.</description>
    <label>Interact Tools Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/Co_Op_TriggerHandler.cls
public class Co_Op_TriggerHandler {

    public static void isBeforeInsert(List<Co_Op__c> newCoOps){
        if(Trigger.isBefore && Trigger.isInsert){
        User u = [SELECT Id, Name, ContactId, AccountId FROM User WHERE Id =: UserInfo.getUserId()];
        for (Co_Op__c  coOp : newCoOps) {
            if (coOp.Account__c == null && u.AccountId != null)
                coOp.Account__c  = u.AccountId;
            if (coOp.Contact__c == null && u.ContactId != null)
                coOp.Contact__c = u.ContactId;
            coOp.Interact_Tools_Email__c = 'Partner.ResourceCenter@ncr.com';  // this line of code written in populateInteractToolEmailTrigger
        }
    }
    }
}