force-app/main/default/objects/Favorite_Bundle__c/Favorite_Bundle__c.object-meta.xml
<CustomObject>
    <label>Favorite Bundle</label>
    <nameField>
        <label>Favorite Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Favorite Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem/fields/Maintenance_Type__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Type__c</fullName>
    <label>Maintenance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Connected HWM</fullName>
            </value>
            <value>
                <fullName>Non-Connected HWM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Opportunity_Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item_Type__c</fullName>
    <label>Opportunity Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Qty_Type__c.field-meta.xml
<CustomField>
    <fullName>Qty_Type__c</fullName>
    <label>Qty Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATMs</fullName>
                <label>ATMs/Units</label>
            </value>
            <value>
                <fullName>Cards</fullName>
            </value>
            <value>
                <fullName>Deposit Transactions</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>Total Transactions</fullName>
            </value>
            <value>
                <fullName>Withdrawals Transactions</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Renewable_Products__c/Renewable_Products__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Renewable Products</label>
</CustomObject>

force-app/main/default/objects/Renewable_Products__c/fields/Product_Revenue_Types__c.field-meta.xml
<CustomField>
    <fullName>Product_Revenue_Types__c</fullName>
    <label>Product Revenue Types</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InactiveLeadAndContactEmail</label>
</CustomObject>

force-app/main/default/objects/User_Favorite_Products__c/User_Favorite_Products__c.object-meta.xml
<CustomObject>
    <label>User Favorite Products</label>
    <nameField>
        <label>Favourite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Favorite Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Favorite_Products__c/fields/Favorite_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Favorite_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Favorite Bundle</label>
    <referenceTo>Favorite_Bundle__c</referenceTo>
    <relationshipLabel>User Favorite Products</relationshipLabel>
    <relationshipName>User_Favorite_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Favorite_Products__c/fields/IsSubscription__c.field-meta.xml
<CustomField>
    <fullName>IsSubscription__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSubscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Favorite_Products__c/fields/LineItemType__c.field-meta.xml
<CustomField>
    <fullName>LineItemType__c</fullName>
    <label>LineItemType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Favorite_Products__c/fields/Maintenance_Type__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Type__c</fullName>
    <label>Maintenance Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Favorite_Products__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>User Favorite Products</relationshipLabel>
    <relationshipName>User_Favorite_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Favorite_Products__c/fields/Qty_Type__c.field-meta.xml
<CustomField>
    <fullName>Qty_Type__c</fullName>
    <label>Qty Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Favorite_Products__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Favorite_Products_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddProductToBundleController.cls
/*
################################################################################################## 
Apex Class Name    : FavoriteController
Modification Log:
Date             Author               Modification
01-20-2022       Puneet Bhatia        EBA_SF-1646 - Added changes for Connected HWM in Salesforce
################################################################################################
*/
public class AddProductToBundleController {
    
    @AuraEnabled
    Public Static List<User_Favorite_Products__c> AddProductToBundleMethod(String PrdList,String BndlList)
    {
        
        List<User_Favorite_Products__c> ListOfBundle=new List<User_Favorite_Products__c>();
         //system.debug(':::::::::::'+PrdList);
         //system.debug(':":":":":":":'+BndlList);
        try{
            List<BundleWrapper> Bundlelst_JsonParse = (List<BundleWrapper>)Json.deserialize(BndlList,List<BundleWrapper>.class);
            List<ProductWrapper> Productlst_JsonParse = (List<ProductWrapper>)Json.deserialize(PrdList,List<ProductWrapper>.class);
            
            for(BundleWrapper   obj1 : Bundlelst_JsonParse){
                if(obj1.Status){ 
                    for(ProductWrapper obj2 : Productlst_JsonParse){
                        if(obj2.Status){
                            User_Favorite_Products__c UserFavProductObj = new User_Favorite_Products__c();
                            UserFavProductObj.Products__c=obj2.Id;
                            //system.debug('>>>>>>'+obj2.Status);
                            UserFavProductObj.Favorite_Bundle__c=obj1.Id;
                           //UserFavProductObj.User__c=UserInfo.getUserId();
                            if(obj2.isSubricption != null){
                                 UserFavProductObj.IsSubscription__c=obj2.isSubricption;
                            }
                            if(String.isNotBlank(obj2.LineItemType)){
                                UserFavProductObj.LineItemType__c=obj2.LineItemType;
                            }
                            if(String.isNotBlank(obj2.HWMMntcType)){
                           		UserFavProductObj.Maintenance_Type__c=obj2.HWMMntcType;
                            }
                            if(String.isNotBlank(obj2.qtyType)){
                           		UserFavProductObj.Qty_Type__c=obj2.qtyType;
                            }
                            
                           
                           ListOfBundle.add(UserFavProductObj);
                        }
                         
                	}
                }   
                
            }
           
           Insert ListOfBundle;
           
           
        }
           
        
        
        catch(Exception e){
            system.debug('>>>>'+e);
        }
        return ListOfBundle;
    }
    public class BundleWrapper {
        public String Id;
        public Boolean Status;
    }
    
    public class ProductWrapper{
        public String Id;
        public Boolean Status;
        Public Boolean isSubricption;
        pUBLIC String LineItemType;
        public String HWMMntcType;
        public String qtyType;
    }
    
    @AuraEnabled
    Public Static String UpdateBundleName(String BundleIdForUpdate ,String UpdatedBundleName){
        //system.debug('BundleIdForUpdate'+BundleIdForUpdate);
        //system.debug('BundleIdForUpdate'+UpdatedBundleName);
        String UpdateStatus='';
        try{
            Favorite_Bundle__c FavObj =  new Favorite_Bundle__c();
            FavObj.id=BundleIdForUpdate;
            FavObj.Name= UpdatedBundleName;
            Update FavObj;
            UpdateStatus = UpdateStatus+'Success' + FavObj.Name;
        }
        catch (Exception e) {

            UpdateStatus=UpdateStatus+e;
        }
        return UpdateStatus;
    }
    
    @AuraEnabled
    public static ProductInfoWrapper getRnwableProds(){     
        Set<String> SubsProdSet= new Set<String>(); 
        Set<String> SubsRevenueSet= new Set<String>();
        Set<String> RnwablRevnSet= new Set<String>();
        Map<String, String> lineItemTypeOpts = new Map<String, String>();
        
        ProductInfoWrapper prodInfoWrapObj= new ProductInfoWrapper();
        List<Renewable_Products__c> renewablePrdLst = Renewable_Products__c.getAll().values();        
        
        if (renewablePrdLst != NULL && renewablePrdLst.size() > 0) {
            if (String.isNotBlank(renewablePrdLst[0].Product_Revenue_Types__c)) { 
                RnwablRevnSet.addAll(renewablePrdLst[0].Product_Revenue_Types__c.split(','));
                prodInfoWrapObj.RnwablRevTypes = RnwablRevnSet;
            }
        }
        
        for(Schema.PicklistEntry p : OpportunityLineItem.Opportunity_Line_Item_Type__c.getDescribe().getPicklistValues()) {
            lineItemTypeOpts.put(p.getValue(), p.getLabel());
        } 
        prodInfoWrapObj.OppLineItemTypes = lineItemTypeOpts;
        
        return prodInfoWrapObj;
    }

    public class ProductInfoWrapper { 
        @AuraEnabled public Set<String> RnwablRevTypes{get;set;}
        @AuraEnabled public Map<String, String> OppLineItemTypes{get;set;}
    }
}