force-app/main/default/objects/Non_ERP_Order__c/Non_ERP_Order__c.object-meta.xml
<CustomObject>
    <label>Non ERP Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Non ERP Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non ERP Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_ERP_Order__c/fields/Amount_in_Local__c.field-meta.xml
<CustomField>
    <fullName>Amount_in_Local__c</fullName>
    <label>Amount (in Local )</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/Customer_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Country_Code__c</fullName>
    <label>Customer Country Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/Enterprise_ID__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ID__c</fullName>
    <label>Enterprise ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/HW_Amount__c.field-meta.xml
<CustomField>
    <fullName>HW_Amount__c</fullName>
    <label>HW Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <label>Master Customer Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/PS_Amount__c.field-meta.xml
<CustomField>
    <fullName>PS_Amount__c</fullName>
    <label>PS Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/Salesperson_Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Global_ID__c</fullName>
    <label>Salesperson Global ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/SW_Amount__c.field-meta.xml
<CustomField>
    <fullName>SW_Amount__c</fullName>
    <label>SW Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/Total_Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Order_Amount__c</fullName>
    <label>Total Order Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/Transaction_Source__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Source__c</fullName>
    <label>Transaction Source</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Non_ERP_Order__c/fields/TS_Amount__c.field-meta.xml
<CustomField>
    <fullName>TS_Amount__c</fullName>
    <label>TS Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NonERPTriggerTestClass.cls
@isTest 
private class NonERPTriggerTestClass {
    static testMethod void Method1() {
        Non_ERP_Order__c Obj = new Non_ERP_Order__c();
        Obj.Amount_in_Local__c='1200120';
        Obj.Currency__c='USD';
        Obj.Customer_Country_Code__c   ='US';
        Obj.Customer_Name__c='TestCustomer';
        Obj.Date__c=System.Today();
        Obj.Enterprise_ID__c='@Test';
        Obj.HW_Amount__c='123121';
        Obj.Master_Customer_Number__c='Test';
        Obj.Order_Number__c='123121';
        Obj.PS_Amount__c='1000';
        Obj.Salesperson_Global_ID__c='35252345fDE';
        Obj.SW_Amount__c='100';
        Obj.Total_Order_Amount__c='10000';
        Obj.Transaction_Source__c='Manual';
        Obj.TS_Amount__c='100';
        Insert Obj;
        Obj.Currency__c='USD';
        update Obj;
        try{
        System.debug('>>>>>>>>>>>>>>>>>:::');
         
         Non_ERP_Order__c Obj1 = new Non_ERP_Order__c();
         Obj1.Transaction_Source__c='Manual';
         Insert Obj1; 
         NonERPBlankFieldException  test = new NonERPBlankFieldException('test');
            Non_ERP_Order__c nonerpObj = [select id from Non_ERP_Order__c where id=:Obj1.id];
            System.assert(nonerpObj.id!=null);
        }
        
        Catch(Exception e){
            System.debug('Error: '+e.getMessage());
            System.assert(e.getMessage()!=null);
        }
        
         
        
    }
}