force-app/main/default/objects/Daily_Non_ERP_Order__c/Daily_Non_ERP_Order__c.object-meta.xml
<CustomObject>
    <label>Daily Non ERP Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Daily Non ERP Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Non ERP Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Customer_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Country_Code__c</fullName>
    <label>Customer Country Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Input_Currency__c.field-meta.xml
<CustomField>
    <fullName>Input_Currency__c</fullName>
    <label>Input Currency</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Input_HW_Amount__c.field-meta.xml
<CustomField>
    <fullName>Input_HW_Amount__c</fullName>
    <label>Input HW Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Input_PS_Amount__c.field-meta.xml
<CustomField>
    <fullName>Input_PS_Amount__c</fullName>
    <label>Input PS Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Input_Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Input_Sales_Org_Code__c</fullName>
    <label>Input Sales Org Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Input_SW_Amount__c.field-meta.xml
<CustomField>
    <fullName>Input_SW_Amount__c</fullName>
    <label>Input SW Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Input_Total_Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Input_Total_Order_Amount__c</fullName>
    <label>Input Total Order Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Input_TS_Amount__c.field-meta.xml
<CustomField>
    <fullName>Input_TS_Amount__c</fullName>
    <label>Input TS Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <label>Master Customer Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Salesperson_Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Global_ID__c</fullName>
    <label>Salesperson Global ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Salesperson_Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Quicklook_ID__c</fullName>
    <label>Salesperson Quicklook ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Non_ERP_Order__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DailyNonERPTriggerTestClass.cls
@isTest 
private class DailyNonERPTriggerTestClass {
    static testMethod void Method1() {
        Daily_Non_ERP_Order__c Obj = new Daily_Non_ERP_Order__c();
        obj.Order_Date__c = Date.today();
        Obj.Order_Number__c='123121';
        Obj.Enterprise_ID__c='@Test';
        Obj.Master_Customer_Number__c='Test';
        Obj.Customer_Country_Code__c   ='TestCountryCode';
        Obj.Customer_Name__c='TestCustomer';
        Obj.Input_Sales_Org_Code__c = '1234';
        Obj.Input_Total_Order_Amount__c ='1200120';
        Obj.Input_Currency__c  ='USD';
        Obj.Input_HW_Amount__c ='1200120';
        Obj.Input_SW_Amount__c = '1200120';
        Obj.Input_PS_Amount__c ='1200120';
        Obj.Input_TS_Amount__c ='1200120';   

        Obj.Salesperson_Quicklook_ID__c='3525234';
        Obj.Salesperson_Global_ID__c='35252345f';       
        Obj.Source_System__c='Synergy';
       
        Insert Obj;
        Obj.Input_Currency__c  ='USD';
        update Obj;
       
		Daily_Non_ERP_Order__c Obj1 = [Select id, Input_Currency__c from Daily_Non_ERP_Order__c where Input_Currency__c = 'USD'];
        System.assert(Obj1.id!=null);
    }
}