force-app/main/default/objects/Case/fields/Campaign_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Status__c</fullName>
    <label>Campaign Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <label>Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Cross sell</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>NCR Channel Partner</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_User_Company__c.field-meta.xml
<CustomField>
    <fullName>Chat_User_Company__c</fullName>
    <label>Company</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_User_Country__c.field-meta.xml
<CustomField>
    <fullName>Chat_User_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ALAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BOUVET ISLAND</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_User_Email__c.field-meta.xml
<CustomField>
    <fullName>Chat_User_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_User_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Chat_User_First_Name__c</fullName>
    <label>First Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_User_Industry__c.field-meta.xml
<CustomField>
    <fullName>Chat_User_Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Telecom</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Payments &amp; Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_User_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Chat_User_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_User_Phone__c.field-meta.xml
<CustomField>
    <fullName>Chat_User_Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_User_Source__c.field-meta.xml
<CustomField>
    <fullName>Chat_User_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Chat_User_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Agent/Distributor</fullName>
            </value>
            <value>
                <fullName>AllpointNetwork.com</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>ATMNetwork.com</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Cardtronics.com</fullName>
            </value>
            <value>
                <fullName>Cashzone</fullName>
            </value>
            <value>
                <fullName>CEC Visit</fullName>
            </value>
            <value>
                <fullName>Customer Referral</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Display</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>NCR Rep</fullName>
            </value>
            <value>
                <fullName>Operation Teamwork</fullName>
            </value>
            <value>
                <fullName>Organic Search/SEO</fullName>
            </value>
            <value>
                <fullName>Paid Search</fullName>
            </value>
            <value>
                <fullName>Paid Social</fullName>
            </value>
            <value>
                <fullName>Phone Inquiry</fullName>
            </value>
            <value>
                <fullName>PPC</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>Programmatic</fullName>
            </value>
            <value>
                <fullName>Publication</fullName>
            </value>
            <value>
                <fullName>Purchased List</fullName>
            </value>
            <value>
                <fullName>Referral Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_User_Type__c.field-meta.xml
<CustomField>
    <fullName>Chat_User_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Forms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Response_Time__c.field-meta.xml
<CustomField>
    <fullName>Customer_Response_Time__c</fullName>
    <label>Customer Response Time (Hours:Min:Sec)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DRT_Escalated_To__c.field-meta.xml
<CustomField>
    <fullName>DRT_Escalated_To__c</fullName>
    <label>Escalated To(Email)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Staff_Response_Time__c.field-meta.xml
<CustomField>
    <fullName>Staff_Response_Time__c</fullName>
    <label>Staff Response Time (Hours:Minutes)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Industry__c.field-meta.xml
<CustomField>
    <fullName>Sub_Industry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Chat_User_Industry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>ATM Deployers</fullName>
            </value>
            <value>
                <fullName>Central Banks, National Institutions &amp; Clearing Houses</fullName>
            </value>
            <value>
                <fullName>Processors, Acquirers &amp; Merchant Gateways</fullName>
            </value>
            <value>
                <fullName>Networks</fullName>
            </value>
            <value>
                <fullName>Cash in Transit</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>Cinema &amp; Theatres</fullName>
            </value>
            <value>
                <fullName>Stadium &amp; Venues</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
            </value>
            <value>
                <fullName>Mass Merchants</fullName>
            </value>
            <value>
                <fullName>Drug Stores</fullName>
            </value>
            <value>
                <fullName>Grocery</fullName>
            </value>
            <value>
                <fullName>Wholesale/Supercenters</fullName>
            </value>
            <value>
                <fullName>Petroleum Convenience Retail (PCR)</fullName>
            </value>
            <value>
                <fullName>Department &amp; Specialty Retail (DSR)</fullName>
            </value>
            <value>
                <fullName>Wholesale Distribution</fullName>
            </value>
            <value>
                <fullName>Telecom Providers</fullName>
            </value>
            <value>
                <fullName>Technology Providers</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Digital Banking</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Branch Transformation</fullName>
            </value>
            <value>
                <fullName>Transaction &amp; Channel Platforms</fullName>
            </value>
            <value>
                <fullName>ATMs &amp; Self-Service</fullName>
            </value>
            <value>
                <fullName>Digital Connected Services</fullName>
            </value>
            <value>
                <fullName>Professional Services for Banks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/What_can_NCR_help_you_with_today__c.field-meta.xml
<CustomField>
    <fullName>What_can_NCR_help_you_with_today__c</fullName>
    <label>What can NCR help you with today?</label>
    <length>120000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Years_In_Business__c.field-meta.xml
<CustomField>
    <fullName>Years_In_Business__c</fullName>
    <label>Years In Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under 1 Year</fullName>
            </value>
            <value>
                <fullName>1 Year - 2 Year</fullName>
            </value>
            <value>
                <fullName>2 year - 5 Year</fullName>
            </value>
            <value>
                <fullName>5 Year - 10 Year</fullName>
            </value>
            <value>
                <fullName>10 Year +</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarketoTestClass.cls
@isTest
public class MarketoTestClass {
	@isTest
    public static void UnitTest(){
        Id CaseRecordTypeId = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('Marketing Digital Response Team').getRecordTypeId();                       
	 Case caseObj = new Case();
         ExistingLeadContactHelper.isfirstMarketo=true;
        caseObj.RecordTypeId = CaseRecordTypeId;
        List<Case> caseList = new List<Case>();
        caseObj.DRT_Escalated_To__c ='test@test.com';
        caseObj.Chat_User_Company__c='Test';
        caseObj.Chat_User_Country__c='Test';
        caseObj.Chat_User_Email__c ='Test@test11.com';
        caseObj.Chat_User_First_Name__c ='Test';                            
        // caseObj.Chat_User_Industry__c='Test';
        caseObj.Chat_User_Last_Name__c = 'Test';
        caseObj.Chat_User_Source__c = 'Test';
        caseObj.Chat_User_Type__c ='Test';
        caseObj.Origin ='Forms';
        // caseObj.Owner.Name ='Test';
        caseObj.Agent_Notes__c = 'Test';
        caseObj.Business_Function__c ='Test';
        caseObj.Campaign_Code__c ='Test';
        caseObj.Campaign_Name__c ='Test';
        caseObj.Campaign_Status__c ='Test';
        caseObj.Campaign_Type__c ='Test';
        caseObj.City__c ='Test';
        //caseObj.RecordTypeId =,
        caseObj.Customer_Response_Time__c = '1 Days: 1 Hours: 12Minutes';
        caseObj.Staff_Response_Time__c = '0 Days: 1 Hours: 12Minutes';
        caseObj.Zip_Or_Postal_Code__c ='test';
        caseObj.State_Province__c = 'Test';
        caseObj.Title__c = 'Test';
        caseObj.Sub_Industry__c = 'Test';
        caseObj.Chat_User_Phone__c = 'Test';
        caseObj.Position__c = 'Test';
        //  caseObj.Number_of_Locations__c = 'Test';
        // caseObj.Years_In_Business__c = 'Test';
        // caseObj.Timing__c = 'Test';
        //  caseObj.Company_Annual_Sales__c = 'Test';
        // caseObj.Number_of_Employees__c = 'Test';
        caseObj.Subject ='Test'; 
        caseObj.Description='Test';
        caseObj.Status='Test';
        caseObj.Comments__c ='Test';
        caseObj.What_can_NCR_help_you_with_today__c='Test';
        caseList.add(caseObj);
        insert caseList;
        system.assert(caseList.size()>0);
        ExistingLeadContactHelper.leadAndContactWithEmail(caseList);
        

    }	
}