force-app/main/default/objects/Idea/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Counter</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Idea/fields/Di_Idea_Product_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Di_Idea_Product_Manager_Name__c</fullName>
    <label>Product Manager Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aaron Oplinger</fullName>
            </value>
            <value>
                <fullName>Alysann Fackler</fullName>
            </value>
            <value>
                <fullName>Aparna Sheth</fullName>
            </value>
            <value>
                <fullName>Barbara Hon</fullName>
            </value>
            <value>
                <fullName>Behrouz Naiem</fullName>
            </value>
            <value>
                <fullName>Bo Bedingfield</fullName>
            </value>
            <value>
                <fullName>Braxton Caswell</fullName>
            </value>
            <value>
                <fullName>Brett Conoly</fullName>
            </value>
            <value>
                <fullName>Brooke Everett</fullName>
            </value>
            <value>
                <fullName>Bryan Link</fullName>
            </value>
            <value>
                <fullName>Calvin Grimes</fullName>
            </value>
            <value>
                <fullName>Carlos Camacho</fullName>
            </value>
            <value>
                <fullName>Chan Glazman</fullName>
            </value>
            <value>
                <fullName>Chris Coussens</fullName>
            </value>
            <value>
                <fullName>Christina Johnson</fullName>
            </value>
            <value>
                <fullName>Christopher Hoffmann</fullName>
            </value>
            <value>
                <fullName>Clay Gross</fullName>
            </value>
            <value>
                <fullName>Craig Heath</fullName>
            </value>
            <value>
                <fullName>Dustin Binns</fullName>
            </value>
            <value>
                <fullName>Erica Pilon</fullName>
            </value>
            <value>
                <fullName>Ethan Cunningham</fullName>
            </value>
            <value>
                <fullName>Heidi Leo</fullName>
            </value>
            <value>
                <fullName>Jay Quint</fullName>
            </value>
            <value>
                <fullName>Jennifer Smay</fullName>
            </value>
            <value>
                <fullName>Jill Capicchioni</fullName>
            </value>
            <value>
                <fullName>Jim Allen</fullName>
            </value>
            <value>
                <fullName>John Doster</fullName>
            </value>
            <value>
                <fullName>Judy Shieh</fullName>
            </value>
            <value>
                <fullName>Kyle King</fullName>
            </value>
            <value>
                <fullName>Lauren Westberg</fullName>
            </value>
            <value>
                <fullName>Lindsey Speranza</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NCR_IdeaCommentCountTest.cls
@isTest(seealldata=true)
public class NCR_IdeaCommentCountTest{

    static testmethod void test() {
        Id communityid;
        user u;
        try{
        communityid = [select id from Community where Name='IdeaExchange' limit 1].id;
        u = [select id from user where name='Ian Abramsky'limit 1];
        }
        catch(exception e){
            System.debug('Error: '+e.getMessage());
        }
        
        Idea i = new Idea();
        ideacomment ic=new ideacomment();
        
        system.runas(u){        
        
        i.title='test';
        i.body='test';
        i.communityid=communityid;
        i.Di_Idea_Product_Manager_Name__c='Lindsey Speranza';
        i.counter__c=2;
        insert i;
       
        
        ic.CommentBody='Test';
        ic.ideaid=i.id;
        insert ic;
        }
        
        
        idea idea=[select id,counter__c,Di_Idea_Product_Manager_Name__c from idea where id=:i.id limit 1];
                        
        Test.startTest();
        system.assertequals(idea.counter__c,2);
        Test.stopTest();
        
        
        delete ic;
        
      
   }
}