force-app/main/default/objects/All_profie_list_config__c/All_profie_list_config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to exclude profiles from QuBy_OpportunityTrigger_BFR trigger</description>
    <label>All profile list config</label>
</CustomObject>

force-app/main/default/objects/All_profie_list_config__c/fields/Profile_id__c.field-meta.xml
<CustomField>
    <fullName>Profile_id__c</fullName>
    <label>Profile id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/All_profie_list_config__c/fields/QuBy_LTNG_ProfileCheck__c.field-meta.xml
<CustomField>
    <fullName>QuBy_LTNG_ProfileCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QuBy_LTNG_ProfileCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Are_we_the_Incumbent__c.field-meta.xml
<CustomField>
    <fullName>Are_we_the_Incumbent__c</fullName>
    <label>Are we the Incumbent?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Yes, exclusive</fullName>
            </value>
            <value>
                <fullName>Yes, multi-vendor</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CATM_Record__c.field-meta.xml
<CustomField>
    <fullName>CATM_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CATM - When checked, this opportunity was created by a CATM user.</description>
    <label>Is Cardtronics Record?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CLM_Sales_Acknowledgment__c.field-meta.xml
<CustomField>
    <fullName>CLM_Sales_Acknowledgment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CLM Sales Acknowledgment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closed_Lost_Comments__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Comments__c</fullName>
    <label>Closed Lost Comments</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CPQ__c.field-meta.xml
<CustomField>
    <fullName>CPQ__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes a CPQ Opportunity</description>
    <inlineHelpText>Denotes a CPQ Opportunity</inlineHelpText>
    <label>Is Subscription/Preferred Offer?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Discontinued_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Discontinued_Reasons__c</fullName>
    <label>Discontinued Reasons</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Customer Management Issues/Changes</fullName>
            </value>
            <value>
                <fullName>Mergers/Acquisitions/Divestitures</fullName>
            </value>
            <value>
                <fullName>NCR Administrative</fullName>
            </value>
            <value>
                <fullName>No Customer Funding</fullName>
            </value>
            <value>
                <fullName>Project Canceled by Customer</fullName>
            </value>
            <value>
                <fullName>Qualified Out by NCR</fullName>
            </value>
            <value>
                <fullName>Services Renewal Not Applicable</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Lost Interest)</fullName>
            </value>
            <value>
                <fullName>Project Postponed (Timing)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/How_important_was_Price_in_the_Decision__c.field-meta.xml
<CustomField>
    <fullName>How_important_was_Price_in_the_Decision__c</fullName>
    <label>How important was Price in the Decision?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Loss_Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Not at all</fullName>
            </value>
            <value>
                <fullName>Slightly</fullName>
            </value>
            <value>
                <fullName>Moderately</fullName>
            </value>
            <value>
                <fullName>Significantly</fullName>
            </value>
            <value>
                <fullName>Primary Reason</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Telecom &amp; Technology</fullName>
            </value>
            <value>
                <fullName>Payments &amp; Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsQuoteCreatedInOtherSystem__c.field-meta.xml
<CustomField>
    <fullName>IsQuoteCreatedInOtherSystem__c</fullName>
    <description>This field tracks if Quotes are created in Other system when there are no QuBy Quotes and allows close/booked the opportunity of answer is yes, else doesn&apos;t allows closing.</description>
    <label>Is Quote Created In Other System</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Key_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Key_Criteria__c</fullName>
    <label>Key Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Business Benefits</fullName>
            </value>
            <value>
                <fullName>Lead Time</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Pre-Contact Termination</fullName>
            </value>
            <value>
                <fullName>Post-Contact Termination</fullName>
            </value>
            <value>
                <fullName>HW</fullName>
            </value>
            <value>
                <fullName>SW</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
                <label>Service</label>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lose_to_a_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Lose_to_a_Competitor__c</fullName>
    <label>Lose to a Competitor?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payments_Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Payments_Contract_End_Date__c</fullName>
    <inlineHelpText>Please indicate customer existing Payment contact end date</inlineHelpText>
    <label>Payments Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Variance__c.field-meta.xml
<CustomField>
    <fullName>Price_Variance__c</fullName>
    <inlineHelpText>Enter the selection that best represents NCR&apos;s price compared to the competitors involved in this opportunity</inlineHelpText>
    <label>Price Variance</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>NCR above 5%</fullName>
            </value>
            <value>
                <fullName>NCR within 5%</fullName>
            </value>
            <value>
                <fullName>NCR under 5%</fullName>
            </value>
            <value>
                <fullName>Unknown/Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>CATM</description>
    <label>Product Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/What_was_the_closest_competitor_price__c.field-meta.xml
<CustomField>
    <fullName>What_was_the_closest_competitor_price__c</fullName>
    <label>What was the closest competitor price?</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/You_have_not_selected_any_TS_HWM_or_SW__c.field-meta.xml
<CustomField>
    <fullName>You_have_not_selected_any_TS_HWM_or_SW__c</fullName>
    <label>Reasons for not adding HWM,SWM,TS or PS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Contract Already In Place</fullName>
            </value>
            <value>
                <fullName>Self-Maintainer/Installer</fullName>
            </value>
            <value>
                <fullName>Competitor - price</fullName>
            </value>
            <value>
                <fullName>Competitor - prior service issues</fullName>
            </value>
            <value>
                <fullName>Channel partner/distributor</fullName>
            </value>
            <value>
                <fullName>Those products are on another opportunity</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Service Offers</fullName>
            </value>
            <value>
                <fullName>NCR Security Services</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Hospitality Networking/Cabling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Professional Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Offer_Category__c.field-meta.xml
<CustomField>
    <fullName>Service_Offer_Category__c</fullName>
    <label>Revenue Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SellingStageController.cls
/*Date           Dev. Name          User Story  
26 Feb 2022    Varsha Pal          #EBA_SF-1854 :CLM: Opportunity pop-up to confirm rep completed CLM documents before close/booking Opportunities
18 July 2022   Stuti Srivastava    #CSI_SF-424  :CLM Warning Message
19-12-2022     Monika              EBA_SF-2491 JDK Locale impact - Upgrade API Part 5  
#################################################################################################################################*/
public class SellingStageController {
    
    @AuraEnabled   
    public static Opportunity getTypeFromOpp(string recordId)
    {
        //added CLM_Sales_Acknowledgment__c for EBA_SF-1854
        //added Industry__c field as the part of Cardtronics Salesforce Integration Enhancement CSI_SF-424
        
        Opportunity opp = [select CPQ__c,Name, RecordType.Name, StageName, isClosed,You_have_not_selected_any_TS_HWM_or_SW__c,
                           (Select id,Name,Product_Category__c,Product2.Service_Offer_Category__c from OpportunityLineItems), Price_Variance__c, 
                           Key_Criteria__c, Lose_to_a_Competitor__c, Are_we_the_Incumbent__c, How_important_was_Price_in_the_Decision__c, 
                           What_was_the_closest_competitor_price__c, Closed_Lost_Comments__c,CLM_Sales_Acknowledgment__c,Industry__c, CATM_Record__c from Opportunity Where Id = :recordId limit 1];
        return opp;
    }
    
    
    
    @AuraEnabled  
    public static List<WrapperDiscontinueReason> getpickvalDR(string recordId)     
    {   
        String SelectedDiscontinueReason='';
        if(String.isNotBlank(recordId))
            SelectedDiscontinueReason = [select id,Discontinued_Reasons__c from Opportunity Where Id = :recordId].Discontinued_Reasons__c;    
        
        List<WrapperDiscontinueReason> options = new List<WrapperDiscontinueReason>();
        
        Schema.DescribeFieldResult fieldResult = opportunity.Discontinued_Reasons__c.getDescribe();
        
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for (Schema.PicklistEntry f : ple) { 
            if(f.getLabel() == SelectedDiscontinueReason){
                options.add(new WrapperDiscontinueReason(f.getLabel(),True));
            }
            else{
                options.add(new WrapperDiscontinueReason(f.getLabel(),False));
            }
        }       
        return options; 
    }  
    // EBA_SF-1854 added a new isclosed flag to check if we need to closed/booked the opportunity or just updating the fields coming from aura components
    @AuraEnabled
    public Static String UpdateOpportunityRecordNewCB(Opportunity opp, Boolean isClosed) 
    {      
        if(isClosed){
            if((opp.RecordType.Name!='Include in Funnel' && opp.RecordType.Name!='Indirect - Include in Funnel Reseller' && opp.RecordType.Name != 'Indirect - Include in Funnel Distributor')){
                opp.StageName='Closed/Booked - NonFunnel';
            }else{
                opp.StageName='Closed/Booked'; 
            }
        }
        try{
            update opp;  
            
        }catch(Exception e){
            return ('Error:'+e.getMessage());
            
        }
        return 'Success';
    }
    @AuraEnabled
    public Static String UpdateOpportunityRecordNewCL(Opportunity opp) 
    {          
        
        opp.StageName='Closed/Lost'; 
        
        
        try{
            update opp;  
            
        }catch(Exception e){
            return ('Error:'+e.getMessage());
            
        }
        return 'Success';
    }
    
    
    
  /*  
    @AuraEnabled
    public Static String UpdateOpportunityRecordNew(String id,String multiplevalue,string selectedprice,string DisContReason, String QtConfirmation, String stg1, String Reason) 
    { 
        Opportunity opp=new Opportunity();
        if(String.isNotBlank(id)){
            opp=[SELECT id,name,StageName, recordType.Name from Opportunity where Id=:id];
        }        
        if(stg1 == 'Closed/Discontinued'){             
            if(String.isNotBlank(DisContReason))    
                opp.Discontinued_Reasons__c=DisContReason;            
        }        
        else{
            if(String.isNotBlank(Reason)){
                opp.You_have_not_selected_any_TS_HWM_or_SW__c=Reason; 
            }
            
            if(String.isNotBlank(multiplevalue))
                opp.Key_Criteria__c=multiplevalue;
            
            if(String.isNotBlank(selectedprice)) 
                opp.Price_Variance__c=selectedprice;
            
            if(String.isNotBlank(QtConfirmation)) 
                opp.IsQuoteCreatedInOtherSystem__c=QtConfirmation; 
            if(stg1=='Closed/Booked' && (opp.RecordType.Name!='Include in Funnel' && opp.RecordType.Name!='Indirect - Include in Funnel Reseller' && opp.RecordType.Name != 'Indirect - Include in Funnel Distributor')){
                stg1='Closed/Booked - NonFunnel';
            }
        }
        opp.StageName=stg1;
        try{
            update opp;  
            
        }catch(Exception e){
            system.debug('ERROR###:'+ e.getMessage());
            return ('Error:'+e.getMessage());
            
        }
        return 'Success';
    }
    
    */
    //Return true : If Current profile available in Custom Setting
    //Return False : If Current profile not available in Custom Setting
    @AuraEnabled    
    public static boolean getIsdisabled(){   
        /*if( QuBy_LTNG_ProfileCheck__c.getValues( userInfo.getProfileId() ) == null )
            return false; 
        else
            return true;*/
         set<string> st  = new set<string>();
        List<All_profie_list_config__c> mcs = All_profie_list_config__c.getall().values();
        for(All_profie_list_config__c p : mcs ){
            if(p.QuBy_LTNG_ProfileCheck__c == true){
                st.add(p.Profile_id__c);
            }            
        } 
        if(! st.Contains( userInfo.getProfileId() )){
            return false;
        }else{
            return true;
        }        
    }  
    
    @AuraEnabled 
    public Static List<String> getReasonForHwandSW(){
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Opportunity.You_have_not_selected_any_TS_HWM_or_SW__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel()); 
        }     
        return pickListValuesList;
    }
    @AuraEnabled
    public static Map<String,  List<String>> getOpts() { 
        
        //Fetching field picklist values
        Schema.sObjectType sobject_type = Opportunity.getSObjectType(); //grab the sobject that was passed
        Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe(); //describe the sobject
        Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap(); //get a map of fields for the passed sobject
        Map<String, List<String>> picklistfieldmap=new Map<String, List<String>>();
        Set<String> techFields=new Set<string>();
        
        for(String s:field_map.keySet()){
            try{
                List<Schema.PicklistEntry> pick_list_values = field_map.get(s).getDescribe().getPickListValues(); //grab the list of picklist values for the passed field on the sobject
                List <String> pklistval=new List <String>();
                for (Schema.PicklistEntry a : pick_list_values) { //for all values in the picklist list            
                    pklistval.add(a.getLabel()); //add the value and label to our final list
                }
                if(pklistval.size()>0){
                    picklistfieldmap.put(s,pklistval);                
                    
                }
                
            }catch(Exception e){
                throw new AuraHandledException(e.getMessage());
            } 
        }
        return picklistfieldmap;
    }
     @AuraEnabled
    public static Date contractDateAvl(string recordId) { 
         Boolean isContractDateReq = false;
        Date cntDate=null;
         for(Opportunity oppp:[select Payments_Contract_End_Date__c from Opportunity where id=:recordId limit 1]){
            if(oppp.Payments_Contract_End_Date__c == null){
                isContractDateReq = true;
            }   
             else{
               cntDate= oppp.Payments_Contract_End_Date__c; 
             }
        }
                return cntDate;
    }
  
    
}