force-app/main/default/objects/KeysForSecuredUrls__c/KeysForSecuredUrls__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Encrypting url using  a private key.</description>
    <label>KeysForSecuredUrls</label>
</CustomObject>

force-app/main/default/objects/KeysForSecuredUrls__c/fields/CryptoKey__c.field-meta.xml
<CustomField>
    <fullName>CryptoKey__c</fullName>
    <label>CryptoKey</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Presales_Engineer__c/Presales_Engineer__c.object-meta.xml
<CustomObject>
    <label>Send to PS</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>P_S_Request_Autonumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Send to PS</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Presales_Engineer__c/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>CC  (1)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Presales_Engineer__c/fields/Presales_Funding_Request__c.field-meta.xml
<CustomField>
    <fullName>Presales_Funding_Request__c</fullName>
    <label>Presales Funding Request</label>
    <referenceTo>Presales_Funding_Request__c</referenceTo>
    <relationshipLabel>Send to PS</relationshipLabel>
    <relationshipName>Presales_Engineers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <trackHistory>false</trueHistory>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/Presales_Funding_Request__c.object-meta.xml
<CustomObject>
    <description>Used by Account Executive to request funding for a presales resource.</description>
    <label>Presales Funding Request</label>
    <nameField>
        <displayFormat>PFR-{0000}</displayFormat>
        <label>PFR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presales Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Presales_Funding_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Fund Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent to PS</fullName>
            </value>
            <value>
                <fullName>Pending for Approval</fullName>
            </value>
            <value>
                <fullName>Pending from Regional Sales Leader</fullName>
            </value>
            <value>
                <fullName>Pending from Leadership Team</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Expected_Date__c.field-meta.xml
<CustomField>
    <fullName>PFR_Expected_Date__c</fullName>
    <description>Expected start date of request</description>
    <inlineHelpText>Expected start date of request</inlineHelpText>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Is_this_Recoverable__c.field-meta.xml
<CustomField>
    <fullName>PFR_Is_this_Recoverable__c</fullName>
    <label>Is this Recoverable?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Justification__c.field-meta.xml
<CustomField>
    <fullName>PFR_Justification__c</fullName>
    <label>Justification</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>PFR_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with funding request</description>
    <inlineHelpText>Opportunity associated with funding request</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Presales Funding Requests</relationshipLabel>
    <relationshipName>Presales_Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Presales_Category__c.field-meta.xml
<CustomField>
    <fullName>PFR_Presales_Category__c</fullName>
    <label>Presales Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1-Network Certification</fullName>
            </value>
            <value>
                <fullName>2-Early Stage Presales</fullName>
            </value>
            <value>
                <fullName>3- Proof of Concept</fullName>
            </value>
            <value>
                <fullName>4-PS SOW Creation &amp; Pricing</fullName>
            </value>
            <value>
                <fullName>5-PS work-ahead pending SOW signature</fullName>
            </value>
            <value>
                <fullName>6-Non-Standard Gratis work / Customer satisfaction issue</fullName>
            </value>
            <value>
                <fullName>1- Network Certification</fullName>
                <isActive>false</isActive>
                <label>1- Network Certification</label>
            </value>
            <value>
                <fullName>2- Early Stage Presales</fullName>
                <isActive>false</isActive>
                <label>2- Early Stage Presales</label>
            </value>
            <value>
                <fullName>4- PS SOW Creation &amp; Pricing</fullName>
                <isActive>false</isActive>
                <label>4- PS SOW Creation &amp; Pricing</label>
            </value>
            <value>
                <fullName>5- PS &apos;work-ahead&apos;, pending SOW signature</fullName>
                <isActive>false</isActive>
                <label>5- PS &apos;work-ahead&apos;, pending SOW signature</label>
            </value>
            <value>
                <fullName>6- Non-Standard Gratis work / Customer satisfaction issue</fullName>
                <isActive>false</isActive>
                <label>6- Non-Standard Gratis work / Customer satisfaction issue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Success_Criteria__c.field-meta.xml
<CustomField>
    <fullName>PFR_Success_Criteria__c</fullName>
    <label>Success Criteria</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>PS resource for Presales Fund Request</description>
    <label>Resource</label>
    <nameField>
        <displayFormat>Resource-{000}</displayFormat>
        <label>Resource ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/PFR_BU__c.field-meta.xml
<CustomField>
    <fullName>PFR_BU__c</fullName>
    <label>BU</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PS</fullName>
                <default>true</default>
                <label>PS</label>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>ISG</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/PFR_Daily_Rate_USD__c.field-meta.xml
<CustomField>
    <fullName>PFR_Daily_Rate_USD__c</fullName>
    <label>Hourly Rate (USD)</label>
    <precision>16</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/PFR_Num_of_days_not_to_exceed__c.field-meta.xml
<CustomField>
    <fullName>PFR_Num_of_days_not_to_exceed__c</fullName>
    <label>Hours not to exceed</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/PFR_Task__c.field-meta.xml
<CustomField>
    <fullName>PFR_Task__c</fullName>
    <label>Task</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/PFR_Travel_Cost__c.field-meta.xml
<CustomField>
    <fullName>PFR_Travel_Cost__c</fullName>
    <label>Travel Cost (USD)</label>
    <precision>16</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/PSFundingRequest__c.field-meta.xml
<CustomField>
    <fullName>PSFundingRequest__c</fullName>
    <label>Presales Funding Request</label>
    <referenceTo>Presales_Funding_Request__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <trackHistory>false</trueHistory>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PSFRResource_R_Test.cls
/*
##################################################################################################
# Class Name............................:PSFRResource_R_Test                                                                                                                                  
# Last Modified by......:  Monika
# Last Modified Date..:    19-12-2022
BA_SF-2491 JDK Locale impact - Upgrade API Part 5                          
################################################################################################
*/
@isTest
public class PSFRResource_R_Test{
    static testMethod void testMethod1(){
        KeysForSecuredUrls__c cs = new KeysForSecuredUrls__c();
        cs.Name='PSFREncryptionKey';
        cs.CryptoKey__c='8cPkFUCoHb9sa3D7@djdkjdk!%@ncmnc';
        //cs.Other fiels values
        insert cs;
        Account Acc=TestRecordsFactory.createAccount();
        Contact con=TestRecordsFactory.createContact(Acc);
        Opportunity opp=TestRecordsFactory.createSimpleOpportunity(Acc);
        Presales_Funding_Request__c PSFR_Obj=new Presales_Funding_Request__c();
        PSFR_Obj.PFR_Opportunity__c=opp.id;
        PSFR_Obj.PFR_Presales_Category__c ='1-Network Certification';
        PSFR_Obj.PFR_Is_this_Recoverable__c='Yes';
        PSFR_Obj.PFR_Expected_Date__c=system.today();
        PSFR_Obj.PFR_Justification__c='Test Justification';
        PSFR_Obj.PFR_Success_Criteria__c='Test Justification';
        insert PSFR_Obj;
        Resource__c objResource=new Resource__c();
        
        objResource.PSFundingRequest__c=PSFR_Obj.id;
        objResource.PFR_Num_of_days_not_to_exceed__c=20;
        objResource.PFR_BU__c='PS';
        objResource.PFR_Daily_Rate_USD__c=2;
        objResource.PFR_Travel_Cost__c=200;
        objResource.PFR_Task__c='Test';
        insert objResource;
        Presales_Engineer__c res = new Presales_Engineer__c();
        res.Email_ID_1__c = 'test1@gmail.com'; 
        res.Presales_Funding_Request__c = PSFR_Obj.id;
        Test.startTest();
        PageReference myVfPage = Page.PSFR_Site_Page;
        Test.setCurrentPage(myVfPage);
        system.assert(myVfPage!=null);
        System.currentPageReference().getParameters().put('id',PSFR_Obj.id);
        PSFRApexController testController = new PSFRApexController();
        testController.AddResource();
        testController.Submit();
        testController.save();
        testController.cancel();
        testController.EditR();
        testController.Auth_Check();
        testController.Generate_Auth_Token();
        testController.addPS();
        try{
            testController.AddPSTeam();
        }
        Catch(Exception e){
            System.debug('exception occured');
        }
        PSFR_Obj.Approval_Status__c='Sent to PS';
        update PSFR_Obj;
        PageReference myVfPage1 = Page.PSFR_Resource;
        Test.setCurrentPage(myVfPage1);
        String cs1 = KeysForSecuredUrls__c.getValues('PSFREncryptionKey').CryptoKey__c;
        Blob cryptoKey = Blob.valueOf(cs1);
        string encodedCipherText = EncodingUtil.base64Encode(Crypto.encryptWithManagedIV('AES256', cryptoKey, Blob.valueOf(PSFR_Obj.id)));
        string encryptedMasterRecordId = encodedCipherText;//encodingUtil.URLEncode(encodedCipherText,'UTF-8');
       // System.currentPageReference().getParameters().put('id',encryptedMasterRecordId);
        System.currentPageReference().getParameters().put('Plid',encryptedMasterRecordId);
        PSFRResource_R ResourceObj=new PSFRResource_R();
        PSFRApexController PFCOV = new PSFRApexController();
        ResourceObj.rm=objResource;
        
        ResourceObj.WrapperList[0].Reso.PFR_Travel_Cost__c=200;
        ResourceObj.WrapperList[0].Reso.PFR_Daily_Rate_USD__c=200;
        ResourceObj.WrapperList[0].Reso.PFR_Num_of_days_not_to_exceed__c=200;
        ResourceObj.WrapperList[0].Reso.PFR_Travel_Cost__c=200;
        ResourceObj.WrapperList[0].Reso.PFR_Task__c='test';
        ResourceObj.addResource();
        // ResourceObj.TestCoverateMethod();
        // PFCOV.TestCoverateMethod();
        ResourceObj.addResource();
        

       ResourceObj.Calcualte();
         //ResourceObj.saveResource();
        try{
            ResourceObj.saveResource();
        }Catch(Exception e){
            System.debug('msg'+e.getMessage());
        }
        ResourceObj.COUNT_FRM_PAGE = 2;
        ResourceObj.removeResource();
        PSFR_Obj.Approval_Status__c='Send to PS';
      
        
        Test.StopTest();
        
    }
    static testMethod void testMethod2(){
         KeysForSecuredUrls__c cs = new KeysForSecuredUrls__c();
        cs.Name='PSFREncryptionKey';
        cs.CryptoKey__c='8cPkFUCoHb9sa3D7@djdkjdk!%@ncmnc';
        //cs.Other fiels values
        insert cs;
        
        Account Acc=TestRecordsFactory.createAccount();
        Contact con=TestRecordsFactory.createContact(Acc);
        Opportunity opp=TestRecordsFactory.createSimpleOpportunity(Acc);
        Presales_Funding_Request__c PSFR_Obj=new Presales_Funding_Request__c();
        PSFR_Obj.PFR_Opportunity__c=opp.id;
        PSFR_Obj.PFR_Presales_Category__c ='1-Network Certification';
        PSFR_Obj.PFR_Is_this_Recoverable__c='Yes';
        PSFR_Obj.PFR_Expected_Date__c=system.today();
        PSFR_Obj.PFR_Justification__c='Test Justification';
        PSFR_Obj.PFR_Success_Criteria__c='Test Justification';
        
        insert PSFR_Obj;
        PSFR_Obj.Approval_Status__c='On Hold';
        update PSFR_Obj;
        Resource__c objResource=new Resource__c();
        
        objResource.PSFundingRequest__c=PSFR_Obj.id;
        objResource.PFR_Num_of_days_not_to_exceed__c=20;
        objResource.PFR_BU__c='PS';
        objResource.PFR_Daily_Rate_USD__c=2;
        objResource.PFR_Travel_Cost__c=200;
        objResource.PFR_Task__c='Test';
        insert objResource;
        
        
        Presales_Engineer__c res = new Presales_Engineer__c();
        res.Email_ID_1__c = 'test1@gmail.com';
        res.Presales_Funding_Request__c = PSFR_Obj.id;
        Test.startTest();
        PageReference myVfPage = Page.PSFR_Site_Page;
        Test.setCurrentPage(myVfPage);
 	    system.assert(myVfPage!=null);
        System.currentPageReference().getParameters().put('id',PSFR_Obj.id);
        PSFRApexController testController = new PSFRApexController();
        testController.AddResource();
        testController.Submit();
        testController.save();
        testController.cancel();
        testController.EditR();
        testController.Auth_Check();
        testController.Generate_Auth_Token();
        testController.addPS();
        Test.StopTest();
    }
    static testMethod void testMethod3(){
         KeysForSecuredUrls__c cs = new KeysForSecuredUrls__c();
        cs.Name='PSFREncryptionKey';
        cs.CryptoKey__c='8cPkFUCoHb9sa3D7@djdkjdk!%@ncmnc';
        //cs.Other fiels values
        insert cs;
        Account Acc=TestRecordsFactory.createAccount();
        Contact con=TestRecordsFactory.createContact(Acc);
        Opportunity opp=TestRecordsFactory.createSimpleOpportunity(Acc);
        Presales_Funding_Request__c PSFR_Obj=new Presales_Funding_Request__c();
        PSFR_Obj.PFR_Opportunity__c=opp.id;
        PSFR_Obj.PFR_Presales_Category__c ='1-Network Certification';
        PSFR_Obj.PFR_Is_this_Recoverable__c='Yes';
        PSFR_Obj.PFR_Expected_Date__c=system.today();
        PSFR_Obj.PFR_Justification__c='Test Justification';
        PSFR_Obj.PFR_Success_Criteria__c='Test Justification';
        
        insert PSFR_Obj;
        PSFR_Obj.Approval_Status__c='On Hold';
        update PSFR_Obj;
        Resource__c objResource=new Resource__c();
        
        objResource.PSFundingRequest__c=PSFR_Obj.id;
        objResource.PFR_Num_of_days_not_to_exceed__c=20;
        objResource.PFR_BU__c='PS';
        objResource.PFR_Daily_Rate_USD__c=2;
        objResource.PFR_Travel_Cost__c=200;
        objResource.PFR_Task__c='Test';
        insert objResource;
        Presales_Engineer__c res = new Presales_Engineer__c();
        res.Email_ID_1__c = 'test1@gmail.com';
        res.Presales_Funding_Request__c = PSFR_Obj.id;
        Test.startTest();
        PageReference myVfPage = Page.PSFR_Site_Page;
        Test.setCurrentPage(myVfPage);
        system.assert(myVfPage!=null);
	    System.currentPageReference().getParameters().put('id',PSFR_Obj.id);
        PSFRApexController testController = new PSFRApexController();
        testcontroller.PS_Token = 'test';
        testController.EditR();
        testController.Auth_Check();
        testController.Generate_Auth_Token();
        testController.addPS();
        Test.StopTest();
    }
    static testMethod void testMethod4(){
         KeysForSecuredUrls__c cs = new KeysForSecuredUrls__c();
        cs.Name='PSFREncryptionKey';
        cs.CryptoKey__c='8cPkFUCoHb9sa3D7@djdkjdk!%@ncmnc';
        //cs.Other fiels values
        insert cs;
        Account Acc=TestRecordsFactory.createAccount();
        Contact con=TestRecordsFactory.createContact(Acc);
        Opportunity opp=TestRecordsFactory.createSimpleOpportunity(Acc);
        Presales_Funding_Request__c PSFR_Obj=new Presales_Funding_Request__c();
        PSFR_Obj.PFR_Opportunity__c=opp.id;
        PSFR_Obj.PFR_Presales_Category__c ='1-Network Certification';
        PSFR_Obj.PFR_Is_this_Recoverable__c='Yes';
        PSFR_Obj.PFR_Expected_Date__c=system.today();
        PSFR_Obj.PFR_Justification__c='Test Justification';
        PSFR_Obj.PFR_Success_Criteria__c='Test Justification';
        
        insert PSFR_Obj;
        Resource__c objResource=new Resource__c();
        
        objResource.PSFundingRequest__c=PSFR_Obj.id;
        objResource.PFR_Num_of_days_not_to_exceed__c=20;
        objResource.PFR_BU__c='PS';
        objResource.PFR_Daily_Rate_USD__c=2;
        objResource.PFR_Travel_Cost__c=200;
        objResource.PFR_Task__c='Test';
        insert objResource;
        Presales_Engineer__c res = new Presales_Engineer__c();
        res.Email_ID_1__c = 'test1@gmail.com';
        res.Presales_Funding_Request__c = PSFR_Obj.id;
        Test.startTest();
        PageReference myVfPage = Page.PSFR_Site_Page;
        Test.setCurrentPage(myVfPage);
        System.currentPageReference().getParameters().put('id',PSFR_Obj.id);
        System.currentPageReference().getParameters().put('Plid',PSFR_Obj.id);
        PSFRApexController testController = new PSFRApexController();
        testcontroller.PS_Token = 'test';
        testController.EditR();
        testController.Auth_Check();
        testController.Generate_Auth_Token();
        testController.addPS();
        PageReference myVfPage1 = Page.PSFR_Resource;
        Test.setCurrentPage(myVfPage1);
        system.assert(myVfPage1!=null);
        
        String cs1 = KeysForSecuredUrls__c.getValues('PSFREncryptionKey').CryptoKey__c;
        Blob cryptoKey = Blob.valueOf(cs1);
        string encodedCipherText = EncodingUtil.base64Encode(Crypto.encryptWithManagedIV('AES256', cryptoKey, Blob.valueOf(PSFR_Obj.id)));
        string encryptedMasterRecordId = encodedCipherText; //encodingUtil.URLEncode(encodedCipherText,'UTF-8');
        System.currentPageReference().getParameters().put('Plid',encryptedMasterRecordId);
        PSFRResource_R ResourceObj=new PSFRResource_R();
        PSFRApexController PFCOV = new PSFRApexController();
        ResourceObj.rm=objResource;
        ResourceObj.WrapperList[0].Reso.PFR_Travel_Cost__c=200;
        ResourceObj.WrapperList[0].Reso.PFR_Daily_Rate_USD__c=200;
        ResourceObj.WrapperList[0].Reso.PFR_Num_of_days_not_to_exceed__c=200;
        ResourceObj.WrapperList[0].Reso.PFR_Travel_Cost__c=200;
        ResourceObj.WrapperList[0].Reso.PFR_Task__c='test';
        ResourceObj.addResource();
        // ResourceObj.TestCoverateMethod();
        // PFCOV.TestCoverateMethod();
        ResourceObj.addResource();
        ResourceObj.Calcualte();
        try{
            ResourceObj.saveResource();
        }Catch(Exception e){
            System.debug('msg'+e.getMessage());
        }
        Test.StopTest();
    }
}