force-app/main/default/objects/Email_Recipient__c/Email_Recipient__c.object-meta.xml
<CustomObject>
    <label>Email Recipient</label>
    <nameField>
        <displayFormat>ER-{000}</displayFormat>
        <label>Email Recipient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Recipients</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Recipient__c/fields/Direct_FUA__c.field-meta.xml
<CustomField>
    <fullName>Direct_FUA__c</fullName>
    <label>Direct FUA</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/fields/Direct_MCN__c.field-meta.xml
<CustomField>
    <fullName>Direct_MCN__c</fullName>
    <label>Direct MCN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/fields/Indirect_FUA__c.field-meta.xml
<CustomField>
    <fullName>Indirect_FUA__c</fullName>
    <label>Indirect FUA</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/fields/Indirect_MCN__c.field-meta.xml
<CustomField>
    <fullName>Indirect_MCN__c</fullName>
    <label>Indirect MCN</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/fields/Reporting_Filter__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Filter__c</fullName>
    <label>Reporting Filter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct MCN</fullName>
            </value>
            <value>
                <fullName>Indirect MCN</fullName>
            </value>
            <value>
                <fullName>Direct FUA</fullName>
            </value>
            <value>
                <fullName>Indirect FUA</fullName>
            </value>
            <value>
                <fullName>All FUA</fullName>
            </value>
            <value>
                <fullName>All MCN</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
                <isActive>false</isActive>
                <label>Both</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/fields/Schedule_External_Report__c.field-meta.xml
<CustomField>
    <fullName>Schedule_External_Report__c</fullName>
    <label>Schedule External Report</label>
    <referenceTo>Schedule_External_Report__c</referenceTo>
    <relationshipLabel>Email Recipients</relationshipLabel>
    <relationshipName>Email_Recipient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/fields/updatedByBatch__c.field-meta.xml
<CustomField>
    <fullName>updatedByBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UpdatedByBatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_External_Report__c/Schedule_External_Report__c.object-meta.xml
<CustomObject>
    <label>Schedule External Report</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Schedule external report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule External Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_External_Report__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Quaterly</fullName>
                <isActive>false</isActive>
                <label>Quaterly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_External_Report__c/fields/Schedule_external_report_name__c.field-meta.xml
<CustomField>
    <fullName>Schedule_external_report_name__c</fullName>
    <label>Schedule external report name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestReportToEmailController.cls
@isTest
public class TestReportToEmailController {
   
    @isTest(SeeAllData='true')
    public static void TestMethod1(){
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName IN('Case_Test_Report_1_9Nd','Case_Test_Report_2_FJ6')];
        String reportId = (String)reportList.get(0).get('Id');
         // Creating test record on Schedule external report object
        Schedule_External_Report__c scheduleExtRepObj = new Schedule_External_Report__c();
        scheduleExtRepObj.Schedule_external_report_name__c = 'Test';
        scheduleExtRepObj.Frequency__c = 'Daily';
        insert scheduleExtRepObj;
        
        // Creating test record on Email Recipient object
        Email_Recipient__c emailRecipientObj = new Email_Recipient__c();
        emailRecipientObj.Schedule_External_Report__c =scheduleExtRepObj.id;
        emailRecipientObj.Direct_MCN__c = '3555062CA';
        emailRecipientObj.Indirect_MCN__c = '';
        emailRecipientObj.updatedByBatch__c = false;
        emailRecipientObj.Email__c = 'test@gmail.com';
        insert emailRecipientObj;
        
        Test.startTest();
        ReportsToEmailController rc = new ReportsToEmailController();
        rc.rptId  = reportId;
        rc.con = emailRecipientObj.Id;
        string rslt =rc.getReportResult();
        System.assert(rslt!=null);
        Test.stopTest(); 
    }
    
    
    
    @isTest(SeeAllData='true')
    public static void TestMethod2(){
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName = 'Case_Test_Report_1_9Nd'];
        String reportId = (String)reportList.get(0).get('Id');
        List<Id> contactIdList = new List<Id>();
        //Creating test account record
        Account acc =  TestRecordsFactory.createAccount('1234320','HOSPITALITY:TSR','NAMER SMB');
        // Creating test contact record
        Contact con = TestRecordsFactory.createContact(acc);
        contactIdList.add(con.Id);
                
        // Creating test case record
         Case case1 = new case(accountid=acc.id,status ='In Progress',Subject='Test case');
        insert case1;
        // Creating test record on Schedule external report object
        Schedule_External_Report__c scheduleExtRepObj = new Schedule_External_Report__c();
        scheduleExtRepObj.Schedule_external_report_name__c = 'Test';
        scheduleExtRepObj.Frequency__c = 'Daily';
        insert scheduleExtRepObj;
        
        // Creating test record on Email Recipient object
        Email_Recipient__c emailRecipientObj = new Email_Recipient__c();
        emailRecipientObj.Schedule_External_Report__c =scheduleExtRepObj.id;
        emailRecipientObj.Direct_MCN__c = '1234320';
        emailRecipientObj.Indirect_MCN__c = '';
        emailRecipientObj.Reporting_Filter__c='Direct MCN';
        emailRecipientObj.updatedByBatch__c = false;
        emailRecipientObj.Email__c = 'test@gmail.com';
        insert emailRecipientObj;
        
        
        
        Test.startTest();
        ReportsToEmailController rc = new ReportsToEmailController();
        rc.rptId  = reportId;
        rc.con = emailRecipientObj.Id;
        string rslt =rc.getReportResult();
        System.assert(rslt!=null);
        Test.stopTest();
    }
    
    
    @isTest(SeeAllData='true')
    public static void TestMethod3(){
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName = 'Case_Test_Report_1_9Nd'];
        String reportId = (String)reportList.get(0).get('Id');
        // Creating test record on Schedule external report object
        Schedule_External_Report__c scheduleExtRepObj = new Schedule_External_Report__c();
        scheduleExtRepObj.Schedule_external_report_name__c = 'Test';
        scheduleExtRepObj.Frequency__c = 'Daily';
        insert scheduleExtRepObj;
        
        // Creating test record on Email Recipient object
        Email_Recipient__c emailRecipientObj = new Email_Recipient__c();
        emailRecipientObj.Schedule_External_Report__c =scheduleExtRepObj.id;
        emailRecipientObj.Direct_MCN__c = '3555062CA';
        emailRecipientObj.Indirect_MCN__c = '55555555555555';
        emailRecipientObj.Reporting_Filter__c='Indirect MCN';
        emailRecipientObj.updatedByBatch__c = false;
        emailRecipientObj.Email__c = 'test@gmail.com';
        insert emailRecipientObj;
        
        Test.startTest();
        ReportsToEmailController rc = new ReportsToEmailController();
        rc.rptId  = reportId;
        rc.con = emailRecipientObj.Id;
        string rslt =rc.getReportResult();
        System.assert(rslt!=null);
        Test.stopTest();
    }
    
    @isTest(SeeAllData='true')
    public static void TestMethod4(){
        
        Test.startTest();
        ReportsToEmailController rc = new ReportsToEmailController();
        String rslt = rc.getReportResult();
        Test.stopTest();
        System.assert(rslt==null);
    }
    
     @isTest(SeeAllData='true')
    public static void TestMethod5(){
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName IN('Case_Test_Report_1_9Nd','Case_Test_Report_2_FJ6')];
        String reportId = (String)reportList.get(1).get('Id');
        // Creating test record on Schedule external report object
        Schedule_External_Report__c scheduleExtRepObj = new Schedule_External_Report__c();
        scheduleExtRepObj.Schedule_external_report_name__c = 'Test';
        scheduleExtRepObj.Frequency__c = 'Daily';
        insert scheduleExtRepObj;
        
        // Creating test record on Email Recipient object
        Email_Recipient__c emailRecipientObj = new Email_Recipient__c();
        emailRecipientObj.Schedule_External_Report__c =scheduleExtRepObj.id;
        emailRecipientObj.Direct_MCN__c = '3555062CA';
        emailRecipientObj.Indirect_MCN__c = '';
        emailRecipientObj.updatedByBatch__c = false;
        emailRecipientObj.Email__c = 'test@gmail.com';
        insert emailRecipientObj;
        
        Test.startTest();
        ReportsToEmailController rc = new ReportsToEmailController();
        rc.rptId  = reportId;
        rc.con = emailRecipientObj.Id;
        String rslt =rc.getReportResult();
        System.assert(rslt!=null);
        Test.stopTest();
    }
    
    @isTest(SeeAllData='true')
    public static void TestMethod6(){
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName = 'Case_Test_Report_1_9Nd'];
        String reportId = (String)reportList.get(0).get('Id');
        // Creating test record on Schedule external report object
        Schedule_External_Report__c scheduleExtRepObj = new Schedule_External_Report__c();
        scheduleExtRepObj.Schedule_external_report_name__c = 'Test';
        scheduleExtRepObj.Frequency__c = 'Daily';
        insert scheduleExtRepObj;
        
        // Creating test record on Email Recipient object
        Email_Recipient__c emailRecipientObj = new Email_Recipient__c();
        emailRecipientObj.Schedule_External_Report__c =scheduleExtRepObj.id;
        emailRecipientObj.Direct_FUA__c = '3555062CA';
        emailRecipientObj.Indirect_MCN__c = '';
        emailRecipientObj.Reporting_Filter__c='Direct FUA';
        emailRecipientObj.updatedByBatch__c = false;
        emailRecipientObj.Email__c = 'test@gmail.com';
        insert emailRecipientObj;
        
        
        Test.startTest();
        ReportsToEmailController rc = new ReportsToEmailController();
        rc.rptId  = reportId;
        rc.con = emailRecipientObj.Id;
        string rslt =rc.getReportResult();
        System.assert(rslt!=null);
        Test.stopTest();
    }
    
    
     @isTest(SeeAllData='true')
    public static void TestMethod7(){
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName = 'Case_Test_Report_1_9Nd'];
        String reportId = (String)reportList.get(0).get('Id');
        // Creating test record on Schedule external report object
        Schedule_External_Report__c scheduleExtRepObj = new Schedule_External_Report__c();
        scheduleExtRepObj.Schedule_external_report_name__c = 'Test';
        scheduleExtRepObj.Frequency__c = 'Daily';
        insert scheduleExtRepObj;
        
        // Creating test record on Email Recipient object
        Email_Recipient__c emailRecipientObj = new Email_Recipient__c();
        emailRecipientObj.Schedule_External_Report__c =scheduleExtRepObj.id;
        emailRecipientObj.Direct_FUA__c = '3555062CA';
        emailRecipientObj.Indirect_FUA__c = '3555062CA,7827272';
        emailRecipientObj.Reporting_Filter__c='Indirect FUA';
        emailRecipientObj.updatedByBatch__c = false;
        emailRecipientObj.Email__c = 'test@gmail.com';
        insert emailRecipientObj;
        
        
        Test.startTest();
        ReportsToEmailController rc = new ReportsToEmailController();
        rc.rptId  = reportId;
        rc.con = emailRecipientObj.Id;
        string rslt =rc.getReportResult();
        System.assert(rslt!=null);
        Test.stopTest();
    }
    
    @isTest(SeeAllData='true')
    public static void TestMethod8(){
        List <Report> reportList = [SELECT Id,DeveloperName FROM Report where DeveloperName = 'Case_Test_Report_1_9Nd'];
        String reportId = (String)reportList.get(0).get('Id');
        // Creating test record on Schedule external report object
        Schedule_External_Report__c scheduleExtRepObj = new Schedule_External_Report__c();
        scheduleExtRepObj.Schedule_external_report_name__c = 'Test';
        scheduleExtRepObj.Frequency__c = 'Daily';
        insert scheduleExtRepObj;
        
        // Creating test record on Email Recipient object
        Email_Recipient__c emailRecipientObj = new Email_Recipient__c();
        emailRecipientObj.Schedule_External_Report__c =scheduleExtRepObj.id;
        emailRecipientObj.Direct_FUA__c = '3555062CA';
        emailRecipientObj.Indirect_FUA__c = '3555062CA,7827272';
        emailRecipientObj.Reporting_Filter__c='All FUA';
        emailRecipientObj.updatedByBatch__c = false;
        emailRecipientObj.Email__c = 'test@gmail.com';
        insert emailRecipientObj;
        
        
        Test.startTest();
        ReportsToEmailController rc = new ReportsToEmailController();
        rc.rptId  = reportId;
        rc.con = emailRecipientObj.Id;
        string rslt =rc.getReportResult();
        System.assert(rslt!=null);
        Test.stopTest();
    }
}