force-app/main/default/objects/Email_Recipient__c/Email_Recipient__c.object-meta.xml
<CustomObject>
    <label>Email Recipient</label>
    <nameField>
        <displayFormat>ER-{000}</displayFormat>
        <label>Email Recipient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Recipients</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Recipient__c/fields/Schedule_External_Report__c.field-meta.xml
<CustomField>
    <fullName>Schedule_External_Report__c</fullName>
    <label>Schedule External Report</label>
    <referenceTo>Schedule_External_Report__c</referenceTo>
    <relationshipLabel>Email Recipients</relationshipLabel>
    <relationshipName>Email_Recipient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Email_Recipient__c/fields/updatedByBatch__c.field-meta.xml
<CustomField>
    <fullName>updatedByBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UpdatedByBatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_External_Report__c/Schedule_External_Report__c.object-meta.xml
<CustomObject>
    <label>Schedule External Report</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Schedule external report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule External Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_External_Report__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Quaterly</fullName>
                <isActive>false</isActive>
                <label>Quaterly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_External_Report__c/fields/Is_Batch_Triggered_on_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Is_Batch_Triggered_on_End_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Batch Triggered on End Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_External_Report__c/fields/NextBatchDate__c.field-meta.xml
<CustomField>
    <fullName>NextBatchDate__c</fullName>
    <label>NextBatchDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_External_Report__c/fields/Schedule_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Time__c</fullName>
    <label>Schedule Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/TriggerReportFlowBatchClass.cls
/****************************************************************************************************************
*   ClassName   : TriggerReportFlowBatchClass
*   Description : Use to edit Email Tracking records . so that flow can be triggerd.  
*   Author      : Md Raza 
*   Version     : Initial
# Modification History.: 
Story No#         Date            DevName                Description
05 Aug 2022     Md Raza                Use to edit Email Tracking records . so that flow can be triggerd.
****************************************************************************************************************/
global class TriggerReportFlowBatchClass Implements Database.Batchable<sObject> {
   
    global Database.QueryLocator start(Database.BatchableContext BC) {
       //conversion of time zones
        DateTime dtTime=DateTime.now();
        TimeZone tz = UserInfo.getTimeZone(); 
        Integer offset=tz.getOffset(dtTime);
        // target Timezone.
        TimeZone targetTZ = Timezone.getTimeZone('America/New_York');
        integer offsetTotargetTZ = targetTZ.getOffset(dtTime);
        integer correction = offsetTotargetTZ- offset;
        DateTime targetDT = dtTime.addMinutes(correction / (1000 * 60));
        Time currentTime = Time.newInstance(targetDT.hour(), targetDT.minute(), targetDT.second(), targetDT.millisecond());
        /*End*/
        return Database.getQueryLocator([SELECT Id,Is_Batch_Triggered_on_End_Date__c,Start_Date__c,End_Date__c,Schedule_Time__c,Frequency__c,NextBatchDate__c,(SELECT Id,updatedByBatch__c FROM Email_Recipient__r ) FROM Schedule_External_Report__c where NextBatchDate__c =:Date.valueof(targetDT) and schedule_time__c <=:currentTime and schedule_time__c >=:currentTime.addMinutes(-30) and Is_Batch_Triggered_on_End_Date__c=false ]);
    }
    global void execute(Database.BatchableContext BC, list<Schedule_External_Report__c> srList){
        List<Email_Recipient__c> listToBeUpdated = new List<Email_Recipient__c>();
        List<Schedule_External_Report__c> nextBatchDateUpdate = new List<Schedule_External_Report__c>();
     
        for(Schedule_External_Report__c src: srList){
                if(src.Email_Recipient__r.size()>0){
                    for(Email_Recipient__c et : src.Email_Recipient__r){ 
                        if(et.updatedByBatch__c == true){
                            et.updatedByBatch__c = false;
                        }
                        else if(et.updatedByBatch__c == false){
                            et.updatedByBatch__c = true;
                        }
                        listToBeUpdated.add(et);
                    }
                    if(src.Frequency__c == 'Daily' && src.NextBatchDate__c != null){
                        src.NextBatchDate__c = src.NextBatchDate__c.addDays(1);
                    }
                    else if(src.Frequency__c == 'Weekly' && src.NextBatchDate__c != null){
                        src.NextBatchDate__c = src.NextBatchDate__c.addDays(7);
                    }
                    else if(src.Frequency__c == 'Monthly' && src.NextBatchDate__c != null){
                        src.NextBatchDate__c = src.NextBatchDate__c.addMonths(1);
                    }
                    else if(src.Frequency__c == 'Quarterly' && src.NextBatchDate__c != null){
                        src.NextBatchDate__c = src.NextBatchDate__c.addMonths(3);
                    }
                    else if(src.Frequency__c == 'Yearly' && src.NextBatchDate__c != null){
                        src.NextBatchDate__c = src.NextBatchDate__c.addYears(1);
                    }
                    if(src.NextBatchDate__c <= src.End_Date__c){
                        nextBatchDateUpdate.add(src);
                    }
                    else{
                        src.NextBatchDate__c = src.NextBatchDate__c.addDays(-1);
                       src.Is_Batch_Triggered_on_End_Date__c = true;
                        nextBatchDateUpdate.add(src);
                    }
                       
                }
        }
        if(listToBeUpdated.size()>0){
            update listToBeUpdated;
        }
        if(nextBatchDateUpdate.size()>0){
            update nextBatchDateUpdate;
        }
    }
    public void finish(Database.BatchableContext BC){
        string cronID = system.scheduleBatch(new TriggerReportFlowBatchClass(), 'Schedule External Report Batch', 10, 1);
    }
}