force-app/main/default/objects/Co_Branded_Collateral__c/Co_Branded_Collateral__c.object-meta.xml
<CustomObject>
    <label>Co-Branded Collateral Request</label>
    <nameField>
        <displayFormat>CBC-{0000}</displayFormat>
        <label>Co-Branded Collateral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Branded Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Branded_Collateral__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_CoBrandedCollateralControllerTest.cls
@isTest
public class PRM_CoBrandedCollateralControllerTest 
{
	static testMethod void myUnitTest() 
    {
        Co_Branded_Collateral__c  mc = new Co_Branded_Collateral__c ();
        mc.Status__c = 'Draft';
        insert mc;
      
        PRM_CoBrandedCollateralController.getCoBrandedCollateral('All');
        PRM_CoBrandedCollateralController.getCoBrandedCollateral('Draft');
        
        PRM_CoBrandedCollateralController.getCoBrandedCollateralDetail(mc.Id);
        PRM_CoBrandedCollateralController.getEditCoBrandedCollateralDetail(mc.Id);
        system.assert(mc.Id!=null);
        
        PRM_CoBrandedCollateralController.getPicklistValues();
        PRM_CoBrandedCollateralController.saveChunk(mc.Id, 'Test', EncodingUtil.urlDecode('Testing', 'UTF-8'), 'txt', '');
        
        Attachment oAttachment = new Attachment();
        Blob b = Blob.valueOf('Test Data');
        oAttachment.parentId = mc.Id;
        oAttachment.Name = 'Test Attachment for Parent';
        oAttachment.Body = b;
        insert oAttachment;
        PRM_CoBrandedCollateralController.saveChunk(mc.Id, 'Test', EncodingUtil.urlDecode('Testing', 'UTF-8'), 'txt', oAttachment.Id);
        
        PRM_CoBrandedCollateralController.getCBCAttachments(mc.Id);
        PRM_CoBrandedCollateralController.saveCoBranded(new Co_Branded_Collateral__c (Status__c = 'Draft'));
        
        PRM_CoBrandedCollateralController.saveEditedCoBranded(mc);
        
        PRM_CoBrandedCollateralController.submitApprovalRequest(mc.Id, 'Test');
        
    }
}