force-app/main/default/objects/Equipment_Declaration__c/Equipment_Declaration__c.object-meta.xml
<CustomObject>
    <description>Custom object that allows Partners to enter the Equipment they are servicing via SalesForce Partner Portal.</description>
    <label>Equipment</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Declaration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipment (Customer Account Name)</relationshipLabel>
    <relationshipName>Equipment_Declarations1</relationshipName>
    <trackHistory>false</trueHistory>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Active_Unit__c.field-meta.xml
<CustomField>
    <fullName>Active_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Unit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2214</fullName>
            </value>
            <value>
                <fullName>2215</fullName>
            </value>
            <value>
                <fullName>5001</fullName>
            </value>
            <value>
                <fullName>5003</fullName>
            </value>
            <value>
                <fullName>5004</fullName>
            </value>
            <value>
                <fullName>5006</fullName>
            </value>
            <value>
                <fullName>5007</fullName>
            </value>
            <value>
                <fullName>5008</fullName>
            </value>
            <value>
                <fullName>5302</fullName>
            </value>
            <value>
                <fullName>5305</fullName>
            </value>
            <value>
                <fullName>5362</fullName>
            </value>
            <value>
                <fullName>5588</fullName>
            </value>
            <value>
                <fullName>5663</fullName>
            </value>
            <value>
                <fullName>5670</fullName>
            </value>
            <value>
                <fullName>5674</fullName>
            </value>
            <value>
                <fullName>5675</fullName>
            </value>
            <value>
                <fullName>5684</fullName>
            </value>
            <value>
                <fullName>5685</fullName>
            </value>
            <value>
                <fullName>5688</fullName>
            </value>
            <value>
                <fullName>5840</fullName>
            </value>
            <value>
                <fullName>5870</fullName>
            </value>
            <value>
                <fullName>5871</fullName>
            </value>
            <value>
                <fullName>5873</fullName>
            </value>
            <value>
                <fullName>5874</fullName>
            </value>
            <value>
                <fullName>5875</fullName>
            </value>
            <value>
                <fullName>5885</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Class_Type__c.field-meta.xml
<CustomField>
    <fullName>Class_Type__c</fullName>
    <label>Class Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Easy Point</fullName>
            </value>
            <value>
                <fullName>Multi Function</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Single Function</fullName>
            </value>
            <value>
                <fullName>Teller Recycler</fullName>
            </value>
            <value>
                <fullName>SelfServ LE</fullName>
            </value>
            <value>
                <fullName>Financial Kiosk</fullName>
            </value>
            <value>
                <fullName>56XX &amp; Personas CD</fullName>
            </value>
            <value>
                <fullName>SelfServ CD</fullName>
            </value>
            <value>
                <fullName>56XX and Personas FF</fullName>
            </value>
            <value>
                <fullName>SelfServ FF</fullName>
            </value>
            <value>
                <fullName>Teller Cash Recycler</fullName>
            </value>
            <value>
                <fullName>Deposit Automation</fullName>
            </value>
            <value>
                <fullName>APTRA Interactive Teller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Class__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Deposit Automation</fullName>
            </value>
            <value>
                <fullName>Envelope Deposit</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Cash Dispense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Installation_Address1__c.field-meta.xml
<CustomField>
    <fullName>Installation_Address1__c</fullName>
    <label>Installation Address1</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Installation_City__c.field-meta.xml
<CustomField>
    <fullName>Installation_City__c</fullName>
    <label>Installation City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Installation_Date_of_New_Unit__c.field-meta.xml
<CustomField>
    <fullName>Installation_Date_of_New_Unit__c</fullName>
    <label>Installation Date of New Unit</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Installation_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Installation_State_Province__c</fullName>
    <label>Installation State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select your Account (Official Name)</inlineHelpText>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipment (Partner Account)</relationshipLabel>
    <relationshipName>Equipment_Declarations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment_Declaration__c/fields/Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Date__c</fullName>
    <inlineHelpText>Provide the failure or error reported, as well as a brief summary of the corrective action and final resolution for the service call.  This information is required for evaluating approval of this request.</inlineHelpText>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/testWarrLaborReimbursementRequest.cls
/*
##################################################################################################
# Project Name..........: NSC Sales Central                                                                        
# File............................: testWarrLaborReimbursementRequest.cls                                                        
# Version.....................: 22.0 
# Created by................: Darshan Singh Farswan                                                                    
# Created Date...........: 08-09-2011                                                                               
# Last Modified by......: Darshan Singh Farswan
# Last Modified Date..: 17-11-2011
# Description...............: The test class is used to provide test coverage for WarrLaborReimbursementRequest class.
################################################################################################
*/


@isTest(SeeAllData= true)
private class testWarrLaborReimbursementRequest{
    static testMethod void testRequest(){
        User[] usr = [Select id, ContactId from User where ContactId != null and Contact.AccountId != null and isActive = true limit 1];
        if(/*usr != null*/ usr.size()>0){
            System.runAs(usr[0]){
                PageReference currentPage= Page.WarrLaborReimbursementRequest;
                Test.setCurrentPage(currentPage);
                Equipment_Declaration__c equipment = new Equipment_Declaration__c();
                equipment.Name = '12343';
                Contact ct = [SELECT Id, AccountId from Contact where id = :usr[0].contactId];
                equipment.Partner_Account__c = ct.AccountId;
                equipment.Customer_Name__c = 'TEST Customer';
                equipment.Account__c = ct.AccountId;
                equipment.Active_Unit__c = false;
                equipment.Class__c = '5885';
                equipment.Class_Type__c = 'Multi Function';
                equipment.Features__c = 'Deposit Auto (Cash)/Recycler BNA';
                equipment.Installation_Address1__c = 'TEST';
                equipment.Installation_City__c = 'TEST';
                equipment.Installation_State_Province__c = 'TEST';
                equipment.Installation_Date_of_New_Unit__c = System.today();
                equipment.Service_Date__c = System.today();
                insert equipment;
                ApexPages.standardController sc1 = new ApexPages.StandardController(equipment);
                WarrLaborReimbursementRequest rr1 = new WarrLaborReimbursementRequest(sc1);
                PageReference pgObj = rr1.createWarrLabourReimbursementObj();
                System.assert(pgObj!=null);
                //rr1.sendMail();
                rr1.cancel();
                equipment.Active_Unit__c = true;
                update equipment;
                ApexPages.standardController sc2 = new ApexPages.StandardController(equipment);
                WarrLaborReimbursementRequest rr2 = new WarrLaborReimbursementRequest (sc1);
                Equipment_Declaration__c equipment2 = new Equipment_Declaration__c();
            }
        }
    }
}