force-app/main/default/objects/Campaign_Activity__c/Campaign_Activity__c.object-meta.xml
<CustomObject>
    <description>Custom Task related to existent  Account/Contact. Once a task is qualified need to create an opportunity.</description>
    <label>Campaign Activity</label>
    <nameField>
        <displayFormat>CA - {0000000}</displayFormat>
        <label>Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the task.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/campaignActivityExtTest.cls
@isTest
private class campaignActivityExtTest{

    static testmethod void testCampActExt(){
    
        //insert campaign Actvity
        Campaign_Activity__c campAct = new Campaign_Activity__c();
        campAct.Status__c = 'Open';
        insert campAct ;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(campAct);
        campaignActivityExt testCampAct = new campaignActivityExt(sc);
        
        testCampAct.saveWithOldStatus();
        Campaign_Activity__c campObj = [select Status__c from Campaign_Activity__c where id=:campAct.id];
        System.assert(campObj.Status__c =='Open');
    }
}