force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Use to maintain a master list of certifications</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Curriculum_Number__c.field-meta.xml
<CustomField>
    <fullName>Curriculum_Number__c</fullName>
    <description>NCR University certification course code number</description>
    <externalId>true</externalId>
    <inlineHelpText>NCR University certification course code number</inlineHelpText>
    <label>Curriculum Number</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PRM_AccountControllerTest.cls
@isTest
private class PRM_AccountControllerTest 
{
    static testMethod void testNCRUPartnerCertifications() 
    {
        Account acc=new Account(Name='Acme Inc');
          system.runAs(TestRecordsFactory.getUser()){ 
        	insert acc;
        }
        
        Certification__c objCert = new Certification__c();
        objCert.Name = 'Test Contact';
        objCert.Curriculum_Number__c = '12345';
        
        insert objCert;
        
        //NCRUPartnerCertifications controller = new NCRUPartnerCertifications(new ApexPages.StandardController(acc));
        
        PRM_AccountController.getAccounts('All Accounts');
        PRM_AccountController.getAccounts('My Accounts');
        PRM_AccountController.getAccountDetail(acc.Id);
        system.assert(PRM_AccountController.getAccountDetail(acc.Id)!= null);
    }
}