force-app/main/default/objects/Order/fields/qtc_Carrier__c.field-meta.xml
<CustomField>
    <fullName>qtc_Carrier__c</fullName>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FedEx</fullName>
            </value>
            <value>
                <fullName>Omni</fullName>
            </value>
            <value>
                <fullName>Pegasus</fullName>
            </value>
            <value>
                <fullName>Seko</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrder__c/qtc_FulfillmentOrder__c.object-meta.xml
<CustomObject>
    <label>Fulfillment Order</label>
    <nameField>
        <label>Fulfillment Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/qtc_FulfillmentOrder__c/fields/Order_Interface_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Interface_Status__c</fullName>
    <label>Order Interface Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted to SOUP</fullName>
            </value>
            <value>
                <fullName>Order Created</fullName>
            </value>
            <value>
                <fullName>Order Booked</fullName>
            </value>
            <value>
                <fullName>Line Processed</fullName>
            </value>
            <value>
                <fullName>ERP Ready</fullName>
            </value>
            <value>
                <fullName>Data Issue on Lines</fullName>
            </value>
            <value>
                <fullName>Technical Issue(SOUP)</fullName>
            </value>
            <value>
                <fullName>Data Issue on Header</fullName>
            </value>
            <value>
                <fullName>Technical Issue(ERP)</fullName>
            </value>
            <value>
                <fullName>Order Shipped</fullName>
            </value>
            <value>
                <fullName>Order Under Process</fullName>
            </value>
            <value>
                <fullName>Quote Expired</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
                <isActive>false</isActive>
                <label>Technical Issue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrder__c/fields/qtc_Carrier__c.field-meta.xml
<CustomField>
    <fullName>qtc_Carrier__c</fullName>
    <description>ERP Carrier Name</description>
    <label>Carrier</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrder__c/fields/qtc_Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>qtc_Tracking_Number__c</fullName>
    <description>ERP Tracking Number</description>
    <label>Tracking Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrder__c/fields/Shipping_Required__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Required__c</fullName>
    <description>Number of fulfillment product need to be shipped</description>
    <label>Shipping Required</label>
    <summaryFilterItems>
        <field>qtc_FulfillmentOrderProduct__c.qtc_Completion_Date_Shipment_Date__c</field>
        <operation>equals</operation>
        <value>&apos;&apos;</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>qtc_FulfillmentOrderProduct__c.qtc_Exclude_from_ERP__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>qtc_FulfillmentOrderProduct__c.qtc_Quantity__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>qtc_FulfillmentOrderProduct__c.qtc_FulfillmentOrder__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrderProduct__c/qtc_FulfillmentOrderProduct__c.object-meta.xml
<CustomObject>
    <label>Fulfillment Order Product</label>
    <nameField>
        <displayFormat>FOP-{00000000}</displayFormat>
        <label>Fulfillment Order Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Order Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/qtc_FulfillmentOrderProduct__c/fields/qtc_Carrier__c.field-meta.xml
<CustomField>
    <fullName>qtc_Carrier__c</fullName>
    <description>ERP Carrier Name</description>
    <label>Carrier</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrderProduct__c/fields/qtc_FulfillmentOrder__c.field-meta.xml
<CustomField>
    <fullName>qtc_FulfillmentOrder__c</fullName>
    <label>Fulfillment Order</label>
    <referenceTo>qtc_FulfillmentOrder__c</referenceTo>
    <relationshipLabel>Fulfillment Order Products</relationshipLabel>
    <relationshipName>Fulfillment_Order_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrderProduct__c/fields/qtc_Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>qtc_Tracking_Number__c</fullName>
    <description>ERP Tracking Number</description>
    <label>Tracking Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CPQERPOrderShipped.cls
public class CPQERPOrderShipped implements Schedulable{
    
     private static final Integer maxTrackingCount = 20;
     private static final Integer maxCarrierCount = 10;
 
    public void execute(SchedulableContext SC) {
        try{
            
            doOrderShipped();
            
        }catch(Exception ex){
            
        }  
    }
    
     private static void doOrderShipped(){
        List<qtc_FulfillmentOrder__c> allFOrder;
        List<qtc_FulfillmentOrder__c> updatedFOrder = new List<qtc_FulfillmentOrder__c>();
        Set<Id> foIds = new Set<Id>();
        Map<Id, ERPTrackingInfo> mapifyERPInfo = null;
        try{
            
            allFOrder = [Select id,Order_Interface_Status__c,qtc_Tracking_Number__c,qtc_Carrier__c               
						from qtc_FulfillmentOrder__c where Order_Interface_Status__c = 'Order Booked' AND Shipping_Required__c = 0 
						ORDER BY LastModifiedDate
						LIMIT 20];
            
            if(allFOrder!=null && allFOrder.size()>0){
                
                for(qtc_FulfillmentOrder__c f:allFOrder){
                    
                     foIds.add(f.id);
                }
                mapifyERPInfo = getERPInformation(foIds);
                for(qtc_FulfillmentOrder__c f:allFOrder){
                    
                    f.Order_Interface_Status__c = 'Order Shipped';
                    if(mapifyERPInfo.containsKey(f.id)){
                        if(mapifyERPInfo.get(f.id).trackingNo.size() > 0){
                            f.qtc_Tracking_Number__c = getDetails(mapifyERPInfo.get(f.id).trackingNo);
                        }
                        if(mapifyERPInfo.get(f.id).carrier.size() > 0){
                            f.qtc_Carrier__c = getDetails(mapifyERPInfo.get(f.id).carrier);
                        }
                    }
                    updatedFOrder.add(f);
                }
                if(updatedFOrder.size()>0){
                    Update updatedFOrder;
                }
                
            }				 
        } catch(Exception ex){
            
        }
    }
    public static String getDetails(Set<String> details){
        Integer index = 0;
        String data = '';
        for(String str : details){
            if(index == 0) {
                data = str;
            }else{
                data = data + ',' +  str;
                
            }
            index = index +1;
        }
        return data;
        
    }
  public static Map<Id, ERPTrackingInfo> getERPInformation(Set<Id> foIds) {
      
        Map<Id, ERPTrackingInfo> mapifyERPInfo = new Map<Id, ERPTrackingInfo>();
      	      
        List<qtc_FulfillmentOrderProduct__c> foProducts = [SELECT id,qtc_Tracking_Number__c, 
                qtc_Carrier__c,qtc_FulfillmentOrder__r.id FROM qtc_FulfillmentOrderProduct__c
                WHERE qtc_FulfillmentOrder__r.id IN: foIds 
                AND (qtc_Tracking_Number__c != NULL OR qtc_Carrier__c != NULL)
                ORDER BY qtc_FulfillmentOrder__r.id 
               ];
      
      for(qtc_FulfillmentOrderProduct__c fo:foProducts){
          
          if(mapifyERPInfo.containsKey(fo.qtc_FulfillmentOrder__r.id)){
              if(mapifyERPInfo.get(fo.qtc_FulfillmentOrder__r.id).trackingNo.size() < maxTrackingCount){
                  mapifyERPInfo.get(fo.qtc_FulfillmentOrder__r.id).trackingNo.add(fo.qtc_Tracking_Number__c);
              }
              if(mapifyERPInfo.get(fo.qtc_FulfillmentOrder__r.id).carrier.size() < maxCarrierCount){
                  mapifyERPInfo.get(fo.qtc_FulfillmentOrder__r.id).carrier.add(fo.qtc_Carrier__c);
              }
           }else{
              mapifyERPInfo.put(fo.qtc_FulfillmentOrder__r.id,new ERPTrackingInfo());
              mapifyERPInfo.get(fo.qtc_FulfillmentOrder__r.id).trackingNo.add(fo.qtc_Tracking_Number__c);
              mapifyERPInfo.get(fo.qtc_FulfillmentOrder__r.id).carrier.add(fo.qtc_Carrier__c); 
          }
      }
      return mapifyERPInfo;
    }
    
    public class ERPTrackingInfo {
        Set<String> trackingNo = new Set<String>();
        Set<String> carrier = new Set<String>();
        
    }
}