force-app/main/default/objects/Deming_Log__c/Deming_Log__c.object-meta.xml
<CustomObject>
    <label>Deming Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Deming Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deming Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deming_Log__c/fields/Customer_Names__c.field-meta.xml
<CustomField>
    <fullName>Customer_Names__c</fullName>
    <label>Customer Names</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deming_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InactiveLeadAndContactEmail</label>
</CustomObject>

force-app/main/default/classes/VFEmailTemplateClassNew.cls
global class VFEmailTemplateClassNew {
    public String RecordId {get;set;} 
   global Deming_Log__c Customes {
 
        get{  
            if(String.isNotBlank(RecordId)){
                Customes=[Select id,Customer_Names__c,User__c from Deming_Log__c where Id =:RecordId];
            }
            return Customes; 
        } 
        set;}
    
    public List<String> getCustName(){
           List<String> Customerlisttoreturn = new List<String>();
           List<String> TemplistCustomerName= new List<String>();
           if(String.isNotBlank(Customes.Customer_Names__c)){
               Customerlisttoreturn = (List<String>)System.JSON.deserialize(Customes.Customer_Names__c, List<String>.class);
               
           }    
           return Customerlisttoreturn;
        
    }
}