force-app/main/default/objects/Anaplan_ProductCategory_FamilyMapping__c/Anaplan_ProductCategory_FamilyMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting stores the Revenue Type(Service Offer Category).Which are used in trigger for calculating opportunity Line items for sending to Anaplan for OCR.</description>
    <label>Anaplan Product Category-Family Mapping</label>
</CustomObject>

force-app/main/default/objects/Anaplan_ProductCategory_FamilyMapping__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EBDEDDSetting__c/EBDEDDSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Turning Feature it EDSD to keep readonly and changing schedule with change in Close Date</description>
    <label>EBDEDDSetting</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Solution_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Solution_Portfolio__c</fullName>
    <label>Solution Portfolio</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATM Reinvention &amp; Branch Transformation</fullName>
            </value>
            <value>
                <fullName>Digital Transformation</fullName>
            </value>
            <value>
                <fullName>Digitizing the Bank</fullName>
            </value>
            <value>
                <fullName>Store Transaction Transformation</fullName>
            </value>
            <value>
                <fullName>Outdoor Transformation</fullName>
            </value>
            <value>
                <fullName>Store Operations Transformation</fullName>
            </value>
            <value>
                <fullName>Omnichannel Commerce</fullName>
            </value>
            <value>
                <fullName>Restaurant Operations Transformation</fullName>
            </value>
            <value>
                <fullName>Event &amp; Travel Transformation</fullName>
            </value>
            <value>
                <fullName>Consumer Engagement &amp; Experience</fullName>
            </value>
            <value>
                <fullName>NCR Platform</fullName>
            </value>
            <value>
                <fullName>Security Solutions</fullName>
            </value>
            <value>
                <fullName>Payment Solutions</fullName>
            </value>
            <value>
                <fullName>Cash Management</fullName>
            </value>
            <value>
                <fullName>Data &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>System Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Area__c</fullName>
    <inlineHelpText>Enter the WCS Customer Service Area that will be applicable for the delivery of the products on this opportunity</inlineHelpText>
    <label>Customer Service Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>US Atlanta</fullName>
            </value>
            <value>
                <fullName>US California</fullName>
            </value>
            <value>
                <fullName>US Charlotte</fullName>
            </value>
            <value>
                <fullName>US Great Lakes</fullName>
            </value>
            <value>
                <fullName>US Midatlantic</fullName>
            </value>
            <value>
                <fullName>US New York</fullName>
            </value>
            <value>
                <fullName>US Northeast</fullName>
            </value>
            <value>
                <fullName>US Northwest</fullName>
            </value>
            <value>
                <fullName>US Other</fullName>
            </value>
            <value>
                <fullName>US South Central</fullName>
            </value>
            <value>
                <fullName>US Southeast</fullName>
            </value>
            <value>
                <fullName>US SVC</fullName>
            </value>
            <value>
                <fullName>WCS - Area Grouping - No Country</fullName>
            </value>
            <value>
                <fullName>WCS - Canada</fullName>
            </value>
            <value>
                <fullName>WCS - Caribbean Latin America</fullName>
            </value>
            <value>
                <fullName>WCS - Central Europe</fullName>
            </value>
            <value>
                <fullName>WCS - France - Belgium</fullName>
            </value>
            <value>
                <fullName>WCS - Greater China</fullName>
            </value>
            <value>
                <fullName>WCS - Iberia</fullName>
            </value>
            <value>
                <fullName>WCS - India</fullName>
            </value>
            <value>
                <fullName>WCS - Israel</fullName>
            </value>
            <value>
                <fullName>WCS - Italy - Turkey</fullName>
            </value>
            <value>
                <fullName>WCS - Japan</fullName>
            </value>
            <value>
                <fullName>WCS - Korea</fullName>
            </value>
            <value>
                <fullName>WCS - Middle East - Africa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery_Date__c</fullName>
    <label>Expected Delivery Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Trigger__c</fullName>
    <label>Invoice Trigger</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsClone__c.field-meta.xml
<CustomField>
    <fullName>IsClone__c</fullName>
    <label>IsClone</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isCloneWithProduct__c.field-meta.xml
<CustomField>
    <fullName>isCloneWithProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCloneWithProduct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Key_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Key_Criteria__c</fullName>
    <label>Key Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Business Benefits</fullName>
            </value>
            <value>
                <fullName>Lead Time</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Pre-Contact Termination</fullName>
            </value>
            <value>
                <fullName>Post-Contact Termination</fullName>
            </value>
            <value>
                <fullName>HW</fullName>
            </value>
            <value>
                <fullName>SW</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
                <label>Service</label>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Solution_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Solution_Portfolio__c</fullName>
    <label>Offer Portfolio</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DIGITAL BANKING</fullName>
            </value>
            <value>
                <fullName>FINANCIAL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>GAMING</fullName>
            </value>
            <value>
                <fullName>GEMS</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>IPS</fullName>
            </value>
            <value>
                <fullName>PC / ELS</fullName>
            </value>
            <value>
                <fullName>RETAIL ASSISTED SERVICE</fullName>
            </value>
            <value>
                <fullName>RETAIL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>RETALIX</fullName>
            </value>
            <value>
                <fullName>SERVICES</fullName>
            </value>
            <value>
                <fullName>TRAVEL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>SYSTEMS MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>CHECK &amp; IMAGE</fullName>
            </value>
            <value>
                <fullName>SELF-SERVICE REINVENTION</fullName>
            </value>
            <value>
                <fullName>BRANCH TRANSFORMATION</fullName>
            </value>
            <value>
                <fullName>ENTERPRISE FRAUD AND SECURITY</fullName>
            </value>
            <value>
                <fullName>TRANSACTION PROCESSING</fullName>
            </value>
            <value>
                <fullName>CASH MANAGEMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ProductClonedFromId__c.field-meta.xml
<CustomField>
    <fullName>ProductClonedFromId__c</fullName>
    <label>ProductClonedFromId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Solution_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Solution_Portfolio__c</fullName>
    <label>Offer Portfolio</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALARIC</fullName>
            </value>
            <value>
                <fullName>CASH MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>CHECK &amp; IMAGE</fullName>
            </value>
            <value>
                <fullName>DIGITAL BANKING</fullName>
            </value>
            <value>
                <fullName>eCLIPBOARD</fullName>
            </value>
            <value>
                <fullName>ENTERPRISE FRAUD AND SECURITY</fullName>
            </value>
            <value>
                <fullName>ENTERTAINMENT SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>FINANCIAL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>GAMING</fullName>
            </value>
            <value>
                <fullName>GEMS</fullName>
            </value>
            <value>
                <fullName>HEALTHCARE ASSISTED SELF SRV &amp; PLATFORM</fullName>
            </value>
            <value>
                <fullName>HEALTHCARE SELF-SERVICE</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>IPS</fullName>
            </value>
            <value>
                <fullName>MULTI CHANNEL SOFTWARE</fullName>
            </value>
            <value>
                <fullName>PAYMENTS</fullName>
            </value>
            <value>
                <fullName>PC / ELS</fullName>
            </value>
            <value>
                <fullName>RETAIL ASSISTED SERVICE</fullName>
            </value>
            <value>
                <fullName>RETAIL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>RETALIX</fullName>
            </value>
            <value>
                <fullName>SELF-SERVICE REINVENTION</fullName>
            </value>
            <value>
                <fullName>SERVICES</fullName>
            </value>
            <value>
                <fullName>TRANSACTION PROCESSING</fullName>
            </value>
            <value>
                <fullName>TRAVEL SELF SERVICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloneOpportunityWithScheduleTest.cls
@isTest 
private class CloneOpportunityWithScheduleTest{
    
    static testMethod void TestMethodforCloneOpportunityWithSScheduel() {
        Account a = TestRecordsFactory.createAccount();
        Id r1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Include in Funnel').getRecordTypeId();//012700000001PoZ = Include in Funnel
        EBDEDDSetting__c ebdedd = new EBDEDDSetting__c();
        ebdedd.Name = 'EDSD_Calc';
        ebdedd.isActive__c = true;
        insert ebdedd;
        
        
        Opportunity opp = new Opportunity();
        opp.name = 'abc';
        opp.AccountID = a.id;
        opp.Name = 'OppQuote Linkage Test Opportunity';
        opp.type = 'Indirect Channel';
        //opp.Solution_Portfolio__c = 'Financial Self Service'; -- P360 Initial Change - Ahad
        opp.CURRENCYISOCODE = 'USD';
        
        opp.INVOICE_TRIGGER__C = 'Shipment';
        //opp.CUSTOMER_SERVICE_AREA__C = 'WCS - US Northeast';
        
        opp.Expected_Delivery_Date__c = System.TODAY().addDays(30);
        opp.closeDate = System.TODAY();
        opp.stagename = 'Analyzing';
        opp.recordTypeId = r1;
        opp.Key_Criteria__c='Best Solution;Business Benefits;Lead Time;Performance;Price';
        insert opp;
        
        Product2 prod = new Product2();
        prod.Name = 'test';
        prod.Family = 'Solution';
        prod.CanUseQuantitySchedule = true;
        insert prod;
        List<Anaplan_ProductCategory_FamilyMapping__c> customSettingList=new List<Anaplan_ProductCategory_FamilyMapping__c>();
        
        Anaplan_ProductCategory_FamilyMapping__c setting = new Anaplan_ProductCategory_FamilyMapping__c();
        setting.Name = 'Cloud';
        setting.Product_Family__c = 'Cloud';
        //insert setting; 
        customSettingList.add(setting);
        
        
        Anaplan_ProductCategory_FamilyMapping__c setting1 = new Anaplan_ProductCategory_FamilyMapping__c();
        setting1.Name = 'CS';
        setting1.Product_Family__c = 'CS';
        //insert setting1;
        customSettingList.add(setting1);
        
        
        Anaplan_ProductCategory_FamilyMapping__c setting2 = new Anaplan_ProductCategory_FamilyMapping__c();
        setting2.Name = 'HW';
        setting2.Product_Family__c = 'HW';
        //insert setting2;
        customSettingList.add(setting2);
        
        
        Anaplan_ProductCategory_FamilyMapping__c setting3 = new Anaplan_ProductCategory_FamilyMapping__c();
        setting3.Name = 'PS';
        setting3.Product_Family__c = 'PS';
        //insert setting3;
        customSettingList.add(setting3);
        
        
        Anaplan_ProductCategory_FamilyMapping__c setting4 = new Anaplan_ProductCategory_FamilyMapping__c();
        setting4.Name = 'SW';
        setting4.Product_Family__c = 'SW';
        //insert setting4 ;
        customSettingList.add(setting4);
        
        
        Anaplan_ProductCategory_FamilyMapping__c setting5 = new Anaplan_ProductCategory_FamilyMapping__c();
        setting5 .Name = 'TS';
        setting5 .Product_Family__c = 'TS';
        //insert setting5;
        customSettingList.add(setting5);
        
        insert customSettingList; 
        Pricebook2 pb = new Pricebook2(name='test PB', isActive=true);
        insert pb;
        
        String stdPriceBook = Test.getStandardPricebookId();	//stdPriceBook =01s700000002GMc
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = stdPriceBook, Product2Id = prod.Id, UnitPrice = 10000, CurrencyIsoCode = 'USD', IsActive = true);
        insert standardPrice;
        //01s7000000030GMAAY - CustomPricebook id
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = GlobalVariable.pricebookId, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true, CurrencyIsoCode = 'USD');
        insert customPrice;
        
        
        OpportunityLineItem OLI1 = new OpportunityLineItem();
        OLI1.OpportunityID = opp.id;
        OLI1.PricebookEntryId = customPrice.id;
        OLI1.Quantity = 2;
        OLI1.unitprice = 20;
        
        insert OLI1;
        OpportunityLineItem OLI2 = new OpportunityLineItem();
        OLI2.OpportunityID = opp.id;
        OLI2.PricebookEntryId = customPrice.id;
        OLI2.Quantity = 2;
        OLI2.unitprice = 20;
        OLI2.ProductClonedFromId__c=OLI1.Id;
        insert OLI2;
        
        
        OpportunityLineItemSchedule olis = new OpportunityLineitemSchedule(OpportunityLineItemId = OLI1.id, scheduleDate = System.today() + 60, type = 'Quantity', quantity = oli1.quantity);
        insert olis;
        
        test.startTest();
        OpportunityLineItemSchedule oliss = new OpportunityLineitemSchedule(OpportunityLineItemId = OLI1.id, scheduleDate = System.today() - 60, type = 'Quantity', quantity = oli1.quantity);
        insert oliss;
        //OpportunityLineItemSchedule olisas = new OpportunityLineitemSchedule(OpportunityLineItemId = OLI2.id, scheduleDate = System.today() - 60, type = 'Quantity', quantity = oli2.quantity);
        //insert olisas;
        // create new Opportunity object 
        System.assertEquals(0, OLI1.OpportunityLineItemSchedules.size());
        Opportunity opp1 = new Opportunity();
        opp1 .name = 'abc';
        opp.AccountID = a.id;
        opp1.IsClone__c=opp.id;
        opp1.isCloneWithProduct__c=true;
        opp.Name = 'OppQuote Linkage Test Opportunity';
        opp1.type = 'Indirect Channel';
        //opp1.Solution_Portfolio__c = 'Financial Self Service'; -- P360 Initial Change - Ahad
        opp1.CURRENCYISOCODE = 'USD';
        
        opp1.INVOICE_TRIGGER__C = 'Shipment';
        //opp1.CUSTOMER_SERVICE_AREA__C = 'WCS - US Northeast';
        
        opp1.Expected_Delivery_Date__c = System.TODAY().addDays(30);
        opp1.closeDate = System.TODAY();
        opp1.stagename = 'Analyzing';
        opp1.recordTypeId = r1;
        opp1.Key_Criteria__c='Best Solution;Business Benefits;Lead Time;Performance;Price';
        insert opp1;
        
        
        
        CustomCloneController.getData(opp.id,true ,false , false);
        test.stopTest();
    }
    
}