force-app/main/default/objects/Presales_Funding_Request__c/Presales_Funding_Request__c.object-meta.xml
<CustomObject>
    <description>Used by Account Executive to request funding for a presales resource.</description>
    <label>Presales Funding Request</label>
    <nameField>
        <displayFormat>PFR-{0000}</displayFormat>
        <label>PFR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presales Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Expected_Date__c.field-meta.xml
<CustomField>
    <fullName>PFR_Expected_Date__c</fullName>
    <description>Expected start date of request</description>
    <inlineHelpText>Expected start date of request</inlineHelpText>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Is_this_Recoverable__c.field-meta.xml
<CustomField>
    <fullName>PFR_Is_this_Recoverable__c</fullName>
    <label>Is this Recoverable?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Justification__c.field-meta.xml
<CustomField>
    <fullName>PFR_Justification__c</fullName>
    <label>Justification</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>PFR_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with funding request</description>
    <inlineHelpText>Opportunity associated with funding request</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Presales Funding Requests</relationshipLabel>
    <relationshipName>Presales_Funding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Presales_Category__c.field-meta.xml
<CustomField>
    <fullName>PFR_Presales_Category__c</fullName>
    <label>Presales Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1-Network Certification</fullName>
            </value>
            <value>
                <fullName>2-Early Stage Presales</fullName>
            </value>
            <value>
                <fullName>3- Proof of Concept</fullName>
            </value>
            <value>
                <fullName>4-PS SOW Creation &amp; Pricing</fullName>
            </value>
            <value>
                <fullName>5-PS work-ahead pending SOW signature</fullName>
            </value>
            <value>
                <fullName>6-Non-Standard Gratis work / Customer satisfaction issue</fullName>
            </value>
            <value>
                <fullName>1- Network Certification</fullName>
                <isActive>false</isActive>
                <label>1- Network Certification</label>
            </value>
            <value>
                <fullName>2- Early Stage Presales</fullName>
                <isActive>false</isActive>
                <label>2- Early Stage Presales</label>
            </value>
            <value>
                <fullName>4- PS SOW Creation &amp; Pricing</fullName>
                <isActive>false</isActive>
                <label>4- PS SOW Creation &amp; Pricing</label>
            </value>
            <value>
                <fullName>5- PS &apos;work-ahead&apos;, pending SOW signature</fullName>
                <isActive>false</isActive>
                <label>5- PS &apos;work-ahead&apos;, pending SOW signature</label>
            </value>
            <value>
                <fullName>6- Non-Standard Gratis work / Customer satisfaction issue</fullName>
                <isActive>false</isActive>
                <label>6- Non-Standard Gratis work / Customer satisfaction issue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Presales_Funding_Request__c/fields/PFR_Success_Criteria__c.field-meta.xml
<CustomField>
    <fullName>PFR_Success_Criteria__c</fullName>
    <label>Success Criteria</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PSFR_RelatedList_Test.cls
/*
##################################################################################################
# Class Name............................:PSFR_RelatedList_Test.cls                                                                                                                                  
# Last Modified by......:  Monika
# Last Modified Date..:    19-12-2022
BA_SF-2491 JDK Locale impact - Upgrade API Part 5 
                               
################################################################################################
*/
@isTest
public class PSFR_RelatedList_Test{
    static testMethod void testMethod1()
     {
         Account Acc=TestRecordsFactory.createAccount();
         Contact con=TestRecordsFactory.createContact(Acc);
         Opportunity opp=TestRecordsFactory.createSimpleOpportunity(Acc);
         Presales_Funding_Request__c PSFR_Obj=new Presales_Funding_Request__c();
         PSFR_Obj.PFR_Opportunity__c=opp.id;
         PSFR_Obj.PFR_Presales_Category__c ='1-Network Certification';
         PSFR_Obj.PFR_Is_this_Recoverable__c='Yes';
         PSFR_Obj.PFR_Expected_Date__c=system.today();
         PSFR_Obj.PFR_Justification__c='Test Justification';
         PSFR_Obj.PFR_Success_Criteria__c='Test Justification';
         insert PSFR_Obj;
          Test.startTest();
          PageReference myVfPage = Page.PSFRRelatedList;
          Test.setCurrentPage(myVfPage);
          System.currentPageReference().getParameters().put('id',PSFR_Obj.id);
          ApexPAges.StandardController sc = new ApexPages.StandardController(PSFR_Obj);
          PSFR_RelatedList testController = new PSFR_RelatedList(sc);
          system.assert(testController!=null);
         
          
          Test.StopTest();
     }   
}