force-app/main/default/objects/Partner_Spotlight__c/Partner_Spotlight__c.object-meta.xml
<CustomObject>
    <label>Partner Spotlight</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Partner Spotlight #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Spotlights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Spotlight__c/fields/Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Partner Spotlights</relationshipLabel>
    <relationshipName>Partner_Spotlights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Spotlight__c/fields/Partner_Spotlight_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Spotlight_Type__c</fullName>
    <label>Partner Spotlight Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partner Feature Friday</fullName>
            </value>
            <value>
                <fullName>MDF Success Story</fullName>
            </value>
            <value>
                <fullName>Partner Ambassador Event</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Business Related Topics</fullName>
            </value>
            <value>
                <fullName>Significant Customer Win</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_PartnerSpotlightListviewController.cls
public with sharing class PRM_PartnerSpotlightListviewController 
{    
    @AuraEnabled
    public static List<Partner_Spotlight__c> getPartnerSpotlight(String selectedView) 
    {
        List<Partner_Spotlight__c> lstSpotlight = new List<Partner_Spotlight__c>();
         
        String queryStr = 'SELECT Id, Name, Partner_Spotlight_Type__c, First_Name__c, Last_Name__c, Partner_Name__r.Name FROM Partner_Spotlight__c where Partner_Spotlight_Type__c = : selectedView  order by Name';
       
        lstSpotlight = (List<Partner_Spotlight__c>)Database.query(String.escapeSingleQuotes(queryStr));
        return lstSpotlight;
    }
}