force-app/main/default/objects/Tab_Access__c/Tab_Access__c.object-meta.xml
<CustomObject>
    <label>Tab Access</label>
    <nameField>
        <label>Tab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tab Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tab_Access__c/fields/Daily_View_Count__c.field-meta.xml
<CustomField>
    <fullName>Daily_View_Count__c</fullName>
    <label>Daily View Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tab_Access__c/fields/Metrics_Date__c.field-meta.xml
<CustomField>
    <fullName>Metrics_Date__c</fullName>
    <label>Metrics Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tab_Access__c/fields/PageName__c.field-meta.xml
<CustomField>
    <fullName>PageName__c</fullName>
    <label>Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tab_Access__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <externalId>true</externalId>
    <label>UniqueId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tab_Access__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tab_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/TableauWorkbookURL__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TableauWorkbookURL</label>
</CustomObject>

force-app/main/default/objects/TableauWorkbookURL__c/fields/TableauServerAddress__c.field-meta.xml
<CustomField>
    <fullName>TableauServerAddress__c</fullName>
    <label>Tableau Server Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/VisualforcePageURL__c.field-meta.xml
<CustomField>
    <fullName>VisualforcePageURL__c</fullName>
    <label>VisualforcePageURL</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook1Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook1Name__c</fullName>
    <label>Workbook_1_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook1URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook1URL__c</fullName>
    <label>Workbook_1_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook2Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook2Name__c</fullName>
    <label>Workbook_2_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook2URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook2URL__c</fullName>
    <label>Workbook_2_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook3Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook3Name__c</fullName>
    <label>Workbook_3_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook3URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook3URL__c</fullName>
    <label>Workbook_3_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook4Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook4Name__c</fullName>
    <label>Workbook_4_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook4URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook4URL__c</fullName>
    <label>Workbook_4_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook5Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook5Name__c</fullName>
    <label>Workbook_5_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook5URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook5URL__c</fullName>
    <label>Workbook_5_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InactiveLeadAndContactEmail</label>
</CustomObject>

force-app/main/default/classes/Tableaupagecontroller.cls
public class Tableaupagecontroller{
    
    //TableauWorkbookURL__c tbobject = new TableauWorkbookURL__c();
    public TableauWorkbookURL__c tbobject {get; set;}
    public String H2Leaders {get; set;}
    public String H3Leaders {get; set;}
    public String wfrcurrent {get; set;}
    public String wfrhistoric {get; set;}
    public String variance {get; set;}
    public String h2funnel {get; set;}
    public String h3funnel{get; set;}
    public String qtdnetnew {get; set;}
    public String attachrate {get; set;}
    public String retemea{get; set;}
    public String finmea {get; set;}
    public String fineuro{get; set;}
   
    public Tableaupagecontroller(){
        
        ID id = UserInfo.getUserId() ;
        
        Set<ID> Tableauslsanalyst = new Set<id>();
        Set<ID> Tableau_sls_corp = new Set<id>();
        Set<ID> Tableau_sls_fs_h2 = new Set<id>();
        Set<ID> Tableau_sls_fs_h3 = new Set<id>();
        Set<ID>Tableau_sls_ret_h2 = new Set<id>();
        Set<ID> Tableau_sls_ret_h3 = new Set<id>();
        Set<ID> Tableau_sls_hos_h2 = new Set<id>();
        Set<ID> Tableau_sls_hos_h3 = new Set<id>();
        Set<ID> Tableau_sls_tnt_h2 = new Set<id>();
        Set<ID> Tableau_sls_tnt_h3 = new Set<id>();
        
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableauslsanalyst' ]){Tableauslsanalyst.add(g.UserOrGroupId);}
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableau_sls_corp' ]){Tableau_sls_corp.add(g.UserOrGroupId);}
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableau_sls_fs_h2' ]){Tableau_sls_fs_h2.add(g.UserOrGroupId);}
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableau_sls_fs_h3' ]){Tableau_sls_fs_h3.add(g.UserOrGroupId);}
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableau_sls_ret_h2' ]){Tableau_sls_ret_h2.add(g.UserOrGroupId);}
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableau_sls_ret_h3' ]){Tableau_sls_ret_h3.add(g.UserOrGroupId);}
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableau_sls_hos_h2' ]){Tableau_sls_hos_h2.add(g.UserOrGroupId);}
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableau_sls_hos_h3' ]){Tableau_sls_hos_h3.add(g.UserOrGroupId);}
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableau_sls_tnt_h2' ]){Tableau_sls_tnt_h2.add(g.UserOrGroupId);}
        for(GroupMember g : [Select Id,UserOrGroupId From GroupMember where group.DeveloperName =:'Tableau_sls_tnt_h3' ]){Tableau_sls_tnt_h3.add(g.UserOrGroupId);}
        
        H2Leaders = 'none' ;
        H3Leaders = 'none' ;
        wfrcurrent = 'none' ;
        wfrhistoric = 'none' ;
        variance = 'none' ;
        h2funnel = 'none' ;
        h3funnel = 'none' ;
        qtdnetnew = 'none' ;
        attachrate = 'none' ;
        retemea = 'none';
        finmea = 'none';
        fineuro = 'none';
        
        if(Tableau_sls_corp.contains(id) || Test.isRunningTest()){
            H2Leaders = 'block' ;
            wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h2funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;
             retemea = 'block';
             finmea = 'block';
             fineuro = 'block';
        }
        if(Tableau_sls_fs_h2.contains(id) || Test.isRunningTest()){
            H2Leaders = 'block' ;
            wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h2funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;

        }
        if(Tableau_sls_fs_h3.contains(id) || Test.isRunningTest()){
            H3Leaders = 'block' ;
            wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h3funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;
             finmea = 'block';
             fineuro = 'block';
        }
        if(Tableau_sls_ret_h2.contains(id) || Test.isRunningTest()){
            H2Leaders = 'block' ;
            wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h2funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;
           
        }
        if(Tableau_sls_ret_h3.contains(id) || Test.isRunningTest()){
            H3Leaders = 'block' ;
            wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h3funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;
             retemea = 'block';
          
        }
        if(Tableau_sls_hos_h2.contains(id) || Test.isRunningTest()){
            H2Leaders = 'block' ;
           wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h2funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;
           
        }
        if(Tableau_sls_hos_h3.contains(id) || Test.isRunningTest()){
            H3Leaders = 'block' ;
            wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h3funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;
         
        }
        if(Tableau_sls_tnt_h2.contains(id)|| Test.isRunningTest() ){
            H2Leaders = 'block' ;
            wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h2funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;
          
        }
        if(Tableau_sls_tnt_h3.contains(id) || Test.isRunningTest()){
            H3Leaders = 'block' ;
            wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h3funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;
           
        }
        if(Tableauslsanalyst.contains(id) || Test.isRunningTest()){
            H2Leaders = 'block' ;
            H3Leaders = 'block' ;
            wfrcurrent = 'block' ;
            wfrhistoric = 'block' ;
            variance = 'block' ;
            h2funnel = 'block' ;
            h3funnel = 'block' ;
            qtdnetnew = 'block' ;
            attachrate = 'block' ;
              retemea = 'block';
             finmea = 'block';
             fineuro = 'block';
        }
       
        /*
tbobject = [select id,TableauServerAddress__c,VisualforcePageURL__c,
Workbook1Name__c,Workbook1URL__c,Workbook2Name__c,
Workbook2URL__c,Workbook3Name__c,Workbook3URL__c,
Workbook4Name__c, Workbook5Name__c, Workbook4URL__c,
Workbook5URL__c
from TableauWorkbookURL__c ] ;
*/
        
    }
    
    public void init(){
        String tabName = 'Tableau'; 
        String tabAccssUniqueId = tabName + Userinfo.getUserId() + String.valueOf(Datetime.now().format('yyMMdd'));
        
        List<Tab_Access__c > tabAccList = [Select UniqueId__c, Daily_View_Count__c  from Tab_Access__c where UniqueId__c = :tabAccssUniqueId LIMIT 1];
        
        Tab_Access__c ta;
        if(tabAccList != null && tabAccList.size() > 0) {
            ta =  tabAccList.get(0);
            ta.Daily_View_Count__c  = ta.Daily_View_Count__c + 1;   
            
        } else {
            ta = new Tab_Access__c(Name = 'Tableau', PageName__c = 'Tableau', Metrics_Date__c = Date.today(), User__c= Userinfo.getUserId(), UniqueId__c= tabAccssUniqueId, Daily_View_Count__c  = 1);        
        }
        upsert ta; 
    }
    
    
}