force-app/main/default/objects/Tableau_Portal_Feedback__c/Tableau_Portal_Feedback__c.object-meta.xml
<CustomObject>
    <label>Tableau Portal Feedback</label>
    <nameField>
        <displayFormat>TF-{000000}</displayFormat>
        <label>Tableau Portal Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tableau Portal Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TableauPortalAdmin_config__c/TableauPortalAdmin_config__c.object-meta.xml
<CustomObject>
    <label>Tableau Portal Admin</label>
    <nameField>
        <displayFormat>TAP-{00000}</displayFormat>
        <label>TableauPortalAdmin_config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TableauPortalAdmin_configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/Carousal__c.field-meta.xml
<CustomField>
    <fullName>Carousal__c</fullName>
    <label>Carousal #</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/Carousal_Description__c.field-meta.xml
<CustomField>
    <fullName>Carousal_Description__c</fullName>
    <inlineHelpText>Put one line description of Carousal image.</inlineHelpText>
    <label>Carousal Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/Corousal_Header__c.field-meta.xml
<CustomField>
    <fullName>Corousal_Header__c</fullName>
    <inlineHelpText>One Line upto 100 characters header of Carousal image.</inlineHelpText>
    <label>Corousal Header</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/Dashboard_Type__c.field-meta.xml
<CustomField>
    <fullName>Dashboard_Type__c</fullName>
    <label>Dashboard Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WFR</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
            <value>
                <fullName>Regional</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Product Base</fullName>
            </value>
            <value>
                <fullName>Compensation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Randomly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/GSA_Team_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>GSA_Team_Member_Name__c</fullName>
    <label>GSA Team Member Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/GSA_Team_Role__c.field-meta.xml
<CustomField>
    <fullName>GSA_Team_Role__c</fullName>
    <label>GSA Team Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/image_Name__c.field-meta.xml
<CustomField>
    <fullName>image_Name__c</fullName>
    <inlineHelpText>Please provide name of image uploaded in static resource for tableau portal with format i.e. png/jpg.</inlineHelpText>
    <label>image Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/Report_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Name__c</fullName>
    <label>Report Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/Report_Owner__c.field-meta.xml
<CustomField>
    <fullName>Report_Owner__c</fullName>
    <label>Report Owner</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/Report_URL__c.field-meta.xml
<CustomField>
    <fullName>Report_URL__c</fullName>
    <label>Report URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>This will determine the placement of contact in GSA Team page.</inlineHelpText>
    <label>Sort Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TableauPortalAdmin_config__c/recordTypes/Carousal.recordType-meta.xml
<RecordType>
    <fullName>Carousal</fullName>
    <active>true</active>
    <description>Define Carousal image and Description</description>
    <label>Carousal</label>
</RecordType>

force-app/main/default/objects/TableauPortalAdmin_config__c/recordTypes/Faq.recordType-meta.xml
<RecordType>
    <fullName>Faq</fullName>
    <active>true</active>
    <label>Faq</label>
</RecordType>

force-app/main/default/classes/TableauControllerTest.cls
@isTest
public class TableauControllerTest {
    @testSetup static void setup() {
        TableauPortalAdmin_config__c tc=new TableauPortalAdmin_config__c( Answer__c='test', Carousal_Description__c='test',RecordTypeId=Schema.SObjectType.TableauPortalAdmin_config__c.getRecordTypeInfosByName().get('GSA Team Member').getRecordTypeId(), Carousal__c=1.0, Corousal_Header__c='test', Dashboard_Type__c='Compensation', Description__c='test', Email__c='test@test.com', Frequency__c='Weekly', GSA_Team_Member_Name__c='test', GSA_Team_Role__c='test', Question__c='test', Report_Name__c='test', Report_Owner__c='test', Report_URL__c='test', Sort_Order__c=1,image_Name__c='test');
       // TableauPortalAdmin_config__c tc1=new TableauPortalAdmin_config__c( Answer__c='test', Carousal_Description__c='test',RecordTypeId=Schema.SObjectType.TableauPortalAdmin_config__c.getRecordTypeInfosByName().get('faq').getRecordTypeId(), Carousal__c=2.0, Corousal_Header__c='test', Dashboard_Type__c='Compensation', Description__c='test', Email__c='test@test.com', Frequency__c='Weekly', GSA_Team_Member_Name__c='test', GSA_Team_Role__c='test', Question__c='test', Report_Name__c='test', Report_Owner__c='test', Report_URL__c='test', Sort_Order__c=2,image_Name__c='test');
        TableauPortalAdmin_config__c tc2=new TableauPortalAdmin_config__c( Answer__c='test', Carousal_Description__c='test',RecordTypeId=Schema.SObjectType.TableauPortalAdmin_config__c.getRecordTypeInfosByName().get('Carousal').getRecordTypeId(), Carousal__c=3.0, Corousal_Header__c='test', Dashboard_Type__c='Compensation', Description__c='test', Email__c='test@test.com', Frequency__c='Weekly', GSA_Team_Member_Name__c='test', GSA_Team_Role__c='test', Question__c='test', Report_Name__c='test', Report_Owner__c='test', Report_URL__c='test', Sort_Order__c=3,image_Name__c='test');
        List<TableauPortalAdmin_config__c> tcl=new List<TableauPortalAdmin_config__c>();
        tcl.add(tc);
       // tcl.add(tc1);
        tcl.add(tc2);
        insert tcl;
    }
    
    
    @isTest static void testgetReports(){
        
        String dashBoardType='Compensation';
        List<TableauPortalAdmin_config__c> reports =new List<TableauPortalAdmin_config__c>();     
        reports=[Select id, Report_Name__c, Report_Owner__c, Frequency__c, Description__c, Report_URL__c from TableauPortalAdmin_config__c where Dashboard_Type__c=:DashboardType];
        
        system.debug(reports);
        List<TableauPortalAdmin_config__c> Returnreport =new List<TableauPortalAdmin_config__c>(); 
        Returnreport= TableauPortalController.getReports(dashBoardType) ; 
        system.debug('@@@@@'+Returnreport);
    }
    @isTest static void testgetCarousalInfo(){
        
        List<TableauPortalAdmin_config__c> c =new List<TableauPortalAdmin_config__c>(); 
        c= TableauPortalController.getCarousalInfo();
        
        
    }
    @isTest static void testgetfaqs(){
        
        List<TableauPortalAdmin_config__c> faqs =new List<TableauPortalAdmin_config__c>();  
        
        faqs = TableauPortalController.getfaqs();
        
        
    }
    @isTest static void testgetteam(){
        List<TableauPortalAdmin_config__c> teams =new List<TableauPortalAdmin_config__c>(); 
        teams= TableauPortalController.getteam();
        system.debug(teams);
        
    }
    @isTest static void testsubmitMessage(){
        
        String name='testName';
        String email='testEmail@abc.com';
        String message='testMessage';
        Tableau_Portal_Feedback__c tf=new Tableau_Portal_Feedback__c(name__c=name, email__c=email, message__c=message);
        TableauPortalController.submitMessage(name, email, message) ;
        
    }
    @isTest static void testloggedInAs(){
        user userList=new user();
        userList =TableauPortalController.loggedInAs();
        system.debug('@@@@'+userList);
        
    }
    
}