force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <label>Deal Registration</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Partner&apos;s account name.</description>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations (Partner Company Name)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deal Registrations (Partner Contact)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DealRegistrationEditController.cls
/**************************************************************************************************************************************************************
   Class was created as a Edit controller for DealRegistration Edit Page. 
   
   #############################################################################################################################################################
   Created By                           Date                  Description
   Rahul Gaira(rg250274)                18th August 2016       Version 1 , which consist of the PopulatePartnerField  for deal Registration
   Monika                               19-12-2022            EBA_SF-2491 JDK Locale impact - Upgrade API Part 5  

****************************************************************************************************************************************************************/

public with sharing class DealRegistrationEditController {
    
  public Deal_Registration__c dealreg{get;set;}
  public String channelPartnerKeyContactText{get;set;} 
  public String channelPartnerAccount{get;set;} 
  //public RecordType rt{get;set;}
    
    
  //Get the schema from the Sobject
 // Map<ID,Schema.RecordTypeInfo> rt_Map = Deal_Registration__c.sObjectType.getDescribe().getRecordTypeInfosById();

  /*
   @constructor Name: populatePartnerField
   @purpose: Constructor was used for the auto population of the partner fields 
   @author : Rahul Gaira(rg250274)                  

  */
  public DealRegistrationEditController(ApexPages.StandardController controller) {
     
    //get the recordType Name
    //Id recordTypeID = Id.valueOf(getRecordTypeId());
   
    //rt = [SELECT Id,Name FROM RecordType WHERE SobjectType='Deal_Registration__c' AND Id =:recordTypeID LIMIT 1];
    //get the userDetail for populating the necessaary fields
    List<User> userlist= getuserDetail();
    this.dealreg = (Deal_Registration__c)controller.getRecord();
    
     IF(userList != null && !UserList.isEmpty() ){
      channelPartnerKeyContactText  = UserList[0].Contact.Name;//UserList[0].Contact.name;
      channelPartnerAccount = UserList[0].Contact.Account.Name;    
        IF(userList[0].ContactId != null)
          dealreg.partner_Contact__c = userList[0].ContactId;
        IF(userList[0].Contact.AccountId != null)
          dealreg.partner_Company_Name__c = userList[0].Contact.AccountId;
        
    }
  }

   /*
   @constructor Name: getRecordTypeId
   @purpose: method was used for getting the recordType name 
   @author : Rahul Gaira(rg250274)                  

  
  public String getRecordTypeId(){
    return ApexPages.currentPage().getParameters().get('RecordType');
  }  */ 

   /*
   @constructor Name: getuserDetail
   @purpose: method was used for getting the user detail. 
   @author : Rahul Gaira(rg250274)                  

  */
  public List<User> getuserDetail(){
    return [SELECT Id , Name , ContactId, Contact.Name, Contact.AccountId, Contact.Account.Name FROM User WHERE id =: UserInfo.getUserId()];
  }
  
  public PageReference submitForApproval(){
      return null;
  }
  

}