force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <label>Deal Registration</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/fields/End_Customer_Key_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Key_Contact_Name__c</fullName>
    <label>Key Contact Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Is_this_part_of_an_RFP__c.field-meta.xml
<CustomField>
    <fullName>Is_this_part_of_an_RFP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is this part of an RFP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Name_of_Account_Financial_Institution__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Account_Financial_Institution__c</fullName>
    <label>Name of Account/Financial Institution</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Partner&apos;s account name.</description>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations (Partner Company Name)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>Partner_Submission_Date__c</fullName>
    <label>Partner Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DealRegReminderTest.cls
@isTest
public class DealRegReminderTest {
    @isTest
    public static void testDealRegReminder(){
        // Create partner account with Industry
        User Usr = [Select Id, profileId from User Where Name = 'Soup User'];
        Account act;
        System.runAs(Usr){
        act = PRM_TestRecordsFactory.createPartnerAccount('1',null);
        insert act;
        }
        Contact con = PRM_TestRecordsFactory.createPartnerContact(act.Id,'1',null);
        insert con;
        User partnerUser = PRM_TestRecordsFactory.createPartnerUser(con.Id, '1', null);
        insert partnerUser;  
        //Insert Deal Registration
        Deal_Registration__c deal = new Deal_Registration__c();
        deal.Partner_Company_Name__c = 	act.Id;
        deal.Name_of_Account_Financial_Institution__c ='ABC Inc';
        deal.End_Customer_Key_Contact_Name__c ='Raman Iyr';
        deal.Is_this_part_of_an_RFP__c =true; 
        system.runAs(partnerUser) {         
            insert deal;
            try{
            PRM_DealRegistrationController.DealRegistrationDetail objInfo = PRM_DealRegistrationController.submitDRForApproval(deal.Id, 'Test');
            	System.assert(objInfo.isFIN==TRUE);
            }catch(Exception e){
                System.assert(e!=null);
            }
                
        }
        deal.Partner_Submission_Date__c = system.now() +1;
        update deal;
        deal.Partner_Submission_Date__c = system.now() +2;
        update deal;
        deal.Partner_Submission_Date__c = system.now() +3;
        update deal;
        deal.Partner_Submission_Date__c = system.now() +4;
        update deal;
        deal.Partner_Submission_Date__c = system.now() +5;
        update deal;
    }
}