force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Options to identify that concern is related to which functionality.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANTIQUE CASH REGISTERS</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>CEC</fullName>
            </value>
            <value>
                <fullName>Channel Partners</fullName>
            </value>
            <value>
                <fullName>CHARITIES/GIVING</fullName>
            </value>
            <value>
                <fullName>COUNTERPOINT</fullName>
            </value>
            <value>
                <fullName>Co-Op</fullName>
            </value>
            <value>
                <fullName>CRE</fullName>
            </value>
            <value>
                <fullName>DRIVERS AND PATCHES</fullName>
            </value>
            <value>
                <fullName>Deal Registration</fullName>
            </value>
            <value>
                <fullName>Deal Registration Costa-Rica</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>EULA Submission</fullName>
            </value>
            <value>
                <fullName>EH&amp;S</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>FEDEX OR SHIPPING</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Global Security</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>HR - Careers</fullName>
            </value>
            <value>
                <fullName>HR - Employee</fullName>
            </value>
            <value>
                <fullName>HR-EMPLOYMENT VERIFICATION</fullName>
            </value>
            <value>
                <fullName>HR-W2’S</fullName>
            </value>
            <value>
                <fullName>HWM</fullName>
            </value>
            <value>
                <fullName>Iconex</fullName>
            </value>
            <value>
                <fullName>Incentives</fullName>
            </value>
            <value>
                <fullName>Innovation</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Get_help_Configuration__mdt/Get_help_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Get Help Configuration</label>
    <pluralLabel>Get Help Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Get_help_Configuration__mdt/fields/Case_Assigned_User_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Assigned_User_Name__c</fullName>
    <description>User name of the case assigned user</description>
    <inlineHelpText>User name of the case assigned user</inlineHelpText>
    <label>Case Assigned User Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Get_help_Configuration__mdt/fields/Email_Send_List__c.field-meta.xml
<CustomField>
    <fullName>Email_Send_List__c</fullName>
    <description>Used for entering the email routes of the person</description>
    <inlineHelpText>Used for entering the email routes of the person, Please add multiple user with comma separated eg r@gmail.com,s@gmail.com</inlineHelpText>
    <label>Email Send List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetHelpRequestCtrlTest.cls
@isTest(seeAllData = true)
public class GetHelpRequestCtrlTest {

 
  
   private static void createAcc(){
        List<Account> accounts = new List<Account>();
        accounts.add(new Account(Name = 'Unit Test Corp'));
        accounts.add(new Account(Name = 'Unit Test LLC'));
        accounts.add(new Account(Name = 'Parent Company Inc'));
        insert accounts;

    }

  /*  private static void createMetadata(){
        Get_help_Configuration__mdt  m = new   Get_help_Configuration__mdt();
     
       
        m.Case_Assigned_User_Name__c='rg250274@ncr.com';
       m.Email_Send_List__c ='r@ncr.com,s@ncr.com';
        insert m;
        
    } */
    private static User createUserandpartnerContact(){
        //createAcc();
        Account ac = [SELECT Id FROM Account LIMIT 1];
        Contact con = new Contact(LastName ='testCon',AccountId = ac.Id);
        insert con;  
        Profile p = [select Name from Profile WHERE name ='Partner Community User'];     
               
       List<USER> userList = [Select id , name from USER Where ProfileId =:p.id And isActive =true];
       return userList[0];
     
    }

    static testmethod  void testsubmit() {
    //    createMetadata();
      PageReference pageRef = Page.GetHelpRequest;
        ApexPages.currentPage().getParameters().put('prevId','');
      Case cas = new Case();
            ApexPages.StandardController dealstd= new ApexPages.StandardController(cas);
            GetHelpRequestCtrl controller = new GetHelpRequestCtrl(dealstd);
        	system.assert(controller!=null);
        	controller.getcases();
        	controller.subject='General';
            controller.submit();
    }
    static testmethod  void testSave() {
    //    createMetadata();
      PageReference pageRef = Page.GetHelpRequest;
        ApexPages.currentPage().getParameters().put('prevId','');
      Case cas = new Case();
            ApexPages.StandardController dealstd= new ApexPages.StandardController(cas);
            GetHelpRequestCtrl controller = new GetHelpRequestCtrl(dealstd);
        	system.assert(controller!=null);
        	controller.getcases();
        	controller.subject='General';
            controller.saveAndNew();
    }
    
    static testMethod  void getHelpController(){
        GetHelpController g = new GetHelpController();
        system.assert(g!=null);
        g.redirectToCase();
    }
    
    static testmethod void testTriggerCloseCase(){
        Account a = TestRecordsFactory.createAccount();
        //Account accounts = new Account(Name = 'Unit Test Corp');
        //insert accounts;
        Contact cont = new Contact(LastName ='testCon',AccountId = a.Id,email ='r@ncr.com');
        insert cont;  
        Case c = new case();
        c.contactId = cont.id;
        c.subject='MDF';
        c.category__c ='MDF';
        c.status ='new';
        c.Origin='IPT SSOT';
        c.RecordTypeId = getRecordType('IPT Partner');
        insert c;
        c.status = 'close';
        update c;
     }
    
    static testmethod void testCaseComment(){
        Account a = TestRecordsFactory.createAccount();
        //Account accounts = new Account(Name = 'Unit Test Corp');
       // insert accounts;
        Contact cont = new Contact(LastName ='testCon',AccountId = a.Id,email ='r@ncr.com');
        system.assert(cont.AccountId!=NUll);
        insert cont;  
        Case c = new case();
        c.contactId = cont.id;
        c.subject='MDF';
        c.category__c ='MDF';
        c.status ='new';
        c.Origin='IPT SSOS';
        c.RecordTypeId = getRecordType('IPT Partner');
        system.debug('c.RecordTypeId' +  c.RecordTypeId);
        insert c;
        casecomment cm = new caseComment();
        cm.CommentBody = 'test';
        cm.ParentId = c.id;
        insert cm;
     }
    
    static testmethod void testSendEmail(){
        List<Case> caseList = new List<Case>();
        Account a = TestRecordsFactory.createAccount();
        //Account accounts = new Account(Name = 'Unit Test Corp');
        //insert accounts;
        Contact cont = new Contact(LastName ='testCon',AccountId = a.Id,email ='r@ncr.com');
        system.assert(cont.AccountId!=NUll);
        insert cont;  
        Case c = new case();
        c.contactId = cont.id;
        c.subject='MDF';
        c.category__c ='MDF';
        c.status ='new';
        c.Origin='IPT SSOS';
        c.RecordTypeId = getRecordType('IPT Partner');
        system.debug('c.RecordTypeId' +  c.RecordTypeId);
        caseList.add(c);
        insert caseList;
       // sendCaseEmail send = new sendCaseEmail();
        sendCaseEmail.getAccountNames(caseList);
     }
    private static Id getRecordType(String name){
		 Map<String,Schema.RecordTypeInfo> rt_Map = Case.sObjectType.getDescribe().getRecordTypeInfosByName();
		 return  rt_Map.get(name).getRecordTypeId();
	}
}