force-app/main/default/objects/Partner_Fund_ROI__c/Partner_Fund_ROI__c.object-meta.xml
<CustomObject>
    <label>MDF Result</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>MDF Request No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDF Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Fund_ROI__c/fields/Current_Revenue_earned__c.field-meta.xml
<CustomField>
    <fullName>Current_Revenue_earned__c</fullName>
    <label>Current Revenue earned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partner_Fund_ROI__c/fields/Fund_Request__c.field-meta.xml
<CustomField>
    <fullName>Fund_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Request</label>
    <referenceTo>SFDC_MDF__c</referenceTo>
    <relationshipName>Partner_Fund_ROI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Fund_ROI__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MDF Results</relationshipLabel>
    <relationshipName>Partner_Fund_ROI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Fund_ROI__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Partner_Fund_ROI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/SFDC_MDF__c.object-meta.xml
<CustomObject>
    <description>Track MDF request details including partner account, requested amount, activity type and date, and approval status.</description>
    <label>Fund Request</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF__c/fields/CAM__c.field-meta.xml
<CustomField>
    <fullName>CAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fund_Requests</relationshipName>
    <trackHistory>false</trueHistory>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Requester_Name__c.field-meta.xml
<CustomField>
    <fullName>Requester_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fund Requests</relationshipLabel>
    <relationshipName>Fund_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PopulateTotalMDFROITest.cls
@isTest
public class PopulateTotalMDFROITest {
    
    @isTest
    public static void PopulateTotalROIfromPFROITest(){
        List<Partner_Fund_ROI__c> partnerFundList = new List<Partner_Fund_ROI__c>();
        partnerFundList.add(new Partner_Fund_ROI__c(Current_Revenue_earned__c  = 1000));
       
        System.runAs(TestRecordsFactory.getUser()){
        Account accountRecoed  = PRM_TestRecordsFactory.createPartnerAccount('test',null);
        Insert accountRecoed;
                
        Contact contactRecord = PRM_TestRecordsFactory.createPartnerContact(accountRecoed.Id, 't', null);
        Insert contactRecord;
        System.assertNotEquals(contactRecord.id, null,'Contact is Null');  
        User camUser = PRM_TestRecordsFactory.createUser(null, '04 NSC UI Administrator', 'x', null);
        Insert camUser; 
        
        SFDC_MDF__c fundRequest = PRM_TestRecordsFactory.createFundRequest('Test Name', accountRecoed.Id, 'Approved');
        fundRequest.CAM__c= camUser.Id;
        fundRequest.Requester_Name__c =contactRecord.Id;
        Insert fundRequest;        
        
        partnerFundList.add(new Partner_Fund_ROI__c(Current_Revenue_earned__c  = 2000, Fund_Request__c = fundRequest.Id,Partner_Account__c = accountRecoed.Id,Partner_Contact__c =contactRecord.Id));
        
        partnerFundList.add(new Partner_Fund_ROI__c(Current_Revenue_earned__c  = 1300));
        partnerFundList.add(new Partner_Fund_ROI__c(Current_Revenue_earned__c  = 1050));
        partnerFundList.add(new Partner_Fund_ROI__c(Current_Revenue_earned__c  = 1800));
        Insert partnerFundList;
        }}
}