force-app/main/default/objects/MDF_Expense_Detail__c/MDF_Expense_Detail__c.object-meta.xml
<CustomObject>
    <label>MDF Expense Detail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>MDF Expense Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDF Expenses Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDF_Expense_Detail__c/fields/Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Cost__c</fullName>
    <label>Estimated Cost</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MDF_Expense_Detail__c/fields/NCR_Approved__c.field-meta.xml
<CustomField>
    <fullName>NCR_Approved__c</fullName>
    <label>NCR Approved</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/SFDC_MDF__c.object-meta.xml
<CustomObject>
    <description>Track MDF request details including partner account, requested amount, activity type and date, and approval status.</description>
    <label>Fund Request</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <description>The date the activity is planned. Optionally incorporate a validation rule to ensure that there is ample lead time to approve the request before the planned activity.</description>
    <inlineHelpText>This is the day of the event or the date the activity begins.</inlineHelpText>
    <label>Activity Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Description__c.field-meta.xml
<CustomField>
    <fullName>Activity_Description__c</fullName>
    <label>Activity Description</label>
    <length>90000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <description>A list of available activity types. Customize as needed.</description>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E-marketing Digital Campaign</fullName>
            </value>
            <value>
                <fullName>E-marketing - Video</fullName>
            </value>
            <value>
                <fullName>Event - Campaign in a box</fullName>
            </value>
            <value>
                <fullName>Event - Conference / Tradeshow only</fullName>
            </value>
            <value>
                <fullName>Event - Customer Briefing Center (CBC) Visit</fullName>
            </value>
            <value>
                <fullName>Event – Partner Seminar / Roadshow</fullName>
            </value>
            <value>
                <fullName>Event - Tradeshow in a box including event</fullName>
            </value>
            <value>
                <fullName>Event – Training</fullName>
            </value>
            <value>
                <fullName>Event – Webinar</fullName>
            </value>
            <value>
                <fullName>NCR defined Sales Program – Funded Head Count Distributor Only</fullName>
            </value>
            <value>
                <fullName>Print – Business case driven</fullName>
            </value>
            <value>
                <fullName>Sales Program - Incentive</fullName>
            </value>
            <value>
                <fullName>Sales Program - Telesales/Telemarketing</fullName>
            </value>
            <value>
                <fullName>Search Engine Marketing/Social Media/PR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The requested amount. Consider activating a validation rule to enforce a certain minimum or maximum amount</description>
    <label>Approved Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Activity End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <label>Estimated Number of Leads</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Other_Vendors_Represented__c.field-meta.xml
<CustomField>
    <fullName>Other_Vendors_Represented__c</fullName>
    <description>Other Vendors Represented in the Activity.</description>
    <inlineHelpText>Other Vendors Represented in the Activity.</inlineHelpText>
    <label>Other Vendors Represented</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fujitsu</fullName>
            </value>
            <value>
                <fullName>Zebra Technologies</fullName>
            </value>
            <value>
                <fullName>Micros</fullName>
            </value>
            <value>
                <fullName>Datalogic</fullName>
            </value>
            <value>
                <fullName>Epson</fullName>
            </value>
            <value>
                <fullName>Cognitive TPG</fullName>
            </value>
            <value>
                <fullName>Elo Touch Solutions</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
            <value>
                <fullName>HP ( Hewlett Packard)</fullName>
            </value>
            <value>
                <fullName>SII (Seiko Instruments)</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Payleven</fullName>
            </value>
            <value>
                <fullName>Motorola solutions</fullName>
            </value>
            <value>
                <fullName>Intermec (by Honeywell)</fullName>
            </value>
            <value>
                <fullName>APG Cash Drawer</fullName>
            </value>
            <value>
                <fullName>Applied Data Corp</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Epicor Retail Solutions</fullName>
            </value>
            <value>
                <fullName>JDA Software</fullName>
            </value>
            <value>
                <fullName>LOC Software</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund request approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request Created</fullName>
                <default>true</default>
                <label>Request Created</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Level 1 Review</fullName>
            </value>
            <value>
                <fullName>Level 2 Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/SFDC_MDF_Claim__c.object-meta.xml
<CustomObject>
    <description>A set of claims tied to a specific fund request.</description>
    <label>Fund Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of the current claim</description>
    <label>Approved Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund claim approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CP_ClaimExtTest.cls
/*This test class is used to test the class "CP_ClaimExt" for code coverage */
@isTest 
public class CP_ClaimExtTest{
    /*This method is used to Test the class for code coverage - testProcessClaimRequestIfMDFReqNotNull */
    static testMethod void testProcessClaimRequestIfMDFReqNotNull() { 
      try{       
            //Create MDF Request and expense details
            SFDC_MDF__c mdfReq=PrepareMDFTestDataUtil.prepareMDFRecord();  
            MDF_Expense_Detail__c mdfExpenseDetails  = PrepareMDFTestDataUtil.prepareMDFExpenseRecord(mdfReq.Id); 
            
            //Create Controller reference
            PageReference pageRef = Page.CP_newClaim;
            Test.setCurrentPage(pageRef);
            ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(new SFDC_MDF_Claim__c());  
             ApexPages.currentPage().getParameters().put('mdfReqId',mdfReq.Id);
            CP_claimExt cpClaimExt= new CP_claimExt(sc);
            //Test processClaimRequest()
            PageReference pageRefObj = cpClaimExt.processClaimRequest(); 
            System.assert(pageRefObj.getParameters().get('message')=='Claim Request is created. Please submit for approval.');
            //Test saveExpenseDetail()
            cpClaimExt.saveExpenseDetail(); 
            
            //Test getLogedInUser()
            cpClaimExt.getLogedInUser(); 
            
            //Set dummy data for code coverage
            cpClaimExt.fileName='TestFile'; 
            cpClaimExt.fileBody=Blob.valueOf('TestBlob');
       }catch(Exception e){
          System.debug(e.getMessage());
       }  
    }
    
    /*This method is used to Test the class for code coverage - testProcessClaimRequestIfMDFReqNull*/
    static testMethod void testProcessClaimRequestIfMDFReqNull() { 
      try{       
            //Create Controller reference  and throw the exception to test negative test
            PageReference pageRef = Page.CP_newClaim;
            Test.setCurrentPage(pageRef);
            ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(new SFDC_MDF_Claim__c()); 
            ApexPages.currentPage().getParameters().put('mdfReqId','');
            CP_claimExt cpClaimExt= new CP_claimExt(sc); 
       }catch(Exception e){
          System.debug(e.getMessage());
          System.assert(e.getMessage()!=null);
       }  
    } 
    
    /*This method is used to Test the class for code coverage - testProcessClaimRequestIfIncorrectMDFClaim */
    static testMethod void testProcessClaimRequestIfIncorrectMDFClaim() { 
      try{       
            //Create MDF Request and expense details
            SFDC_MDF__c mdfReq=PrepareMDFTestDataUtil.prepareMDFRecord();  
            MDF_Expense_Detail__c mdfExpenseDetails  = PrepareMDFTestDataUtil.prepareMDFExpenseRecord(mdfReq.Id);  
             
            //Prepare incorrect mdfClaim
            SFDC_MDF_Claim__c mdfClaim = new SFDC_MDF_Claim__c();
            mdfClaim.Status__c='Approved'; 
            mdfClaim.Amount__c =-1;
            
            //Create Controller reference
            PageReference pageRef = Page.CP_newClaim;
            Test.setCurrentPage(pageRef);
            ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(new SFDC_MDF_Claim__c());  
            ApexPages.currentPage().getParameters().put('mdfReqId',mdfReq.Id);
            CP_claimExt cpClaimExt= new CP_claimExt(sc);
            cpClaimExt.mdfClaim=mdfClaim;
            //Test processClaimRequest()
            PageReference pageRefObj = cpClaimExt.processClaimRequest(); 
            System.assert(pageRefObj.getParameters().get('message')=='Claim Request is created. Please submit for approval.');
       }catch(Exception e){
          System.debug(e.getMessage());
       }  
    } 
    /*This method is used to Test the class for code coverage - testProcessClaimRequestIfIncorrectMDFExpenseDetails */
    static testMethod void testProcessClaimRequestIfIncorrectMDFExpenseDetails() { 
      try{       
            //Create MDF Request and expense details
            SFDC_MDF__c mdfReq=PrepareMDFTestDataUtil.prepareMDFRecord();  
            MDF_Expense_Detail__c mdfExpenseDetails  = PrepareMDFTestDataUtil.prepareMDFExpenseRecord(mdfReq.Id);  
            
            //Create Controller reference
            PageReference pageRef = Page.CP_newClaim;
            Test.setCurrentPage(pageRef);
            ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(new SFDC_MDF_Claim__c());  
            ApexPages.currentPage().getParameters().put('mdfReqId',mdfReq.Id);
            CP_claimExt cpClaimExt= new CP_claimExt(sc); 
            
            //Prepare incorrect mdfExpenseDetails
            mdfExpenseDetails.Estimated_Cost__c =1000;
            mdfExpenseDetails.NCR_Approved__c=2000;  
            List<MDF_Expense_Detail__c> mdfExepeseList = new List<MDF_Expense_Detail__c>();
            mdfExepeseList.add(mdfExpenseDetails);
            cpClaimExt.mdfExepeseList=mdfExepeseList;
            //Test processClaimRequest()
            PageReference pageRefObj = cpClaimExt.processClaimRequest(); 
            System.assert(pageRefObj.getParameters().get('message')=='Claim Request is created. Please submit for approval.');
       }catch(Exception e){
          System.debug(e.getMessage());
       }  
    } 
    
    static testMethod void testException(){
        //Create MDF Request
        SFDC_MDF__c mdfReq= new SFDC_MDF__c();
        mdfReq.Name= 'Test Activity .............................................................';
        mdfReq.Activity_Date__c= Date.today().addDays(35);
        mdfReq.End_Date__c= Date.today().addDays(40);
        mdfReq.Activity_Type__c= 'Event - Roadshow';
        mdfReq.Other_Vendors_Represented__c='Micros';
        mdfReq.Activity_Description__c='TestDescription';
        mdfReq.Number_of_Leads__c= 1000;       
        mdfReq.Status__c='Request Created'; 
        insert mdfReq;
        
        //Create Controller reference
            PageReference pageRef = Page.CP_newClaim;
            Test.setCurrentPage(pageRef);
            ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(new SFDC_MDF_Claim__c());  
             ApexPages.currentPage().getParameters().put('mdfReqId',mdfReq.Id);
            CP_claimExt cpClaimExt= new CP_claimExt(sc);
            //Test processClaimRequest()
        try{
           cpClaimExt.processClaimRequest(); 
        }
        catch(Exception e){
            System.assert(e.getMessage()!=null);
        }
           
            
    }
}