force-app/main/default/objects/MDF_Expense_Detail__c/MDF_Expense_Detail__c.object-meta.xml
<CustomObject>
    <label>MDF Expense Detail</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>MDF Expense Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDF Expenses Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDF_Expense_Detail__c/fields/Actual_Cost__c.field-meta.xml
<CustomField>
    <fullName>Actual_Cost__c</fullName>
    <label>Actual Cost (Based on POP)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MDF_Expense_Detail__c/fields/Actvity__c.field-meta.xml
<CustomField>
    <fullName>Actvity__c</fullName>
    <description>This is the sub type of the activity specified in the Activity field of MDF Request.</description>
    <label>Activity Line Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDF_Expense_Detail__c/fields/Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Cost__c</fullName>
    <label>Estimated Cost</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MDF_Expense_Detail__c/fields/Fund_Claim__c.field-meta.xml
<CustomField>
    <fullName>Fund_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Fund Claim to which expense detail record is associated.</description>
    <label>Fund Claim</label>
    <referenceTo>SFDC_MDF_Claim__c</referenceTo>
    <relationshipLabel>MDF Expenses Detail</relationshipLabel>
    <relationshipName>MDF_Expenses_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MDF_Expense_Detail__c/fields/MDF_Request__c.field-meta.xml
<CustomField>
    <fullName>MDF_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MDF Request</label>
    <referenceTo>SFDC_MDF__c</referenceTo>
    <relationshipLabel>MDF Expenses Detail</relationshipLabel>
    <relationshipName>MDF_Expenses_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MDF_Expense_Detail__c/fields/NCR_Approved__c.field-meta.xml
<CustomField>
    <fullName>NCR_Approved__c</fullName>
    <label>NCR Approved</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MDF_Expense_Detail__c/fields/NCR_Estimated_Participation__c.field-meta.xml
<CustomField>
    <fullName>NCR_Estimated_Participation__c</fullName>
    <label>Approved Reimbursement Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/SFDC_MDF__c.object-meta.xml
<CustomObject>
    <description>Track MDF request details including partner account, requested amount, activity type and date, and approval status.</description>
    <label>Fund Request</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The requested amount. Consider activating a validation rule to enforce a certain minimum or maximum amount</description>
    <label>Approved Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Total_Estimated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Estimated_Cost__c</fullName>
    <label>Total Estimated Cost</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Total_NCR_Estimated_Participation__c.field-meta.xml
<CustomField>
    <fullName>Total_NCR_Estimated_Participation__c</fullName>
    <description>Total Approved Reimbursement Limit of all Activity Line Item.</description>
    <label>Total Approved Reimbursement Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/SFDC_MDF_Claim__c.object-meta.xml
<CustomObject>
    <description>A set of claims tied to a specific fund request.</description>
    <label>Fund Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Actual_Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Actual_Total_Cost__c</fullName>
    <description>Actual Total Cost of the MDF Activity.</description>
    <label>Actual Total Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of the current claim</description>
    <label>Approved Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Fund_Request__c.field-meta.xml
<CustomField>
    <fullName>Fund_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Note: This cannot be a master detail relationship if you plan to use approval workflow as the fund request will be locked (during approval and most likely post approval) and therefore any child claims cannot be saved</description>
    <label>Fund Request</label>
    <referenceTo>SFDC_MDF__c</referenceTo>
    <relationshipLabel>Fund Claims</relationshipLabel>
    <relationshipName>R00N30000002DjDcEAK</relationshipName>
    <trackHistory>false</trueHistory>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MDFExpenseDetailExtClaim.cls
public with sharing class MDFExpenseDetailExtClaim {
  
  private SFDC_MDF_Claim__c mdfClaim;
  public  String pageMode {get;set;}
  public  List<MDF_Expense_Detail__c> mdfExpenseDetailList {get;set;}
  private ApexPages.StandardController sc;
  private List<MDF_Expense_Detail__c> mdfExpenseDetailToDelList ; 
  
  public MDFExpenseDetailExtClaim (ApexPages.StandardController sc) {
   
    this.sc = sc;
    pageMode = 'view';
    mdfExpenseDetailToDelList = new List<MDF_Expense_Detail__c>();
      
    mdfExpenseDetailList = [SELECT Id,MDF_Request__c, Fund_Claim__c,  Estimated_Cost__c, NCR_Estimated_Participation__c,
                            Actual_Cost__c,NCR_Approved__c,Actvity__c FROM MDF_Expense_Detail__c
                            WHERE Fund_Claim__c =: sc.getId() LIMIT 500
                           ];
  }
  
  // Return MDF Request
  public SFDC_MDF_Claim__c  getMdfClaim() {
    if (mdfClaim == null) {
      List<SFDC_MDF_Claim__c> mdfClaimList = [SELECT Id, Actual_Total_Cost__c, Amount__c, Fund_Request__r.Total_Estimated_Cost__c, Fund_Request__r.Total_NCR_Estimated_Participation__c
                                          FROM SFDC_MDF_Claim__c WHERE id =: sc.getId() LIMIT 1
                                         ];
                                       
      if (mdfClaimList.size() > 0) {
       //get request record
        mdfClaim = mdfClaimList[0] ;
      } else {
          return null;
      }
    }
    
    return mdfClaim;
  }
  
  
  // Opens Page in edit mode
  public void editMode() {
    pageMode = 'edit';
  }
  
  // Cancel editing and open page in view mode
  public void cancelEditing() {
    pageMode = 'view';
  }
  
  // Delete Expense Detail
  public void deleteExpenseDetail() {
    Integer rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
    MDF_Expense_Detail__c del = mdfExpenseDetailList.remove(rowIndex);
    
    if (del.Id != null) {
      mdfExpenseDetailToDelList.add(del);
    }
  }
  
  // Save Expense Detail. If new record is added, insert the record in DB else update existing one.
  public void saveExpenseDetail() {
    try {
      upsert mdfExpenseDetailList;
      
      if (mdfExpenseDetailToDelList.size() > 0) {
        delete mdfExpenseDetailToDelList;
      } 
      pageMode = 'view';
      
      // Refetch MDF Request once again because changes in MDF expense detail changes rollup field on MDF request
      // record and to show updated values we have to refetch MDF request.
      
      mdfClaim = null ;
      
    } catch (Exception ex) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,ex.getMessage()));
    }
  }
  
  
  
}