force-app/main/default/objects/Automation_Setting__c/Automation_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting delivered as part of the Hospitality Service Cloud rollout enabling to toggle Service Cloud automation on/off. These flags of this custom setting will be utilized in Salesforce automation to turn logic on/off either globally, for specific profiles, or specific users.</description>
    <label>Automation Setting</label>
</CustomObject>

force-app/main/default/objects/Automation_Setting__c/fields/Skip_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Skip_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if checked will not execute any Triggers</description>
    <label>Skip Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCR_EmailMessage__c/NCR_EmailMessage__c.object-meta.xml
<CustomObject>
    <label>NCR EmailMessage</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>EmailMessage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCR EmailMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCR_EmailMessage__c/fields/Email_Type__c.field-meta.xml
<CustomField>
    <fullName>Email_Type__c</fullName>
    <label>Email Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dynamic Content</fullName>
            </value>
            <value>
                <fullName>Dynamic Content with Template</fullName>
            </value>
            <value>
                <fullName>Inactive Users Leads And Contacts Notification</fullName>
            </value>
            <value>
                <fullName>IdeaExchange</fullName>
            </value>
            <value>
                <fullName>NCR Dispute Update</fullName>
            </value>
            <value>
                <fullName>IPT Case Comment</fullName>
            </value>
            <value>
                <fullName>GLDC Log Failed</fullName>
            </value>
            <value>
                <fullName>NCR Update Failed</fullName>
            </value>
            <value>
                <fullName>LeadOwnerNotification</fullName>
            </value>
            <value>
                <fullName>GenericPlainText</fullName>
            </value>
            <value>
                <fullName>CasesEscalatedToNotification</fullName>
            </value>
            <value>
                <fullName>sendCaseEmail</fullName>
            </value>
            <value>
                <fullName>PSFR_SENDTOPS_UpdateEmailID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCR_EmailMessage__c/fields/HTML_Body__c.field-meta.xml
<CustomField>
    <fullName>HTML_Body__c</fullName>
    <label>HTML Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NCR_EmailMessage__c/fields/Recipient1__c.field-meta.xml
<CustomField>
    <fullName>Recipient1__c</fullName>
    <label>Recipient1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/NCR_EmailMessage__c/fields/Recipient2__c.field-meta.xml
<CustomField>
    <fullName>Recipient2__c</fullName>
    <label>Recipient2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TriggerDeactivation__c/TriggerDeactivation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is to deactivate trigger. This is only for developer.</description>
    <label>Trigger Deactivation</label>
</CustomObject>

force-app/main/default/objects/TriggerDeactivation__c/fields/TriggerToSkip__c.field-meta.xml
<CustomField>
    <fullName>TriggerToSkip__c</fullName>
    <label>TriggerToSkip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerControl.cls
/*************************************************************************************************************************************
  
# Modification History : 

Story No#       Date                DevName             Description
EBA_SF-1210     30th Nov 2021       Saurav Gautam       Moved the Messaging.SingleEmailMessage to a workflow by Using
                                                        NCR_EmailMessage__c object.

SFHS-292        28th Apr 2022       Basel Altamimi      Extend the control logic to include Hospitality Service Cloud
                                                        automation setting
**************************************************************************************************************************************/

public class TriggerControl {

    public Boolean RunTrigger(String TriggerName) {

        if (skipTriggerExecution_ServiceCloud()) {
            SendEmailTOIDC(TriggerName, Automation.AutomationSetting, getActiveCustomSettingOwner());
            return false;
        }

        System.debug('TriggerName' + TriggerName);
        List<TriggerDeactivation__c> listCodes = TriggerDeactivation__c.getAll().values();
        Map<String, TriggerDeactivation__c> UserIdInCustomSetting = new Map<String, TriggerDeactivation__c>();
        System.debug('start map');
        for (TriggerDeactivation__c obj : listCodes) {
            System.debug('inside loop' + obj.UserId__c);
            UserIdInCustomSetting.put(obj.UserId__c, obj);
        }
        System.debug('map filled' + UserIdInCustomSetting);
        if (listCodes.size() > 0) {
            String TriggerToSkip ;
            if (UserIdInCustomSetting.containsKey(UserInfo.getUserId())) {
                TriggerToSkip = UserIdInCustomSetting.get(UserInfo.getUserId()).TriggerToSkip__c;
            }
            System.debug(UserInfo.getUserId() + ' UserId' + TriggerToSkip);
            if (UserIdInCustomSetting.containsKey(UserInfo.getUserId()) && TriggerToSkip.contains(TriggerName)) {
                System.debug('Triggers bypass');
                SendEmailTOIDC(TriggerToSkip, Automation.TriggerDeactivationSetting, UserInfo.getName());
                return false;
                //Don't call dispatcher inside this block
            } else {
                System.debug('Run  Triggers ');
                return true;
            }
        } else {
            System.debug('Run  Triggers ');
            return true;
        }

    }

    public static void SendEmailTOIDC(String triggerName, Automation messageSource, String relatedTo) {
        //Changes for story EBA_SF-1210 start from-----------------------------------------------------------
        NCR_EmailMessage__c ncrEmail = new NCR_EmailMessage__c();
        String emailBody = '';
        emailBody += generateEmailMessage(triggerName, messageSource, relatedTo);

        ncrEmail.HTML_Body__c = emailBody;
        ncrEmail.Recipient1__c = 'ni230033@ncr.com';
        //ncrEmail.Recipient2__c ='pk185150@ncr.com';
        ncrEmail.Subject__c = 'Trigger Deactivated In Prod';
        ncrEmail.Email_Type__c = 'NCR Update Failed';
        //Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        //String[] toAddresses = new String[] {'ni230033@ncr.com'};
        //String[] toAddresses = new String[] {'pk185150@ncr.com'};
        //mail.setToAddresses(toAddresses);
        //mail.setSubject('Trigger Deactivated In Prod');
        //mail.setplainTextBody(msg);
        //mail.setHtmlBody( emailBody );
        //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        insert ncrEmail;
        //-----------------------End Here-for EBA_SF-1210 -----------------------------------------------------
    }

    /**
     * As part of the Hospitality Service Cloud rollout, return if the Service Cloud automation setting is set to on/off
     * for specific User/Profile/Org default.
     * @return boolean value that indicates whether to skip the trigger execution or not.
     */
    private static Boolean skipTriggerExecution_ServiceCloud() {
        Automation_Setting__c setting = getActiveCustomSetting();
        return setting != null ? setting.Skip_Trigger__c : false;
    }

    private static String getActiveCustomSettingOwner() {
        Automation_Setting__c setting = getActiveCustomSetting();

        String ownerName;
        if (setting.SetupOwnerId == UserInfo.getUserId()) {
            ownerName = UserInfo.getName();
        } else if (setting.SetupOwnerId == UserInfo.getProfileId()) {
            ownerName = UserInfo.getProfileId() + ' Profile';
        } else {
            ownerName = 'Org default';
        }

        return ownerName;
    }

    private static Automation_Setting__c getActiveCustomSetting() {
        // Get automation setting for the context user
        Automation_Setting__c setting = Automation_Setting__c.getInstance(UserInfo.getUserId());
        if (setting == null || !setting.Skip_Trigger__c) {
            // Get automation setting based on the user profile
            setting = Automation_Setting__c.getInstance(UserInfo.getProfileId());

            if (setting == null || !setting.Skip_Trigger__c) {
                // Get org default
                setting = Automation_Setting__c.getOrgDefaults();
            }
        }

        return setting;
    }

    public enum Automation {
        TriggerDeactivationSetting, AutomationSetting
    }
    private static String generateEmailMessage(String triggerName, Automation sourceAutomation, String relatedTo) {
        String message;

        if (sourceAutomation == Automation.TriggerDeactivationSetting) {
            message = String.format('Hello,<br/><br/>{0} has been deactivated for {1}<br/> Please do not forget to reactivate triggers by removing {2} custom setting data.</br></br></br>'
                    , new List<String>{
                            triggerName, relatedTo, 'Trigger Deactivation'
                    });
        } else if (sourceAutomation == Automation.AutomationSetting) {
            message = String.format('Hello,<br/><br/>All triggers have been deactivated<br/> Please do not forget to reactivate triggers by enable it back for {0} in {1} custom setting.</br></br></br>'
                    , new List<String>{
                            relatedTo, 'Automation Setting'
                    });
        } else {
            message = String.format('Hello,<br/><br/>{0} has been deactivated<br/> Please do not forget to reactivate the trigger.</br></br></br>', new List<String>{
                    triggerName
            });
        }

        message += 'Thanks,<br/>NSC Administration';
        return message;
    }
}