force-app/main/default/objects/Di_Idea_Favorites__c/Di_Idea_Favorites__c.object-meta.xml
<CustomObject>
    <label>Idea Favorites</label>
    <nameField>
        <displayFormat>Favorite-{0000}</displayFormat>
        <label>IdeaFavorites#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idea Favorites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Di_Idea_Favorites__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Idea_Favorites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdeaTheme/fields/DI_Co_owner__c.field-meta.xml
<CustomField>
    <fullName>DI_Co_owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Idea_Themes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IdeaTheme/fields/DI_Owner__c.field-meta.xml
<CustomField>
    <fullName>DI_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Idea_Themes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InactiveLeadAndContactEmail</label>
</CustomObject>

force-app/main/default/classes/DI_StatusUpdateTest.cls
@isTest
  Public class DI_StatusUpdateTest{
    static testMethod void TestDI_StatusUpdate(){
   
 /* Profile p = [SELECT Id FROM Profile WHERE Name = '61 DI Community Members'];

            User u = new User(
              Alias = 'testu',
              Email = 'old@gmail.com',
              EmailEncodingKey = 'UTF-8',
              LastName = 'Test',
              LanguageLocaleKey = 'en_US',
              LocaleSidKey = 'en_US',
              TimeZoneSidKey='America/Los_Angeles',
              ProfileId = p.Id,
              UserName='sume@gmail.com',
              Quicklook_ID__c = 'test',
              title = 'new'
              );*/
  
   
    Community c=[select id from community limit 1]; 
   
    ideatheme ith=new ideatheme();
        ith.title='abc';
        ith.DI_Owner__c =userinfo.getUserid();
        ith.DI_Co_owner__c = userinfo.getUserid();
        ith.Status = 'Accepting Ideas';
        ith.Communityid=c.id;
    insert ith;
    System.assert(ith.id!=null); 
    system.assertEquals(ith.title,'abc');
    Di_Idea_Favorites__c obj = new Di_Idea_Favorites__c();
        obj.DI_Idea_Theme__c = ith.id;
        obj.User__c = userinfo.getUserid();
    insert obj;
	System.assert(obj.id!=null);    
    ith.Status = 'Closed';
    update ith;
    
    
    
   
    }

  }