force-app/main/default/objects/Competitors__c/Competitors__c.object-meta.xml
<CustomObject>
    <description>Data listing of NCR Competitors by offer portfolio</description>
    <label>Competitors</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Telecom &amp; Technology</fullName>
            </value>
            <value>
                <fullName>Payments &amp; Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organization this opportunity is related to</description>
    <inlineHelpText>To find an org code search by your first or last name</inlineHelpText>
    <label>Sales Team Organization</label>
    <referenceTo>Sales_Org__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <description>Contains all of the applicable NCR sales organizations</description>
    <label>Sales Org</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Prompter__c/Value_Prompter__c.object-meta.xml
<CustomObject>
    <label>Value Prompter</label>
    <nameField>
        <label>Value Prompe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Prompter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Value_Prompter__c/fields/Access_to_the_Power_Person__c.field-meta.xml
<CustomField>
    <fullName>Access_to_the_Power_Person__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do we have access to the Power Person?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Are_Top_Risk_Identify_if_they_Occur_CMR__c.field-meta.xml
<CustomField>
    <fullName>Are_Top_Risk_Identify_if_they_Occur_CMR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Are Top Risk Identify if they Occur CM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Business_Issue__c.field-meta.xml
<CustomField>
    <fullName>Business_Issue__c</fullName>
    <label>Business Issue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Can_it_be_related_to_Revenue_or_Profit__c.field-meta.xml
<CustomField>
    <fullName>Can_it_be_related_to_Revenue_or_Profit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can it be related to Revenue or Profit?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Do_prospect_agreed_potential_buss_value__c.field-meta.xml
<CustomField>
    <fullName>Do_prospect_agreed_potential_buss_value__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do prospect agreed potential buss value?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Has_Plan_confirmed_with_customer__c.field-meta.xml
<CustomField>
    <fullName>Has_Plan_confirmed_with_customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Plan confirmed with customer?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Has_the_Business_Value_been_quantified__c.field-meta.xml
<CustomField>
    <fullName>Has_the_Business_Value_been_quantified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has the Business Value been quantified?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Have_we_developed_an_eVP__c.field-meta.xml
<CustomField>
    <fullName>Have_we_developed_an_eVP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Have we developed eVP for Power Person?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Is_prospect_req_any_unique_or_diff_sol__c.field-meta.xml
<CustomField>
    <fullName>Is_prospect_req_any_unique_or_diff_sol__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is prospect req any unique or diff sol?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Value Prompter</relationshipLabel>
    <relationshipName>Value_Prompter</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <externalId>true</externalId>
    <label>Opportunity Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Value_Prompter__c/fields/Problem__c.field-meta.xml
<CustomField>
    <fullName>Problem__c</fullName>
    <label>Problem</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ValuePrompterControllerTest.cls
/*
##################################################################################################
# Class Name............................:ValuePrompterControllerTest                                                                                                                                  
# Last Modified by......:  Monika
# Last Modified Date..:    19-12-2022
EBA_SF-2491 JDK Locale impact - Upgrade API Part 5                               
################################################################################################
*/
@isTest
private class ValuePrompterControllerTest{
    
    static testMethod void myTest() {
        Account acc=TestRecordsFactory.createAccount();
        Competitors__c comp=TestRecordsFactory.createCompetitor();
        Sales_Org__c  so=TestRecordsFactory.createSalesOrg();
        Opportunity opp = TestRecordsFactory.createSimpleOpportunity(acc);
        
        Value_Prompter__c vp = TestRecordsFactory.createValuePrompterFromOpp(opp);
        ValuePrompterController.getOppValuePrompter(opp.id);
        
        vp = new Value_Prompter__c(Id = vp.Id, Business_Issue__c = '', Problem__c = '', Opportunity_Id__c = opp.Id, Opportunity__c = opp.Id); 
        ValuePrompterController.saveValuePrompter(vp, opp.id);
        ValuePrompterController.checkValuePrompterAccess(opp.id, vp.Id);
        ValuePrompterController.emailMeValPrompter(vp);
        ValuePrompterController.submitValPrmForApproval(vp.Id);
        ValuePrompterController.recallApprovalRequest(vp.Id);
        
        Test.startTest();
        opp.Industry__c = 'Retail';
        update opp;
        vp.Has_the_Business_Value_been_quantified__c = true;
        vp.Do_prospect_agreed_potential_buss_value__c = true;
        vp.Access_to_the_Power_Person__c = true;
        vp.Has_Plan_confirmed_with_customer__c = true;
        vp.Have_we_developed_an_eVP__c = true;
        vp.Are_Top_Risk_Identify_if_they_Occur_CMR__c = true;
        vp.Can_it_be_related_to_Revenue_or_Profit__c = true;
        vp.Is_prospect_req_any_unique_or_diff_sol__c = true;
        update vp;
        system.assertEquals(vp.Have_we_developed_an_eVP__c , true);
        
        Test.stopTest();
        
    }
}