force-app/main/default/objects/Product2/fields/DataHubReferenceKey__c.field-meta.xml
<CustomField>
    <fullName>DataHubReferenceKey__c</fullName>
    <label>Data Hub Reference Key</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OPID__c.field-meta.xml
<CustomField>
    <fullName>OPID__c</fullName>
    <description>This field is synced from Zuora Product to NSC Product2.</description>
    <label>OPID(Text)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topline</fullName>
                <default>true</default>
                <label>Topline</label>
            </value>
            <value>
                <fullName>Zuora Product</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>SID</fullName>
            </value>
            <value>
                <fullName>PID</fullName>
            </value>
            <value>
                <fullName>Sub-Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Topline_Product_Lkp__c.field-meta.xml
<CustomField>
    <fullName>Topline_Product_Lkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated with topline matching with Topline Product text field on Product2.</description>
    <label>Topline Product Lkp</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Topline Product Lookup)</relationshipLabel>
    <relationshipName>Topline_Product_Lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ToplineProduct__c.field-meta.xml
<CustomField>
    <fullName>ToplineProduct__c</fullName>
    <description>This field is used to sync Topline Product field on Product in Zuora to Topline Product field on Product2 in NSC.</description>
    <label>Topline Product(Text)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Aggregation (default)</fullName>
            </value>
            <value>
                <fullName>Account Opening</fullName>
            </value>
            <value>
                <fullName>ACH / Wire</fullName>
            </value>
            <value>
                <fullName>Bill Pay</fullName>
            </value>
            <value>
                <fullName>Business Banking</fullName>
            </value>
            <value>
                <fullName>Check Imaging</fullName>
            </value>
            <value>
                <fullName>Check Reordering</fullName>
            </value>
            <value>
                <fullName>CheckFree Fees Collected</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Create Your Own</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Cross-Sell</fullName>
            </value>
            <value>
                <fullName>CuneXus</fullName>
            </value>
            <value>
                <fullName>Deferred Revenue - Annual Conference</fullName>
            </value>
            <value>
                <fullName>Digital Banking Communications</fullName>
            </value>
            <value>
                <fullName>Digital Banking Other</fullName>
            </value>
            <value>
                <fullName>Digital Banking Security</fullName>
            </value>
            <value>
                <fullName>Early Warning System</fullName>
            </value>
            <value>
                <fullName>EyeVerify</fullName>
            </value>
            <value>
                <fullName>FinanceWorks</fullName>
            </value>
            <value>
                <fullName>Funds Transfer</fullName>
            </value>
            <value>
                <fullName>Implementations</fullName>
            </value>
            <value>
                <fullName>Internet Banking</fullName>
            </value>
            <value>
                <fullName>LivePerson</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Multi-Factor Authenication</fullName>
            </value>
            <value>
                <fullName>New Account Opening</fullName>
            </value>
            <value>
                <fullName>Online Fraud (RSA)</fullName>
            </value>
            <value>
                <fullName>Online Statements</fullName>
            </value>
            <value>
                <fullName>PFM Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductUtil.cls
public class ProductUtil {
    
     public void populateToplines(Map<String, List<Product2>> zPrdMap, Set<String> OPIDSet) {
       
      /*  if ((!zPrdMap.isEmpty()) && (!OPIDSet.isEmpty())) {
           Map<String, Product2> toplineMap = new Map<String, Product2>();
            
           for(Product2 topline : [SELECT Id, Name, Offer_Portfolio_Id__c FROM Product2
                                WHERE Product_Type__c = 'Topline'AND IsActive = true 
                                AND DataHubReferenceKey__c != null and Name IN :zPrdMap.keySet()
                                AND Offer_Portfolio_Id__c IN :OPIDSet]) {
               toplineMap.put(topline.Name, topline);
           }
           
           for (String toplineName : zPrdMap.keySet()) {
               List<Product2> zPrdList = zPrdMap.get(toplineName);
               Product2 topline = toplineMap.get(toplineName);
               
               if(topline != null) {
                   for(Product2 zPrd : zPrdList) {
                       if(topline.Name == zPrd.ToplineProduct__c && topline.Offer_Portfolio_Id__c == zPrd.OPID__c) {
                           zPrd.Topline_Product_Lkp__c = topline.Id;
                       }  else {
                            //zPrd.addError('No matching topline found for Product: ' + zPrd.Name);
                       } 
                   }    
               } else {
                   // adderror to zPrdList that no matching topline found;
               }                 
           }                         
        }*/
    } 
}