force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topline</fullName>
                <default>true</default>
                <label>Topline</label>
            </value>
            <value>
                <fullName>Zuora Product</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>SID</fullName>
            </value>
            <value>
                <fullName>PID</fullName>
            </value>
            <value>
                <fullName>Sub-Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Offer_Category__c.field-meta.xml
<CustomField>
    <fullName>Service_Offer_Category__c</fullName>
    <label>Revenue Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PricebookBatchTest.cls
@isTest
private class PricebookBatchTest {
    
     public static testMethod void runTest(){
         Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
         
        //Execute an update DML on the Pricebook2 record, to make IsStandard to true
        Update standardPricebook;
         
         
         Pricebook2 customPricebook = new Pricebook2(Name = 'Samsung Galaxy PriceBook', isActive = true);
         insert customPricebook;
         System.assertNotEquals(customPricebook.id, null,'customPricebook is Null');  
         
        Product2 prod = new Product2();
        prod.Name = 'Orderman';
        prod.Family = 'Hardware';
        prod.CanUseQuantitySchedule = true;
        prod.Service_Offer_Category__c='HW';
         prod.Product_Type__c ='Topline';
         prod.IsActive = true;
        insert prod;
       
         
        
         
            PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id, Product2Id = prod.Id, UnitPrice = 10000, CurrencyIsoCode = 'USD', IsActive = true);
        insert standardPrice;
        
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPricebook.Id, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true, CurrencyIsoCode = 'USD');
        insert customPrice;
        
       
         Test.startTest();
         	Database.executeBatch(new PriceBookBatch(), 1);
         Test.stopTest();
     }

}