force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/All_profie_list_config__c/All_profie_list_config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to exclude profiles from QuBy_OpportunityTrigger_BFR trigger</description>
    <label>All profile list config</label>
</CustomObject>

force-app/main/default/objects/All_profie_list_config__c/fields/Profile_id__c.field-meta.xml
<CustomField>
    <fullName>Profile_id__c</fullName>
    <label>Profile id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/All_profie_list_config__c/fields/QuBy_LTNG_ProfileCheck__c.field-meta.xml
<CustomField>
    <fullName>QuBy_LTNG_ProfileCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QuBy_LTNG_ProfileCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Generates a number for the opportunity</description>
    <displayFormat>{000000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/QuBy_Detail__c.object-meta.xml
<CustomObject>
    <label>All QuBy Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>All QuBy Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuBy_Detail__c/fields/Annuity_Modification_Date__c.field-meta.xml
<CustomField>
    <fullName>Annuity_Modification_Date__c</fullName>
    <label>Recurring Revenue Modification Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Annuity_Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Annuity_Quote_Status__c</fullName>
    <label>Recurring Revenue Quote Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Converted_Annuity_Quote_Amount__c.field-meta.xml
<CustomField>
    <fullName>Converted_Annuity_Quote_Amount__c</fullName>
    <formula>Annuity_Quote_Amount__c / Currency_Conversion_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Converted RecurringRevenue Quote Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Converted_Solution_Quote_Amount__c.field-meta.xml
<CustomField>
    <fullName>Converted_Solution_Quote_Amount__c</fullName>
    <formula>Solution_Quote_Amount__c  /  Currency_Conversion_Rate__c</formula>
    <label>Converted Orders Funnel Quote Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/ERP_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order_Number__c</fullName>
    <label>Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/isChannel__c.field-meta.xml
<CustomField>
    <fullName>isChannel__c</fullName>
    <label>isChannel</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/MCN__c.field-meta.xml
<CustomField>
    <fullName>MCN__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>All QuBy Quotes</relationshipLabel>
    <relationshipName>All_QuBy_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Opportunity_No__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_No__c</fullName>
    <description>This will be supporting process for real time failures</description>
    <label>Opportunity No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Solution_Modification_Date__c.field-meta.xml
<CustomField>
    <fullName>Solution_Modification_Date__c</fullName>
    <label>Orders Funnel Modification Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Solution_Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Solution_Quote_Status__c</fullName>
    <label>Orders Funnel Quote Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Total_Quote_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Quote_Amount__c</fullName>
    <description>This field is use to add both solution and annuity quote amount.
This field is used in Opportunity Re engineering.</description>
    <formula>Annuity_Quote_Amount__c + Solution_Quote_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Quote Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DJ</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuBy_QuoteRelatedList.cls
/*##################################################################################################
# Project Name..........: QuBy
# File..................: QuBy_QuoteRelatedList.cls                                                        
# Version...............: 32.0 
# Created by............: Mudit Saxena                                                                 
# Created Date..........: 28-07-2016                                                                               
# Last Modified by......: Mudit Saxena 
# Last Modified Date....: 28-07-2016
# Description...........: All quotes associated with a single opportunity will
display quote values order numbers (if acknowledged) and displayed on the opportunity page.

##################################################################################################*/
public class QuBy_QuoteRelatedList{

    /*#################################################################################################################
    # Method Name............: isDisabled
    # Param..................: None                                               
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 20-04-2017                                                                             
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 20-04-2017                                                                             
    # Description............: This method is use to check if user have access of this whole component functionality.                               
    #################################################################################################################*/
    @AuraEnabled
    public static boolean isDisabled( ){
        /*if( QuBy_LTNG_ProfileCheck__c.getValues( userInfo.getProfileId() ) == null ){ 
            return true;
        }else{
            return false;
        }*/
         set<string> st  = new set<string>();
        List<All_profie_list_config__c> mcs = All_profie_list_config__c.getall().values();
        for(All_profie_list_config__c p : mcs ){
            if(p.QuBy_LTNG_ProfileCheck__c == true){
                st.add(p.Profile_id__c);
            }            
        } 
        if(! st.Contains( userInfo.getProfileId())){
            return true;
        }else{
            return false;
        }
    }
    
    /*#################################################################################################################
    # Method Name............: getRecords
    # Param..................: String opportunityId     :   Opportunity Record Id
    decimal pageNumber      :   PageNumber
    String pageSize          :  Page Size                                     
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 20-04-2017                                                                             
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 20-04-2017                                                                             
    # Description............: This method is use to fetch already associated quotes to the Opportunity.                                
    #################################################################################################################*/
    @AuraEnabled
    public static lightningTableWrapper getRecords( String opportunityId ){     
        
        //String queryString = 'Select id,Order_Type__c,Quote_Number__c,Name,ERP_Order_Number__c,MCN__c,Solution_Quote_Status__c, Annuity_Quote_Status__c,CurrencyIsoCode,Annuity_Modification_Date__c,Solution_Modification_Date__c,Converted_Annuity_Quote_Amount__c,Converted_Solution_Quote_Amount__c,Total_Quote_Amount__c,CreatedDate from QuBy_Detail__c WHERE Opportunity__c =: opportunityId AND ( Annuity_Modification_Date__c < LAST_N_DAYS:365 OR Solution_Modification_Date__c < LAST_N_DAYS:365 ) ORDER BY Annuity_Modification_Date__c DESC ';
      String queryString = 'Select id,Order_Type__c,Quote_Number__c,Name,ERP_Order_Number__c,MCN__c,Solution_Quote_Status__c, Annuity_Quote_Status__c,CurrencyIsoCode,Annuity_Modification_Date__c,Solution_Modification_Date__c,Converted_Annuity_Quote_Amount__c,Converted_Solution_Quote_Amount__c,Total_Quote_Amount__c,CreatedDate from QuBy_Detail__c WHERE Opportunity__c =: opportunityId  ORDER BY Annuity_Modification_Date__c DESC ';
 lightningTableWrapper ltw = new lightningTableWrapper();
       // ltw.total = [ Select count() from QuBy_Detail__c WHERE Opportunity__c =: opportunityId AND ( Annuity_Modification_Date__c < LAST_N_DAYS:365 OR Solution_Modification_Date__c < LAST_N_DAYS:365 ) ];
        ltw.total = [ Select count() from QuBy_Detail__c WHERE Opportunity__c =: opportunityId  ];
        List<dataWrapper> dataList = new List<dataWrapper>();
        for( QuBy_Detail__c QD : database.query( String.escapeSingleQuotes(queryString) ) ){
            dataList.add( new dataWrapper( QD ) );  
        }
        ltw.sObjectrecords = dataList;
        return ltw;
    }
    
    
    /*#################################################################################################################
    # Method Name............: availableQuotes
    # Param..................: List <String> disQuoteId         :   List of Quotes Id which we have to disAssociate.
    string OpportunityID             :  Opportunity Record Id.                                          
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 20-04-2017
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 20-04-2017
    # Description............: This method is use for Disassociating Existing Quote from opportunity.
    #################################################################################################################*/
    @AuraEnabled
    public static lightningTableWrapper getAvailableQuotes( String opportunityId ){
        string AccountMCN = [ SELECT Account.Master_Customer_Number__c FROM Opportunity WHERE ID =: opportunityId LIMIT 1 ].Account.Master_Customer_Number__c;
        string countryCode = [ SELECT Account.Account_Country_Code__c FROM Opportunity WHERE ID =: opportunityId LIMIT 1 ].Account.Account_Country_Code__c;
        //string isChannel='true';
        
        String queryString = 'Select id,Order_Type__c,Quote_Number__c,Name,ERP_Order_Number__c,MCN__c,Solution_Quote_Status__c, Annuity_Quote_Status__c,CurrencyIsoCode,Annuity_Modification_Date__c,Solution_Modification_Date__c,Converted_Annuity_Quote_Amount__c,Converted_Solution_Quote_Amount__c,Total_Quote_Amount__c,CreatedDate from QuBy_Detail__c WHERE Opportunity__c = null AND MCN__c =: AccountMCN AND Country_Code__c =: countryCode  AND ( Annuity_Modification_Date__c = LAST_N_DAYS:365 OR Solution_Modification_Date__c = LAST_N_DAYS:365 ) ORDER BY Annuity_Modification_Date__c DESC ';
        //String queryString = 'Select id,Quote_Number__c,Name,ERP_Order_Number__c,MCN__c,Solution_Quote_Status__c, Annuity_Quote_Status__c,CurrencyIsoCode,Annuity_Modification_Date__c,Solution_Modification_Date__c,Converted_Annuity_Quote_Amount__c,Converted_Solution_Quote_Amount__c,Total_Quote_Amount__c from QuBy_Detail__c ';
        lightningTableWrapper ltw = new lightningTableWrapper();
        ltw.total = [ Select count() from QuBy_Detail__c WHERE Opportunity__c = null AND MCN__c =: AccountMCN AND Country_Code__c =: countryCode  AND ( Annuity_Modification_Date__c = LAST_N_DAYS:365 OR Solution_Modification_Date__c = LAST_N_DAYS:365 ) ];
        //ltw.total = [ Select count() from QuBy_Detail__c ];
        List<dataWrapper> dataList = new List<dataWrapper>();
        for( QuBy_Detail__c QD : database.query( String.escapeSingleQuotes(queryString) ) ){
            dataList.add( new dataWrapper( QD ) );  
        }
        ltw.sObjectrecords = dataList;
        return ltw;
    }
    
    /*#################################################################################################################
    # Method Name............: availableQuotesInBatches
    # Param..................: string opportunityId :1opportunity Id and loffset and imits to fetch available Quotes.
    string OpportunityID             :  Opportunity Record Id.                                          
    # Created by.............: Ravikant Maurya                                                                 
    # Created Date...........: 09-07-2018
    # Last Modified by.......: Ravikant maurya 
    # Last Modified Date.....: 20-04-2017
    # Description............: This method is use for fetching defined size Quote from opportunity.
    #################################################################################################################*/
    @AuraEnabled
    public static lightningTableWrapper availableQuotesInBatches( String opportunityId, Integer limits , Integer offsets ){
        Integer intlimits = integer.valueof(limits);
        Integer intoffsets = integer.valueof(offsets);
        string AccountMCN = [ SELECT Account.Master_Customer_Number__c FROM Opportunity WHERE ID =: opportunityId LIMIT 1 ].Account.Master_Customer_Number__c;
        string countryCode = [ SELECT Account.Account_Country_Code__c FROM Opportunity WHERE ID =: opportunityId LIMIT 1 ].Account.Account_Country_Code__c;
        //string isChannel='true';
        
        String queryString = 'Select id,Order_Type__c,Quote_Number__c,Name,ERP_Order_Number__c,MCN__c,Solution_Quote_Status__c, Annuity_Quote_Status__c,CurrencyIsoCode,Annuity_Modification_Date__c,Solution_Modification_Date__c,Converted_Annuity_Quote_Amount__c,Converted_Solution_Quote_Amount__c,Total_Quote_Amount__c,CreatedDate from QuBy_Detail__c WHERE Opportunity__c = null AND MCN__c =: AccountMCN AND Country_Code__c =: countryCode  AND ( Annuity_Modification_Date__c = LAST_N_DAYS:365 OR Solution_Modification_Date__c = LAST_N_DAYS:365 ) ORDER BY Annuity_Modification_Date__c DESC  Limit :intlimits Offset :intoffsets';
        
        //System.debug('@@@@'+queryString);
        //String queryString = 'Select id,Quote_Number__c,Name,ERP_Order_Number__c,MCN__c,Solution_Quote_Status__c, Annuity_Quote_Status__c,CurrencyIsoCode,Annuity_Modification_Date__c,Solution_Modification_Date__c,Converted_Annuity_Quote_Amount__c,Converted_Solution_Quote_Amount__c,Total_Quote_Amount__c from QuBy_Detail__c  Limit :intlimits Offset :intoffsets ';
        lightningTableWrapper ltw = new lightningTableWrapper();
        ltw.total = [ Select count() from QuBy_Detail__c WHERE Opportunity__c = null AND MCN__c =: AccountMCN AND Country_Code__c =: countryCode  AND ( Annuity_Modification_Date__c = LAST_N_DAYS:365 OR Solution_Modification_Date__c = LAST_N_DAYS:365 ) ];
    
        List<dataWrapper> dataList = new List<dataWrapper>();
        for( QuBy_Detail__c QD : database.query( String.escapeSingleQuotes(queryString) ) ){
            dataList.add( new dataWrapper( QD ) );  
        }
        ltw.sObjectrecords = dataList;
        return ltw;
    }
    
    
    
    /*#################################################################################################################
    # Method Name............: search
    # Param..................: List <String> disQuoteId         :   List of Quotes Id which we have to disAssociate.
                               string OpportunityID             :   Opportunity Record Id.                                          
                               String searchstr
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 20-04-2017
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 20-04-2017
    # Description............: This method is use for search.
    #################################################################################################################*/
    @AuraEnabled
    public static lightningTableWrapper search( String opportunityId,string searchstr ){ 
         String SearchCondition = '%' + searchstr + '%';
        
        String queryString = 'Select id,Order_Type__c,Quote_Number__c,Name,ERP_Order_Number__c,MCN__c,Solution_Quote_Status__c, Annuity_Quote_Status__c,CurrencyIsoCode,Annuity_Modification_Date__c,Solution_Modification_Date__c,Converted_Annuity_Quote_Amount__c,Converted_Solution_Quote_Amount__c,Total_Quote_Amount__c,CreatedDate from QuBy_Detail__c WHERE Opportunity__c =: opportunityId AND ( Annuity_Modification_Date__c = LAST_N_DAYS:365 OR Solution_Modification_Date__c = LAST_N_DAYS:365 ) AND ( Quote_Number__c LIKE: SearchCondition OR Name LIKE: SearchCondition ) ORDER BY Annuity_Modification_Date__c DESC '; 
        //system.debug('::::queryString::::' + queryString);
        lightningTableWrapper ltw = new lightningTableWrapper();
        
        String countString = 'Select COUNT() from QuBy_Detail__c WHERE Opportunity__c =: opportunityId AND ( Annuity_Modification_Date__c = LAST_N_DAYS:365 OR Solution_Modification_Date__c = LAST_N_DAYS:365 ) AND ( Quote_Number__c LIKE: SearchCondition OR Name  LIKE: SearchCondition ) '; 
        ltw.total = Database.countQuery( countString );
        List<dataWrapper> dataList = new List<dataWrapper>();
        for( QuBy_Detail__c QD : database.query( String.escapeSingleQuotes(queryString) ) ){
            dataList.add( new dataWrapper( QD ) );  
        }
        //system.debug('::::dataList:::' + dataList );
        
        ltw.sObjectrecords = dataList;
        return ltw;
    }
    
    /*#################################################################################################################
    # Method Name............: searchAvailableQuotes
    # Param..................: List <String> disQuoteId         :   List of Quotes Id which we have to disAssociate.
    string OpportunityID             :  Opportunity Record Id.                                          
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 20-04-2017
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 20-04-2017
    # Description............: This method is use for Disassociating Existing Quote from opportunity.
    #################################################################################################################*/
    @AuraEnabled
    public static lightningTableWrapper searchAvailableQuotes( String opportunityId,string searchstr ){
        string AccountMCN = [ SELECT Account.Master_Customer_Number__c FROM Opportunity WHERE ID =: opportunityId LIMIT 1 ].Account.Master_Customer_Number__c;
        string countryCode = [ SELECT Account.Account_Country_Code__c FROM Opportunity WHERE ID =: opportunityId LIMIT 1 ].Account.Account_Country_Code__c;
        String SearchCondition = '%' + searchstr + '%';
        
        String queryString = 'Select id,Order_Type__c,Quote_Number__c,Name,ERP_Order_Number__c,MCN__c,Solution_Quote_Status__c, Annuity_Quote_Status__c,CurrencyIsoCode,Annuity_Modification_Date__c,Solution_Modification_Date__c,Converted_Annuity_Quote_Amount__c,Converted_Solution_Quote_Amount__c,Total_Quote_Amount__c,CreatedDate from QuBy_Detail__c WHERE Opportunity__c = null AND MCN__c =: AccountMCN AND Country_Code__c =: countryCode AND  ( Annuity_Modification_Date__c = LAST_N_DAYS:365 OR Solution_Modification_Date__c = LAST_N_DAYS:365 ) AND ( Quote_Number__c LIKE: SearchCondition OR Name  LIKE: SearchCondition ) ORDER BY Annuity_Modification_Date__c DESC ';
        lightningTableWrapper ltw = new lightningTableWrapper();
        //ltw.total = [ Select count() from QuBy_Detail__c WHERE Opportunity__c = null AND MCN__c =: AccountMCN AND Country_Code__c =: countryCode AND isChannel__c !=: isChannel AND Lastmodifieddate > LAST_N_DAYS:365 ];
        
        String countString = 'Select COUNT() from QuBy_Detail__c WHERE Opportunity__c = null AND MCN__c =: AccountMCN AND Country_Code__c =: countryCode  AND ( Annuity_Modification_Date__c = LAST_N_DAYS:365 OR Solution_Modification_Date__c = LAST_N_DAYS:365 ) AND ( Quote_Number__c LIKE: SearchCondition OR Name LIKE: SearchCondition ) '; 
        ltw.total = Database.countQuery( countString );
        
        List<dataWrapper> dataList = new List<dataWrapper>();
        for( QuBy_Detail__c QD : database.query( String.escapeSingleQuotes(queryString) ) ){
            dataList.add( new dataWrapper( QD ) );  
        }
        ltw.sObjectrecords = dataList;
        return ltw;
    }
    
    
    
    /*#################################################################################################################
    # Method Name............: disAssociateQuote
    # Param..................: List <String> disQuoteId         :   List of Quotes Id which we have to disAssociate.
    string OpportunityID             :  Opportunity Record Id.                                          
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 20-04-2017
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 20-04-2017
    # Description............: This method is use for Disassociating Existing Quote from opportunity.
    #################################################################################################################*/
    @AuraEnabled
    public static messageWrapper disAssociateQuote( List <String> disQuoteId,string OpportunityID ){        
        Set<string>allowedProfile = new Set<string>{ '04 NSC UI Administrator','System Administrator','02 NSC Administrator','01 GS Admin','03 PRM Admin' };        
            opportunity opportunity = [ SELECT stagename, isClosed FROM Opportunity WHERE id =: OpportunityID LIMIT 1];     
        String profileName = [ Select Name from Profile where Id =: UserInfo.getProfileId() ].Name;        
        
        messageWrapper MW = new messageWrapper();       
         
        if( opportunity.isClosed && !allowedProfile.Contains( profileName ) ){                                  
            MW.type = 'error';
            MW.Message = 'You cannot disassociate quote from a closed opportunity.';
        }else{
            if( disQuoteId != null && disQuoteId.size() > 0 ){
                List<QuBy_Detail__c>updateDetails = new List<QuBy_Detail__c>();
                for( QuBy_Detail__c QBDET : [ SELECT id,Opportunity__c,Opportunity_No__c FROM QuBy_Detail__c WHERE ID IN : disQuoteId ] ){
                    QBDET.Opportunity__c = null;
                    QBDET.Opportunity_No__c = null;
                    updateDetails.add( QBDET );
                }
                
                if( updateDetails != null && updateDetails.size() > 0 ){
                    try{
                        if ( Schema.sObjectType.QuBy_Detail__c.isUpdateable() ){
                          update updateDetails;
                            MW.type = 'success';
                          MW.Message = updateDetails.size() + ' Quote disassociate successfully.';
                        }else{                          
                            MW.type = 'error';
                            MW.Message = 'You are not authorized to Disassociate Quotes. Please Contact Sales Operations for Access.';    
                        }
                    }catch( exception QE ){
                        //system.debug( 'ERROR : ' + QE.getMessage() );
                        MW.type = 'error';
                        if(QE.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ) {
                            String tempStr = QE.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,') ;
                            String msg = tempStr.substringBefore(':') ;
                            MW.Message = msg;
                        } else if(QE.getMessage().contains('FIELD_FILTER_VALIDATION_EXCEPTION')) {
                            String tempStr = QE.getMessage().substringAfter('FIELD_FILTER_VALIDATION_EXCEPTION,') ;
                            String msg = tempStr.substringBefore(':') ;
                            MW.Message = msg;
                        }
                        else {
                            //MW.Message = QE.getMessage();
                            MW.Message = 'Some internal error occured, Please contact your System Administrator.';
                        }
                    }
                }                
            }else{
                MW.type = 'info';
                MW.Message = 'Please select atleast one quote to disAssociate.';
            }
        }
        return MW;
    }
    
    /*##################################################################################################
    # Method Name............: associateQuote
    # Param..................: None                                               
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 28-07-2016                                                                               
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 28-07-2016
    # Description............: This method is use for associating QuBy Quote.                          
    ##################################################################################################*/
    @AuraEnabled
    public static messageWrapper associateQuote( List <String> QuoteId,string OpportunityID ){
        Set<string>allowedProfile = new Set<string>{ '04 NSC UI Administrator','System Administrator','02 NSC Administrator','01 GS Admin','03 PRM Admin' };
            opportunity opportunity = [ SELECT stagename, isClosed FROM Opportunity WHERE id =: OpportunityID LIMIT 1]; 
        String profileName = [ Select Name from Profile where Id =: UserInfo.getProfileId() ].Name;
        String oppNumber =[ SELECT Opportunity_Number__c FROM Opportunity WHERE id =: OpportunityID LIMIT 1 ].Opportunity_Number__c;
        
        messageWrapper MW = new messageWrapper();   
        
        if( opportunity.isClosed  && !allowedProfile.Contains( profileName ) ){
            MW.type = 'error';MW.Message = 'You cannot associate quote to a closed opportunity.';         
        }else{
            if( QuoteId != null && QuoteId.size() > 0 ){
                List<QuBy_Detail__c>updateDetails = new List<QuBy_Detail__c>();
                for( QuBy_Detail__c QBDET : [ SELECT id,Opportunity_No__c FROM QuBy_Detail__c WHERE ID IN : QuoteId ] ){
                    QBDET.Opportunity_No__c = oppNumber;                    
                    updateDetails.add( QBDET );
                }   
                if( updateDetails != null && updateDetails.size() > 0 ){
                    try{
                        if ( Schema.sObjectType.QuBy_Detail__c.isUpdateable() ){
                            update updateDetails;
                            
                            MW.type = 'success';
                            MW.Message = updateDetails.size() + ' Quote Associate successfully.';
                        }else{
                          MW.type = 'error';
                          MW.Message = 'You are not authorized to Associate Quotes. Please Contact Sales Operations for Access.';
                        }
                    }catch( exception QE ){
                        //system.debug( 'CUSTOM ERROR : ' + QE.getMessage() ); 
                        MW.type = 'error';
                        if(QE.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                            String tempStr = QE.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,') ;String msg = tempStr.substringBefore(':') ;MW.Message = msg;
                        } else if(QE.getMessage().contains('FIELD_FILTER_VALIDATION_EXCEPTION')) {
                            String tempStr = QE.getMessage().substringAfter('FIELD_FILTER_VALIDATION_EXCEPTION,') ;String msg = tempStr.substringBefore(':') ;MW.Message = msg;
                        }
                        else {
                            //MW.Message = QE.getMessage();
                            MW.Message = 'Some internal error occured, Please contact your System Administrator.';
                        }
                        
                        
                    }
                    
                }
                
            }else{
                MW.type = 'info';MW.Message = 'Please select atleast one quote to Associate.';
            }
        }
        return MW;
    }
    
    /*#################################################################################################################
    # Method Name............: lightningTableWrapper
    # Param..................: None                                         
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 20-04-2017
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 20-04-2017
    # Description............: Wrapper for Pagination with data Wrapper List.
    #################################################################################################################*/
    public class lightningTableWrapper {
        @AuraEnabled
        public Integer page { get;set; }
        
        @AuraEnabled
        public Integer total { get;set; }
        
        @AuraEnabled
        public List<dataWrapper> sObjectrecords { get;set; }
    }
    
    /*#################################################################################################################
    # Method Name............: dataWrapper
    # Param..................: None                                         
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 20-04-2017
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 20-04-2017
    # Description............: Wrapper for showing table. Both Associate and Disassociate.
    #################################################################################################################*/
    public class dataWrapper{
        @AuraEnabled public string id{get;set;}    
        @AuraEnabled public string QuoteNumber{get;set;}        
        @AuraEnabled public string QuoteName{get;set;}
        @AuraEnabled public integer QuoteAmount{get;set;}       
        @AuraEnabled public string OrderNumber{get;set;}
        @AuraEnabled public string OrderType{get;set;}
        @AuraEnabled public string modificationDate{get;set;}
        @AuraEnabled public string SolutionQuoteStatus{get;set;}
        @AuraEnabled public string AnnuityQuoteStatus{get;set;}
        @AuraEnabled Public Date CreatedDate{get;set;}
        
        public dataWrapper( QuBy_Detail__c QD ){
            this.id = QD.Id;
            this.QuoteNumber = QD.Quote_Number__c;
            
            this.QuoteName = QD.Name;
            //this.CreatedDate = date.newinstance(QD.CreatedDate.year(), QD.CreatedDate.month(), QD.CreatedDate.day());
            
            if( ( QD.Annuity_Quote_Status__c != null && QD.Annuity_Quote_Status__c.toUpperCase() == 'ACKNOWLEDGED') || ( QD.Solution_Quote_Status__c != null && QD.Solution_Quote_Status__c.toUpperCase() == 'ACKNOWLEDGED' ) ){
                this.OrderNumber = QD.ERP_Order_Number__c;
            }else{
                this.OrderNumber = '-';
            }
            
            
            this.AnnuityQuoteStatus = QD.Annuity_Quote_Status__c;
            this.SolutionQuoteStatus = QD.Solution_Quote_Status__c;
            this.QuoteAmount = integer.valueof( QD.Total_Quote_Amount__c );
            
            if( QD.Annuity_Modification_Date__c == null && QD.Solution_Modification_Date__c == null  ){
                this.modificationDate = '';
            }else if( QD.Annuity_Modification_Date__c != null && QD.Solution_Modification_Date__c == null ){
                this.modificationDate = string.valueof( QD.Annuity_Modification_Date__c );              
            }else if( QD.Annuity_Modification_Date__c == null && QD.Solution_Modification_Date__c != null ){
                this.modificationDate = string.valueof( QD.Solution_Modification_Date__c );             
            }else if( QD.Solution_Modification_Date__c > QD.Annuity_Modification_Date__c ) {
                this.modificationDate = string.valueof( QD.Solution_Modification_Date__c );             
            }else{
                this.modificationDate = string.valueof( QD.Annuity_Modification_Date__c );
            }
           this.OrderType = QD.Order_Type__c; 
        }
    }
    
    /*#################################################################################################################
    # Method Name............: messageWrapper
    # Param..................: None                                         
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 20-04-2017
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 20-04-2017
    # Description............: Wrapper for showing Messages.
    #################################################################################################################*/
    public class messageWrapper{
        @AuraEnabled public string type{get;set;}           
        @AuraEnabled public string Message{get;set;}
    }
}