force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>End-user Customer account that is in a RoR country</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Industry_Code__c.field-meta.xml
<CustomField>
    <fullName>Industry_Code__c</fullName>
    <label>Industry Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BNK</fullName>
            </value>
            <value>
                <fullName>HOS</fullName>
            </value>
            <value>
                <fullName>RET</fullName>
            </value>
            <value>
                <fullName>TEL</fullName>
            </value>
            <value>
                <fullName>P&amp;N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NSCCommonInfoUtilTest.cls
/*
####################################################################################################################                                                        
# Created by................: Ajay Dixit                                                                      
# Created Date...........: 07-06-2017                                                                                  
# Last Modified by......: Ajay Dixit                                                                           
# Last Modified Date..: 07-06-2017                                                                                
# Description...............: Test Class
####################################################################################################################
*/

@isTest

public class NSCCommonInfoUtilTest {
    public static testMethod void testCommonUtil(){
        NSCCommonInfoUtil ncu= NSCCommonInfoUtil.getInstance();
        ncu.buildMapOfAllRecordTypes('Account');
        ncu.buildMapOfRecordTypes('Account');
        ncu.BuildSoqlString('Account', new Set<String>{'id'}, null, 'id!=null', 'id', 100);
        ncu.getMapOfAllProfiles();
        ncu.getNonRORCtrs_PicklistVals();
        Account a=TestRecordsFactory.createAccount();
        ncu.getObject('Account', a.id);
        ncu.getPicklistAsSelectOptions('Account', 'Account_Country_Code__c', true);
        ncu.getPicklistValues('Account', 'Account_Country_Code__c', true);
        Id i = ncu.getProfileId('System Administrator');
        ncu.getQueueUsers('test', 'test');
        ncu.getQueueUsers('test', null);        
        ncu.getTheaterAreaMapping();
        ncu.selectStar('Account', true);
        ncu.selectStar('Account', false);        
        ncu.sortOptionList(new List<SelectOption>{new SelectOption('Ajay',''), new SelectOption('B','Puneet')});
        ncu.getPrdCat_PicklistVals();
        ncu.CollectLocaleConversionRate();
        ncu.userHasLightningPermission(Userinfo.getUserId());
        ncu.getFiscalMonthEndDate(); 
        ncu.getRecordTypeId('Account', 'Customer');
        ncu.getSystemUsers();
        NSCCommonInfoUtil.getIdOf('Test');
        NSCCommonInfoUtil.getIdSetOf('Test');
        system.assertEquals(i, '00e70000000sR8UAAU'); 
    }
    
    public static testMethod void testCommonUtil2(){
     	  Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
          PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name='ICM_Access' LIMIT 1];
          User u = new User(Email='standarduser@testorg.com',FirstName='test', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id,  
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser12@org.com.test',Quicklook_ID__c='tst12');
         insert u;
         
         List<PermissionSetAssignment> prmAgnLst = new List<PermissionSetAssignment>();
         prmAgnLst.add(new PermissionSetAssignment(PermissionSetId=ps.Id, AssigneeId=u.Id));
         Database.SaveResult[] insertRslt = Database.insert(prmAgnLst, false);
         String msg = NSCCommonInfoUtil.getInstance().prsSaveRslt(insertRslt, prmAgnLst);
             
         Database.DeleteResult[] deleteRslt = Database.delete(prmAgnLst, false);
         NSCCommonInfoUtil.getInstance().prsDelRslt(deleteRslt, prmAgnLst);
         system.assert(msg != null,'There is some error while inserting the records.');  
         NSCCommonInfoUtil.getDependentPicklistValues(Lead.Industry_Code__c);
     }
}