force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOB__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>CLA BRAZIL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>EUROPE EXC RUSSIA</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDIA &amp; SEA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
            <value>
                <fullName>NAMER CFI</fullName>
            </value>
            <value>
                <fullName>NAMER DIRECT</fullName>
            </value>
            <value>
                <fullName>NAMER MAJORS</fullName>
            </value>
            <value>
                <fullName>NAMER SMB</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA AND SPA</fullName>
            </value>
            <value>
                <fullName>SAPAC</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Co_Op__c/Co_Op__c.object-meta.xml
<CustomObject>
    <label>Co Op</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Ops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Op__c/fields/Activity_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_End_Date__c</fullName>
    <description>End Date of the activity.</description>
    <label>Activity End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Co_Op__c/fields/Activity_Name__c.field-meta.xml
<CustomField>
    <fullName>Activity_Name__c</fullName>
    <label>Activity Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Op__c/fields/Activity_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Start_Date__c</fullName>
    <description>Stant date of Activity.</description>
    <label>Activity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Co_Op__c/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <formula>Account__r.Master_Customer_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Master Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Op_Supporting_Document__c/Co_Op_Supporting_Document__c.object-meta.xml
<CustomObject>
    <label>Co Op Supporting Document</label>
    <nameField>
        <label>Co Op Supporting Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supporting Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <description>Reference for the attachment associated with co op.</description>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Co_Op_Request__c.field-meta.xml
<CustomField>
    <fullName>Co_Op_Request__c</fullName>
    <description>Reference to co op request.</description>
    <label>Co Op</label>
    <referenceTo>Co_Op__c</referenceTo>
    <relationshipLabel>Supporting Documents</relationshipLabel>
    <relationshipName>Supporting_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed reimbursement request form</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Other required supporting documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Contact__c.field-meta.xml
<CustomField>
    <fullName>Active_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field that ,when checked, indicates that the Contact is active</description>
    <label>Active Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Web_Portal_Login__c.field-meta.xml
<CustomField>
    <fullName>Web_Portal_Login__c</fullName>
    <description>This contact&apos;s login for access of the NCR Web Portal</description>
    <label>Web Portal Login</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CoOpViewExtTest.cls
@isTest
public class CoOpViewExtTest {
    private static Account createAccount(){
       
        Account act = new Account();
        act.Name = 'Partner Test Account';
        List<RecordType> actRecordtypes = [SELECT Id, Name From RecordType WHERE DeveloperName='Partner' AND IsActive = true AND SobjectType = 'Account' Limit 1];
        if (actRecordtypes.size() > 0)
            act.RecordTypeId = actRecordtypes[0].Id;
        act.Account_Country_Code__c = 'US';
        act.Active_Account__c = true;
        act.CurrencyIsoCode = 'USD';
        act.Industry = 'RETAIL:CHANNEL';
        act.Account_Region__c = 'EMEA';
        act.Master_Customer_Number__c = '91663446';
        return act;
    }
    
    private static Contact createContact(Id AccountID){
        //Insert Partner Contact
        Contact con = new Contact();
        con.lastName = 'Mahla';
        con.Email = 'test@gmail.com';
        con.AccountId = AccountID;
        con.Active_Contact__c = true;
        con.Web_Portal_Login__c = 'wplUser';
        return con;
        
    }
    
    private static User createUser(Id ContactId){
          //Insert Partner User
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE '%Partner Community User%' Limit 1];
        User u1 = new User();
        u1.ContactId = contactId;
        u1.Username = 'wplUser@ncr.com';
        u1.ProfileId = portalProfile.Id;
        u1.Alias = 'test123';
        u1.Email = 'sm245987@gmail.com';
        u1.EmailEncodingKey = 'UTF-8';
        u1.LastName = 'McTesty';
        u1.CommunityNickname = 'test12345';
        u1.TimeZoneSidKey = 'America/Los_Angeles';
        u1.LocaleSidKey = 'en_US';
        u1.LanguageLocaleKey = 'en_US';
        u1.FederationIdentifier = 'wplUser';
        return u1;   
    }
    
    public static testmethod void testCoOpViewExt() {
        Account acc = createAccount();
        System.runAs(TestRecordsFactory.getUser()){
           insert acc;  
        }
       
        Contact con = createContact(acc.id);
        insert con;
        user u = createUser(con.Id);
        insert u;
         
       // system.runAs(u) {
            // Insert Co-Op Request
            Co_Op__c coOpReq = new Co_Op__c();
            coOpReq.Activity_Name__c = 'Co Op Req';
            coOpReq.Activity_Start_Date__c = System.today();
            coOpReq.Activity_End_Date__c = System.today();
            insert coOpReq;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(coOpReq);
            CoOpViewExt controller = new CoOpViewExt(sc);
            PageReference pageRef = Page.ipt_co_op_view;
            pageRef.getParameters().put('id', String.valueOf(coOpReq.Id));
            Test.setCurrentPage(pageRef);
            
            controller.submitRequest();
            
            Attachment att = new Attachment();
            att.ParentId = coOpReq.Id;
            att.Name = 'Test Attachment';
            att.Body = Blob.valueOf('test');
            insert att;
            
            Co_Op_Supporting_Document__c supportingDoc = new Co_Op_Supporting_Document__c ();
            supportingDoc.Name = att.Name;
            supportingDoc.Attachment_Id__c = att.Id;
            supportingDoc.Co_Op_Request__c = coOpReq.Id;
            supportingDoc.Type__c = 'Invoices';
            insert supportingDoc;
            
            Co_Op_Supporting_Document__c supportingDoc1 = new Co_Op_Supporting_Document__c ();
            supportingDoc1.Name = att.Name;
            supportingDoc1.Attachment_Id__c = att.Id;
            supportingDoc1.Co_Op_Request__c = coOpReq.Id;
            supportingDoc1.Type__c = 'Proof of payment';
            insert supportingDoc1;
            
            PageReference pgObj = controller.submitRequest();
            System.assert(pgObj!=null);
            controller.redirectToEdit();
            controller.cancel();
        
       // }
        
    }
}