force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APL_Account_Revenue__c/APL_Account_Revenue__c.object-meta.xml
<CustomObject>
    <label>Account Revenue</label>
    <nameField>
        <label>APL Account Revenue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Revenues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APL_Account_Revenue__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Revenues</relationshipLabel>
    <relationshipName>Account_Revenues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APL_Account_Revenue__c/fields/customer_nbr__c.field-meta.xml
<CustomField>
    <fullName>customer_nbr__c</fullName>
    <label>Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APL_Account_Revenue__c/fields/fml_account_code__c.field-meta.xml
<CustomField>
    <fullName>fml_account_code__c</fullName>
    <label>FML Account Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APL_Account_Revenue__c/fields/USD_Amount__c.field-meta.xml
<CustomField>
    <fullName>USD_Amount__c</fullName>
    <label>USD Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APL_Revenue_Category_Mapping__c/APL_Revenue_Category_Mapping__c.object-meta.xml
<CustomObject>
    <description>This object has FML Account Code to Revenue Category mapping data. DRM system is ROR for this data.</description>
    <label>Revenue Category Mapping</label>
    <nameField>
        <label>Revenue Category Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Category Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/APL_Revenue_Category_Mapping__c/fields/FML_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>FML_Account_Code__c</fullName>
    <label>FML Account Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/APL_RevenueDisplayControllerTest.cls
@isTest
private class APL_RevenueDisplayControllerTest {
    
    static testMethod void myTest() {
        Account acc=TestRecordsFactory.createAccount();
  
        List<APL_Account_Revenue__c> aplRevenueList = new List<APL_Account_Revenue__c>{new APL_Account_Revenue__c(Account__c= acc.Id, fml_account_code__c='4001', 
                                            customer_nbr__c = acc.Master_Customer_Number__c, USD_Amount__c= 100),
                                            new APL_Account_Revenue__c(Account__c= acc.Id, fml_account_code__c='4002', 
                                            customer_nbr__c = acc.Master_Customer_Number__c, USD_Amount__c= 100)
                                            };
        insert aplRevenueList;
        
        List<APL_Revenue_Category_Mapping__c> revCatList = new List<APL_Revenue_Category_Mapping__c>{ new APL_Revenue_Category_Mapping__c(FML_Account_Code__c = '4001', 
                                                                                                        Category__c  = 'HARDWARE MAINTENANCE_4001'),
                                                                                                      new APL_Revenue_Category_Mapping__c(FML_Account_Code__c = '4002', 
                                                                                                        Category__c  = 'SW MAINTENANCE_4002')
                                                                                                     }; 
       
        insert revCatList ;
        
        APL_RevenueDisplayController.getRevenueByCategory(acc.Id);
        APL_HierarchyRevenueDisplayController.RevenueWrapper r= APL_HierarchyRevenueDisplayController.getRevenueByCategory(acc.Id);
        System.assertEquals(r.HWM_Value,100);
    }
}