force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_Industry_Name__c.field-meta.xml
<CustomField>
    <fullName>MDM_Industry_Name__c</fullName>
    <label>Industry Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Bill_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Bill-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <externalId>true</externalId>
    <label>Site Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site record type is used to represent Sites/Locations related to an Account.</description>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Forecast_Category__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Category__c</fullName>
    <description>This custom field is used to fill forecast category field in salesforce1 as standard forecast category field is not editable in salesforce1.</description>
    <label>Forecast Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Omitted</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
            <value>
                <fullName>Commit</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Exclude Pipeline</fullName>
            </value>
            <value>
                <fullName>Exclude Upside</fullName>
            </value>
            <value>
                <fullName>Exclude Commit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HierarchyControllerTest.cls
@isTest
private class HierarchyControllerTest {
    static testMethod void myTest() {
        Account ac=new Account();
        Account parentAcc =new Account();
       
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        
        User Usr = [Select Id from User Where Name = 'Soup User'];
        System.runAs(Usr){            
            parentAcc.Name='Test Parent Account';
            parentAcc.Account_Country_Code__c='A2';
            parentAcc.MDM_Industry_Name__c='FINANACIAL:BANKING';
            parentAcc.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            insert parentAcc;
            
            ac.Name='Test Account';
            ac.Account_Country_Code__c='A2';
            ac.MDM_Industry_Name__c='FINANACIAL:BANKING';
            ac.RecordTypeId = rtMapByName.get(Label.RT_Acc_Customer).getRecordTypeId();
            ac.parentId = parentAcc.Id;
            insert ac; 
            
            Account site =new Account(Name = 'Test site', Site_Number__c = 'test1234', Primary_Bill_To__c = true,
                                    parentId = ac.Id, RecordTypeId = rtMapByName.get(Label.RT_Acc_Site).getRecordTypeId());
            insert site;
        }
        
        String st = HierarchyController.getAccountHierarchyData(parentAcc.Id);
        HierarchyController.getSites(ac.Id);
        HierarchyController.getAccountBasics(ac.Id);
        HierarchyController.getAccountSites(ac.Id, 0);
        HierarchyController.getConfs();
        HierarchyController.getCols('Opportunity','Name,Account.Name,Amount,Owner.lastName', 'Name,Account.Name,Forecast_Category__c,closedate');
        system.assert(st != null ,'Account data not returned'); 
    }
    
    
    static testMethod void relatedListTest() {
        Account ac=new Account();
        Account parentAcc =new Account();
       
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        
        User Usr = [Select Id from User Where Name = 'Soup User'];
        System.runAs(Usr){            
            parentAcc.Name='Test Parent Account';
            parentAcc.Account_Country_Code__c='A2';
            parentAcc.MDM_Industry_Name__c='FINANACIAL:BANKING';
            parentAcc.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            insert parentAcc;
            
            ac.Name='Test Account';
            ac.Account_Country_Code__c='A2';
            ac.MDM_Industry_Name__c='FINANACIAL:BANKING';
            ac.RecordTypeId = rtMapByName.get(Label.RT_Acc_Customer).getRecordTypeId();
            ac.parentId = parentAcc.Id;
            insert ac; 
            
            Account site =new Account(Name = 'Test site', Site_Number__c = 'test1234', Primary_Bill_To__c = true,
                                      parentId = ac.Id,RecordTypeId = rtMapByName.get(Label.RT_Acc_Site).getRecordTypeId());
            insert site;
            
            Opportunity opp = TestRecordsFactory.createSimpleOpportunity(ac);
        }
        
       String jsonData = '{"fields":"Name, Account.Name, StageName, CloseDate, Amount","relatedFieldApiName":"AccountId","recordId":"0010100000ADHdtAAH","numberOfRecords":7,"sobjectApiName":"Opportunity","sortedBy":"Name","sortedDirection":"ASC"}';
       Account a = RelatedListController.getAccountBasics(ac.Id);
       RelatedListController.initData(jsonData);

       RelatedListController.allChildAccounts(parentAcc.Id); 
           RelatedListController.getIconName('Account');
         RelatedListController.deleteRecord(ac.Id);
       system.assertNotEquals(a, null, 'Account data not returned'); 
        
                    
                   
    }
}