force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/ASM_Role_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Account Point of Contacts</label>
    <nameField>
        <displayFormat>APOC{000000}</displayFormat>
        <label>APOC ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Point of Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Point of Contacts</relationshipLabel>
    <relationshipName>Account_Point_of_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/NCR_Employee_Detail__c.field-meta.xml
<CustomField>
    <fullName>NCR_Employee_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to associate NCR Employee Detail so that we can assign the roles to the users.</description>
    <label>NCR Employee Detail</label>
    <referenceTo>NCR_Employee_Detail__c</referenceTo>
    <relationshipLabel>Account Point of Contacts</relationshipLabel>
    <relationshipName>Account_Point_of_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/QuickLook_ID__c.field-meta.xml
<CustomField>
    <fullName>QuickLook_ID__c</fullName>
    <label>Role User QuickLook ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Role_Name__c.field-meta.xml
<CustomField>
    <fullName>Role_Name__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Director</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>Account Services Manager</fullName>
                <isActive>false</isActive>
                <label>Account Services Manager</label>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Support Analyst</fullName>
            </value>
            <value>
                <fullName>Account Support Manager</fullName>
            </value>
            <value>
                <fullName>Channel Account Manager</fullName>
            </value>
            <value>
                <fullName>CMS Account Manager</fullName>
            </value>
            <value>
                <fullName>COA</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>COL</fullName>
            </value>
            <value>
                <fullName>Collector</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Customer Advocate</fullName>
            </value>
            <value>
                <fullName>Customer Delivery Partner (CDP)</fullName>
            </value>
            <value>
                <fullName>Customer Project Manager (CPM)</fullName>
            </value>
            <value>
                <fullName>Customer Relationship Manager</fullName>
            </value>
            <value>
                <fullName>Customer Success Analyst</fullName>
            </value>
            <value>
                <fullName>Customer Success Leader</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
            <value>
                <fullName>Executive Service Manager</fullName>
            </value>
            <value>
                <fullName>Executive Services Manager</fullName>
                <isActive>false</isActive>
                <label>Executive Services Manager</label>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Field Operations</fullName>
            </value>
            <value>
                <fullName>Field Service Coordinator</fullName>
            </value>
            <value>
                <fullName>Field Training</fullName>
            </value>
            <value>
                <fullName>Global Account Manager</fullName>
            </value>
            <value>
                <fullName>Inside Sales Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Role_User_Name__c.field-meta.xml
<CustomField>
    <fullName>Role_User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Point_of_Contacts_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Role_User_Qlook_Id__c.field-meta.xml
<CustomField>
    <fullName>Role_User_Qlook_Id__c</fullName>
    <formula>If(Role_User_Name__c != null,Role_User_Name__r.Quicklook_ID__c, NCR_Employee_Detail__r.Quicklook_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User QuicklookId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BPM_Configuration__c/BPM_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BPM Configuration</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <label>Quicklook ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/NCR_Employee_Detail__c.object-meta.xml
<CustomObject>
    <description>This object stores the details of all NCR employees.</description>
    <label>NCR Employee Detail</label>
    <nameField>
        <label>NCR Employee Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCR Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/APOCReassignmentBatch.cls
/*
##################################################################################################
# Project Name..........: Account Point Of Contact(APOC)
# File............................: APOCReassignmentBatch.cls                                                        
# Created by................: Varsha Pal                                                                   
# Created Date...........: 02/26/2020 (MM/DD/YYYY)                                                                             
# Last Modified by......:  Varsha Pal
# Last Modified Date..: 02/26/2020 (MM/DD/YYYY)
# Description...............: This class is used for reassigning APOC record from inactive user to active user
if there is an upgrade or downgrade(same quicklookid of user)
# JIRA Story - #EBA_SF-1092(P1: APOC: APOC record re-assignment automation) 
# test class -UserUpDownTest
##################################################################################################
*/

public class APOCReassignmentBatch implements Database.Batchable<sObject>, Database.Stateful,schedulable {
    public  Id uid;
    public APOCReassignmentBatch(){system.debug('Base');}
    public APOCReassignmentBatch(Id uid){
        this.uid = uid;
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
        if(uid!=null){
            return Database.getQueryLocator('Select id,QuickLook_ID__c,Role_User_Name__c,Role_User_Qlook_Id__c,account__c,role_name__c from ASM_Role_Hierarchy__c where Role_User_Name__c = :uid');
        }else{
        	return Database.getQueryLocator('Select id,QuickLook_ID__c,Role_User_Name__c,Role_User_Qlook_Id__c,account__c,role_name__c from ASM_Role_Hierarchy__c where Role_User_Name__r.isactive= false and ncr_employee_detail__c!=null');    
        }
    }
    //String msg=' ';
    public void execute(Database.BatchableContext BC, List<ASM_Role_Hierarchy__c> scope){
        Set<String> qlSet = new Set<String>();
        List<ASM_Role_Hierarchy__c> roles = new List<ASM_Role_Hierarchy__c>();
        //Store all the records in roles(list) and qlid in a set for which QuickLook_ID__c(text field) and Role_User_Qlook_Id__c(formula field) are not same and it is associated to an account
        for(ASM_Role_Hierarchy__c a : scope){
            if(a.Role_User_Qlook_Id__c!=null && a.account__c!=null){
                if(a.Role_User_Qlook_Id__c!=a.QuickLook_ID__c && !(a.Role_User_Qlook_Id__c.contains('-'))){
                    a.QuickLook_ID__c = a.Role_User_Qlook_Id__c;
                }
                qlSet.add(a.QuickLook_ID__c);
                roles.add(a);
            }               
        }
        //get all the active users for the quicklookId where there is an upgrade or downgrade
        Map<String,User> qlUserMap = new Map<String,User>();
        for(User u : [Select id,QuickLook_ID__c,Name from User where quicklook_id__c in:qlSet and Isactive=true and usertype!='csnonly']){
            qlUserMap.put(u.QuickLook_ID__c.tolowerCase(),u);
        }
        for(ASM_Role_Hierarchy__c a : roles){
            if(qlUserMap.get(a.QuickLook_ID__c.tolowerCase())!=null){
                a.Role_User_Name__c = qlUserMap.get(a.QuickLook_ID__c.tolowerCase()).id;
            }
        }
        APOC_MassUpdateAllRolesHandler.stopNotification = true;
        APOC_MassUpdateAllRolesHandler.runonce = false;
        database.update(roles,false);
    }
    public void execute(SchedulableContext SC) {
        database.executebatch(new APOCReassignmentBatch());
    }
    public void finish(Database.BatchableContext BC){
        /*if(msg.contains('Failed')){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(BPM_Configuration__c.getValues('CAHierarchyJobReciever').values__c.split(','));
            mail.setOrgWideEmailAddressId('0D270000000XZHr');
            mail.setPlainTextBody(msg);
            mail.setSubject('APOCReassignmentBatch Job Failed');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {
                mail
                    });
        }*/
        system.debug('Base');
    }
}