force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitors__c/Competitors__c.object-meta.xml
<CustomObject>
    <description>Data listing of NCR Competitors by offer portfolio</description>
    <label>Competitors</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Customer_Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Area__c</fullName>
    <inlineHelpText>Enter the WCS Customer Service Area that will be applicable for the delivery of the products on this opportunity</inlineHelpText>
    <label>Customer Service Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>US Atlanta</fullName>
            </value>
            <value>
                <fullName>US California</fullName>
            </value>
            <value>
                <fullName>US Charlotte</fullName>
            </value>
            <value>
                <fullName>US Great Lakes</fullName>
            </value>
            <value>
                <fullName>US Midatlantic</fullName>
            </value>
            <value>
                <fullName>US New York</fullName>
            </value>
            <value>
                <fullName>US Northeast</fullName>
            </value>
            <value>
                <fullName>US Northwest</fullName>
            </value>
            <value>
                <fullName>US Other</fullName>
            </value>
            <value>
                <fullName>US South Central</fullName>
            </value>
            <value>
                <fullName>US Southeast</fullName>
            </value>
            <value>
                <fullName>US SVC</fullName>
            </value>
            <value>
                <fullName>WCS - Area Grouping - No Country</fullName>
            </value>
            <value>
                <fullName>WCS - Canada</fullName>
            </value>
            <value>
                <fullName>WCS - Caribbean Latin America</fullName>
            </value>
            <value>
                <fullName>WCS - Central Europe</fullName>
            </value>
            <value>
                <fullName>WCS - France - Belgium</fullName>
            </value>
            <value>
                <fullName>WCS - Greater China</fullName>
            </value>
            <value>
                <fullName>WCS - Iberia</fullName>
            </value>
            <value>
                <fullName>WCS - India</fullName>
            </value>
            <value>
                <fullName>WCS - Israel</fullName>
            </value>
            <value>
                <fullName>WCS - Italy - Turkey</fullName>
            </value>
            <value>
                <fullName>WCS - Japan</fullName>
            </value>
            <value>
                <fullName>WCS - Korea</fullName>
            </value>
            <value>
                <fullName>WCS - Middle East - Africa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery_Date__c</fullName>
    <label>Expected Delivery Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Trigger__c</fullName>
    <label>Invoice Trigger</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the primary competitor with NCR for this opportunity</inlineHelpText>
    <label>Primary Competitor</label>
    <referenceTo>Competitors__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organization this opportunity is related to</description>
    <inlineHelpText>To find an org code search by your first or last name</inlineHelpText>
    <label>Sales Team Organization</label>
    <referenceTo>Sales_Org__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Solution_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Solution_Portfolio__c</fullName>
    <label>Offer Portfolio</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DIGITAL BANKING</fullName>
            </value>
            <value>
                <fullName>FINANCIAL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>GAMING</fullName>
            </value>
            <value>
                <fullName>GEMS</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>IPS</fullName>
            </value>
            <value>
                <fullName>PC / ELS</fullName>
            </value>
            <value>
                <fullName>RETAIL ASSISTED SERVICE</fullName>
            </value>
            <value>
                <fullName>RETAIL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>RETALIX</fullName>
            </value>
            <value>
                <fullName>SERVICES</fullName>
            </value>
            <value>
                <fullName>TRAVEL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>SYSTEMS MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>CHECK &amp; IMAGE</fullName>
            </value>
            <value>
                <fullName>SELF-SERVICE REINVENTION</fullName>
            </value>
            <value>
                <fullName>BRANCH TRANSFORMATION</fullName>
            </value>
            <value>
                <fullName>ENTERPRISE FRAUD AND SECURITY</fullName>
            </value>
            <value>
                <fullName>TRANSACTION PROCESSING</fullName>
            </value>
            <value>
                <fullName>CASH MANAGEMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/IncludeinFunnel.recordType-meta.xml
<RecordType>
    <fullName>IncludeinFunnel</fullName>
    <active>true</active>
    <businessProcess>NCR Sales Process</businessProcess>
    <description>An opportunity that is included in NCR&apos;s funnel and forecast</description>
    <label>Include in Funnel</label>
</RecordType>

force-app/main/default/objects/QuBy_Detail__c/QuBy_Detail__c.object-meta.xml
<CustomObject>
    <label>All QuBy Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>All QuBy Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuBy_Detail__c/fields/Invoice_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Trigger__c</fullName>
    <label>Invoice Trigger</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <description>Contains all of the applicable NCR sales organizations</description>
    <label>Sales Org</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/Is_Active_in_RoR__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_in_RoR__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active in RoR?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Solution_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Solution_Portfolio__c</fullName>
    <label>Offer Portfolio</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuBy_TestOppInfoForQB.cls
/*##################################################################################################
# Project Name..........: QuBy
# File..................: QuBy_TestOppInfoForQB.cls                                                        
# Version...............: 32.0 
# Created by............: Mudit Saxena                                                                 
# Created Date..........: 28-08-2016                                                                               
# Last Modified by......: Mudit Saxena 
# Last Modified Date....: 28-08-2016
# Description...........: This is test class for QuBy_OppInfoForQB class.                          
##################################################################################################*/
@isTest
private class QuBy_TestOppInfoForQB{
    
    static testMethod void UnittestFirst() {
        
        QuBy_Detail__c QD = new QuBy_Detail__c();
        QD.Name = 'TESTQD';
        
        QD.Quote_Number__c = '123';
        insert QD;
        ApexPages.currentPage().getParameters().put('qno','123');
        QuBy_OppInfoForQB quby = new QuBy_OppInfoForQB( );
        System.assertEquals(ApexPages.currentPage().getParameters().put('qno','123'), '123');
    }
    
    static testMethod void UnittestSecond() {
        
        QuBy_Detail__c QD = new QuBy_Detail__c();
        QD.Name = 'TESTQD';
        
        insert QD;
        
        ApexPages.currentPage().getParameters().put('qno','123');
        QuBy_OppInfoForQB quby = new QuBy_OppInfoForQB( );
        System.assertEquals(ApexPages.currentPage().getParameters().put('qno','123'), '123');
    }
    
    static testMethod void UnittestThird() {
        
        //Inserting Dummy Account.
        Account a = new Account ( name = 'testing task Deletion of Closed Opp', 
                                 LOB__c='FINANCIAL',
                                 Master_Customer_Number__c = 'TEST000012', 
                                 Account_Country_Code__c = 'US', CurrencyIsoCode = 'USD', 
                                 Active_Account__c = true );
        System.runAs(TestRecordsFactory.getUser()){
            insert a;
        }
        
        //Inserting Dummy Sales Org.        
        Sales_Org__c s = new Sales_Org__c ( name = 'test org', Is_Active_in_RoR__c = true );
        insert s;
        
        //Inserting Dummy Competitor
        Competitors__c c = new Competitors__c (name = 'testing competitor');        
        insert c;
        
        //Inserting Dummy Opportunity
        Id RecordTypeId = [ Select Id From RecordType  Where SobjectType = 'Opportunity' and DeveloperName = 'IncludeinFunnel'  ].Id;
        Opportunity opp = new Opportunity();   
        opp.name = 'abc';
        opp.AccountID = a.id;
        opp.Name = 'Test Opportunity';
        //opp.SalesLogixId__c = 'aaaaa';
        opp.type = 'Indirect Channel';
        opp.Solution_Portfolio__c = 'Entertainment Self Service';
        opp.CURRENCYISOCODE = 'USD';
        opp.SALES_ORG__C = s.id;
        opp.INVOICE_TRIGGER__C='Shipment';
        opp.CUSTOMER_SERVICE_AREA__C = 'WCS - US Northeast';
        opp.PRIMARY_COMPETITOR__C = c.id;
        opp.Expected_Delivery_Date__c = System.TODAY().addDays(30);
        opp.closeDate = System.TODAY();
        opp.stagename = 'Analyzing';
        opp.recordTypeId = RecordTypeId;        
        insert opp;
        
        ApexPages.currentPage().getParameters().put('oppno',opp.id);
        QuBy_OppInfoForQB quby = new QuBy_OppInfoForQB( );
        ApexPages.currentPage().getParameters().put('oppno',null);
        QuBy_OppInfoForQB quby1 = new QuBy_OppInfoForQB( );
        System.assertEquals(ApexPages.currentPage().getParameters().put('oppno',null), null);
        // System.assertEquals(ApexPages.currentPage().getParameters().put('oppno',opp.id), null);
        
        
    }
}