force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Advocated_Solution__c.field-meta.xml
<CustomField>
    <fullName>Advocated_Solution__c</fullName>
    <label>Advocated Solution</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery_Date__c</fullName>
    <label>Expected Delivery Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Trigger__c</fullName>
    <label>Invoice Trigger</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Generates a number for the opportunity</description>
    <displayFormat>{000000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <formula>Sales_Org__r.Sales_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Solution_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Solution_Portfolio__c</fullName>
    <label>Offer Portfolio</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DIGITAL BANKING</fullName>
            </value>
            <value>
                <fullName>FINANCIAL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>GAMING</fullName>
            </value>
            <value>
                <fullName>GEMS</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>IPS</fullName>
            </value>
            <value>
                <fullName>PC / ELS</fullName>
            </value>
            <value>
                <fullName>RETAIL ASSISTED SERVICE</fullName>
            </value>
            <value>
                <fullName>RETAIL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>RETALIX</fullName>
            </value>
            <value>
                <fullName>SERVICES</fullName>
            </value>
            <value>
                <fullName>TRAVEL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>SYSTEMS MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>CHECK &amp; IMAGE</fullName>
            </value>
            <value>
                <fullName>SELF-SERVICE REINVENTION</fullName>
            </value>
            <value>
                <fullName>BRANCH TRANSFORMATION</fullName>
            </value>
            <value>
                <fullName>ENTERPRISE FRAUD AND SECURITY</fullName>
            </value>
            <value>
                <fullName>TRANSACTION PROCESSING</fullName>
            </value>
            <value>
                <fullName>CASH MANAGEMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/QuBy_Detail__c.object-meta.xml
<CustomObject>
    <label>All QuBy Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>All QuBy Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuBy_Detail__c/fields/Advocated_Solution__c.field-meta.xml
<CustomField>
    <fullName>Advocated_Solution__c</fullName>
    <label>Advocated Orders Funnel</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Invoice_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Trigger__c</fullName>
    <label>Invoice Trigger</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/QuickLook_ID__c.field-meta.xml
<CustomField>
    <fullName>QuickLook_ID__c</fullName>
    <label>Assigned Salesperson QILD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <label>Sales Org Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_ID__c</fullName>
    <label>User Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuBy_OppInfoForQB.cls
/*##################################################################################################
# Project Name..........: QuBy
# File..................: QuBy_OppInfoForQB.cls                                                        
# Version...............: 32.0 
# Created by............: Mudit Saxena                                                                 
# Created Date..........: 28-08-2016                                                                               
# Last Modified by......: Mudit Saxena 
# Last Modified Date....: 28-08-2016
# Description...........: This class use to construct json for parameters which we are sending to QuBy.
                          
##################################################################################################*/
public with sharing class QuBy_OppInfoForQB {
    public String oppJSON {get;set;}
    
    /*##################################################################################################
    # Method Name............: QuBy_OppInfoForQB ( Constructor )
    # Param..................: Standred Controller Instance                                               
    # Created by.............: Mudit Saxena                                                                 
    # Created Date...........: 28-08-2016                                                                               
    # Last Modified by.......: Mudit Saxena 
    # Last Modified Date.....: 28-08-2016
    # Description............: Standred Controller Constructor.                          
    ##################################################################################################*/
    public QuBy_OppInfoForQB(  ) {
        String QuoteNo = ApexPages.currentPage().getParameters().get('qno');
        if( QuoteNo != null ){
            
            List<QuBy_Detail__c> QB = [ SELECT id, name, Quote_Number__c FROM QuBy_Detail__c where Quote_Number__c =: QuoteNo ];
            if( QB.size()>0 ){
                system.JSONGenerator gen = system.JSON.createGenerator(true);
                //gen.writeStringField('LaunchType','openQuote');
                oppJSON=generateQtJson(QB.get(0));
            
            }
           
        }else{
            String oppid = ApexPages.currentPage().getParameters().get('oppno');
            if( oppid != null ){                
                Opportunity opp = [ SELECT id, name, Opportunity_Number__c, Expected_Delivery_Date__c, /*Advocated_Solution__c,*/ Invoice_Trigger__c, /*Solution_Portfolio__c, - P360 Initial Change-Ahad*/ Sales_Org_Code__c, Owner.Quicklook_id__c, Owner.Name, Owner.Global_ID__c, Account.Name, Account.Master_Customer_Number__c, Account.Account_Country_Code__c, Account.Industry  FROM Opportunity where id =: oppid ];
                User u=[Select quicklook_id__c from user where id=:UserInfo.getUserId()]  ;        
                oppJSON=generateOppJson(opp,u);
            }
            else{
                oppJSON=generateStdJson();
            }
        }
        
    }
    public  string generateOppJson(Opportunity opp, User u){
          JSONGenerator gen = JSON.createGenerator(true);
          gen.writeStartObject();
          gen.writeStringField('LaunchType','QuoteCreate');
          gen.writeStringField('id',opp.id);
          gen.writeStringField('OpportunityName',opp.name);
          gen.writeStringField('OpportunityNumber',opp.Opportunity_Number__c);
          if(opp.Expected_Delivery_Date__c!=null){
            gen.writeDateField('ExpectedDeliveryDate',opp.Expected_Delivery_Date__c);
            }
        /*  if(opp.Advocated_Solution__c!=null){
              //for p360 changes removing Advocated Solution, replacing by '';
          //gen.writeStringField('AdvocatedSolution',opp.Advocated_Solution__c); 
         
          }*/
         gen.writeStringField('AdvocatedSolution','');
          if(opp.Invoice_Trigger__c!=null){
          gen.writeStringField('InvoiceTrigger',opp.Invoice_Trigger__c); 
          }
          /*if(opp.Solution_Portfolio__c!=null){
              //for p360 changes removing OfferPortfolio, replacing by '';
          gen.writeStringField('OfferPortfolio','');
              } - P360 Initial Change-Ahad */ 
          if(opp.Sales_Org_Code__c!=null){
          gen.writeStringField('SalesOrgCode',opp.Sales_Org_Code__c);
              }
          gen.writeStringField('OpportunityOwnerQuicklook',opp.Owner.Quicklook_ID__c);
          if(opp.Owner.Name!=null){
          gen.writeStringField('OwnerFullName',opp.Owner.Name);
              }
         if(opp.Owner.Global_ID__c!=null){
          gen.writeStringField('OwnerGlobalId',opp.Owner.Global_ID__c);
              }
          //gen.writeStringField('AccountName',opp.Account.Name);
          gen.writeStringField('AccountName','');
          gen.writeStringField('MCN',opp.Account.Master_Customer_Number__c); 
          if(opp.Account.Industry!=null){
          gen.writeStringField('AccountLOB',opp.Account.Industry);
          }
          if(opp.Account.Account_Country_Code__c!=null){
          gen.writeStringField('AccountCountry',opp.Account.Account_Country_Code__c);
          }
          gen.writeStringField('UserQuicklook',u.Quicklook_ID__c);          
          gen.writeEndObject();
          //end of the parent JSON object  
          String jsonString = gen.getAsString();
          return jsonString;
     }
     /*
    public  string generateQtJson(QuBy__c qb){
          JSONGenerator gen = JSON.createGenerator(true);
          gen.writeStartObject();
          gen.writeStringField('LaunchType','QuoteOpen');
          gen.writeStringField('id',qb.id);
          gen.writeStringField('QuoteName',qb.name);
          gen.writeStringField('QuoteNumber',qb.Quote_Number__c);                    
          gen.writeEndObject();
          String jsonString = gen.getAsString();
          return jsonString;
     }
     */
    public  string generateQtJson(QuBy_detail__c qb){
          JSONGenerator gen = JSON.createGenerator(true);
          gen.writeStartObject();
          gen.writeStringField('LaunchType','QuoteOpen');
          gen.writeStringField('id',qb.id);
          gen.writeStringField('QuoteName',qb.name);
          gen.writeStringField('QuoteNumber',qb.Quote_Number__c);                    
          gen.writeEndObject();
          String jsonString = gen.getAsString();
          return jsonString;
     }
    public  string generateStdJson(){
          JSONGenerator gen = JSON.createGenerator(true);
          gen.writeStartObject();
          gen.writeStringField('LaunchType','QuoteBuilder');                 
          gen.writeEndObject();
          String jsonString = gen.getAsString();
          return jsonString;
     }
}