force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Active_Contact__c.field-meta.xml
<CustomField>
    <fullName>Active_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field that ,when checked, indicates that the Contact is active</description>
    <label>Active Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Web_Portal_Login__c.field-meta.xml
<CustomField>
    <fullName>Web_Portal_Login__c</fullName>
    <description>This contact&apos;s login for access of the NCR Web Portal</description>
    <label>Web Portal Login</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/SFDC_MDF__c.object-meta.xml
<CustomObject>
    <description>Track MDF request details including partner account, requested amount, activity type and date, and approval status.</description>
    <label>Fund Request</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <description>The date the activity is planned. Optionally incorporate a validation rule to ensure that there is ample lead time to approve the request before the planned activity.</description>
    <inlineHelpText>This is the day of the event or the date the activity begins.</inlineHelpText>
    <label>Activity Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Description__c.field-meta.xml
<CustomField>
    <fullName>Activity_Description__c</fullName>
    <label>Activity Description</label>
    <length>90000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <description>A list of available activity types. Customize as needed.</description>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E-marketing Digital Campaign</fullName>
            </value>
            <value>
                <fullName>E-marketing - Video</fullName>
            </value>
            <value>
                <fullName>Event - Campaign in a box</fullName>
            </value>
            <value>
                <fullName>Event - Conference / Tradeshow only</fullName>
            </value>
            <value>
                <fullName>Event - Customer Briefing Center (CBC) Visit</fullName>
            </value>
            <value>
                <fullName>Event – Partner Seminar / Roadshow</fullName>
            </value>
            <value>
                <fullName>Event - Tradeshow in a box including event</fullName>
            </value>
            <value>
                <fullName>Event – Training</fullName>
            </value>
            <value>
                <fullName>Event – Webinar</fullName>
            </value>
            <value>
                <fullName>NCR defined Sales Program – Funded Head Count Distributor Only</fullName>
            </value>
            <value>
                <fullName>Print – Business case driven</fullName>
            </value>
            <value>
                <fullName>Sales Program - Incentive</fullName>
            </value>
            <value>
                <fullName>Sales Program - Telesales/Telemarketing</fullName>
            </value>
            <value>
                <fullName>Search Engine Marketing/Social Media/PR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The requested amount. Consider activating a validation rule to enforce a certain minimum or maximum amount</description>
    <label>Approved Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is automatically checked by the fund request approval process and in turn recalculates the budget balances</description>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Activity End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <label>Estimated Number of Leads</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Other_Vendors_Represented__c.field-meta.xml
<CustomField>
    <fullName>Other_Vendors_Represented__c</fullName>
    <description>Other Vendors Represented in the Activity.</description>
    <inlineHelpText>Other Vendors Represented in the Activity.</inlineHelpText>
    <label>Other Vendors Represented</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fujitsu</fullName>
            </value>
            <value>
                <fullName>Zebra Technologies</fullName>
            </value>
            <value>
                <fullName>Micros</fullName>
            </value>
            <value>
                <fullName>Datalogic</fullName>
            </value>
            <value>
                <fullName>Epson</fullName>
            </value>
            <value>
                <fullName>Cognitive TPG</fullName>
            </value>
            <value>
                <fullName>Elo Touch Solutions</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
            <value>
                <fullName>HP ( Hewlett Packard)</fullName>
            </value>
            <value>
                <fullName>SII (Seiko Instruments)</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Payleven</fullName>
            </value>
            <value>
                <fullName>Motorola solutions</fullName>
            </value>
            <value>
                <fullName>Intermec (by Honeywell)</fullName>
            </value>
            <value>
                <fullName>APG Cash Drawer</fullName>
            </value>
            <value>
                <fullName>Applied Data Corp</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Epicor Retail Solutions</fullName>
            </value>
            <value>
                <fullName>JDA Software</fullName>
            </value>
            <value>
                <fullName>LOC Software</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund request approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request Created</fullName>
                <default>true</default>
                <label>Request Created</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Level 1 Review</fullName>
            </value>
            <value>
                <fullName>Level 2 Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/SFDC_MDF_Claim__c.object-meta.xml
<CustomObject>
    <description>A set of claims tied to a specific fund request.</description>
    <label>Fund Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of the current claim</description>
    <label>Approved Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to trigger budget recalculate workflow</description>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Fund_Request__c.field-meta.xml
<CustomField>
    <fullName>Fund_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Note: This cannot be a master detail relationship if you plan to use approval workflow as the fund request will be locked (during approval and most likely post approval) and therefore any child claims cannot be saved</description>
    <label>Fund Request</label>
    <referenceTo>SFDC_MDF__c</referenceTo>
    <relationshipLabel>Fund Claims</relationshipLabel>
    <relationshipName>R00N30000002DjDcEAK</relationshipName>
    <trackHistory>false</trueHistory>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund claim approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchShareMDFClaimTest.cls
@isTest
public class BatchShareMDFClaimTest 
{
    public static testMethod void testBatchShareMDFClaim() 
    {
        
        //Insert Partner Account
        Account act = new Account();
        act.Name = 'Partner Test Account';
        List<RecordType> actRecordtypes = [SELECT Id, Name From RecordType WHERE DeveloperName='Partner' AND IsActive = true AND SobjectType = 'Account' Limit 1];
        if (actRecordtypes.size() > 0)
            act.RecordTypeId = actRecordtypes[0].Id;
        act.Account_Country_Code__c = 'US';
        act.Active_Account__c = true;
        act.CurrencyIsoCode = 'USD';
        act.Industry = 'FINANCIAL:BANKING';
        act.Master_Customer_Number__c = '91663446';
        system.runAs(TestRecordsFactory.getUser()){
        insert act;
        }
        //Insert Partner Contact
        Contact con = new Contact();
        con.lastName = 'Mahla';
        con.Email = 'sm245987@gmail.com';
        con.AccountId = act.Id;
        con.Active_Contact__c = true;
        con.Web_Portal_Login__c = 'wplUser';
        insert con;
        
         //Insert Partner Contact
        Contact con2 = new Contact();
        con2.lastName = 'Mahla';
        con2.Email = 'sm245987@gmail.com';
        con2.AccountId = act.Id;
        con2.Active_Contact__c = true;
        con2.Web_Portal_Login__c = 'wplUser';
        insert con2;
        
        //Insert Partner User
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name ='IPT Partner Community Login User' Limit 1];
        User u1 = new User();
        u1.ContactId = con.Id;
        u1.Username = 'wplUser@ncr.com';
        u1.ProfileId = portalProfile.Id;
        u1.Alias = 'test123';
        u1.Email = 'sm245987@gmail.com';
        u1.EmailEncodingKey = 'UTF-8';
        u1.LastName = 'McTesty';
        u1.CommunityNickname = 'test12345';
        u1.TimeZoneSidKey = 'America/Los_Angeles';
        u1.LocaleSidKey = 'en_US';
        u1.LanguageLocaleKey = 'en_US';
        u1.FederationIdentifier = 'wplUser';
        insert u1;
        
        User u2 = new User();
        u2.ContactId = con2.Id;
        u2.Username = 'wplUser1@ncr.com';
        u2.ProfileId = portalProfile.Id;
        u2.Alias = 'test1234';
        u2.Email = 'sm2459874@gmail.com';
        u2.EmailEncodingKey = 'UTF-8';
        u2.LastName = 'McTesty';
        u2.CommunityNickname = 'test123456';
        u2.TimeZoneSidKey = 'America/Los_Angeles';
        u2.LocaleSidKey = 'en_US';
        u2.LanguageLocaleKey = 'en_US';
        u2.FederationIdentifier = 'wplUser1';
        u1.isActive = true;
        insert u2;
        
        //create new fund request
        SFDC_MDF__c mdf = new SFDC_MDF__c();
        mdf.Name= 'test-MDF';
        mdf.Activity_Date__c= Date.today();
        mdf.End_Date__c= Date.today().addDays(1);
        mdf.Activity_Type__c= 'Event - Roadshow';
        mdf.Other_Vendors_Represented__c='Micros';
        mdf.Activity_Description__c='TestDescription';
        mdf.Number_of_Leads__c= 1000;       
        mdf.Status__c='Request Created'; 
        //mdf.budget__c = budget.Id;
        mdf.amount__c = Decimal.valueOf('1000'); 
        mdf.Approved__c = true;
        mdf.OwnerId = u1.Id;
        insert mdf;
        
        
        //create new fund claim
        SFDC_MDF_Claim__c mdfClaim = new SFDC_MDF_Claim__c();
        mdfClaim.name = 'test';
        mdfClaim.Fund_Request__c = mdf.id;
        mdfClaim.Released_Month__c = 'Jan';
        mdfClaim.Released_Year__c = '2017';
        mdfClaim.OwnerId = u1.Id;
        insert mdfClaim;
        
        Test.startTest();
        Database.executeBatch(new BatchShareMDFClaim(new Set<Id>{mdfClaim.Id}));
        SFDC_MDF_Claim__Share mdfShareObj = [select id from SFDC_MDF_Claim__Share where ParentId=:mdfClaim.id];
        System.assert(mdfShareObj.id!=null);
        Database.executeBatch(new BatchShareMDF(new Set<Id>{mdf.Id}));
        Test.stopTest();
        
        Database.executeBatch(new BatchShareMDFWithPartnerUser(new Set<Id>{u2.Id}));
    }
}