force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>End-user Customer account that is in a RoR country</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/ASM_Role_Hierarchy__c/ASM_Role_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Account Point of Contacts</label>
    <nameField>
        <displayFormat>APOC{000000}</displayFormat>
        <label>APOC ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Point of Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Point of Contacts</relationshipLabel>
    <relationshipName>Account_Point_of_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <externalId>true</externalId>
    <label>Master</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/NCR_Employee_Detail__c.field-meta.xml
<CustomField>
    <fullName>NCR_Employee_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to associate NCR Employee Detail so that we can assign the roles to the users.</description>
    <label>NCR Employee Detail</label>
    <referenceTo>NCR_Employee_Detail__c</referenceTo>
    <relationshipLabel>Account Point of Contacts</relationshipLabel>
    <relationshipName>Account_Point_of_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/QuickLook_ID__c.field-meta.xml
<CustomField>
    <fullName>QuickLook_ID__c</fullName>
    <label>Role User QuickLook ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Role_Name__c.field-meta.xml
<CustomField>
    <fullName>Role_Name__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Director</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>Account Services Manager</fullName>
                <isActive>false</isActive>
                <label>Account Services Manager</label>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Support Analyst</fullName>
            </value>
            <value>
                <fullName>Account Support Manager</fullName>
            </value>
            <value>
                <fullName>Channel Account Manager</fullName>
            </value>
            <value>
                <fullName>CMS Account Manager</fullName>
            </value>
            <value>
                <fullName>COA</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>COL</fullName>
            </value>
            <value>
                <fullName>Collector</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Customer Advocate</fullName>
            </value>
            <value>
                <fullName>Customer Delivery Partner (CDP)</fullName>
            </value>
            <value>
                <fullName>Customer Project Manager (CPM)</fullName>
            </value>
            <value>
                <fullName>Customer Relationship Manager</fullName>
            </value>
            <value>
                <fullName>Customer Success Analyst</fullName>
            </value>
            <value>
                <fullName>Customer Success Leader</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
            <value>
                <fullName>Executive Service Manager</fullName>
            </value>
            <value>
                <fullName>Executive Services Manager</fullName>
                <isActive>false</isActive>
                <label>Executive Services Manager</label>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Field Operations</fullName>
            </value>
            <value>
                <fullName>Field Service Coordinator</fullName>
            </value>
            <value>
                <fullName>Field Training</fullName>
            </value>
            <value>
                <fullName>Global Account Manager</fullName>
            </value>
            <value>
                <fullName>Inside Sales Specialist</fullName>
            </value>
            <value>
                <fullName>PO/Billing Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BPM_Configuration__c/BPM_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BPM Configuration</label>
</CustomObject>

force-app/main/default/objects/CA_Hierarchy__c/CA_Hierarchy__c.object-meta.xml
<CustomObject>
    <description>This is to store customer advocate hierarchy which is different from salesforce(NCR) Hierarchy for APOC system</description>
    <label>CA Hierarchy</label>
    <nameField>
        <displayFormat>CA{00000}</displayFormat>
        <label>CA Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CA_Hierarchy__c/fields/CA_QuicklookId__c.field-meta.xml
<CustomField>
    <fullName>CA_QuicklookId__c</fullName>
    <label>CA QuicklookId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CA_Hierarchy__c/fields/Manager1_Quicklookid__c.field-meta.xml
<CustomField>
    <fullName>Manager1_Quicklookid__c</fullName>
    <label>Manager1 Quicklookid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CATM</description>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <label>Quicklook ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/NCR_Employee_Detail__c.object-meta.xml
<CustomObject>
    <description>This object stores the details of all NCR employees.</description>
    <label>NCR Employee Detail</label>
    <nameField>
        <label>NCR Employee Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCR Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Contingent_Manager__c.field-meta.xml
<CustomField>
    <fullName>Contingent_Manager__c</fullName>
    <label>Contingent Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_ID__c</fullName>
    <label>Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/InActive__c.field-meta.xml
<CustomField>
    <fullName>InActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_ID__c</fullName>
    <label>User Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Manager_Level_01_ID__c.field-meta.xml
<CustomField>
    <fullName>Manager_Level_01_ID__c</fullName>
    <description>This field is used in Sales Order Reporting.</description>
    <label>Manager Level 01 ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UserDeactivateNotificationTest.cls
/*************************************************************************************************
*   ClassName :   UserDeactivateNotificationTest
*   Description :   
*   Author      :   
# Modification History.: 
Story No#       Date            DevName            Description
EBA_SF-1909     12-08-2022      Monika      Technical Debt - Apex sharing violation part 1 
*************************************************************************************************/
@isTest
public class UserDeactivateNotificationTest {
    @TestSetUp
    public static void unitTest(){
        
        
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            User u = new User(Alias = 'standt', Email='standarduser@testorg.com', quicklook_Id__c = 'aa123456',
                              EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='stand11111@testorg.com');
            insert u;
            User usr =[SELECT ID,Manager_Level_01_ID__c FROM USER where Quicklook_ID__c='sm185526'];
            Account acc=TestRecordsFactory.createAccount();
        Account acc1=TestRecordsFactory.createAccount('APOC1111');
        Contact con = TestRecordsFactory.createContact(acc);
        /*List<BPM_Configuration__c> bpmConfList = new List<BPM_Configuration__c>();
            bpmConfList.add(new BPM_Configuration__c(Name='APOCMail',values__C='vp250252@ncr.com'));
            bpmConfList.add(new BPM_Configuration__c(Name='APOCBCC',values__C='vp250252@ncr.com'));
        bpmConfList.add(new BPM_Configuration__c(Name='BPMContactIdForNotifyActionOwner',values__C=con.id));
        bpmConfList.add(new BPM_Configuration__c(Name='APOCAccount',values__C=acc1.Master_Customer_Number__c));
            bpmConfList.add(new BPM_Configuration__c(Name='BPM Email - added into QLID',values__C='@ncr.com.invalid'));
        insert bpmConfList;*/
                    List<NCR_Employee_Detail__c> ncrlist = new List<NCR_Employee_Detail__c>();

        NCR_Employee_Detail__c n = new NCR_Employee_Detail__c(Name='User1',Quicklook_ID__c='sm185526',Global_ID__c='1000',Contingent_Manager__c='1001',Employee_type__c='NCR',Inactive__c=false);
            ncrlist.add(n);
            NCR_Employee_Detail__c n1 = new NCR_Employee_Detail__c(Name='User2',Quicklook_ID__c='nb250130',Global_ID__c='1001',Contingent_Manager__c='1002',Employee_type__c='NCR',Inactive__c=false);
            ncrlist.add(n1);
        NCR_Employee_Detail__c n2 = new NCR_Employee_Detail__c(Name='User2',Quicklook_ID__c='nb250250',Global_ID__c=usr.Manager_Level_01_ID__c,Contingent_Manager__c='1002',Employee_type__c='NCR',Inactive__c=false);
            ncrlist.add(n2);
            insert ncrlist;
         
        List<ASM_Role_Hierarchy__c> asms = new List<ASM_Role_Hierarchy__c>();
            ASM_Role_Hierarchy__c asm = new ASM_Role_Hierarchy__c();
            asm.Role_Name__c = 'PO/Billing Person';
            asm.Master__c = acc.Master_Customer_Number__c;
            asm.Account__c = acc.Id;
            asm.QuickLook_ID__c = 'sm185526';  
        asms.add(asm);
        ASM_Role_Hierarchy__c asm1 = new ASM_Role_Hierarchy__c();
            asm1.Role_Name__c = 'Customer Advocate';
            asm1.Master__c = acc.Master_Customer_Number__c;
            asm1.Account__c = acc.Id;
            asm1.QuickLook_ID__c = 'sm185526';
        asms.add(asm1);
        ASM_Role_Hierarchy__c asm2 = new ASM_Role_Hierarchy__c();
            asm2.Role_Name__c = 'Account Support Manager';
            asm2.Master__c = acc.Master_Customer_Number__c;
            asm2.Account__c = acc.Id;
            asm2.QuickLook_ID__c = 'sm185526';
          asms.add(asm2);
        ASM_Role_Hierarchy__c asm3 = new ASM_Role_Hierarchy__c();
            asm3.Role_Name__c = 'Account Executive';
            asm3.Master__c = acc.Master_Customer_Number__c;
            asm3.Account__c = acc.Id;
            asm3.QuickLook_ID__c = 'sm185526';
          asms.add(asm3);
        ASM_Role_Hierarchy__c asm4 = new ASM_Role_Hierarchy__c();
            asm4.Role_Name__c = 'Account Director';
            asm4.Master__c = acc.Master_Customer_Number__c;
            asm4.Account__c = acc.Id;
            asm4.QuickLook_ID__c = 'sm185526';
          asms.add(asm4);
         ASM_Role_Hierarchy__c asm5 = new ASM_Role_Hierarchy__c();
            asm5.Role_Name__c = 'Account Manager';
            asm5.Master__c = acc.Master_Customer_Number__c;
            asm5.Account__c = acc.Id;
            asm5.QuickLook_ID__c = 'sm185526';
          asms.add(asm5);
         ASM_Role_Hierarchy__c asm6 = new ASM_Role_Hierarchy__c();
            asm6.Role_Name__c = 'Account Support Analyst';
            asm6.Master__c = acc.Master_Customer_Number__c;
            asm6.Account__c = acc.Id;
            asm6.QuickLook_ID__c = 'nb250130';
          asms.add(asm6);
        List<BPM_Configuration__c> bpmConfList = new List<BPM_Configuration__c>();
        bpmConfList.add(new BPM_Configuration__c(Name='APOCMail',values__C='vp250252@ncr.com'));
        bpmConfList.add(new BPM_Configuration__c(Name='APOCBCC',values__C='vp250252@ncr.com'));
        bpmConfList.add(new BPM_Configuration__c(Name='BPMContactIdForNotifyActionOwner',values__C=con.id));
        bpmConfList.add(new BPM_Configuration__c(Name='APOCAccount',values__C=acc.Master_Customer_Number__c));
        bpmConfList.add(new BPM_Configuration__c(Name='BPM Email - added into QLID',values__C='@ncr.com.invalid'));
        bpmConfList.add(new BPM_Configuration__c(Name='BPMProfile',values__C='BPM Partner Community User'));
        // bpmConfList.add(new BPM_Configuration__c(Name='excProfileId',values__C='00e70000001NyoaAAC'));
        bpmConfList.add(new BPM_Configuration__c(Name='excProfileId',values__C=NSCCommonInfoUtil.getIdOf('iPaas_Administration_Profile_Id')));
        bpmConfList.add(new BPM_Configuration__c(Name='BPMDefaultPOQLID',values__C='ob230024'));
        
        insert bpmConfList;
        
        
            insert asms;
         insert new CA_Hierarchy__c(CA_QuicklookId__c= 'nb250130',Manager1_Quicklookid__c='ad250024');
         
          
    }
    @isTest static void TestOnDeactivationOfUsers(){
        Test.startTest();
        User user1 = [SELECT ID,IsActive,Quicklook_ID__c FROM USER WHERE Quicklook_ID__c ='sm185526'];
        try{
       	user1.IsActive = false;
        update user1;
        }catch(Exception ex){
            System.debug('exception occured');
        }
        Test.stopTest();
        System.assertEquals(user1.Quicklook_ID__c,'sm185526');
    }
    @isTest static void TestOnDeactivationOfUsers1(){
        Test.startTest();
       	User user0 = [SELECT ID,IsActive FROM USER WHERE Name =: Label.AdmUser and isactive =true];
        User user1 = [SELECT ID,IsActive FROM USER WHERE Quicklook_ID__c ='sm185526'];
        System.runas(user0){
            try{
                user1.IsActive = false;
                update user1;
            }catch(Exception ex){
                System.debug('exception occured');
            }
        }
        Test.stopTest();
        System.assert(!user1.IsActive);
    }
    @isTest static void TestOnDeactivationOfUsers2(){
        Test.startTest();
       	User user0 = [SELECT ID,IsActive FROM USER WHERE Name =:Label.AdmUser and isactive =true];
        User user1 = [SELECT ID,IsActive FROM USER WHERE Quicklook_ID__c ='mm185627'];
        PageReference myVfPage = Page.APOCDeactivateAlertPDF;
        Test.setCurrentPage(myVfPage);
        ApexPages.currentPage().getParameters().put('Id',user1.Id);
        APOCDeactivateCntlr ap = new APOCDeactivateCntlr();
        System.runas(user0){
            try{
                user1.IsActive = false;
                update user1;
            }catch(Exception ex){
                System.debug('exception occured');
            }
        }
        Test.stopTest();
        System.assert(!user1.IsActive);
    }
}