force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <externalId>true</externalId>
    <label>Site Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Hospitality_Experience_Cloud_Automation__c.field-meta.xml
<CustomField>
    <fullName>Hospitality_Experience_Cloud_Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hospitality Experience Cloud Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PID__c.field-meta.xml
<CustomField>
    <fullName>PID__c</fullName>
    <externalId>true</externalId>
    <label>PID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>External Serial Number</description>
    <externalId>true</externalId>
    <label>Serial Number (Custom)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Site_Id__c.field-meta.xml
<CustomField>
    <fullName>Site_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Number</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (Site)</relationshipLabel>
    <relationshipName>Site_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Case/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <formula>Account.Master_Customer_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Master Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PID__c.field-meta.xml
<CustomField>
    <fullName>PID__c</fullName>
    <description>This field will be used to input the PID numbers that are being reviewed.</description>
    <inlineHelpText>What PIDs are being reviewed</inlineHelpText>
    <label>PID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Site_Id__c.field-meta.xml
<CustomField>
    <fullName>Site_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Site record types are allowed.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case (Customer Site)</relationshipLabel>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <description>This text field will be used for the analyst to input all the site numbers being reviewed</description>
    <inlineHelpText>What site numbers are being reviewed</inlineHelpText>
    <label>Site Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Contact__c.field-meta.xml
<CustomField>
    <fullName>Active_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field that ,when checked, indicates that the Contact is active</description>
    <label>Active Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hospitality_ACR_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Hospitality_ACR_Processing_Status__c</fullName>
    <description>Used for tracking HSR AccountContactRelations Creation Batch Job</description>
    <label>Hospitality ACR Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Process</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solution_Set_HW_Role_Relation__c/Solution_Set_HW_Role_Relation__c.object-meta.xml
<CustomObject>
    <label>Solution Set - HW Role Relation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solution Set - HW Role Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution_Set_HW_Role_Relation__c/fields/HW_Role_Id__c.field-meta.xml
<CustomField>
    <fullName>HW_Role_Id__c</fullName>
    <externalId>true</externalId>
    <label>HW Role Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Alt_Work_Site_Flag__c.field-meta.xml
<CustomField>
    <fullName>Alt_Work_Site_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Alt Work Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Config_Details__c.field-meta.xml
<CustomField>
    <fullName>Config_Details__c</fullName>
    <label>Config Details</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Customer_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Customer External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Customer_Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_Number__c</fullName>
    <label>Customer Ticket Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Out_of_Scope__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Scope__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Scope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/PID__c.field-meta.xml
<CustomField>
    <fullName>PID__c</fullName>
    <label>PID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Priority_Type__c.field-meta.xml
<CustomField>
    <fullName>Priority_Type__c</fullName>
    <formula>IF( Request_Type_Mapping__c = &apos;RMA-RRW&apos;, 1,
			IF( Request_Type_Mapping__c = &apos;RMA-STD&apos;, 2,
						IF(Request_Type_Mapping__c = &apos;3rd Party Dispatch&apos;, 3, 4
									)
						)
			)</formula>
    <label>Priority Type</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Request_Type_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Request_Type_Mapping__c</fullName>
    <formula>IF(AND(Out_of_Scope__c, ISPICKVAL(Service_Level_Name__c, &apos;15 Day Repair &amp; Return&apos;)),&apos;RMA-RRA&apos; ,  
			IF(AND(Out_of_Scope__c, ISPICKVAL(Service_Level_Name__c, &apos;5x9 NBD PO&apos;)),&apos;RMA-STD&apos; ,
						IF(ISPICKVAL(Request_Type__c, &apos;NEW FOR NEW&apos;), &apos;New-OBF&apos;,
									IF(ISPICKVAL(Request_Type__c, &apos;RMA UPGRADE&apos;) ,&apos;RMA-UPG&apos; ,
												IF(ISPICKVAL(Request_Type__c, &apos;WRONG PART SHIPPED&apos;) ,&apos;RMA-ERR&apos; ,
															IF(ISPICKVAL(Request_Type__c, &apos;OUT OF BOX FAILURE&apos;) ,&apos;RMA-OBF&apos; ,
                IF(AND(ISPICKVAL(Service_Level_Type__c, &apos;TPM&apos;), Service_Level_Response__c != &apos;RRR&apos;), &apos;3rd Party Dispatch&apos; ,  
			                IF(AND(ISPICKVAL(Service_Level_Type__c, &apos;AED&apos;), Service_Level_Response__c != &apos;RRR&apos;), &apos;RMA-STD&apos; ,
					                	IF(AND(Service_Level_Response__c = &apos;RRR&apos;, OR(ISPICKVAL(Service_Level_Type__c, &apos;AED&apos;), ISPICKVAL(Service_Level_Type__c, &apos;TPM&apos;))), &apos;RMA-RRW&apos;
																											, &apos;Unknown&apos;
																									)
																						)
																			)
																)
													)
											)
								)
					)
		)</formula>
    <label>Request Type (Mapping)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Service_Level_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Level_Id__c</fullName>
    <label>Service Level Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Method__c</fullName>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>2nd Day Air</fullName>
            </value>
            <value>
                <fullName>3 Day Select</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Next Day Air</fullName>
            </value>
            <value>
                <fullName>Next Day Air Saver</fullName>
            </value>
            <value>
                <fullName>Next Flight Out</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
            <value>
                <fullName>Saturday Delivery</fullName>
            </value>
            <value>
                <fullName>FedEx First Overnight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Site_Id__c.field-meta.xml
<CustomField>
    <fullName>Site_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/SN_Override__c.field-meta.xml
<CustomField>
    <fullName>SN_Override__c</fullName>
    <label>SN Override</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/SN_Override_Flag__c.field-meta.xml
<CustomField>
    <fullName>SN_Override_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SN Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Solution_Set_HW_Role_Relation__c.field-meta.xml
<CustomField>
    <fullName>Solution_Set_HW_Role_Relation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution Set - HW Role Relation</label>
    <referenceTo>Solution_Set_HW_Role_Relation__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Street_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Street_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HSRSelector.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Selector class that contains all Database queries for Hospitality Service Cloud custom
* logic. This class also contains all data mock records used for unit testing, the
* data mock is used to control the values returned by the query and help avoid running any
* unnecessary SOQL or DMLs that might fail due to external factors (like field visibility
* or custom validation).
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Basel Altamimi    <ba250204@ncr.com>
* @modifiedBy     Basel Altamimi    <ba250204@ncr.com>
* @version        1.0
* @created        2022-05-20
* @modified       2022-05-25
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v1.0            ba250204@ncr.com
* 2022-05-20
*
* v1.1            ba250204@ncr.com
* 2022-07-15      Code refactoring (switch from hard-coded Strings to HSRConstants).
*                 Add AccountContactRelation selector methods
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

public inherited sharing class HSRSelector {

    @TestVisible
    private static Boolean mockResults = false;

    // === Account ===
    public static List<Account> getAccountsByCustomersNumbers(List<String> customersNumbers) {
        return (isMock() ?
                mockAccountRecords() : [
                        SELECT
                                Id,
                                Owner.UserRoleId
                        FROM Account
                        WHERE Master_Customer_Number__c IN :customersNumbers
                        AND (
                                RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_CUSTOMER
                                OR RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_PARTNER
                        )
                ]
        );
    }

    public static Database.QueryLocator getAccountQueryLocator_ARCBatchJob(List<Id> contactsIds) {
        return Database.getQueryLocator([
                SELECT
                        Id,
                        ParentId
                FROM Account
                WHERE RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_SITE
                AND Active_Account__c = TRUE
                AND ParentId IN (
                        SELECT
                                AccountId
                        FROM AccountContactRelation
                        WHERE ContactId IN :contactsIds
                        AND (
                                Account.RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_CUSTOMER
                                OR Account.RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_PARTNER
                        )
                )
                AND Id NOT IN (
                        SELECT
                                AccountId
                        FROM AccountContactRelation
                        WHERE ContactId IN :contactsIds
                        AND Account.RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_SITE
                )
        ]);
    }

    public static List<Account> getSiteAccountsByParentId_ACRToCreate(List<Id> contactsIds, Integer numberOfRecords) {
        return isMock() ?
                mockAccountRecords() : [
                        SELECT
                                Id,
                                ParentId
                        FROM Account
                        WHERE RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_SITE
                        AND Active_Account__c = TRUE
                        AND ParentId IN (
                                SELECT
                                        AccountId
                                FROM AccountContactRelation
                                WHERE ContactId IN :contactsIds
                                AND (
                                        Account.RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_CUSTOMER
                                        OR Account.RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_PARTNER
                                )
                        )
                        AND Id NOT IN (
                                SELECT
                                        AccountId
                                FROM AccountContactRelation
                                WHERE ContactId IN :contactsIds
                                AND Account.RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_SITE
                        )
                        LIMIT :numberOfRecords
                ];
    }

    // === Contact ===
    public static List<Contact> getContactsByEmail(String email) {
        return (isMock() ?
                mockContactRecords() : [
                        SELECT
                                Id,
                                (
                                        SELECT
                                                Id
                                        FROM Users
                                )
                        FROM Contact
                        WHERE Email LIKE :email
                        AND Active_Contact__c = TRUE
                ]
        );
    }

    public static List<Contact> getContactsByACRStatus(String status) {
        return (isMock() ?
                mockContactRecords() : [
                        SELECT
                                Id,
                                AccountId,
                                Hospitality_ACR_Processing_Status__c
                        FROM Contact
                        WHERE Hospitality_ACR_Processing_Status__c = :status
                ]);
    }

    public static Boolean hasPendingACRProcessingRequests() {
        return [
                SELECT
                        Id
                FROM Contact
                WHERE Hospitality_ACR_Processing_Status__c = :HSRConstants.CONTACT_ACR_STATUS_TO_PROCESS
                LIMIT 1
        ].size() > 0;
    }

    // === Account Contact Relation ===
    public static List<AccountContactRelation> getPendingACRToDelete(Id contactId, List<Id> parentAccountIds, Integer numberOfRecords) {
        return [
                SELECT
                        Id
                FROM AccountContactRelation
                WHERE ContactId = :contactId
                AND Account.RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_SITE
                AND (
                        Account.Active_Account__c = FALSE
                        OR (
                                Hospitality_Experience_Cloud_Automation__c = TRUE
                                AND Account.ParentId NOT IN :parentAccountIds
                        )
                )
                LIMIT :numberOfRecords
        ];
    }

    public static List<AccountContactRelation> getMCNAccountContactRelations(List<Id> contactIds) {
        return [
                SELECT
                        Id,
                        ContactId,
                        AccountId
                FROM AccountContactRelation
                WHERE ContactId IN :contactIds
                AND (
                        Account.RecordType.DeveloperName LIKE :HSRConstants.ACCOUNT_RT_CUSTOMER
                        OR Account.RecordType.DeveloperName = :HSRConstants.ACCOUNT_RT_PARTNER
                )
        ];
    }

    // === User ===
    public static List<Contact> getContactsByUserIds(List<Id> userIds) {
        return (isMock() ?
                mockContactRecords() : [
                        SELECT
                                Id,
                                AccountId
                        FROM Contact
                        WHERE Id IN (
                                SELECT
                                        ContactId
                                FROM User
                                WHERE Id IN :userIds
                        )
                ]
        );
    }


    // === Work Order ===
    public static List<WorkOrder> getWorkOrdersById(List<String> orderIds) {
        return (isMock() ?
                mockWorkOrderRecords() : [
                        SELECT
                                Id,
                                Street,
                                Street_Line_2__c,
                                City,
                                PostalCode,
                                State,
                                SN_Override_Flag__c,
                                SN_Override__c,
                                Out_of_Scope__c,
                                Shipment_Method__c,
                                Request_Type_Mapping__c,
                                Priority_Type__c,
                                Alt_Work_Site_Flag__c,
                                Customer_External_Id__c,
                                Service_Level_Id__c,
                                Config_Details__c,
                                Description,
                                Serial_Number__c,
                                WorkOrderNumber,
                                Customer_Ticket_Number__c,

                                AccountId,
                                Account.Master_Customer_Number__c,
                                Account.Account_Country_Code__c,

                                Site_Id__c,
                                Site_Id__r.Site_Number__c,
                                Site_Id__r.Name,
                                Site_Id__r.BillingCountry,
                                ContactId,
                                Contact.FirstName,
                                Contact.LastName,
                                Contact.Phone,
                                Contact.Email,

                                CaseId,
                                Case.Subject,
                                Case.CaseNumber,

                                AssetId,
                                Asset.PID__c,

                                Solution_Set_HW_Role_Relation__c,
                                Solution_Set_HW_Role_Relation__r.HW_Role_Id__c,

                                Support_Class_Failure_Reason_Relation__c,
                                Support_Class_Failure_Reason_Relation__r.Failure_Reason_Id__c
                        FROM WorkOrder
                        WHERE Id IN :orderIds
                ]
        );
    }

    // === Profile ===
    public static Profile getProfileByName(String profileName) {
        return [
                SELECT
                        Id
                FROM Profile
                WHERE Name LIKE :profileName
        ];
    }

    // === Async Apex Job ===
    public static List<AsyncApexJob> getRunningBatchByClassName(String className, List<String> jobType) {
        return [
                SELECT
                        Id
                FROM AsyncApexJob
                WHERE ApexClass.Name = :className
                AND Status IN :HSRConstants.ASYNC_JOB_IN_PROGRESS_STATUS
                AND JobType IN :jobType
        ];
    }

    // -------------------- Data mock --------------------
    @TestVisible
    private static List<WorkOrder> mockWorkOrders { get; set; }
    private static List<WorkOrder> mockWorkOrderRecords() {
        return mockWorkOrders == null ? new List<WorkOrder>() : mockWorkOrders;
    }

    @TestVisible
    private static List<Account> mockAccounts { get; set; }
    private static List<Account> mockAccountRecords() {
        return mockAccounts == null ? new List<Account>() : mockAccounts;
    }

    @TestVisible
    private static List<Contact> mockContacts { get; set; }
    private static List<Contact> mockContactRecords() {
        return mockContacts == null ? new List<Contact>() : mockContacts;
    }

    // -------------------- Util Methods --------------------
    private static Boolean isMock() {
        return Test.isRunningTest() && mockResults;
    }
}