force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Active_Contact__c.field-meta.xml
<CustomField>
    <fullName>Active_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field that ,when checked, indicates that the Contact is active</description>
    <label>Active Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Web_Portal_Login__c.field-meta.xml
<CustomField>
    <fullName>Web_Portal_Login__c</fullName>
    <description>This contact&apos;s login for access of the NCR Web Portal</description>
    <label>Web Portal Login</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/EULA_submission__c.object-meta.xml
<CustomObject>
    <label>EULA submissions</label>
    <nameField>
        <displayFormat>EULA-{0000}</displayFormat>
        <label>EULA submissions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EULA submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EULA_submission__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/fields/Date_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Agreement__c</fullName>
    <label>Date of Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/fields/End_Date_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>End_Date_of_Agreement__c</fullName>
    <label>End Date of Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/fields/Solution_Name_or_Identifying_PID__c.field-meta.xml
<CustomField>
    <fullName>Solution_Name_or_Identifying_PID__c</fullName>
    <label>Solution Name or Identifying PID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EULASubmissionTriggerTest.cls
@isTest
private class EULASubmissionTriggerTest{

    static testmethod  void EULASubmissionTest() {
            Test.startTest(); //denote testing context
        	
        	//Insert Partner Account
        	Account act = new Account();
        	act.Name = 'Partner Test Account';
        	List<RecordType> actRecordtypes = [SELECT Id, Name From RecordType WHERE DeveloperName='Partner' AND IsActive = true AND SobjectType = 'Account' Limit 1];
        	if (actRecordtypes.size() > 0)
            act.RecordTypeId = actRecordtypes[0].Id;
        	act.Account_Country_Code__c = 'US';
        	act.Active_Account__c = true;
        	act.CurrencyIsoCode = 'USD';
        	act.Industry = 'FINANCIAL:BANKING';
        	act.Master_Customer_Number__c = '91663446';
        
        System.runAs(TestRecordsFactory.getUser()){
           insert act;
        }
        	//insert act;
        
        	//Insert Partner Contact
        	Contact con = new Contact();
        	con.lastName = 'Mahla';
        	con.Email = 'sm245987@gmail.com';
        	con.AccountId = act.Id;
            con.Active_Contact__c = true;
            con.Web_Portal_Login__c = 'wplUser';
            insert con;
            
             //Insert Partner Contact
            Contact con2 = new Contact();
            con2.lastName = 'Mahla';
            con2.Email = 'sm245987@gmail.com';
            con2.AccountId = act.Id;
            con2.Active_Contact__c = true;
            con2.Web_Portal_Login__c = 'wplUser';
            insert con2;
            
            //Insert Partner User
            Profile portalProfile = [SELECT Id FROM Profile WHERE Name ='IPT Partner Community Login User' Limit 1];
            User u1 = new User();
            u1.ContactId = con.Id;
            u1.Username = 'wplUser@ncr.com';
            u1.ProfileId = portalProfile.Id;
            u1.Alias = 'test123';
            u1.Email = 'sm245987@gmail.com';
            u1.EmailEncodingKey = 'UTF-8';
            u1.LastName = 'McTesty';
            u1.CommunityNickname = 'test567890';
            u1.TimeZoneSidKey = 'America/Los_Angeles';
            u1.LocaleSidKey = 'en_US';
            u1.LanguageLocaleKey = 'en_US';
            u1.FederationIdentifier = 'wplUser';
            insert u1;
        	System.runAs(u1){
        	EULA_submission__c es = new EULA_submission__c();
        	es.Customer_Name__c ='Test';
            es.Solution_Name_or_Identifying_PID__c ='abc';
		    es.Address__c = 'xyz';
		    es.Date_of_Agreement__c = system.today();
		    es.End_Date_of_Agreement__c = system.today() + 1;
       		//es.OwnerId = u1.id;
			es.Status__c = 'Created';
            Insert es;
          System.assertNotEquals(es, null,'EULA_submission__c should not be null');

        }
            Test.stopTest(); //rev
     
    }
 }