force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <description>CATM</description>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account UID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/Credit_Detail__c.object-meta.xml
<CustomObject>
    <description>This object stores the Credit data information. The Data is coming from EDW via iPaaS.</description>
    <label>AR Detail</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Credit Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Credit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Assigned_Collector__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Collector__c</fullName>
    <label>Primary Collector</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Customer_Balance__c.field-meta.xml
<CustomField>
    <fullName>Customer_Balance__c</fullName>
    <label>Customer Balance</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Not_Due_1_360_Days__c.field-meta.xml
<CustomField>
    <fullName>Not_Due_1_360_Days__c</fullName>
    <label>Not Due 1-360 Days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Not_Due_360_Days__c.field-meta.xml
<CustomField>
    <fullName>Not_Due_360_Days__c</fullName>
    <label>Not Due 360+ Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <label>On Hold</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Past_due_000_to_030_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_000_to_030_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_000_to_030_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Past_due_031_to_045_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_031_to_045_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_031_to_045_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Past_due_046_to_060_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_046_to_060_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_046_to_060_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Past_due_061_to_75_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_061_to_75_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_061_to_75_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Past_due_76_to_90_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_76_to_90_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_76_to_90_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Past_due_90_plus_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_90_plus_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_90_plus_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <label>Risk Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X181_360_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X181_360_Days_Late__c</fullName>
    <label>Aging – 181-360</label>
    <precision>16</precision>
    <scale>2</scale>
    <trackHistory>false</trueHistory>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X1_30_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X1_30_Days_Late__c</fullName>
    <label>Aging &lt; 31</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X31_60_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X31_60_Days_Late__c</fullName>
    <label>Aging – 31-60</label>
    <precision>16</precision>
    <scale>2</scale>
    <trackHistory>false</trueHistory>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X361_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X361_Days_Late__c</fullName>
    <label>Aging &gt; 360</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X61_90_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X61_90_Days_Late__c</fullName>
    <label>Aging – 61-90</label>
    <precision>16</precision>
    <scale>2</scale>
    <trackHistory>false</trueHistory>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X91_180_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X91_180_Days_Late__c</fullName>
    <label>Aging – 91-180</label>
    <precision>16</precision>
    <scale>2</scale>
    <trackHistory>false</trueHistory>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/Credit_Detail_Break_Up__c.object-meta.xml
<CustomObject>
    <label>Credit Detail Break Up</label>
    <nameField>
        <label>Credit Detail Break Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Detail Break Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Aging_181_360__c.field-meta.xml
<CustomField>
    <fullName>Aging_181_360__c</fullName>
    <label>Aging – 181-360</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Aging_31_60__c.field-meta.xml
<CustomField>
    <fullName>Aging_31_60__c</fullName>
    <label>Aging – 31-60</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Aging_31__c.field-meta.xml
<CustomField>
    <fullName>Aging_31__c</fullName>
    <label>Aging &lt; 31</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Aging_360__c.field-meta.xml
<CustomField>
    <fullName>Aging_360__c</fullName>
    <label>Aging &gt; 360</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Aging_61_90__c.field-meta.xml
<CustomField>
    <fullName>Aging_61_90__c</fullName>
    <label>Aging – 61-90</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Aging_91_180__c.field-meta.xml
<CustomField>
    <fullName>Aging_91_180__c</fullName>
    <label>Aging – 91-180</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Classification_Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Classification_Invoice_Type__c</fullName>
    <label>Classification Invoice Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Collector_Name__c.field-meta.xml
<CustomField>
    <fullName>Collector_Name__c</fullName>
    <label>Collector Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Credit_Detail__c.field-meta.xml
<CustomField>
    <fullName>Credit_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Detail</label>
    <referenceTo>Credit_Detail__c</referenceTo>
    <relationshipLabel>Credit Detail Break Ups</relationshipLabel>
    <relationshipName>Credit_Detail_Break_Ups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Customer_Balance__c.field-meta.xml
<CustomField>
    <fullName>Customer_Balance__c</fullName>
    <label>Customer Balance</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Not_Due_1_360_Days__c.field-meta.xml
<CustomField>
    <fullName>Not_Due_1_360_Days__c</fullName>
    <label>Not Due 1-360 Days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Not_Due_360_Days__c.field-meta.xml
<CustomField>
    <fullName>Not_Due_360_Days__c</fullName>
    <label>Not Due 360+ Days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <label>On Hold</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Past_due_000_to_030_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_000_to_030_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_000_to_030_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Past_due_031_to_045_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_031_to_045_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_031_to_045_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Past_due_046_to_060_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_046_to_060_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_046_to_060_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Past_due_061_to_75_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_061_to_75_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_061_to_75_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Past_due_76_to_90_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_76_to_90_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_76_to_90_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Past_due_90_plus_days__c.field-meta.xml
<CustomField>
    <fullName>Past_due_90_plus_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past_due_90_plus_days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <label>Risk Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail_Break_Up__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Credit_Detail_Clean.cls
/**
* Class is used to clean obsolete Credit Detail on daily basis.
*
* @author  Ajay Dixit
* @Data   2020-04-28
*/
global class Credit_Detail_Clean implements Database.Batchable<sObject>,Database.Stateful {
    private Integer hours=24;
    global Boolean clean; 
    global Integer successCounter = 0;
    global Integer failureCounter = 0; 
    global String Status = '';
    Exception[] errorslist = new Exception[0];
    global integer totalSizeRecords=0;
    public Credit_Detail_Clean(Boolean cleanup) {
        this.clean = cleanup;       
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        if(clean){
            DateTime currentDate = DateTime.Now().addHours(-hours); 
            system.debug('***@@@@'+currentDate);
            return DataBase.getQueryLocator([Select Id, LastModifiedDate From Credit_Detail_Break_Up__c where LastModifiedDate<:currentDate]);
        }else{
            return DataBase.getQueryLocator([Select id From Credit_Detail__c]); 
        }        
    }
    global void execute(Database.BatchableContext BC,List<sObject> scope) {
        try {
            system.debug('***@@@'+scope);
            if(clean){
                
                List <Credit_Detail_Break_Up__c> deleteCreditBreakup=new  List <Credit_Detail_Break_Up__c>();
                deleteCreditBreakup=(List <Credit_Detail_Break_Up__c>) scope;
                system.debug('***$$$'+deleteCreditBreakup);
                if (scope.size() > 0 && ! TEST.isRunningTest()) {               
                    Delete deleteCreditBreakup;
                }   
            }else{
                totalSizeRecords+=scope.size();
                //Map<Id, Id> accountOwnerIdToNSCAdminIdMap = new Map<Id,Id>();
                //User nscAdminUser = [Select Id FROM User where name = 'NSC Admin'];
                User nscAdminUser = [Select Id FROM User where Quicklook_ID__c = 'NSCAdmin'];
                //get all credit breakup in scope
                //SELECT Aging_31_60__c,Aging_31__c,Aging_61_90__c,Aging_91_180__c,Aging_181_360__c,Aging_360__c,Classification_Invoice_Type__c,Customer_Balance__c,Industry__c,Not_Due_1_360_Days__c,Not_Due_360_Days__c,On_Hold__c,Risk_Level__c,Unique_ID__c FROM Credit_Detail_Break_Up__c
                List <Credit_Detail__c> rollupCreditList=new  List <Credit_Detail__c>();
                List <Credit_Detail__c> CreditDetail=[SELECT Account__r.OwnerId, Account__r.Owner.IsActive, Account__r.Owner.Profile.Name, (SELECT Aging_31_60__c,Aging_31__c,Aging_61_90__c,Aging_91_180__c,Aging_181_360__c,Aging_360__c,Classification_Invoice_Type__c,Customer_Balance__c,Industry__c,Not_Due_1_360_Days__c,Not_Due_360_Days__c,Past_due_000_to_030_days__c,Past_due_031_to_045_days__c,Past_due_046_to_060_days__c,Past_due_061_to_75_days__c,Past_due_76_to_90_days__c,Past_due_90_plus_days__c,On_Hold__c,Risk_Level__c,Unique_ID__c,Collector_Name__c FROM Credit_Detail_Break_Ups__r), Customer_Balance__c,Not_Due_1_360_Days__c,Not_Due_360_Days__c,On_Hold__c,Risk_Level__c,Unique_ID__c,X1_30_Days_Late__c,X31_60_Days_Late__c,X61_90_Days_Late__c,X91_180_Days_Late__c,X181_360_Days_Late__c,X361_Days_Late__c, Assigned_Collector__c FROM Credit_Detail__c WHERE Id = :scope];
                //Added Collector_Name__c,Assigned_Collector__c in query - EBA_SF-828
                for(Credit_Detail__c cd:CreditDetail){
                    Credit_Detail__c cdn=new Credit_Detail__c();
                    cdn.id=cd.id;
                    //Reset Values
                    /*********************** Credit Detail Owner Assignment ****************************/
                    if(cd.Account__r.Owner.IsActive == false || cd.Account__r.Owner.Profile.Name == 'Read Only'){
                        cdn.OwnerId = nscAdminUser.Id;
                    }else{
                        cdn.OwnerId = cd.Account__r.OwnerId;
                    }
                    
                    cdn.Customer_Balance__c=0;
                    cdn.X1_30_Days_Late__c=0;
                    cdn.X31_60_Days_Late__c=0;
                    cdn.X61_90_Days_Late__c=0;
                    cdn.X91_180_Days_Late__c=0;
                    cdn.X181_360_Days_Late__c=0;
                    cdn.X361_Days_Late__c=0;
                    cdn.Not_Due_1_360_Days__c=0;
                    cdn.Not_Due_360_Days__c=0;
                    cdn.Past_due_000_to_030_days__c=0;
                    cdn.Past_due_031_to_045_days__c=0;
                    cdn.Past_due_046_to_060_days__c=0;
                    cdn.Past_due_061_to_75_days__c=0;
                    cdn.Past_due_76_to_90_days__c=0;
                    cdn.Past_due_90_plus_days__c=0;
                    cdn.Risk_Level__c='';
                    cdn.On_Hold__c='NO';
                    system.debug('***### cd'+cd);
                    system.debug('***###'+cd.Credit_Detail_Break_Ups__r.size());
                       //EBA_SF-828
                        String AR_collector = '';
                    for(Credit_Detail_Break_Up__c cdb:cd.Credit_Detail_Break_Ups__r){
                        if(cdb.Customer_Balance__c != null){
                            cdn.Customer_Balance__c=cdn.Customer_Balance__c+cdb.Customer_Balance__c;
                            cdn.X1_30_Days_Late__c=cdn.X1_30_Days_Late__c+cdb.Aging_31__c;
                            cdn.X31_60_Days_Late__c=cdn.X31_60_Days_Late__c+cdb.Aging_31_60__c;
                            cdn.X61_90_Days_Late__c=cdn.X61_90_Days_Late__c+cdb.Aging_61_90__c;
                            cdn.X91_180_Days_Late__c=cdn.X91_180_Days_Late__c+cdb.Aging_91_180__c;
                            cdn.X181_360_Days_Late__c=cdn.X181_360_Days_Late__c+cdb.Aging_181_360__c;
                            cdn.X361_Days_Late__c=cdn.X361_Days_Late__c+cdb.Aging_360__c;
                            cdn.Not_Due_1_360_Days__c=cdn.Not_Due_1_360_Days__c+cdb.Not_Due_1_360_Days__c;
                            cdn.Not_Due_360_Days__c=cdn.Not_Due_360_Days__c+cdb.Not_Due_360_Days__c;
                            cdn.Past_due_000_to_030_days__c = cdn.Past_due_000_to_030_days__c+cdb.Past_due_000_to_030_days__c;
                            cdn.Past_due_031_to_045_days__c=cdn.Past_due_031_to_045_days__c+cdb.Past_due_031_to_045_days__c;
                            cdn.Past_due_046_to_060_days__c=cdn.Past_due_046_to_060_days__c+cdb.Past_due_046_to_060_days__c;
                            cdn.Past_due_061_to_75_days__c=cdn.Past_due_061_to_75_days__c+cdb.Past_due_061_to_75_days__c;
                            cdn.Past_due_76_to_90_days__c=cdn.Past_due_76_to_90_days__c+cdb.Past_due_76_to_90_days__c;
                            cdn.Past_due_90_plus_days__c=cdn.Past_due_90_plus_days__c+cdb.Past_due_90_plus_days__c;
                            cdn.Risk_Level__c=cdb.Risk_Level__c;
                            cdn.On_Hold__c=cdb.On_Hold__c;
                            //EBA_SF-828
                            if( String.isBlank(AR_collector)){
                                AR_collector = cdb.Collector_Name__c;
                            }
                        }
                        
                    }
                    //EBA_SF-828
                    cdn.Assigned_Collector__c = AR_collector;
                    rollupCreditList.add(cdn);
                    
                }
                
                update rollupCreditList;
                successCounter++;
                
            }
            
            
        } catch (Exception e) {
            failureCounter++;
            errorslist.add(e);
            
        }
    }
    global void finish(Database.BatchableContext BC) {
        if(clean){
            Credit_Detail_Clean rollup = new Credit_Detail_Clean(false);
            ID batchprocessid = Database.executeBatch(rollup);
        }
        
        else
        {
            string emailBodytoReplaced = 'Total number of records ==> '+totalSizeRecords
                +'<Br/>Number of batch completed ==> '+successCounter
                +'<Br/>Number of batch failed ==> '+failureCounter;
            
            string emailHeader='';
            
            if(failureCounter==0)
            {
                emailHeader='Batch Job Succeeded';
            } 
            else 
            {
                emailHeader='Batch Job Failed'; 
                emailBodytoReplaced += '<Br/><Br/> Fix the record and re-run the batch by using below command <Br/> <p style="color:blue">Credit_Detail_Clean batch = new Credit_Detail_Clean(False);<Br/>database.executebatch(batch, 200);</p>';
                integer n=1;
                for(Exception e : errorslist) 
                {  
                    emailBodytoReplaced += n+'.'+' '+'Exception Occured:' + e.getMessage() + '<Br/>' + e.getStackTraceString()+'<Br/>';
                    n++;
                    
                }
            }
            
            string emailSubject = emailHeader+' For Credit Detail Cleanup';
            string emailSubHeader = emailHeader+' For Credit Detail Cleanup';
            EmailTemplate template = [Select id, Body, HtmlValue, Subject from EmailTemplate where name = 'NCR Standard'];
            String EmailBody=template.HtmlValue;
            
            CommonUtility.sendEmail(emailSubject,emailHeader,emailSubHeader,emailBodytoReplaced,EmailBody,(Label.BatchClassEmailNotification).split(',')); 
        }
    }
}