force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_Industry_Name__c.field-meta.xml
<CustomField>
    <fullName>MDM_Industry_Name__c</fullName>
    <label>Industry Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NPS__c.field-meta.xml
<CustomField>
    <fullName>NPS__c</fullName>
    <label>Current Year NPS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Result__c/Survey_Result__c.object-meta.xml
<CustomObject>
    <label>Survey Result</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Result__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Results</relationshipLabel>
    <relationshipName>Survey_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Result__c/fields/NPS__c.field-meta.xml
<CustomField>
    <fullName>NPS__c</fullName>
    <formula>CASE(NPS_Score__c, 10,&apos;Promoter&apos;,9,&apos;Promoter&apos;,8,&apos;Passive&apos;,7,&apos;Passive&apos;,6,&apos;Detractor&apos;,5,&apos;Detractor&apos;,4,&apos;Detractor&apos;,3,&apos;Detractor&apos;,2,&apos;Detractor&apos;,1,&apos;Detractor&apos;,0,&apos;Detractor&apos;,&apos;&apos;)</formula>
    <label>NPS Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Result__c/fields/NPS_Score__c.field-meta.xml
<CustomField>
    <fullName>NPS_Score__c</fullName>
    <label>Likely to Recommend</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Result__c/fields/Qualtrics_Response_ID__c.field-meta.xml
<CustomField>
    <fullName>Qualtrics_Response_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Qualtrics Response ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Survey_Result__c/fields/Respondent_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Respondent_End_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Respondent End Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/NPSScoreCalcTest.cls
@isTest
public class NPSScoreCalcTest {
	@isTest
    public static void accList(){
        Account ac=new Account();
        User Usr = [Select Id from User Where Name = 'Soup User'];
        System.runAs(Usr){
        ac.Name='TestNPS';
        ac.Account_Country_Code__c='A2';
        ac.MDM_Industry_Name__c='FINANACIAL:BANKING';
        insert ac;
    		} 
        Contact con = TestRecordsFactory.createContact( ac );
       	List <Survey_Result__c> npscoreList = new List<Survey_Result__c>();
        String NPS_Year  = String.valueOf(System.Today().year());
        Survey_Result__c npl = new Survey_Result__c();
        npl.Name = NPS_Year+' Testing';
        npl.NPS_Score__c = 9;
        npl.Respondent_End_Date__c= System.today();
        npl.Contact__c = con.Id;
        npl.Qualtrics_Response_ID__c = '12345';
        npscoreList.add(npl);
        insert npscoreList;
        Account accObj = [select id,NPS__c from account where id=:ac.id];
        System.assert(accObj.NPS__c==100);
    }
}