force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Available_Credit__c.field-meta.xml
<CustomField>
    <fullName>Available_Credit__c</fullName>
    <label>Available Credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <inlineHelpText>Current credit limit from EDW.  Limits of less than $1000 are not updated here.</inlineHelpText>
    <label>Credit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Values_As_Of__c.field-meta.xml
<CustomField>
    <fullName>Credit_Values_As_Of__c</fullName>
    <inlineHelpText>Date of last Credit Limit update to EDW.</inlineHelpText>
    <label>Credit Values As Of:</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <description>CATM</description>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account UID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/Credit_Detail__c.object-meta.xml
<CustomObject>
    <description>This object stores the Credit data information. The Data is coming from EDW via iPaaS.</description>
    <label>AR Detail</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Credit Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Credit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Customer_Balance__c.field-meta.xml
<CustomField>
    <fullName>Customer_Balance__c</fullName>
    <label>Customer Balance</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Not_Due_1_360_Days__c.field-meta.xml
<CustomField>
    <fullName>Not_Due_1_360_Days__c</fullName>
    <label>Not Due 1-360 Days</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Not_Due_360_Days__c.field-meta.xml
<CustomField>
    <fullName>Not_Due_360_Days__c</fullName>
    <label>Not Due 360+ Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <label>On Hold</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Risk_Level__c</fullName>
    <label>Risk Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X181_360_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X181_360_Days_Late__c</fullName>
    <label>Aging – 181-360</label>
    <precision>16</precision>
    <scale>2</scale>
    <trackHistory>false</trueHistory>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X1_30_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X1_30_Days_Late__c</fullName>
    <label>Aging &lt; 31</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X31_60_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X31_60_Days_Late__c</fullName>
    <label>Aging – 31-60</label>
    <precision>16</precision>
    <scale>2</scale>
    <trackHistory>false</trueHistory>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X361_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X361_Days_Late__c</fullName>
    <label>Aging &gt; 360</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X61_90_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X61_90_Days_Late__c</fullName>
    <label>Aging – 61-90</label>
    <precision>16</precision>
    <scale>2</scale>
    <trackHistory>false</trueHistory>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/X91_180_Days_Late__c.field-meta.xml
<CustomField>
    <fullName>X91_180_Days_Late__c</fullName>
    <label>Aging – 91-180</label>
    <precision>16</precision>
    <scale>2</scale>
    <trackHistory>false</trueHistory>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Controller_CreditDetails_ltng.cls
public class Controller_CreditDetails_ltng {
    
    @AuraEnabled
    public static Credit_Detail__c Loadcompletedetail(id ID)
    {
       system.debug('######## inside controller controller_creditdetails_ltng------received account id is ::'+ID);
        return [Select Account__c,
       // Average_Days_Late__c,
        Customer_Balance__c,
        Id,Name,
        Not_Due_1_360_Days__c,
        Not_Due_360_Days__c,
        On_Hold__c,
        Risk_Level__c,
        Unique_ID__c,
        X1_30_Days_Late__c,
        X31_60_Days_Late__c,
        X61_90_Days_Late__c,
        X91_180_Days_Late__c,
        X181_360_Days_Late__c,
        X361_Days_Late__c,
                Account__r.Credit_Limit__c,
                Account__r.Credit_Values_As_Of__c,
                Account__r.Available_Credit__c
               // Account__r.AR_issues__c
               // commenting duE to EA_SF-688
                From Credit_Detail__c
                WHERE Account__c = :ID
                limit 1];
    }
    
    
}