force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Use to maintain a master list of certifications</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Curriculum_Number__c.field-meta.xml
<CustomField>
    <fullName>Curriculum_Number__c</fullName>
    <description>NCR University certification course code number</description>
    <externalId>true</externalId>
    <inlineHelpText>NCR University certification course code number</inlineHelpText>
    <label>Curriculum Number</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NCRUPartnerCertificationsTest.cls
@isTest
private class NCRUPartnerCertificationsTest 
{
    static testMethod void testNCRUPartnerCertifications() 
    {
        Account acc=new Account(Name='Acme Inc');
        system.runAs(TestRecordsFactory.getUser()){
             insert acc;
        }
       
        
        Certification__c objCert = new Certification__c();
        objCert.Name = 'Test Contact';
        objCert.Curriculum_Number__c = '12345';
        objCert.Account__c = acc.Id;
        insert objCert;
        
        NCRUPartnerCertifications controller = new NCRUPartnerCertifications(new ApexPages.StandardController(acc));
        
        List<Certification__c> certificateList= NCRUPartnerCertifications.getNCRUPartnerCertifications(acc.Id);
        System.assert(certificateList.size()==0);
    }
}