force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>EG</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOB__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>CLA BRAZIL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>EUROPE EXC RUSSIA</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDIA &amp; SEA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
            <value>
                <fullName>NAMER CFI</fullName>
            </value>
            <value>
                <fullName>NAMER DIRECT</fullName>
            </value>
            <value>
                <fullName>NAMER MAJORS</fullName>
            </value>
            <value>
                <fullName>NAMER SMB</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA AND SPA</fullName>
            </value>
            <value>
                <fullName>SAPAC</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RoR_Update_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>RoR_Update_Date_Time__c</fullName>
    <description>Date which the RoR interface last updated this record</description>
    <label>RoR Update Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/All_profie_config__c/All_profie_config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>All profile config</label>
</CustomObject>

force-app/main/default/objects/All_profie_config__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <label>Profile Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/All_profie_config__c/fields/Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Profile_Name__c</fullName>
    <label>Profile Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country Code of the customer that is assigned to the invoices on a dispute.</description>
    <label>Country Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_Analyst_Email__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Analyst_Email__c</fullName>
    <description>The email of the dispute analyst assigned to the dispute.</description>
    <inlineHelpText>The email of the dispute analyst assigned to the dispute.</inlineHelpText>
    <label>Dispute Analyst Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_Created_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Created_By_Name__c</fullName>
    <label>Dispute Created By Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_CreatedBy_Qlook__c.field-meta.xml
<CustomField>
    <fullName>Dispute_CreatedBy_Qlook__c</fullName>
    <label>Dispute CreatedBy Qlook</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_UpdatedBy_Qlook__c.field-meta.xml
<CustomField>
    <fullName>Dispute_UpdatedBy_Qlook__c</fullName>
    <label>Dispute UpdatedBy Qlook</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Master_Customer_Nbr__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Nbr__c</fullName>
    <label>Master Customer Nbr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <formula>Account.Master_Customer_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Master Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Dispute.recordType-meta.xml
<RecordType>
    <fullName>Dispute</fullName>
    <active>true</active>
    <businessProcess>CADD Dispute Case</businessProcess>
    <description>This type is used for creating cases against Invoices that are in Dispute by the customer</description>
    <label>Dispute</label>
</RecordType>

force-app/main/default/objects/Dispute_Invoices__c/Dispute_Invoices__c.object-meta.xml
<CustomObject>
    <label>Dispute Invoices</label>
    <nameField>
        <label>Dispute Invoices Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispute_Invoices__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country Code of the Invoice</description>
    <label>Country Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispute_Invoices__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <description>Currency code of the invoice</description>
    <label>Currency Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SetDisputeStatusCode__c/SetDisputeStatusCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map Dispute Status to its Code</description>
    <label>Set Dispute Status Code</label>
</CustomObject>

force-app/main/default/objects/SetDisputeStatusCode__c/fields/caseStatus__c.field-meta.xml
<CustomField>
    <fullName>caseStatus__c</fullName>
    <description>Contains Dispute Status</description>
    <label>caseStatus</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SetDisputeStatusCode__c/fields/caseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>caseStatusCode__c</fullName>
    <description>Contains Dispute Status Code</description>
    <label>caseStatusCode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DisputeSyncServiceTest.cls
@isTest
private class DisputeSyncServiceTest {
    
    static testMethod void syncDisputeTest() {        
        SOUP_Endpoint__c se = new SOUP_Endpoint__c(name='CCAD Invoice Rest', Username__c='test', Password__c = 'test', Endpoint_URL__c= 'test.ncr.com');
        insert se;
        
        All_profie_config__c obj = new All_profie_config__c();
        obj.Profile_Id__c ='Test';
        obj.Profile_Name__c ='CCAD Service Ignored Profile';
        obj.Name='CCAD Service Ignored Profile';
        insert obj;
        
        SetDisputeStatusCode__c disputeStaus = new SetDisputeStatusCode__c(Name='New',caseStatus__c='New' , caseStatusCode__c = 10);
        insert disputeStaus;
        
        Account acc = TestRecordsFactory.createAccount();
        System.assertEquals(acc.Name, 'Test Acc','Account Name is null');
        //RecordType r =[Select id from recordtype where developername ='Partner']; 
        Id r = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
        System.assertNotEquals(r, null,'RecordType is null');
        System.runAs(TestRecordsFactory.getUser()) {
            Account apocAcc = new Account(      
                Account_Country_Code__c = 'EG',
                Active_Account__c = true,        
                Master_Customer_Number__c = 'APOC1111',
                Name = 'Unit Test ' + System.now(),
                RecordTypeId = r,//'0127000000014kqAAA',
                RoR_Update_Date_Time__c = System.now(),
                Industry = 'RETAIL:CHANNEL',
                account_region__c='INDIA'
            );
            
            insert apocAcc;
        }

        DisputeSyncService.ContactDetail custContact = new DisputeSyncService.ContactDetail();
        custContact.Name = 'Test Contact';
        custContact.Email = 'test@gmail.com';
        custContact.Phone = '121313132424';
        
        DisputeSyncService.ContactDetail altContact = new DisputeSyncService.ContactDetail();
        altContact.Name = 'Test Contact';
        altContact.Email = 'test@ncr.com';
        altContact.Phone = '121313132424';
        
        
        DisputeSyncService.AttachmentDetail attDetail = new DisputeSyncService.AttachmentDetail();
        attDetail.Attachment_FULL_URL = 'test@ncr.com'; 
        attDetail.Attachment_Description = 'test';
        attDetail.Attachment_Source = DisputeSyncService.SourceSystem.CCAD;

               
        DisputeSyncService.DisputeAttachment dispAttach = new DisputeSyncService.DisputeAttachment();
        dispAttach.Attachment = new List<DisputeSyncService.AttachmentDetail>{attDetail};
            
        DisputeSyncService.InvoiceDetail invDetail = new DisputeSyncService.InvoiceDetail();
        invDetail.Invoice_Id = 'INV1234';
        invDetail.Invoice_Amount = '100';
        
        DisputeSyncService.InvoiceData invData = new DisputeSyncService.InvoiceData();
        invData.Invoicedetail = new List<DisputeSyncService.InvoiceDetail>{invDetail};
       
        
        DisputeSyncService.DisputeDetail disputeDetail = new DisputeSyncService.DisputeDetail();
        disputeDetail.CustomerName = acc.Name;
        disputeDetail.MasterCustomerNumber = acc.Master_Customer_Number__c;
        disputeDetail.CountryCode = acc.Account_Country_Code__c;
        disputeDetail.CustomerContact = custContact;
        disputeDetail.AlternateContact =  altContact;
        disputeDetail.DisputeAnalyst_QLId = 'ma185260';     
        disputeDetail.CCADDisputeNbr = '12345';
        disputeDetail.ERPDisputeNbr = '12345';
        disputeDetail.ReasonCode = '374';  
        disputeDetail.Description = 'Test Description';
        disputeDetail.Escalated = false;
        disputeDetail.Status = '10';
        disputeDetail.CreateByUser_QLId = 'test1234'; 
        disputeDetail.UpdatedByUser_QLId = 'test1234'; 
        disputeDetail.DisputedAmount = 100;
        disputeDetail.CurrencyCode = 'USD';
        disputeDetail.CreditAmount = 100;
        disputeDetail.RebillAmount = 100;
        disputeDetail.DisputeSource = DisputeSyncService.SourceSystem.CCAD;
        disputeDetail.CaseComments = 'test';
        disputeDetail.isPublicComment  = false;
        disputeDetail.AttachmentList = dispAttach;
        disputeDetail.InvoiceList = invData;  
        Test.setMock(HttpCalloutMock.class, new UserInvoiceAuthanticationCCADMockCallOut());     
        System.assertNotEquals(disputeDetail, null,'disputeDetail is null');
       Test.startTest();
        DisputeSyncService.SyncDispute(disputeDetail);
        DisputeSyncService.SyncDispute(disputeDetail);
       Test.stopTest();
    }
    
    
     static testMethod void runTest() {    
        SOUP_Endpoint__c se = new SOUP_Endpoint__c(name='CCAD Invoice Rest', Username__c='test', Password__c = 'test', Endpoint_URL__c= 'test.ncr.com');
        insert se;
    	Id DisputeRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Dispute').getRecordTypeId();  
        System.assertNotEquals(DisputeRecordTypeId, null,'Dispute RecordTypeId is null'); 
        All_profie_config__c obj = new All_profie_config__c();
         obj.Profile_Id__c ='Test';
         obj.Profile_Name__c ='CCAD Service Ignored Profile';
         obj.Name='CCAD Service Ignored Profile';
         insert obj;
         SetDisputeStatusCode__c disputeStaus = new SetDisputeStatusCode__c(Name='New',caseStatus__c='New' , caseStatusCode__c = 10);
        insert disputeStaus;
        Case caseObj = new Case();
        caseObj.RecordTypeId = DisputeRecordTypeId;
        caseObj.Master_Customer_Nbr__c='12345';
        caseObj.Country_Code__c='IT';
        caseObj.Currency_Code__c='USD'; 
        caseObj.Dispute_UpdatedBy_Qlook__c='12345';
        caseObj.Dispute_CreatedBy_Qlook__c='54321';  
        caseObj.Dispute_Analyst_Email__c='test@test.com';     
        caseObj.Status='New';
        caseObj.Dispute_Created_By_Name__c='Test';
        caseObj.Dispute_Analyst_Name__c='testing';
        insert caseObj;
         
        Dispute_Invoices__c invOvj= new Dispute_Invoices__c();
        invOvj.Invoice_Number__c= '201820662';
        invOvj.Total_Invoice_Amount__c=1234567;
        invOvj.Customer_Trx_ID__c=1378389;
        invOvj.Dispute__c=caseObj.id;
        insert invOvj;
       
         
        Test.startTest(); 
        Test.setMock(HttpCalloutMock.class, new UserInvoiceAuthanticationCCADMockCallOut()); 
        DisputeUtil.getInvoiceDetailInFuture(caseObj.Id, caseObj.Country_Code__c);
        Test.stopTest();
        
         CCADDLogsUtility.insertCCADDLogs('Test', 'Test', 'Test', '1223455', '32324324322222225454566634', 'test');

     }
    
   
    
}