force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOB__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>CLA BRAZIL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>EUROPE EXC RUSSIA</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDIA &amp; SEA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
            <value>
                <fullName>NAMER CFI</fullName>
            </value>
            <value>
                <fullName>NAMER DIRECT</fullName>
            </value>
            <value>
                <fullName>NAMER MAJORS</fullName>
            </value>
            <value>
                <fullName>NAMER SMB</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA AND SPA</fullName>
            </value>
            <value>
                <fullName>SAPAC</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Counterpoint__c.field-meta.xml
<CustomField>
    <fullName>Counterpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Counterpoint fields indicates partner deals in Retail-Counterpoint.</description>
    <label>Counterpoint</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Industry__c.field-meta.xml
<CustomField>
    <fullName>Partner_Industry__c</fullName>
    <description>Industry or Industries focued on by this partner.</description>
    <label>Partner Supported Industries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Program_Industry__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Industry__c</fullName>
    <label>Partner Program Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
            <value>
                <fullName>TRAVEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Level__c</fullName>
    <inlineHelpText>NCR Interact program level that defines the requirements and benefits of a partner.</inlineHelpText>
    <label>Partner Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>No Program Level</fullName>
                <default>true</default>
                <label>No Program Level</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <label>Deal Registration</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <formula>Partner_Company_Name__r.Master_Customer_Number__c</formula>
    <label>Master Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Partner&apos;s account name.</description>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations (Partner Company Name)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CROSS LOB</fullName>
            </value>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
            <value>
                <fullName>TRAVEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateDealStatusPartnerTerminatedTest.cls
@isTest
public class UpdateDealStatusPartnerTerminatedTest {
    @isTest
    public static void UpdateDealStatusPartnerTerminatedTest(){
        User partnerUser = [Select Id from User WHERE Name = 'Soup User'];
        System.runAs(partnerUser){
            RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'Partner' AND SobjectType = 'Account' LIMIT 1];
            //Insert Account
            Account accountRecord = PRM_TestRecordsFactory.createPartnerAccount('Test',null);
            accountRecord.Active_Account__c = true;
            insert accountRecord;
            Contact testcontact = new Contact(LastName='TEST', Email = 'testrecord234@test.com');
            insert testcontact;
            //Insert Deal Registration
            Deal_Registration__c dr = new Deal_Registration__c();
            dr.Partner_Company_Name__c =   accountRecord.Id;
                      
                insert dr;
                account ACC = new account();
                for(account accTest : [SELECT ID, Active_Account__c FROM account WHERE ID = : accountRecord.Id]){
                    ACC.Id = accTest.Id;
                    ACC.Active_Account__c = false;
                }
                update ACC;
            system.assertNotEquals(ACC,null);
            system.assertEquals(ACC.Active_Account__c , false);
        }
        
    }
    @isTest
    public static void UpdateDealStatusPartnerTerminatedTest1(){
        User partnerUser = [Select Id from User WHERE Name = 'Soup User'];
        System.runAs(partnerUser){
            Id r = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
            //RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName='Partner'];
            //Insert Account
            //Account accountRecord = PRM_TestRecordsFactory.createPartnerAccount('Test',null);
            
            Account objAccount = new Account();
        objAccount.Name = 'Partner Test Account';
        objAccount.Account_Country_Code__c = 'US';
        objAccount.Active_Account__c = true;
        objAccount.CurrencyIsoCode = 'USD';
        objAccount.Industry = 'RETAIL:CHANNEL';
        objAccount.Account_Region__c = 'EMEA';
        objAccount.Master_Customer_Number__c = '9166344';
        objAccount.Partner_Industry__c = 'Financial;Retail';
        objAccount.LOB__c = 'FINANCIAL';
        objAccount.Account_Region__c = 'CLA';
        objAccount.Partner_Program_Industry__c = 'Retail';
        objAccount.Partner_Program_Level__c = 'Silver';
        objAccount.Counterpoint__c = true;
            objAccount.RecordTypeId = r;
            objAccount.Active_Account__c = true;
            insert objAccount;
            Contact testcontact = new Contact(LastName='TEST', Email = 'testrecord234@test.com');
            insert testcontact;
            //Insert Deal Registration
            Deal_Registration__c dr = new Deal_Registration__c();
            dr.Partner_Company_Name__c =   objAccount.Id;
                      
            insert dr;
            account accTest = [SELECT ID, Active_Account__c FROM account WHERE ID = : objAccount.Id];
            account ACC = new account();
            ACC.Id = accTest.Id;
            ACC.Active_Account__c = false;
            update ACC;
            system.assertNotEquals(ACC,null);
            system.assertEquals(ACC.Active_Account__c , false);
        }
        
    }
}