force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/Account_Entitlements__c.object-meta.xml
<CustomObject>
    <label>Account Entitlements</label>
    <nameField>
        <label>Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Entitlements__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Active_Count__c.field-meta.xml
<CustomField>
    <fullName>Active_Count__c</fullName>
    <label>Active Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Expired_Count__c.field-meta.xml
<CustomField>
    <fullName>Expired_Count__c</fullName>
    <label>Expired Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Expired_Warranty_Count__c.field-meta.xml
<CustomField>
    <fullName>Expired_Warranty_Count__c</fullName>
    <label>Expired Warranty Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Hold_Count__c.field-meta.xml
<CustomField>
    <fullName>Hold_Count__c</fullName>
    <label>Hold Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Primary_Product_Desc__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Desc__c</fullName>
    <label>Primary Product Desc</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <label>Product Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Unique Key = Master Customer Number + Product Id</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/EntitlementSectionHierarchy.cls
public with sharing class EntitlementSectionHierarchy {

    @AuraEnabled(cacheable =true)
    public static WrapEntitlementWithTotal2 getAccountEntitlementList( String accountRecordID  ){
        Set<Id> allAccountIds = findChildAccountIds(new Set<Id>{accountRecordID});
        System.debug('accountRecordID>>' + accountRecordID);
        List<Account_Entitlements__c> accountEntitlementsList = new List<Account_Entitlements__c>(); 
        Set <String> prodDesc=new Set<String>();
        if(accountRecordID != null){
            accountEntitlementsList = [SELECT Id, Account__r.RecordType.Name, Hold_Count__c, Expired_Warranty_Count__c, Expired_Count__c, Active_Count__c, Account__c, Primary_Product_Desc__c, Master_Customer_Number__c, Product_Id__c, Unique_Key__c, Name FROM Account_Entitlements__c where Account__c IN :allAccountIds];
        }
        List<Account_Entitlements__c> oh=new List<Account_Entitlements__c>();

        Decimal totalHoldCount = 0;
        Decimal totalActiveCount = 0;
        Decimal totalExpCount = 0;
        Decimal totalExpWarCount = 0;
        System.debug('accountEntitlementsList : '+accountEntitlementsList);

        for(Account_Entitlements__c gh: accountEntitlementsList){
            System.debug('@@@' + gh);
            WrapEntitlementWithTotal wrapObj = new WrapEntitlementWithTotal();
            if(prodDesc.contains(gh.Primary_Product_Desc__c))  {
                for(Account_Entitlements__c ohh:oh){
                    if(ohh.Primary_Product_Desc__c==gh.Primary_Product_Desc__c){
                    if(gh.Hold_Count__c!=null)
                        ohh.Hold_Count__c= (ohh.Hold_Count__c != null ? ohh.Hold_Count__c : 0) +gh.Hold_Count__c; 
                    if(gh.Expired_Warranty_Count__c!=null)
                        ohh.Expired_Warranty_Count__c= (ohh.Expired_Warranty_Count__c != null ? ohh.Expired_Warranty_Count__c : 0) + gh.Expired_Warranty_Count__c;
                    if(gh.Active_Count__c!=null)
                        ohh.Active_Count__c= (ohh.Active_Count__c != null ? ohh.Active_Count__c : 0) + gh.Active_Count__c;
                    if(gh.Expired_Count__c!=null)
                        ohh.Expired_Count__c= (ohh.Expired_Count__c != null ? ohh.Expired_Count__c : 0) + gh.Expired_Count__c;
                    }
                }
                totalActiveCount += (gh.Active_Count__c != null ? gh.Active_Count__c : 0);
                totalHoldCount += (gh.Hold_Count__c != null ?  gh.Hold_Count__c : 0);
                totalExpCount += (gh.Expired_Count__c != null ? gh.Expired_Count__c : 0);
                totalExpWarCount += (gh.Expired_Warranty_Count__c != null ? gh.Expired_Warranty_Count__c : 0);

            }else{
                wrapObj.prodDes = gh.Primary_Product_Desc__c;
                wrapObj.activeCount = gh.Active_Count__c;                
                totalActiveCount += (gh.Active_Count__c != null ? gh.Active_Count__c : 0);
                wrapObj.holdCount = gh.Hold_Count__c;
                totalHoldCount += (gh.Hold_Count__c != null ?  gh.Hold_Count__c : 0);
                wrapObj.expCount = gh.Expired_Count__c;
                totalExpCount += (gh.Expired_Count__c != null ? gh.Expired_Count__c : 0);
                wrapObj.ExpWarCount = gh.Expired_Warranty_Count__c;
                totalExpWarCount += (gh.Expired_Warranty_Count__c != null ? gh.Expired_Warranty_Count__c : 0);
                System.debug('gh : '+gh);
                oh.add(gh);
                prodDesc.add(gh.Primary_Product_Desc__c);
            }        
        }
        WrapEntitlementWithTotal2 wrapClassObj = new WrapEntitlementWithTotal2();
        WrapEntitlementWithTotal wrapObjLast = new WrapEntitlementWithTotal();
        wrapObjLast.prodDes = 'Total';
        wrapObjLast.activeCount = totalActiveCount;
        wrapObjLast.holdCount = totalHoldCount;
        wrapObjLast.expCount = totalExpCount;
        wrapObjLast.ExpWarCount = totalExpWarCount;
        wrapClassObj.wrap = wrapObjLast;
        wrapClassObj.entitlementList = oh;
    
        return wrapClassObj;
    }
    
    public static Set<Id> findChildAccountIds(Set<Id> parentAccIds) {
        Set<Id> outputAccIds = new Set<Id>();
        outputAccIds.addAll(parentAccIds);

        Map<Id, Account> accountMap = new  Map<Id, Account>([SELECT Id, Name, ParentId FROM Account where ParentId IN :parentAccIds]);

        if(!accountMap.isEmpty()) {
            Set<Id> childAcctIds = findChildAccountIds(accountMap.keySet());

            if (childAcctIds != null && !childAcctIds.isEmpty()) {
                outputAccIds.addAll(childAcctIds);
            }
        }
        return outputAccIds;
    }


    public class WrapEntitlementWithTotal{
        @AuraEnabled
        public String prodDes;
        @AuraEnabled
        public Decimal activeCount;
        @AuraEnabled
        public Decimal holdCount;
        @AuraEnabled
        public Decimal expCount;
        @AuraEnabled
        public Decimal ExpWarCount;
    }
    public class WrapEntitlementWithTotal2{
        @AuraEnabled
        public WrapEntitlementWithTotal wrap;
        @AuraEnabled
        public List<Account_Entitlements__c> entitlementList;
    }
}