force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CDM_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>CDM_Account_Status__c</fullName>
    <label>NCR Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_Data_Source_Code__c.field-meta.xml
<CustomField>
    <fullName>MDM_Data_Source_Code__c</fullName>
    <inlineHelpText>Data Source Code indicates the source application. NCR Sales Central (NSC) often carries the Data Source Code of ‘APOL’ which stands for ‘Apollo’ which was a predecessor application to NSC within NCR.</inlineHelpText>
    <label>Data Source Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_Coordinator_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Coordinator_Email__c</fullName>
    <description>Note: This field was requested to be removed from the layout by Jane green
Jan12: Kayla Hittig requested the field to be added back to the layout</description>
    <label>Project Coordinator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Invoice_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Trigger__c</fullName>
    <label>Invoice Trigger</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Primary_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Competitor</label>
    <referenceTo>Competitors__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EndCustomerUnknown__c.field-meta.xml
<CustomField>
    <fullName>EndCustomerUnknown__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, End_Customer__c will not be mandatory. I unchecked, End_Customer__c is mandatory.</description>
    <inlineHelpText>Please select, if the End Customer is not known Or Please update End Customer below</inlineHelpText>
    <label>End Customer Unknown</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery_Date__c</fullName>
    <label>Expected Delivery Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Trigger__c</fullName>
    <label>Invoice Trigger</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Key_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Key_Criteria__c</fullName>
    <label>Key Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Business Benefits</fullName>
            </value>
            <value>
                <fullName>Lead Time</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Pre-Contact Termination</fullName>
            </value>
            <value>
                <fullName>Post-Contact Termination</fullName>
            </value>
            <value>
                <fullName>HW</fullName>
            </value>
            <value>
                <fullName>SW</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
                <label>Service</label>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the primary competitor with NCR for this opportunity</inlineHelpText>
    <label>Primary Competitor</label>
    <referenceTo>Competitors__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organization this opportunity is related to</description>
    <inlineHelpText>To find an org code search by your first or last name</inlineHelpText>
    <label>Sales Team Organization</label>
    <referenceTo>Sales_Org__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Skip_Validation_Rule_for_Lead_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Skip_Validation_Rule_for_Lead_Conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Validation Rule for Lead Conversion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Deliver_To_Site__c.field-meta.xml
<CustomField>
    <fullName>Deliver_To_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Twinned from Quote</description>
    <label>Deliver To Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Deliver To Site)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/qtc_Bill_To_Site__c.field-meta.xml
<CustomField>
    <fullName>qtc_Bill_To_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Twinned from quote</description>
    <label>Bill To Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Bill To Site)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topline</fullName>
                <default>true</default>
                <label>Topline</label>
            </value>
            <value>
                <fullName>Zuora Product</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>SID</fullName>
            </value>
            <value>
                <fullName>PID</fullName>
            </value>
            <value>
                <fullName>Sub-Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/qtcOrderActivation__e/qtcOrderActivation__e.object-meta.xml
<CustomObject>
    <description>Platform event to activate an order via batch automation</description>
    <label>Order Activation</label>
    <pluralLabel>Order Activations</pluralLabel>
</CustomObject>

force-app/main/default/objects/qtcOrderActivation__e/fields/qtcOrderId__c.field-meta.xml
<CustomField>
    <fullName>qtcOrderId__c</fullName>
    <description>Holds the Order Id of the Order record</description>
    <label>Order Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/qtcOrderActivation__e/fields/qtcRetryAttempt__c.field-meta.xml
<CustomField>
    <fullName>qtcRetryAttempt__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Count of the number of retry attempts</description>
    <label>Retry Attempt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <description>Contains all of the applicable NCR sales organizations</description>
    <label>Sales Org</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderActivationEventTriggerHandlerTest.cls
@isTest
public with sharing class OrderActivationEventTriggerHandlerTest {
    static String   STATUS_DRAFT = 'Draft',
                    SETUP_MASTER_CUSTOMER_NUMBER = 'SETUPMASTERCONTRACT',
                    EXPECTED_MASTER_CUSTOMER_NUMBER='EXPECTEDMASTERNUMBER';
    static Date     START_DATE = Date.today(),
                    END_DATE = START_DATE.addDays(25);
    static Integer BULK_COUNT = LIMITS.getLimitQueries()+1;

    
    @TestSetup
    static void setupData(){
       
        
        Account thisAccount = new Account(name = 'ContractTestAccount',
                        LOB__c = 'FINANCIAL',
                        // MDM_Data_Source_Code__c='SF',
                        Master_Customer_Number__c = SETUP_MASTER_CUSTOMER_NUMBER,
                        Account_Country_Code__c = 'US', CurrencyIsoCode = 'USD',
                        Active_Account__c = true,
                        Project_Coordinator_Email__c = 'abc@test.com',
                         CDM_Account_Status__c = 'Active'
                                         );
        System.runAs(TestRecordsFactory.getUser()){
            insert thisAccount;
        }
        
        Opportunity thisOpportunity = new Opportunity();
        thisOpportunity.name = 'abc';
        thisOpportunity.AccountID = thisAccount.id;
        thisOpportunity.Name = 'OppQuote Linkage Test Opportunity';
        thisOpportunity.type = 'Indirect Channel';
        thisOpportunity.CURRENCYISOCODE = 'USD';
        //thisOpportunity.SALES_ORG__C = s.id;
        thisOpportunity.INVOICE_TRIGGER__C = 'Shipment';
        //thisOpportunity.PRIMARY_COMPETITOR__C = c.id;
        thisOpportunity.Expected_Delivery_Date__c = System.TODAY().addDays(30);
        thisOpportunity.closeDate = System.TODAY();
        thisOpportunity.stagename = 'Prospecting';
       // thisOpportunity.recordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByDeveloperName().get();
        thisOpportunity.Key_Criteria__c='Best Solution;Business Benefits;Lead Time;Performance;Price';
        thisOpportunity.EndCustomerUnknown__c = true; 
        thisOpportunity.Skip_Validation_Rule_for_Lead_Conversion__c = true;
        thisOpportunity.ForecastCategoryName ='Omitted';
        insert thisOpportunity;
        
        SBQQ__Quote__c thisQuote = new SBQQ__Quote__c(
            SBQQ__Account__c = thisAccount.Id,
            SBQQ__Opportunity2__c = thisOpportunity.Id,
            SBQQ__Primary__c = true
        );
        insert thisQuote;
        blng__BillingRule__c billingRule = new blng__BillingRule__c(
            Name = 'Test Billing Rule',
            blng__Active__c = true,
            blng__GenerateInvoices__c = 'No',
            blng__InitialBillingTrigger__c = 'Order Product Activation Date',
            blng__PartialPeriodTreatment__c = 'Separate'
        );
        insert billingRule;

        blng__TaxRule__c taxrule = new blng__TaxRule__c(
            Name = 'Test Rule',
            blng__TaxableYesNo__c = 'Yes',
            blng__Active__c = TRUE);
        insert taxrule;

        blng__RevenueRecognitionRule__c revenueRecognizationRule = new blng__RevenueRecognitionRule__c(
            Name = 'Test Schedule',
            blng__CreateRevenueSchedule__c = 'Yes',
            blng__Active__c = true
        );
        insert revenueRecognizationRule;
        
        List<Product2> lstProducts = new List<Product2>();
        lstProducts.add(new product2(   name='A', 
                                        family='Hardware',
                                        blng__BillingRule__c = billingRule.Id, 
                                        blng__RevenueRecognitionRule__c = revenueRecognizationRule.Id, 
                                        blng__TaxRule__c = taxrule.ID,
                                        ProductCode = 'H400-0001-0000', 
                                        product_type__c = 'Topline'));
        lstProducts.add(new product2(   name='B', 
                                        family='Hardware',
                                        blng__BillingRule__c = billingRule.Id, 
                                        blng__RevenueRecognitionRule__c = revenueRecognizationRule.Id, 
                                        blng__TaxRule__c = taxrule.ID,
                                        ProductCode = 'H400-0001-0000',
                                        product_type__c = 'Topline' ));
        lstProducts.add(new product2(   name='C', 
                                        family='Hardware',
                                        blng__BillingRule__c = billingRule.Id, 
                                        blng__RevenueRecognitionRule__c = revenueRecognizationRule.Id, 
                                        blng__TaxRule__c = taxrule.ID,
                                        ProductCode = 'H400-0001-0000', 
                                        product_type__c = 'Topline'));
        lstProducts.add(new product2(   name='D', 
                                        family='Hardware',
                                        blng__BillingRule__c = billingRule.Id, 
                                        blng__RevenueRecognitionRule__c = revenueRecognizationRule.Id, 
                                        blng__TaxRule__c = taxrule.ID,
                                        ProductCode = 'H400-0001-0000'));
        insert lstProducts;
        
        Id stdPbId = Test.getStandardPricebookId();        
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = stdPbId, Product2Id = lstProducts[0].id, UnitPrice = 100, IsActive = true);
        insert standardPrice;
        
        Order thisOrder = new order(    Pricebook2Id = stdPbId, 
                                        AccountId = thisAccount.id, 
                                        Status = STATUS_DRAFT, 
                                        EffectiveDate = Date.Today(), 
                                        blng__BillingDayOfMonth__c = '28',
                                        qtc_Bill_To_Site__c = thisAccount.Id,
                                        Deliver_To_Site__c = thisAccount.Id,
                                        SBQQ__Quote__c = thisQuote.Id);
        insert thisOrder;
        
        OrderItem thisOrderProduct = new OrderItem(     PriceBookEntryId = standardPrice.Id, 
                                                        OrderId = thisOrder.Id, 
                                                        Quantity = 1, 
                                                        SBQQ__OrderedQuantity__c = 1, 
                                                        UnitPrice = standardPrice.UnitPrice, 
                                                        SBQQ__ChargeType__c = 'One-Time',
                                                        ServiceDate = Date.Today());
        insert thisOrderProduct;
    }

    @isTest
    static void triggerHandler_PriceCalcCompleted_PositiveTest(){
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        testOrder.SBQQ__PriceCalcStatus__c = 'Completed';
        SBQQ.TriggerControl.disable();
        update testOrder;
        SBQQ.TriggerControl.enable();
        List<qtcOrderActivation__e> listEvents = new List<qtcOrderActivation__e>();
        qtcOrderActivation__e event = new qtcOrderActivation__e(
            qtcOrderId__c = testOrder.Id
        );
        listEvents.add( event );

        Test.startTest();
            SBQQ.TriggerControl.disable();
            OrderActivationEventTriggerHandler triggerHandler = new OrderActivationEventTriggerHandler( listEvents, null);
            triggerHandler.handleAfterInsert();
            SBQQ.TriggerControl.enable();
        Test.stopTest();
        Order resultOrder = [SELECT Id, status FROM Order LIMIT 1];
        System.assertEquals('Activated', resultOrder.status, 'We expect the order status to be updated to Activated');
        System.assertEquals(1, triggerHandler.listContractOrderEvents.size(), 'We expect a contract order event to be added to this list');

    }

    @isTest
    static void triggerHandler_PriceCalcNotNeeded_PositiveTest(){
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        testOrder.SBQQ__PriceCalcStatus__c = 'Not Needed';
        SBQQ.TriggerControl.disable();
        update testOrder;
        SBQQ.TriggerControl.enable();
        List<qtcOrderActivation__e> listEvents = new List<qtcOrderActivation__e>();
        qtcOrderActivation__e event = new qtcOrderActivation__e(
            qtcOrderId__c = testOrder.Id
        );
        listEvents.add( event );

        Test.startTest();
            SBQQ.TriggerControl.disable();
            OrderActivationEventTriggerHandler triggerHandler = new OrderActivationEventTriggerHandler( listEvents, null);
            triggerHandler.handleAfterInsert();
            SBQQ.TriggerControl.enable();
        Test.stopTest();
        Order resultOrder = [SELECT Id, status FROM Order LIMIT 1];
        System.assertEquals('Activated', resultOrder.status, 'We expect the order status to be updated to Activated');
        System.assertEquals(1, triggerHandler.listContractOrderEvents.size(), 'We expect a contract order event to be added to this list');

    }

    @isTest
    static void triggerHandler_PriceCalcQueued_NegativeTest(){
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        testOrder.SBQQ__PriceCalcStatus__c = 'Queued';
        SBQQ.TriggerControl.disable();
        update testOrder;
        SBQQ.TriggerControl.enable();
        List<qtcOrderActivation__e> listEvents = new List<qtcOrderActivation__e>();
        qtcOrderActivation__e event = new qtcOrderActivation__e(
            qtcOrderId__c = testOrder.Id,
            qtcRetryAttempt__c = 0 
        );
        listEvents.add( event );

        Test.startTest();
            SBQQ.TriggerControl.disable();
            OrderActivationEventTriggerHandler triggerHandler = new OrderActivationEventTriggerHandler( listEvents, null);
            triggerHandler.handleAfterInsert();
            SBQQ.TriggerControl.enable();
        Test.stopTest();
        Order resultOrder = [SELECT Id, status FROM Order LIMIT 1];
        System.assertEquals(STATUS_DRAFT, resultOrder.status, 'We expect the order status to remain the same');

        System.assertEquals(1, triggerHandler.listOrderActivationEventsToRepublish.size(), 'We expect an event to be added to this list to republish the event');
        System.assertEquals(1, triggerHandler.listOrderActivationEventsToRepublish[0].qtcRetryAttempt__c, 'We expect the retry attempt to increment by 1');

        System.assertEquals(0, triggerHandler.listContractOrderEvents.size(), 'We expect no event to be added to this list for contracting');

    }

    @isTest
    static void triggerHandler_exceedFiveAttempts_NegativeTest(){
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        testOrder.SBQQ__PriceCalcStatus__c = 'Queued';
        SBQQ.TriggerControl.disable();
        update testOrder;
        SBQQ.TriggerControl.enable();
        List<qtcOrderActivation__e> listEvents = new List<qtcOrderActivation__e>();
        qtcOrderActivation__e event = new qtcOrderActivation__e(
            qtcOrderId__c = testOrder.Id,
            qtcRetryAttempt__c = 5 
        );
        listEvents.add( event );

        Test.startTest();
            SBQQ.TriggerControl.disable();
            OrderActivationEventTriggerHandler triggerHandler = new OrderActivationEventTriggerHandler( listEvents, null);
            triggerHandler.handleAfterInsert();
            SBQQ.TriggerControl.enable();
        Test.stopTest();
        Order resultOrder = [SELECT Id, status FROM Order LIMIT 1];
        System.assertEquals(STATUS_DRAFT, resultOrder.status, 'We expect the order status to remain the same');

        System.assertEquals(0, triggerHandler.listOrderActivationEventsToRepublish.size(), 'We expect No event to be added to this list to republish the event');

        System.assertEquals(0, triggerHandler.listContractOrderEvents.size(), 'We expect no event to be added to this list for contracting');

    }



    @isTest
    static void afterInsert_PriceCalcCompleted_PositiveTest(){
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        testOrder.SBQQ__PriceCalcStatus__c = 'Completed';
        SBQQ.TriggerControl.disable();
        update testOrder;
        SBQQ.TriggerControl.enable();
        List<qtcOrderActivation__e> listEvents = new List<qtcOrderActivation__e>();
        qtcOrderActivation__e event = new qtcOrderActivation__e(
            qtcOrderId__c = testOrder.Id
        );
        listEvents.add( event );

        Test.startTest();
            SBQQ.TriggerControl.disable();
            List<Database.SaveResult> results = EventBus.publish(listEvents);
            Test.getEventBus().deliver();
            SBQQ.TriggerControl.enable();
        Test.stopTest();

        Order resultOrder = [SELECT Id, status FROM Order LIMIT 1];
        System.assertEquals('Activated', resultOrder.status, 'We expect the order status to be updated to Activated');

    }
}