force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOB__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>CLA BRAZIL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>EUROPE EXC RUSSIA</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDIA &amp; SEA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
            <value>
                <fullName>NAMER CFI</fullName>
            </value>
            <value>
                <fullName>NAMER DIRECT</fullName>
            </value>
            <value>
                <fullName>NAMER MAJORS</fullName>
            </value>
            <value>
                <fullName>NAMER SMB</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA AND SPA</fullName>
            </value>
            <value>
                <fullName>SAPAC</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <description>Note: This field was requested to be removed from the layout by Jane green</description>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Independent Service Organization</fullName>
            </value>
            <value>
                <fullName>Independent Software Vendor</fullName>
            </value>
            <value>
                <fullName>Managed Services Provider</fullName>
            </value>
            <value>
                <fullName>Master VAR</fullName>
            </value>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/SFDC_MDF__c.object-meta.xml
<CustomObject>
    <description>Track MDF request details including partner account, requested amount, activity type and date, and approval status.</description>
    <label>Fund Request</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The partner account making the MDF request</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fund Requests</relationshipLabel>
    <relationshipName>R00N30000002DjDDEA0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Account_Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Partner_Type__c</fullName>
    <label>Account Partner Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <description>The date the activity is planned. Optionally incorporate a validation rule to ensure that there is ample lead time to approve the request before the planned activity.</description>
    <inlineHelpText>This is the day of the event or the date the activity begins.</inlineHelpText>
    <label>Activity Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Activity End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <description>Partner Industry from Account should be auto-populated but Channel operations team should have an ability to edit/modify this value</description>
    <label>LOB</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Telecom &amp; Technology</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FundRequestHandlerTest.cls
@isTest
public class FundRequestHandlerTest {
    
    @isTest
    public static void beforeInsertHandlerTest(){
        Account acc = new Account();
        acc.Name='Teat';
        acc.Industry='RETAIL:PUBLIC SECTOR';
        acc.LOB__c = 'RETAIL';
        acc.Partner_Type__c = 'Solution Provider';
        acc.Account_Region__c ='EMEA';
        system.runas(TestRecordsFactory.getUser())
        {
            insert acc; 
        }
         
        List<SFDC_MDF__c> fundList = new List <SFDC_MDF__c>();
        SFDC_MDF__c fund = new SFDC_MDF__c();
        fund.Account__c=acc.Id;
        fund.Name='Fund Request test';
        fund.Activity_Date__c = Date.today()+39;
        fund.End_Date__c =Date.today()+139;
        fundList.add(fund);
        Insert fundList;
        
        Test.startTest();
        FundRequestHandler.beforeInsertHandler(fundList);
         for(SFDC_MDF__C fund1:fundList){
            system.assertEquals(acc.Partner_Type__c, fund1.Account_Partner_Type__c);
        }
        Test.stopTest();
        
        
    }
}