force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CDM_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>CDM_Account_Status__c</fullName>
    <label>NCR Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CDM_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>CDM_Account_Type__c</fullName>
    <description>This field has been created under CDM project and values for this field will be coming from CDM via SOUP.</description>
    <label>Account Type</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deliver_To__c.field-meta.xml
<CustomField>
    <fullName>Deliver_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deliver-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Bill_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Bill-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Deliver_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Deliver_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Deliver-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Ship_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Ship-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_Coordinator_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Coordinator_Email__c</fullName>
    <description>Note: This field was requested to be removed from the layout by Jane green
Jan12: Kayla Hittig requested the field to be added back to the layout</description>
    <label>Project Coordinator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ship-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Document__c/Customer_Document__c.object-meta.xml
<CustomObject>
    <description>Track status&apos;s and other information that will be sent from DocuSign.</description>
    <label>CLM Document History</label>
    <nameField>
        <label>Customer Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLM Documents History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Document__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <description>This will provide information on which line of business the documents are for and will allow users to filter by LOB when viewing documents.</description>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
            <value>
                <fullName>Banking</fullName>
                <isActive>false</isActive>
                <label>Banking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Document__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Customer_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel_Office__c.field-meta.xml
<CustomField>
    <fullName>Channel_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel/Local Office</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(5 AND ((1 OR 4) AND 2) OR 3) AND (6 AND 7) AND 8</booleanFilter>
        <filterItems>
            <field>Account.CDM_Account_Type__c</field>
            <operation>equals</operation>
            <value>PARTNER, LOCAL OFFICE</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Country_Code__c</field>
            <operation>equals</operation>
            <value>US</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>C9 Administration, 02 NSC Administrator, 04 NSC UI Administrator,HOSP Inside Sales, 50 Hospitality Account Director, 55 Hosted Solutions Sales, iPaas Administration, Soup Integration</value>
        </filterItems>
        <filterItems>
            <field>Account.CDM_Sub_Account_Type__c</field>
            <operation>equals</operation>
            <value>CHANNEL</value>
        </filterItems>
        <filterItems>
            <field>Account.Active_Account__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <filterItems>
            <field>Account.LOB__c</field>
            <operation>equals</operation>
            <value>HOSPITALITY, RETAIL</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Channel Office)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EndCustomerUnknown__c.field-meta.xml
<CustomField>
    <fullName>EndCustomerUnknown__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, End_Customer__c will not be mandatory. I unchecked, End_Customer__c is mandatory.</description>
    <inlineHelpText>Please select, if the End Customer is not known Or Please update End Customer below</inlineHelpText>
    <label>End Customer Unknown</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery_Date__c</fullName>
    <label>Expected Delivery Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Trigger__c</fullName>
    <label>Invoice Trigger</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Key_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Key_Criteria__c</fullName>
    <label>Key Criteria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Business Benefits</fullName>
            </value>
            <value>
                <fullName>Lead Time</fullName>
            </value>
            <value>
                <fullName>Availability</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Pre-Contact Termination</fullName>
            </value>
            <value>
                <fullName>Post-Contact Termination</fullName>
            </value>
            <value>
                <fullName>HW</fullName>
            </value>
            <value>
                <fullName>SW</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
                <label>Service</label>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Skip_Validation_Rule_for_Lead_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Skip_Validation_Rule_for_Lead_Conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Validation Rule for Lead Conversion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CROSS LOB</fullName>
            </value>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
            <value>
                <fullName>TRAVEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CPQCLMQuoteExpirationServiceTest.cls
/********************
* Class Name: CPQCLMQuoteExpirationServiceTest
* Description: This Test class resposible to Test logic to send documents to cancelled at CLM upon quote expiration in CPQ
* Created By: Pankaj Pandey
* Created Date: 16-AUG-2022
* 
* Srno       Date            Description
* 1       16-AUG-2022     	SFCPQBLG-1174
* 
* *******************************************/
@isTest
public with sharing class CPQCLMQuoteExpirationServiceTest {
	@testSetup
    public static void setup(){
        
           Account thisAccount = new Account(name = 'ContractTestAccount',
                                          LOB__c = 'FINANCIAL',
                                          Master_Customer_Number__c = 'SETUPMASTERCONTRACT',
                                          Account_Country_Code__c = 'US', CurrencyIsoCode = 'USD',
                                          Active_Account__c = true,
                                          Primary_Bill_To__c = true,
                                          Bill_To__c = true,
                                          Ship_To__c = true, 
                                          Primary_Ship_To__c = true,
                                          Deliver_To__c = true, 
                                          Primary_Deliver_To__c = true,
                                          CDM_Account_Type__c='LOCAL OFFICE',
                                          CDM_Account_Status__c = 'Active',
                                          industry = 'HOSPITALITY:QSR',
                                          Project_Coordinator_Email__c = 'abc@test.com'
                                         );
        User soupUser = TestRecordsFactory.getUser();
        System.runAs( soupUser ){
            insert thisAccount;
        }
        
        Opportunity thisOpportunity = new Opportunity(
            AccountID = thisAccount.id,
            Name = 'OppQuote Linkage Test Opportunity',
            type = 'Indirect Channel',
            CURRENCYISOCODE = 'USD',
            INVOICE_TRIGGER__C = 'Shipment',
            Expected_Delivery_Date__c = System.TODAY().addDays(30),
            closeDate = System.TODAY(),
            Channel_Office__c= thisAccount.id,
            stagename = 'Prospecting',
            Key_Criteria__c='Best Solution;Business Benefits;Lead Time;Performance;Price',
            EndCustomerUnknown__c = true,
            Skip_Validation_Rule_for_Lead_Conversion__c = true,
            ForecastCategoryName ='Omitted'
        );
        insert thisOpportunity;
        
        List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
                  
            SBQQ__Quote__c thisQuote = new SBQQ__Quote__c(
            CurrencyIsoCode = 'USD',
            SBQQ__Account__c = thisAccount.Id,
            SBQQ__Opportunity2__c = thisOpportunity.Id,
            SBQQ__Primary__c=true,
            SBQQ__SalesRep__c = soupUser.Id,
            qtc_Quote_Name__c = 'test quote name',
            SBQQ__Status__c='Expired');
            
            quotes.add(thisQuote);
             
        insert quotes;
        
        CUSTOMER_DOCUMENT__C doc = new CUSTOMER_DOCUMENT__C(DOCUMENT_TYPE__C = 'AE Order Form',
        DOCUMENT_LINK__C = 'https://na11.springcm.com/atlas/Documents/DocExplorer?aid=10293&Id=e37f23ad-70c2-ec11-9c48-d89d6716196d',
        Document_Status__c = 'Sent for Signature',QUOTE__C = thisQuote.ID,ACCOUNT__C = thisAccount.id,
        NAME = 'Test CPQ TO CLM Quote Expire.');
        insert doc;
        
    }
    
    static testmethod  void testMethods(){
        
        Test.startTest();
        System.schedule('CLM Document Request Test',  '0 0 * * * ?', new CPQCLMQuoteExpirationService(true));
        Test.stopTest();       
        
    }

}