force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>End-user Customer account that is in a RoR country</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Business_Function__c.field-meta.xml
<CustomField>
    <fullName>Business_Function__c</fullName>
    <label>Business Function</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>C-Level</fullName>
            </value>
            <value>
                <fullName>CPI</fullName>
            </value>
            <value>
                <fullName>Customer Support/Service</fullName>
            </value>
            <value>
                <fullName>Digital Commerce</fullName>
            </value>
            <value>
                <fullName>Finance/Accounting</fullName>
            </value>
            <value>
                <fullName>Fraud Management</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NCR Ambassador</fullName>
            </value>
            <value>
                <fullName>NCR Champion</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Other: (please specify)</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Project Management</fullName>
            </value>
            <value>
                <fullName>Quality/Improvement</fullName>
            </value>
            <value>
                <fullName>Research &amp; Development</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Vendor Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Decision_Maker__c.field-meta.xml
<CustomField>
    <fullName>Decision_Maker__c</fullName>
    <inlineHelpText>Contacts labeled as Not Involved will not be surveyed</inlineHelpText>
    <label>Decision Maker</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>Not involved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Entry-Level Manager</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Individual Contributor</fullName>
            </value>
            <value>
                <fullName>Middle Manager</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Project/Team Leader</fullName>
            </value>
            <value>
                <fullName>Sr. Exec/CXO</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Vice President/Director</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Language__c.field-meta.xml
<CustomField>
    <fullName>Primary_Language__c</fullName>
    <inlineHelpText>Select the Primary Language for this contact. If not in the list, select Other, then enter into the Secondary Language field.</inlineHelpText>
    <label>Primary Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Bahasa Indonesia</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>English UK</fullName>
            </value>
            <value>
                <fullName>English US</fullName>
                <default>true</default>
                <label>English US</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>French Canadian</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Greek</fullName>
            </value>
            <value>
                <fullName>Hebrew</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Portuguese BR</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Spanish LA</fullName>
            </value>
            <value>
                <fullName>Spanish WE</fullName>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
            <value>
                <fullName>Tagalog (Philippines)</fullName>
            </value>
            <value>
                <fullName>Thai</fullName>
            </value>
            <value>
                <fullName>Turkish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_Flag__c.field-meta.xml
<CustomField>
    <fullName>Survey_Flag__c</fullName>
    <label>Relationship Survey</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No-Prospect</fullName>
            </value>
            <value>
                <fullName>No-Customer Policy</fullName>
            </value>
            <value>
                <fullName>No-Customer Opt Out</fullName>
            </value>
            <value>
                <fullName>No-Customer Contract</fullName>
            </value>
            <value>
                <fullName>No-Account Request</fullName>
            </value>
            <value>
                <fullName>No-Indirect Customer</fullName>
            </value>
            <value>
                <fullName>No-Per CX Team</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PartnerContact.recordType-meta.xml
<RecordType>
    <fullName>PartnerContact</fullName>
    <active>true</active>
    <description>Partner Contact (used for Financial and Retail Partner Contacts)</description>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/User/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CROSS LOB</fullName>
            </value>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
            <value>
                <fullName>TRAVEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ValidateContactRecordTypeTest.cls
@isTest
public class ValidateContactRecordTypeTest {
  static testMethod void testUpdateContactRecordType() {
    // Get all Active Account RecordTypes that are available to the running user
    Map<String,Id> accountTypesMap = RecordTypeInfoUtil.GetRecordTypeIdsByDeveloperName(Account.SObjectType);
  
    // Get all Active contact RecordTypes that are available to the running user
    Map<String,Id> contactTypesMap = RecordTypeInfoUtil.GetRecordTypeIdsByDeveloperName(Contact.SObjectType);
    
    // Inser Customer Accounts
    List<Account> actList = new List<Account>();
    
    if (accountTypesMap.get('Customer') != null) {
      Account act ;
      for (Integer i = 000 ; i < 100 ; i++) {
        act = new Account();
        act.Name = 'Test Acc' + String.valueOf(i);
        act.RecordTypeId = accountTypesMap.get('Customer');
        act.LOB__c = 'FINANCIAL';
        act.Master_Customer_Number__c = 'TEST000' + String.valueOf(i);
        act.Account_Country_Code__c = 'US';
        act.CurrencyIsoCode = 'USD';
        act.Active_Account__c = true;
        actList.add(act);
      } 
    }
    
    if (actList.size() > 0) {
      insert actList;
      
      // Insert #100 contacts with first account
      List<Contact> conList = new List<Contact>();
      Contact con ;
      for (Integer i = 0; i < 100 ; i++) {
        con = new Contact();
        con.LastName = 'LastName'+String.valueOf(i);
        con.AccountId = actList[0].Id;
        con.Email = 'test.email'+String.valueOf(i)+'@domain.com';
        con.Decision_Maker__c = 'Decision Maker';
        con.Level__c = 'Entry-Level Manager';
        con.Business_Function__c = 'Customer Support/Service';
        con.Primary_Language__c  = 'English US';
        con.Survey_Flag__c = 'Yes'; // Relationship Survey
        conList.add(con);
      }
      
      // Insert #1 contact with each other accounts
      integer j = 100;
      for (Integer i = 1; i < 100 ; i++) {
        
        con = new Contact();
        con.LastName = 'LastName'+String.valueOf(j);
        con.AccountId = actList[i].Id;
        con.Email = 'test.email'+String.valueOf(j)+'@domain.com';
        con.Decision_Maker__c = 'Decision Maker';
        con.Level__c = 'Entry-Level Manager';
        con.Business_Function__c = 'Customer Support/Service';
        con.Primary_Language__c  = 'English US';
        con.Survey_Flag__c = 'Yes'; // Relationship Survey
        conList.add(con);
        j++;
      }
      
      if (conList.size() > 0) {
        insert conList;
      }
      
      // Update Contact with differnt record type
      for (Contact cont : conList) {
        cont.RecordTypeId = contactTypesMap.get('PartnerContact');
      }
      
      try {
        if(conList.size() > 0) {
          update conList;
        }
      } catch (Exception ex) {
        Boolean expectedExceptionThrown =  ex.getMessage().contains('Plese change the related Account\'s Record Type, this will automatically change the Contact\'s Record Type.') ? true : false;
        System.AssertEquals(expectedExceptionThrown, true);
      }
      
    }
  }
}