force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_Industry_Name__c.field-meta.xml
<CustomField>
    <fullName>MDM_Industry_Name__c</fullName>
    <label>Industry Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/Account_Entitlements__c.object-meta.xml
<CustomObject>
    <label>Account Entitlements</label>
    <nameField>
        <label>Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Entitlements__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Active_Count__c.field-meta.xml
<CustomField>
    <fullName>Active_Count__c</fullName>
    <label>Active Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Expired_Count__c.field-meta.xml
<CustomField>
    <fullName>Expired_Count__c</fullName>
    <label>Expired Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Hold_Count__c.field-meta.xml
<CustomField>
    <fullName>Hold_Count__c</fullName>
    <label>Hold Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Entitlements__c/fields/Primary_Product_Desc__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Desc__c</fullName>
    <label>Primary Product Desc</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EntitlementSectionHandlerTest.cls
@isTest
public class EntitlementSectionHandlerTest {
@isTest
    public static void getAccountEntitlementListTest(){
        Account ac=new Account();
        Account parentAcc =new Account();
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        User Usr = [Select Id from User Where Name = 'Soup User'];
        System.runAs(Usr){
            parentAcc.Name='Test Parent Account';
            parentAcc.Account_Country_Code__c='A2';
            parentAcc.MDM_Industry_Name__c='FINANACIAL:BANKING';
            parentAcc.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            insert parentAcc;
            
            ac.Name='Test Account';
            ac.Account_Country_Code__c='A2';
            ac.MDM_Industry_Name__c='FINANACIAL:BANKING';
            ac.RecordTypeId = rtMapByName.get(Label.RT_Acc_Customer).getRecordTypeId();
            ac.parentId = parentAcc.Id;
            insert ac; 
        } 
        
        List<Account_Entitlements__c> entitlmentList = new  List<Account_Entitlements__c>();
        Account_Entitlements__c el = new Account_Entitlements__c(Account__c = ac.Id);
        el.Primary_Product_Desc__c = 'Test';
        el.Active_Count__c = 4;
        el.Hold_Count__c =2;
        el.Expired_Count__c = 23;
        entitlmentList.Add(el);
        
        Account_Entitlements__c el1 = new Account_Entitlements__c(Account__c = ac.Id);
        el1.Primary_Product_Desc__c = 'Test';
        el1.Active_Count__c = 4;
        el1.Hold_Count__c =2;
        el1.Expired_Count__c = 23;        
        entitlmentList.Add(el1);
        
        insert entitlmentList;
        System.assertNotEquals(el1, null,'entitlmentList should not be null');

        EntitlementSectionHandler.getAccountEntitlementList(ac.id);
        EntitlementSectionHierarchy.getAccountEntitlementList(ac.Id);
    }
    

}