force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>EG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RoR_Update_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>RoR_Update_Date_Time__c</fullName>
    <description>Date which the RoR interface last updated this record</description>
    <label>RoR Update Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>End-user Customer account that is in a RoR country</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Majors_Product_Matrix__c/Majors_Product_Matrix__c.object-meta.xml
<CustomObject>
    <label>Majors Product Matrix</label>
    <nameField>
        <displayFormat>MPM-{0000}</displayFormat>
        <label>Majors Product Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Majors Product Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Majors_Product_Matrix__c/fields/MCN__c.field-meta.xml
<CustomField>
    <fullName>MCN__c</fullName>
    <description>This will holds the master customer number related to account.</description>
    <externalId>true</externalId>
    <label>MCN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Majors_Product_Matrix__c/fields/NEW_COMPETETORS__c.field-meta.xml
<CustomField>
    <fullName>NEW_COMPETETORS__c</fullName>
    <description>This is the field used in lightning component to display the list competetors</description>
    <label>NEW COMPETETORS</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Majors_Product_Matrix__c/fields/NOT_SOLD_LIST__c.field-meta.xml
<CustomField>
    <fullName>NOT_SOLD_LIST__c</fullName>
    <description>This is the field used to display not sold items in lightning component</description>
    <label>NOT SOLD LIST</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Majors_Product_Matrix__c/fields/PRODUCTTOPLINES__c.field-meta.xml
<CustomField>
    <fullName>PRODUCTTOPLINES__c</fullName>
    <description>It holds list of all the product top lines list with ; separator.</description>
    <label>PRODUCTTOPLINES</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Majors_Product_Matrix__c/fields/PURCHASED_LIST__c.field-meta.xml
<CustomField>
    <fullName>PURCHASED_LIST__c</fullName>
    <description>It holds the purchased products with ; separator symbol</description>
    <label>PURCHASED LIST</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ToplineCompetetors__c/ToplineCompetetors__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ToplineCompetetors</label>
</CustomObject>

force-app/main/default/objects/ToplineCompetetors__c/fields/Competetors__c.field-meta.xml
<CustomField>
    <fullName>Competetors__c</fullName>
    <description>This is the field used to reference in lightning component to get the list of competetors</description>
    <label>Competetors</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MultiselecttoplinesControllerTest.cls
/*
Last Modified Date..:    19-12-2022
EBA_SF-2491 JDK Locale impact - Upgrade API Part 5  
*/
@IsTest
Public class MultiselecttoplinesControllerTest{
    
    static testMethod void testmultiselectlist(){
        Account acc = new Account(      
            Account_Country_Code__c = 'EG',
            Active_Account__c = true,        
            Master_Customer_Number__c = '12345',
            Name = 'Unit Test1 ',
            RecordTypeId = NSCCommonInfoUtil.getInstance().getRecordTypeId('Account','Customer'),
            RoR_Update_Date_Time__c = System.now(),
            Industry = 'RETAIL:CHANNEL'
            
        );
        User u = TestRecordsFactory.getUser();   
        System.runas(u){
            insert acc;
        }
        
        Majors_Product_Matrix__c mp=new Majors_Product_Matrix__c (
            MCN__c='12345',
            New_Competetors__c='NCR;Diebod',
            Purchased_List__c='test1',
            Not_Sold_List__c='test2;test3',
            Producttoplines__c='test1;test2;test3'
            
        );
        insert mp;
        
        ToplineCompetetors__c cs = new ToplineCompetetors__c();
        cs.Competetors__c='test1;test2;test4;test4';
        cs.name='testcs';
        //cs.Other fiels values
        insert cs;
        
        
        MultiselecttoplinesController.getpickval_CompetitorValues();
        MultiselecttoplinesController.NewGetPicklistNotSoldValue(acc.id);
        MultiselecttoplinesController.addCompetetors('inputtext');
        MultiselecttoplinesController.saveCompetetors('NCR',acc.id);
        Majors_Product_Matrix__c str1=[select id,New_Competetors__c from Majors_Product_Matrix__c where MCN__c =:acc.Master_Customer_Number__c] ;
        System.assert(str1.New_Competetors__c=='NCR');
        MultiselecttoplinesController.SaveNotSoldvalues('inputtext2',acc.id);
        MultiselecttoplinesController.NewGetPicklistCompetetorsValue(acc.id);
        MultiselecttoplinesController.saveSelectedSoldItems('NCR','Diebod',acc.id);
        
    }     
    
}