force-app/main/default/objects/Account/fields/Account_Name_Local__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_Local__c</fullName>
    <label>Account Name (Local)</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOB__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>CLA BRAZIL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>EUROPE EXC RUSSIA</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDIA &amp; SEA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
            <value>
                <fullName>NAMER CFI</fullName>
            </value>
            <value>
                <fullName>NAMER DIRECT</fullName>
            </value>
            <value>
                <fullName>NAMER MAJORS</fullName>
            </value>
            <value>
                <fullName>NAMER SMB</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA AND SPA</fullName>
            </value>
            <value>
                <fullName>SAPAC</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRICA DIRECT</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CCASA</fullName>
            </value>
            <value>
                <fullName>CENTRAL EUROPE</fullName>
            </value>
            <value>
                <fullName>CHILE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>COLOMBIA</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>FRANCE BELGIUM</fullName>
            </value>
            <value>
                <fullName>HK TAIWAN</fullName>
            </value>
            <value>
                <fullName>IBERIA</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDIA AND SEA</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>KOREA</fullName>
            </value>
            <value>
                <fullName>MEA DISTRIBUTORS</fullName>
            </value>
            <value>
                <fullName>MEXICO</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
            <value>
                <fullName>NAMER CFI</fullName>
            </value>
            <value>
                <fullName>NAMER CANADA</fullName>
            </value>
            <value>
                <fullName>NAMER CENTRAL</fullName>
            </value>
            <value>
                <fullName>NAMER ENTERPRISE</fullName>
            </value>
            <value>
                <fullName>NAMER MIDWEST</fullName>
            </value>
            <value>
                <fullName>NAMER NATIONAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Executive_Sponsorship_Program_2017__c.field-meta.xml
<CustomField>
    <fullName>Executive_Sponsorship_Program_2017__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Top Accounts for Executive Sponsorship Program 2017. Requested from Tara Hannan 1/30/2017
Note: This field was requested to be removed from the layout by Jane green</description>
    <label>Executive Sponsorship Program 2017</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interact_Reseller_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Interact_Reseller_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interact Reseller Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FINANCIAL</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>T&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Level__c</fullName>
    <inlineHelpText>NCR Interact program level that defines the requirements and benefits of a partner.</inlineHelpText>
    <label>Partner Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>No Program Level</fullName>
                <default>true</default>
                <label>No Program Level</label>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rules_of_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Rules_of_Engagement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rules of Engagement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PRM_AccountController.cls
public class PRM_AccountController 
{
	@AuraEnabled
    public static List<Account> getAccounts(String selectedView)
    {
       
        List<Account> lstAccount;
            
        if(selectedView == 'All Accounts')
        {
            lstAccount =  [Select Id, Name, Owner.Name, RecordType.Name, LOB__c, Partner_Program_Level__c
                       from Account order by CreatedDate ];
        }
        else
        {
            lstAccount =  [Select Id, Name, Owner.Name, RecordType.Name, LOB__c, Partner_Program_Level__c
                       		from Account where OwnerId =: UserInfo.getUserId() order by CreatedDate ];
        }
        return lstAccount;
    }
    
    
    @AuraEnabled
    public static Account getAccountDetail(String recId)
    {
        Account objAccount = [Select Id, Name, Phone, Fax, Website, Partner_Program_Level__c, 
                              Industry, CurrencyIsoCode, Area__c, Account_Region__c, LOB__c,BillingAddress, Account_Name_Local__c,
                              BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Interact_Reseller_Agreement__c,rules_of_engagement__c
                              From Account where Id =: recId];
        return objAccount;
    }
    
   //removed executive_sponsorship_program_2017__c from query due to EBA_SF-688
}