force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Generates a number for the opportunity</description>
    <displayFormat>{000000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Quote_Details__c/Quote_Details__c.object-meta.xml
<CustomObject>
    <label>Quote Details</label>
    <nameField>
        <displayFormat>SPOT-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Details__c/fields/Linked__c.field-meta.xml
<CustomField>
    <fullName>Linked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Linked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Details__c/fields/MCN__c.field-meta.xml
<CustomField>
    <fullName>MCN__c</fullName>
    <label>MCN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Details__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>550</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestUpdateAccountIdQuoteTrigger.cls
/*
##################################################################################################
# Project Name..........: Order Opportunity Linkage                                                                       
# File..................: TestupdateAccountIdQuoteTrigger.cls                                                        
# Version...............: 30.0 
# Created by............: IDC, Gurgaon                                                                   
# Created Date..........: 29-04-2014                                                                               
# Last Modified by......: IDC, Gurgaon
# Last Modified Date....: 25-04-2014
# Description...........: The test class is written to test the updateAccountId trigger on Quote Details.
################################################################################################
*/
@isTest
private class TestUpdateAccountIdQuoteTrigger {  
    static testMethod void unitTest() { 
        //create Account record
        User Usr = [Select Id from User Where Name = 'Soup User'];
        Account a = new Account (name = 'testing task Deletion of Closed Opp', 
                                 Master_Customer_Number__c = 'TEST000015', 
                                 Account_Country_Code__c = 'US', CurrencyIsoCode = 'USD', 
                                 Active_Account__c = true);
    				
					System.runAs(Usr){ insert a; }
        
        
        //create new Quote Detail record
        List<Quote_Details__c> quoteList = new List<Quote_Details__c>();
        
        Quote_Details__c quoteObj1 = new Quote_Details__c( CurrencyIsoCode = 'USD', MCN__c = 'TEST000015');
        string quoteName = '';
        
        for(integer i=0; i< 256 ; i++){
            quoteName  += 'a';
        }
        quoteObj1.Quote_Name__c = quoteName;
        quoteList.add(quoteObj1); 
        
        //create new Quote Detail record
        Quote_Details__c quoteObj2 = new Quote_Details__c(Quote_Name__c = 'Test Quote', CurrencyIsoCode = 'USD', MCN__c = 'TEST000012', Linked__c = true);
        quoteList.add(quoteObj2);
        
        insert quoteList; 
        system.assertNotEquals(quoteList[0].id, null);
       
           
         //create opportunity record
        Opportunity  opp = TestUtitlity.createOppRecord();
        Test.startTest();
         // create new SPOT Quote
       /*  SPOT_Quote__c spquote = new SPOT_Quote__c(Name = 'Test', Opportunity_Number__c = opp.Id, 
                                                    SPOT_Quote_Number__c = quoteObj2.id, CurrencyIsoCode = 'USD');
        
                                                    
        insert spquote; 
       */
        update quoteList;
        Test.stopTest();
    }
}