force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CATM</description>
    <label>Account #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AutoPay_Setup__c.field-meta.xml
<CustomField>
    <fullName>AutoPay_Setup__c</fullName>
    <description>This field will contains Autopay status of customer. Populate from ERP</description>
    <label>AutoPay Setup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.SuspendProcessing_Contact__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Contact</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Document__c/Customer_Document__c.object-meta.xml
<CustomObject>
    <description>Track status&apos;s and other information that will be sent from DocuSign.</description>
    <label>CLM Document History</label>
    <nameField>
        <label>Customer Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLM Documents History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Document__c/fields/Customer_Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Signature_Date__c</fullName>
    <label>Customer Signature Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Customer_Document__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Executing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Ready to Send to Customer for Signature</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Preview</fullName>
            </value>
            <value>
                <fullName>Choose the Salesperson to email to</fullName>
            </value>
            <value>
                <fullName>Customer is Redlining Document</fullName>
            </value>
            <value>
                <fullName>Additional User is Approving</fullName>
            </value>
            <value>
                <fullName>Sales is reviewing Customer redlines</fullName>
            </value>
            <value>
                <fullName>Sales is Sending for Additional Review</fullName>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Customer is Redlining Other Documents, Order Form has not been sent</fullName>
            </value>
            <value>
                <fullName>Sales Review</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Signature Cancelled</fullName>
            </value>
            <value>
                <fullName>Signature Request Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Document__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Customer_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AutoPaySetupReportTest.cls
@isTest(SeeAllData=false)
public class AutoPaySetupReportTest {
    @testSetup
    static void setup(){        
        User Usr = [Select Id,email,ManagerId, profileId from User Where Name = 'Soup User' limit 1];          

        System.runAs(CPQ_TestDataFactory.getSoupUser()) {
            for(Integer i=1; i<10;i++){           
        
                Opportunity o = new Opportunity();
                Contact ct = new Contact(FirstName = 'Test', LastName='ing'+i, Email = 'test.ing'+i+'@ncr.com');
                insert ct;
                System.debug('got Contact in test:'+ i + ' --->' + ct);
                Map<String,String> fieldApiNameToFieldValue = new Map<String,String>();
                Account at = new Account(Name = 'Test Account 2',Master_Customer_Number__c='9789123',Bill_To__c= True, AutoPay_Setup__c='', Primary_Contact__c = ct.Id);
                insert at;
                User usrObj = new User();
                SBQQ__Quote__c qt = new SBQQ__Quote__c(SBQQ__SalesRep__c= Usr.id, qtc_Legal_Document_Status__c = 'Completed',
                                                       qtc_Payments_Only_Quote__c = 'No', SBQQ__Ordered__c = false);
                qt.SBQQ__Account__c = at.Id;
                insert qt;
                Customer_Document__c cdObj = new Customer_Document__c(Name='TestAashirwaad', Account__c= at.id, Quote__r=qt,Customer_Signature_Date__c= datetime.newInstance(2022, 9, 15, 12, 30, 0),
                                                                      Document_Type__c='AE Order Form',Document_Status__c = 'Completed' );
                insert cdObj;
            }
        }
    }
    static testmethod void testAutoPaySetupReportScheduleJob(){
        String sch = '0 5 12 10 2 ?';
        Test.startTest();
        String jobId = System.Schedule('ScheduleAutoPaySetupReportTest', sch, new AutoPaySetupReport());
        EmailTemplate et = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where DeveloperName ='CPQ_Quote_with_FO_for_SalesReps'];
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'salesforce.donotreply@ncr.com'];
        List<SBQQ__Quote__c> QuoteList = [SELECT id,Name,SBQQ__Account__r.Name, SBQQ__Account__r.Master_Customer_Number__c,SBQQ__SalesRep__c,qtc_Legal_Document_Status__c,SBQQ__SalesRep__r.email,SBQQ__SalesRep__r.ManagerId,
                                       (SELECT id,Customer_Signature_Date__c FROM Customer_Documents__r wHERE Document_Status__c = 'Completed' AND
                                        (Document_Type__c ='AE Order Form' OR Document_Type__c = 'AE Amendment') order by Customer_Signature_Date__c DESC limit 1)
                                       FROM SBQQ__Quote__c WHERE AutoPay_Setup__c not in ('True', 'Manual') AND qtc_Legal_Document_Status__c = 'Completed' AND
                                       qtc_Payments_Only_Quote__c = 'No' AND SBQQ__Ordered__c = false];
        Test.stopTest();
    }
    
}