force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_Industry_Name__c.field-meta.xml
<CustomField>
    <fullName>MDM_Industry_Name__c</fullName>
    <label>Industry Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APL_Account_Open_Dispatches__c/APL_Account_Open_Dispatches__c.object-meta.xml
<CustomObject>
    <label>Account Open Dispatches</label>
    <nameField>
        <label>Open Dispatches Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Open Dispatches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APL_Account_Open_Dispatches__c/fields/Account_Master_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Account_Master_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>APL_Account_Open_Dispatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APL_Account_Open_Dispatches__c/fields/priority_code__c.field-meta.xml
<CustomField>
    <fullName>priority_code__c</fullName>
    <label>Priority Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APL_Account_Open_Dispatches__c/fields/SLA_Category__c.field-meta.xml
<CustomField>
    <fullName>SLA_Category__c</fullName>
    <label>SLA Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpenDispatchesHandlerTest.cls
@isTest
public class OpenDispatchesHandlerTest {
    @isTest
    public static void getDispatchTest(){
       Account ac=new Account();
        Account parentAcc =new Account();
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        User Usr = [Select Id from User Where Name = 'Soup User'];
        System.runAs(Usr){
            
            parentAcc.Name='Test Parent Account';
            parentAcc.Account_Country_Code__c='A2';
            parentAcc.MDM_Industry_Name__c='FINANACIAL:BANKING';
            parentAcc.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            insert parentAcc;
            
            ac.Name='Test Account';
            ac.Account_Country_Code__c='A2';
            ac.MDM_Industry_Name__c='FINANACIAL:BANKING';
            ac.RecordTypeId = rtMapByName.get(Label.RT_Acc_Customer).getRecordTypeId();
            ac.parentId = parentAcc.Id;
            insert ac; 
        } 
        List<APL_Account_Open_Dispatches__c> openDispatchList = new  List<APL_Account_Open_Dispatches__c>();
        APL_Account_Open_Dispatches__c od = new APL_Account_Open_Dispatches__c();
        od.Priority_code__c = '1';
        od.Account_Master_Lookup__c = ac.id;
        od.SLA_Category__c = 'Open Call Outside SLA';
        openDispatchList.Add(od);
         APL_Account_Open_Dispatches__c od1 = new APL_Account_Open_Dispatches__c();
         od1.Account_Master_Lookup__c = ac.id;
        od1.Priority_code__c = '2';
        od1.SLA_Category__c = 'Open Call Within SLA';
         openDispatchList.Add(od1);
         APL_Account_Open_Dispatches__c od2 = new APL_Account_Open_Dispatches__c();
         od2.Account_Master_Lookup__c = ac.id;
        od2.Priority_code__c = '2';
        od2.SLA_Category__c = 'Open Call Within SLA';
         openDispatchList.Add(od2);
        insert openDispatchList;
        system.assert(openDispatchList.size() >0); 
        OpenDispatchesHandler.getDispatch(ac.id);
        OpenDispatchesHierarchyHandler.getDispatch(ac.id);
        OpenDispatchesHierarchyHandler.getDispatch(parentAcc.id);
    }
}