force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is account active in RoR?</description>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>End-user Customer account that is in a RoR country</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/ASM_Role_Hierarchy__c/ASM_Role_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Account Point of Contacts</label>
    <nameField>
        <displayFormat>APOC{000000}</displayFormat>
        <label>APOC ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Point of Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
                <default>true</default>
                <label>Create</label>
            </value>
            <value>
                <fullName>Overwrite</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <externalId>true</externalId>
    <label>Master</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/NCR_Employee_Detail__c.field-meta.xml
<CustomField>
    <fullName>NCR_Employee_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to associate NCR Employee Detail so that we can assign the roles to the users.</description>
    <label>NCR Employee Detail</label>
    <referenceTo>NCR_Employee_Detail__c</referenceTo>
    <relationshipLabel>Account Point of Contacts</relationshipLabel>
    <relationshipName>Account_Point_of_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/QuickLook_ID__c.field-meta.xml
<CustomField>
    <fullName>QuickLook_ID__c</fullName>
    <label>Role User QuickLook ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Role_Name__c.field-meta.xml
<CustomField>
    <fullName>Role_Name__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Director</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>Account Services Manager</fullName>
                <isActive>false</isActive>
                <label>Account Services Manager</label>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Support Analyst</fullName>
            </value>
            <value>
                <fullName>Account Support Manager</fullName>
            </value>
            <value>
                <fullName>Channel Account Manager</fullName>
            </value>
            <value>
                <fullName>CMS Account Manager</fullName>
            </value>
            <value>
                <fullName>COA</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>COL</fullName>
            </value>
            <value>
                <fullName>Collector</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Customer Advocate</fullName>
            </value>
            <value>
                <fullName>Customer Delivery Partner (CDP)</fullName>
            </value>
            <value>
                <fullName>Customer Project Manager (CPM)</fullName>
            </value>
            <value>
                <fullName>Customer Relationship Manager</fullName>
            </value>
            <value>
                <fullName>Customer Success Analyst</fullName>
            </value>
            <value>
                <fullName>Customer Success Leader</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
            <value>
                <fullName>Executive Service Manager</fullName>
            </value>
            <value>
                <fullName>Executive Services Manager</fullName>
                <isActive>false</isActive>
                <label>Executive Services Manager</label>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Field Operations</fullName>
            </value>
            <value>
                <fullName>Field Service Coordinator</fullName>
            </value>
            <value>
                <fullName>Field Training</fullName>
            </value>
            <value>
                <fullName>Global Account Manager</fullName>
            </value>
            <value>
                <fullName>Inside Sales Specialist</fullName>
            </value>
            <value>
                <fullName>PO/Billing Person</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Role_User_Name__c.field-meta.xml
<CustomField>
    <fullName>Role_User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Point_of_Contacts_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BPM_Configuration__c/BPM_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BPM Configuration</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CATM</description>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <label>Quicklook ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/NCR_Employee_Detail__c.object-meta.xml
<CustomObject>
    <description>This object stores the details of all NCR employees.</description>
    <label>NCR Employee Detail</label>
    <nameField>
        <label>NCR Employee Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCR Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Contingent_Manager__c.field-meta.xml
<CustomField>
    <fullName>Contingent_Manager__c</fullName>
    <label>Contingent Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_ID__c</fullName>
    <label>Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/InActive__c.field-meta.xml
<CustomField>
    <fullName>InActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_ID__c</fullName>
    <label>User Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Manager_Level_01_ID__c.field-meta.xml
<CustomField>
    <fullName>Manager_Level_01_ID__c</fullName>
    <description>This field is used in Sales Order Reporting.</description>
    <label>Manager Level 01 ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/APOC_MassUpdateAllRolesHandlerTest.cls
@isTest
public class APOC_MassUpdateAllRolesHandlerTest {
    @TestSetUp
    public static void unitTest(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        Profile p1 = [SELECT Id FROM Profile WHERE Name='90 Chatter Free'];  
        
        User userObj = new User(Alias = 'commuser', Email='standarduser1@testorg.com', quicklook_Id__c = 'ab123456',
                                EmailEncodingKey='UTF-8', LastName='Testing123', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, 
                                TimeZoneSidKey='America/Los_Angeles', UserName='stand11122@testorg.com');
        insert userObj;
        
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', quicklook_Id__c = 'aa123456',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p1.Id, 
                          TimeZoneSidKey='America/Los_Angeles', Manager = userObj, UserName='stand11111@testorg.com',Manager_Level_01_ID__c='1001');
        insert u;
        User u1 = new User(Alias = 'standt', Email='standarduser@testorg.com', quicklook_Id__c = 'ad123456',
                           EmailEncodingKey='UTF-8', LastName='Testing30', LanguageLocaleKey='en_US', 
                           LocaleSidKey='en_US', ProfileId = p1.Id, 
                           TimeZoneSidKey='America/Los_Angeles', Manager = userObj, UserName='Testing30@testorg.com',Manager_Level_01_ID__c='1001',isactive=false);
        insert u1;
        System.debug('u !!'+u.id);
        System.debug('userObj !!'+userObj.id);
        
        Map<Id, ASM_Role_Hierarchy__c> oldMap = new Map<Id, ASM_Role_Hierarchy__c>();
        // Account accObj = new Account(Name = 'Test', Master_Customer_Number__c = '13308');
        //insert accObj;''
        User Usr = [Select Id from User Where Name = 'Soup User'];
        System.runAs(Usr){
            Account acc=TestRecordsFactory.createAccount('abc');
            Account acc1=TestRecordsFactory.createAccount('acctest');
            Contact con = TestRecordsFactory.createContact(acc);
            List<Contact> cl = new List<Contact>{new Contact(Lastname='testing',Email='apoc@test.com')};
                System.enqueueJob(new  APOC_MassUpdateAllRolesHandler.ConCrtnQueue(cl));
            List<BPM_Configuration__c> bpmConfList = new List<BPM_Configuration__c>();
            bpmConfList.add(new BPM_Configuration__c(Name='APOCMail',values__C='vp250252@ncr.com'));
            bpmConfList.add(new BPM_Configuration__c(Name='APOCBCC',values__C='vp250252@ncr.com'));
            bpmConfList.add(new BPM_Configuration__c(Name='BPMContactIdForNotifyActionOwner',values__C=con.id));
            bpmConfList.add(new BPM_Configuration__c(Name='APOCAccount',values__C=acc.Master_Customer_Number__c));
            bpmConfList.add(new BPM_Configuration__c(Name='BPM Email - added into QLID',values__C='@ncr.com.invalid'));
            bpmConfList.add(new BPM_Configuration__c(Name='BPMProfile',values__C='BPM Partner Community User'));
            //  bpmConfList.add(new BPM_Configuration__c(Name='excProfileId',values__C='00e70000001NyoaAAC'));
            bpmConfList.add(new BPM_Configuration__c(Name='excProfileId',values__C=NSCCommonInfoUtil.getIdOf('iPaas_Administration_Profile_Id')));
            bpmConfList.add(new BPM_Configuration__c(Name='BPMDefaultPOQLID',values__C='ob230024'));
            
            insert bpmConfList;
       
            List<NCR_Employee_Detail__c> ncrlist = new List<NCR_Employee_Detail__c>();
            
            NCR_Employee_Detail__c n = new NCR_Employee_Detail__c(Name='User1',Quicklook_ID__c='ab123456',Global_ID__c='1000',Contingent_Manager__c='1001',Employee_type__c='NCR',Inactive__c=false);
            ncrlist.add(n);
            NCR_Employee_Detail__c n1 = new NCR_Employee_Detail__c(Name='User2',Quicklook_ID__c='aa123456',Global_ID__c='1001',Contingent_Manager__c='1002',Employee_type__c='NCR',Inactive__c=false);
            ncrlist.add(n1);
            NCR_Employee_Detail__c n2 = new NCR_Employee_Detail__c(Name='User2',Quicklook_ID__c='nb250250',Global_ID__c=u.Manager_Level_01_ID__c,Contingent_Manager__c='1002',Employee_type__c='NCR',Inactive__c=false);
            ncrlist.add(n2);
            NCR_Employee_Detail__c n3 = new NCR_Employee_Detail__c(Name='User3',Quicklook_ID__c='ac123456',Global_ID__c=u.Manager_Level_01_ID__c,Contingent_Manager__c='1002',Employee_type__c='NCR',Inactive__c=false);
            ncrlist.add(n3);
            NCR_Employee_Detail__c n4 = new NCR_Employee_Detail__c(Name='User3',Quicklook_ID__c='ad123456',Global_ID__c=u.Manager_Level_01_ID__c,Contingent_Manager__c='1002',Employee_type__c='NCR',Inactive__c=false);
            ncrlist.add(n4);
            insert ncrlist;
            system.assert(n.id!=null);
            System.debug('acc 1 '+acc);
            //acc.Active_Account__c = true;
            //update acc;
            ASM_Role_Hierarchy__c obj = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='ab123456',Role_Name__c = 'PO/Billing Person');
            Insert obj;
            ASM_Role_Hierarchy__c obj2 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='aa123456',Role_Name__c = 'Account Support Manager');
            Insert obj2;    
            ASM_Role_Hierarchy__c obj3 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='nb250250',Role_Name__c = 'Account Support Manager');
            Insert obj3; 
            ASM_Role_Hierarchy__c obj4 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='aa123456',Role_Name__c = 'Customer Advocate');
            Insert obj4; 
            system.assert(obj.id!=null);
            
        }
    }
    
    @isTest
    static void Test1(){
        account acc = [select id,name,Active_Account__c,Master_Customer_Number__c from Account limit 1];
       
        System.debug('acc '+acc);
        Test.startTest();
        
        ASM_Role_Hierarchy__c obj = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='ab123456',Role_Name__c = 'Account Support Manager');
        APOC_MassUpdateAllRolesHandler.isInsertFromUI = true; 
        Insert obj;
        system.assertEquals(obj.QuickLook_ID__c,'ab123456');
        Test.stopTest();
    }
    @isTest
    static void Test2(){
        Test.startTest();
        user u = [select id,quicklook_Id__c from User where quicklook_Id__c = 'ab123456' limit 1 ];
        ASM_Role_Hierarchy__c obj2 = [select id,action__c,QuickLook_ID__c,Role_User_Name__c,Role_Name__c from ASM_Role_Hierarchy__c  where Role_Name__c = 'Account Support Manager' limit 1];
       
        System.debug('this is obj2 before '+obj2);
        //obj2.Action__c = 'Overwrite';
        obj2.QuickLook_ID__c='ab123456';
        obj2.Role_User_Name__c = u.id;
        update obj2;
        system.assertEquals(obj2.QuickLook_ID__c,'ab123456');
        Test.stopTest();
        
    }
    @isTest
    static void Test4(){
        Test.startTest();
        user u = [select id,quicklook_Id__c from User where quicklook_Id__c = 'ab123456' limit 1 ];
       
        ASM_Role_Hierarchy__c obj2 = [select id,action__c,QuickLook_ID__c,Role_User_Name__c,Role_Name__c from ASM_Role_Hierarchy__c  where Role_Name__c = 'Account Support Manager' limit 1];
        System.debug('this is obj2 before '+obj2);
        //obj2.Action__c = 'Overwrite';
        obj2.QuickLook_ID__c='ab123456';
        obj2.Role_User_Name__c = u.id;
        obj2.Role_Name__c ='Account Director';
        update obj2;
        system.assertEquals(obj2.QuickLook_ID__c,'ab123456');
        ASM_Role_Hierarchy__c obj3 = [select id,action__c,QuickLook_ID__c,Role_User_Name__c from ASM_Role_Hierarchy__c limit 1];
        System.debug('this is obj2 after '+obj3);
        Test.stopTest();
        
    }
    @isTest
    static void Test3(){
        Test.startTest();
        ASM_Role_Hierarchy__c obj3 = [select id,action__c from ASM_Role_Hierarchy__c limit 1];
        system.assert(obj3.id!=null);
        obj3.Action__c = 'delete';
        delete obj3;
        Test.stopTest();
    }
    @isTest
    static void test5(){
        Test.startTest();
        Account acc =[Select id,Master_Customer_Number__c from Account where Master_Customer_Number__c like '%acctest%'];
        system.assert(acc!=null);
        ASM_Role_Hierarchy__c obj1 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='ac123456',Role_Name__c = 'Customer Advocate');
        database.Insert( obj1,false);
         system.assertEquals(obj1.QuickLook_ID__c,'ac123456');
        Test.stopTest();
    }
    @isTest
    static void test6(){
        Test.startTest();
        ASM_Role_Hierarchy__c obj1 = new ASM_Role_Hierarchy__c(Master__c = 'abc', QuickLook_ID__c='ac123456',Role_Name__c = 'Customer Advocate');
     
        database.Insert( obj1,false);
        system.assertEquals(obj1.QuickLook_ID__c,'ac123456');
        Test.stopTest();
    }
    @isTest
    static void test7(){
        Test.startTest();
        Account acc =[Select id,Master_Customer_Number__c from Account where Master_Customer_Number__c like '%acctest%'];
        system.assert(acc!=null);
        ASM_Role_Hierarchy__c obj1 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='kk123456',Role_Name__c = 'Customer Advocate');
        database.Insert( obj1,false);
        system.assertEquals(obj1.Master__c,acc.Master_Customer_Number__c);
        Test.stopTest();
    }
    @isTest
    static void test8(){
        Test.startTest();
        Account acc =[Select id,Master_Customer_Number__c from Account where Master_Customer_Number__c like '%acctest%'];
        ASM_Role_Hierarchy__c obj1 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c,Role_Name__c = 'Customer Advocate');
        database.Insert( obj1,false);
        ASM_Role_Hierarchy__c obj2 = new ASM_Role_Hierarchy__c(Role_Name__c = 'Customer Advocate');
        database.Insert( obj2,false);
        ASM_Role_Hierarchy__c obj4 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='ac123456',Role_Name__c = 'PO/Billing Person',action__c='Overwrite');
        Insert obj4; 
        system.assert(acc!=null);
        Test.stopTest();
    }
    @isTest
    static void test9(){
        Test.startTest();
        Account acc =[Select id,Master_Customer_Number__c from Account where Master_Customer_Number__c like '%acctest%'];
        NCR_Employee_Detail__c nc =[Select id from NCR_Employee_Detail__c where quicklook_id__C='ac123456'];
       
        ASM_Role_Hierarchy__c obj1 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='ad123456',Role_Name__c = 'PO/Billing Person');
        database.Insert( obj1,false);
        ASM_Role_Hierarchy__c obj2 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='ad123456',Role_Name__c = 'Customer Advocate');
        database.Insert( obj2,false);
        obj1.NCR_Employee_Detail__c = nc.id;
        update obj1;
        ASM_Role_Hierarchy__c obj3 = [select id,action__c,QuickLook_ID__c,Role_User_Name__c,Role_Name__c,NCR_Employee_Detail__c from ASM_Role_Hierarchy__c  where Role_Name__c = 'Customer Advocate' limit 1];
        obj3.NCR_Employee_Detail__c = nc.id;
        update obj3;
        ASM_Role_Hierarchy__c obj4 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='ac123456',Role_Name__c = 'PO/Billing Person',Action__c='Delete');
        database.Insert(obj4,false);
    
         system.assertEquals(obj4.Master__c,acc.Master_Customer_Number__c);
        Test.stopTest();
    }
    @isTest
    static void Test10(){
        Test.startTest();
        user u = [select id,quicklook_Id__c from User where quicklook_Id__c = 'ab123456' limit 1 ];
        
        ASM_Role_Hierarchy__c obj2 = [select id,action__c,QuickLook_ID__c,Role_User_Name__c,Role_Name__c from ASM_Role_Hierarchy__c  where Role_Name__c = 'Customer Advocate' limit 1];
        System.debug('this is obj2 before '+obj2);
        //obj2.Action__c = 'Overwrite';
        obj2.QuickLook_ID__c='ab123456';
        obj2.Role_User_Name__c = u.id;
        update obj2;
        system.assertEquals(obj2.QuickLook_ID__c,'ab123456');
        Test.stopTest();
         
    }
    @isTest
    static void Test11(){
        Test.startTest();
        User Usr = [Select Id from User Where Name = 'iPaas Administrator'];
        System.runAs(Usr){               
            Account acc =[Select id,Master_Customer_Number__c from Account where Master_Customer_Number__c like '%acctest%'];
            
            ASM_Role_Hierarchy__c obj1 = new ASM_Role_Hierarchy__c(Master__c = acc.Master_Customer_Number__c, QuickLook_ID__c='ac123456',Role_Name__c = 'Customer Advocate');
            database.Insert( obj1,false);
            system.assertEquals(obj1.Master__c,acc.Master_Customer_Number__c);
        }         
        Test.stopTest();
    }
}