force-app/main/default/objects/Account/fields/Backlog_Orders_Closed_amount__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Orders_Closed_amount__c</fullName>
    <label>Backlog Orders Closed amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Backlog_Orders_Open_amount__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Orders_Open_amount__c</fullName>
    <label>Backlog Orders Open amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_with_Master_customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Country_with_Master_customer_Number__c</fullName>
    <description>In Account Country with master customer make a unique key which is used for data Migration from team Web</description>
    <externalId>true</externalId>
    <label>Country with Master customer Number</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Interface_Type__c.field-meta.xml
<CustomField>
    <fullName>Interface_Type__c</fullName>
    <label>Interface Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Batch</fullName>
                <default>true</default>
                <label>Batch</label>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Real-Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>NCR Rev Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Other Direct</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EDBI_Order__c/EDBI_Order__c.object-meta.xml
<CustomObject>
    <description>This object is used to sync all orders data from EDBI to NSC.</description>
    <label>EDBI Order</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EDBI Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EDBI_Order__c/fields/Backlog_Orders_Amount__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Orders_Amount__c</fullName>
    <label>Backlog Orders Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EDBI_Order__c/fields/Backlog_Orders_Status__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Orders_Status__c</fullName>
    <label>Backlog Orders Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDBI_Order__c/fields/Country_Code_With_Master_Customer_Nbr__c.field-meta.xml
<CustomField>
    <fullName>Country_Code_With_Master_Customer_Nbr__c</fullName>
    <externalId>true</externalId>
    <label>Country Code With Master Customer Nbr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDBI_Order__c/fields/Customer_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Country_Code__c</fullName>
    <label>Customer Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDBI_Order__c/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDBI_Order__c/fields/Max_Customer_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Max_Customer_Requested_Date__c</fullName>
    <label>Max Customer Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EDBI_Order__c/fields/Max_Promise_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Max_Promise_DateTime__c</fullName>
    <label>Max Promise DateTime</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EDBI_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/ERP_Orders_Backlog__c.object-meta.xml
<CustomObject>
    <label>ERP Orders</label>
    <nameField>
        <displayFormat>EOB-{00000000}</displayFormat>
        <label>ERP Orders Backlog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/Amount_in_USD__c.field-meta.xml
<CustomField>
    <fullName>Amount_in_USD__c</fullName>
    <label>Amount in USD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <label>Master Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/Order_Status_Ind__c.field-meta.xml
<CustomField>
    <fullName>Order_Status_Ind__c</fullName>
    <externalId>true</externalId>
    <label>Order Status Ind</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/OrderNumber_Country_code__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber_Country_code__c</fullName>
    <externalId>true</externalId>
    <label>OrderNumber Country code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <externalId>true</externalId>
    <label>Product ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesOrdersBacklogBatchTest.cls
@isTest(SeeAllData=false)
public class SalesOrdersBacklogBatchTest {
    @isTest
    public static void testBatch(){
        /*EDBI_Order__c edbiOrder = new EDBI_Order__c();
        edbiOrder.Order_Number__c='100';
        edbiOrder.Backlog_Orders_Amount__c=100.00;
        edbiOrder.Backlog_Orders_Status__c='BOOKED'; 
        edbiOrder.Master_Customer_Number__c='Test001';
        edbiOrder.Max_Promise_DateTime__c=Date.valueOf('2019-10-20');
        edbiOrder.Max_Customer_Requested_Date__c=Date.valueOf('2019-10-20');
        edbiOrder.Customer_Country_Code__c = 'US' ;
        edbiOrder.Country_Code_With_Master_Customer_Nbr__c='UDIV001';
        insert edbiOrder;
        
        
        EDBI_Order__c edbiOrder1 = new EDBI_Order__c();
        edbiOrder1.Order_Number__c='101';
        edbiOrder1.Backlog_Orders_Amount__c=100.00;
        edbiOrder1.Backlog_Orders_Status__c='CLOSED'; 
        edbiOrder1.Master_Customer_Number__c='Test001';
        edbiOrder1.Max_Promise_DateTime__c=Date.valueOf('2019-10-20');
        edbiOrder1.Max_Customer_Requested_Date__c=Date.valueOf('2019-10-20');
        edbiOrder1.Customer_Country_Code__c = 'US' ;
        edbiOrder1.Country_Code_With_Master_Customer_Nbr__c='UDIV001';
        insert edbiOrder1;*/
           
         EDBI_Order__c edbiOrder = new EDBI_Order__c();
        edbiOrder.Order_Number__c='100';
        edbiOrder.Backlog_Orders_Amount__c=100.00;
        edbiOrder.Backlog_Orders_Status__c='BOOKED'; 
        edbiOrder.Master_Customer_Number__c='Test001';
        edbiOrder.Max_Promise_DateTime__c=Date.valueOf('2019-10-20');
        edbiOrder.Max_Customer_Requested_Date__c=Date.valueOf('2019-10-20');
        edbiOrder.Customer_Country_Code__c = 'US' ;
        edbiOrder.Country_Code_With_Master_Customer_Nbr__c='UDIV001';
        insert edbiOrder;
        
        
         EDBI_Order__c edbiOrder1 = new EDBI_Order__c();
        edbiOrder1.Order_Number__c='101';
        edbiOrder1.Backlog_Orders_Amount__c=100.00;
        edbiOrder1.Backlog_Orders_Status__c='CLOSED'; 
        edbiOrder1.Master_Customer_Number__c='Test001';
        edbiOrder1.Max_Promise_DateTime__c=Date.valueOf('2019-10-20');
        edbiOrder1.Max_Customer_Requested_Date__c=Date.valueOf('2019-10-20');
        edbiOrder1.Customer_Country_Code__c = 'US' ;
        edbiOrder1.Country_Code_With_Master_Customer_Nbr__c='UDIV001';
        insert edbiOrder1;
        
       ERP_Orders_Backlog__c erpBacklog = new ERP_Orders_Backlog__c();
        erpBacklog.Amount_in_USD__c='100';
        erpBacklog.Country_Code_With_Master_Customer_Nbr__c='USTest001';
        erpBacklog.Order_Number__c='101';
        erpBacklog.Product_ID__c='1XY';
        erpBacklog.Order_Number__c = '101' ;
        erpBacklog.Order_Status_Ind__c='CLOSED'; 
        erpBacklog.OrderNumber_Country_code__c = '101US' ;
        erpBacklog.Country_Code__c = 'US' ;
        insert erpBacklog;
        
        ERP_Orders_Backlog__c erpBacklog1 = new ERP_Orders_Backlog__c();
        erpBacklog1.Amount_in_USD__c='100';
        erpBacklog1.Country_Code_With_Master_Customer_Nbr__c='USTest001';
        erpBacklog1.Order_Number__c='100';
        erpBacklog1.Product_ID__c='1XY';
        erpBacklog1.Order_Number__c = '100' ;
        erpBacklog1.Order_Status_Ind__c='BOOKED';
        erpBacklog1.OrderNumber_Country_code__c = '100US' ;
        erpBacklog1.Country_Code__c = 'US' ;
        insert erpBacklog1;
        
      /*  Account a = new Account(); 
        a.Name = 'Dummy Account'; 
        a.AccountNumber = '1234';
        a.BillingStreet = '5601 N Lindero Canyon Rd';
        a.BillingCity = 'Westlake Village';
        a.BillingState = 'CA';
        a.BillingPostalCode = '91362';
        a.ShippingStreet = a.BillingStreet; 
        a.ShippingCity = a.BillingCity;
        a.ShippingState = a.BillingState;
        a.ShippingPostalCode = a.BillingPostalCode;
        a.Phone = '818-867-5309';
        a.Fax = '818-597-6310';
        a.Master_Customer_Number__c = '1234'; 
        a.Tier__c = '1';
        a.Interface_Type__c = 'Batch'; 
        a.Backlog_Orders_Closed_amount__c=100.00;
        a.Backlog_Orders_Open_amount__c=100.00;
        a.Country_with_Master_customer_Number__c='UDIV001';
        System.runAs(TestRecordsFactory.getUser()){
            insert a;
        }*/
        Account a = new Account(); 
        a.Name = 'Dummy Account'; 
        a.AccountNumber = '1234';
        a.BillingStreet = '5601 N Lindero Canyon Rd';
        a.BillingCity = 'Westlake Village';
        a.BillingState = 'CA';
        a.BillingPostalCode = '91362';
        a.ShippingStreet = a.BillingStreet; 
        a.ShippingCity = a.BillingCity;
        a.ShippingState = a.BillingState;
        a.ShippingPostalCode = a.BillingPostalCode;
        a.Phone = '818-867-5309';
        a.Fax = '818-597-6310';
        a.Master_Customer_Number__c = 'Test001'; 
          a.Tier__c = '1';
        a.Backlog_Orders_Closed_amount__c=100.00;
        a.Backlog_Orders_Open_amount__c=100.00;
        a.Country_with_Master_customer_Number__c='USTest001';
        System.runAs(TestRecordsFactory.getUser()){
            insert a;
        }
        
        
        test.startTest();
        SalesOrdersBacklogBatch salesBackUp = new SalesOrdersBacklogBatch(new Set<String>{'USTest001'});   
        ID batchprocessid = Database.executeBatch(salesBackUp);
        System.assert(batchprocessid!=null);
        test.stopTest();
    }
}