force-app/main/default/objects/Account/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CDM_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>CDM_Account_Type__c</fullName>
    <description>This field has been created under CDM project and values for this field will be coming from CDM via SOUP.</description>
    <label>Account Type</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deliver_To__c.field-meta.xml
<CustomField>
    <fullName>Deliver_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deliver-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Bill_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Bill-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Deliver_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Deliver_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Deliver-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Ship_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Ship-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ship-To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site record type is used to represent Sites/Locations related to an Account.</description>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Order/fields/Deliver_To_Site__c.field-meta.xml
<CustomField>
    <fullName>Deliver_To_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Twinned from Quote</description>
    <label>Deliver To Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Deliver To Site)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/qtc_Bill_To_Site__c.field-meta.xml
<CustomField>
    <fullName>qtc_Bill_To_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Twinned from quote</description>
    <label>Bill To Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Bill To Site)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/qtc_Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>qtc_Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>twin from quote</description>
    <label>Ship To Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QuoteExtControllerTests.cls
@isTest
private class QuoteExtControllerTests {
    private static Id ACCOUNT_SITE_RECORDTYPEID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get( 'Site' ).getRecordTypeId();
    
    testMethod static void testSubmit() {
        
        Profile adminProfile = [SELECT id from Profile WHERE Name = '04 NSC UI Administrator' Limit 1];
                
        User testUser = new User(alias = 'standt', email='standarduser11@ncr.com',
                    emailencodingkey='UTF-8', lastname='Testing3',Quicklook_Id__c='ValProfl', languagelocalekey='en_US',
                    localesidkey='en_US', profileid = adminProfile.Id,timezonesidkey='America/Los_Angeles',
                    username='standarduser1@.ncr.com'+System.now().getTime()+'.com');
        insert testUser;
        
        Group testGroup = new Group(Name = 'Account Admin');
        insert testGroup;
        
        GroupMember testMember = new GroupMember(GroupId = testGroup.Id, UserOrGroupId = testUser.Id);
        insert testMember;
                    
       System.runAs(testUser){
           
            Account parentAccount = new Account(Name='Parent Account');
            insert parentAccount;
            
            Account testAccount = new Account(
                RecordTypeId = ACCOUNT_SITE_RECORDTYPEID,
                Name='Test Company Name123',
                Primary_Bill_To__c = true,
                Bill_To__c = true,
                Ship_To__c = true, 
                Primary_Ship_To__c = true,
                Deliver_To__c = true, 
                Primary_Deliver_To__c = true,
                ParentId = parentAccount.Id,
                CDM_Account_Type__c = 'Site');
            insert testAccount;
       
            SBQQ__Quote__c quote = new SBQQ__Quote__c(
                SBQQ__Type__c='Quote', 
                SBQQ__Status__c= 'Draft',
                ApprovalStatus__c = 'Pending',
                qtc_Bill_To_Site__c =testAccount.Id,
                Deliver_To_Site__c =testAccount.Id,
                qtc_Ship_To_Account__c =testAccount.Id,
                SBQQ__Account__c = parentAccount.Id
            );
            insert quote;
        }
        SBQQ__Quote__c testQuote = [SELECT Id,ApprovalStatus__c,SBQQ__Status__c  FROM SBQQ__Quote__c LIMIT 1];
        Test.startTest();
        QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(testQuote));
        con.onSubmit();
        SBQQ__Quote__c resultQuote = [SELECT ApprovalStatus__c,SBQQ__Status__c FROM SBQQ__Quote__c WHERE Id = :testQuote.Id LIMIT 1];
        System.assert(resultQuote.id!=null);
        Test.stopTest();
        
        
    }
    
    testMethod static void testErrorSubmit() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        insert quote;
        System.assert(quote.id!=null);
        Test.startTest();
        QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(quote));
        
        // Delete the quote in order to throw an error
        delete quote;
        
        con.onSubmit();
        
        Test.stopTest();
        
        con.onCancel();
    }
    
    testMethod static void testRecall() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        insert quote;
        
        Test.startTest();
        QuoteExtController.recallApproval(quote.Id);
        QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(quote));
        con.onRecall();
        quote = [SELECT ApprovalStatus__c FROM SBQQ__Quote__c WHERE Id = :quote.Id LIMIT 1];
        System.assert(quote.id!=null);
        Test.stopTest();
        
        
    }
    
    testMethod static void testErrorRecall() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        insert quote;
        System.assert(quote.id!=null);
        Test.startTest();
        QuoteExtController con = new QuoteExtController(new ApexPages.StandardController(quote));
        
        // Delete the quote in order to throw an error
        delete quote;
        
        con.onRecall();
        Test.stopTest();
              
        con.onCancel();
    }
}