force-app/main/default/objects/Account/fields/CardtronicsId__c.field-meta.xml
<CustomField>
    <fullName>CardtronicsId__c</fullName>
    <description>CATM</description>
    <externalId>true</externalId>
    <label>CardtronicsId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Automation_Setting__c/Automation_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting delivered as part of the Hospitality Service Cloud rollout enabling to toggle Service Cloud automation on/off. These flags of this custom setting will be utilized in Salesforce automation to turn logic on/off either globally, for specific profiles, or specific users.</description>
    <label>Automation Setting</label>
</CustomObject>

force-app/main/default/objects/Automation_Setting__c/fields/Skip_Flow__c.field-meta.xml
<CustomField>
    <fullName>Skip_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if checked will not execute Flows</description>
    <label>Skip Flow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Automation_Setting__c/fields/Skip_Outbound_Integration__c.field-meta.xml
<CustomField>
    <fullName>Skip_Outbound_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if checked will not do outbound calls</description>
    <label>Skip Outbound Integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Automation_Setting__c/fields/Skip_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Skip_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if checked will not execute any Triggers</description>
    <label>Skip Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Automation_Setting__c/fields/Skip_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Skip_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if checked will not execute Validation Rules</description>
    <label>Skip Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Contact__c.field-meta.xml
<CustomField>
    <fullName>Active_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field that ,when checked, indicates that the Contact is active</description>
    <label>Active Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CardtronicsId__c.field-meta.xml
<CustomField>
    <fullName>CardtronicsId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>CATM</description>
    <externalId>true</externalId>
    <label>CardtronicsId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>Lead Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CATM</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>CATM</description>
    <label>Products</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CardtronicsId__c.field-meta.xml
<CustomField>
    <fullName>CardtronicsId__c</fullName>
    <description>CATM</description>
    <externalId>true</externalId>
    <label>CardtronicsId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Marketing_Notes__c.field-meta.xml
<CustomField>
    <fullName>Lead_Marketing_Notes__c</fullName>
    <label>Lead - Marketing Notes</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>Partner List Import</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AIRLINES</fullName>
                <label>Airlines</label>
            </value>
            <value>
                <fullName>AIRPORTS</fullName>
                <label>Airports</label>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>ATM Deployers</fullName>
            </value>
            <value>
                <fullName>Central Banks, National Institutions &amp; Clearing Houses</fullName>
            </value>
            <value>
                <fullName>Processors, Acquirers &amp; Merchant Gateways</fullName>
            </value>
            <value>
                <fullName>Networks</fullName>
            </value>
            <value>
                <fullName>Cash in Transit</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>Cinema &amp; Theatres</fullName>
            </value>
            <value>
                <fullName>Stadium &amp; Venues</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
            </value>
            <value>
                <fullName>Mass Merchants</fullName>
            </value>
            <value>
                <fullName>Drug Stores</fullName>
            </value>
            <value>
                <fullName>Grocery</fullName>
            </value>
            <value>
                <fullName>Food, Drug, Mass Merchant (FDMM)</fullName>
            </value>
            <value>
                <fullName>Convenience Fuel Retail (CFR)</fullName>
            </value>
            <value>
                <fullName>Wholesale/Supercenters</fullName>
            </value>
            <value>
                <fullName>Department &amp; Specialty Retail (DSR)</fullName>
            </value>
            <value>
                <fullName>Petroleum Convenience Retail (PCR)</fullName>
            </value>
            <value>
                <fullName>Wholesale Distribution</fullName>
            </value>
            <value>
                <fullName>Telecom Providers</fullName>
            </value>
            <value>
                <fullName>Technology Providers</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Digital Banking</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Branch Transformation</fullName>
            </value>
            <value>
                <fullName>Transaction &amp; Channel Platforms</fullName>
            </value>
            <value>
                <fullName>ATMs &amp; Self-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Marketing_Notes__c.field-meta.xml
<CustomField>
    <fullName>Lead_Marketing_Notes__c</fullName>
    <label>Lead Marketing Notes</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>CATM</description>
    <label>Product Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>CATM</description>
    <inlineHelpText>Concatenates the unique products added to the opportunity.</inlineHelpText>
    <label>Cardtronics Product List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SW_Unattached_Code__c.field-meta.xml
<CustomField>
    <fullName>SW_Unattached_Code__c</fullName>
    <label>SW Unattached Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Pmdm_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Pmdm_Product_Family__c</fullName>
    <label>Pmdm Product Family</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Professional Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CardtronicsId__c.field-meta.xml
<CustomField>
    <fullName>CardtronicsId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>CardtronicsId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TempTrigger_Tests.cls
@isTest
private class TempTrigger_Tests {

    @TestSetup
    static void makeUser(){
        User Usr = [Select Id from User Where Name = 'Soup User'];
        Id psid = [Select Id from PermissionSet Where Name='ETL_PreventOverwrite'].Id;
        insert new PermissionSetAssignment(AssigneeId=Usr.Id, PermissionSetId=psid);
    }

    @isTest
    static void leadTest(){
        User Usr = [Select Id from User Where Name = 'Soup User'];
        insert new Automation_Setting__c(SetupOwnerId=Usr.Id, Skip_Flow__c=true,
            Skip_Outbound_Integration__c=true,Skip_Trigger__c=true,Skip_Validation_Rule__c=true);
        Lead l;
        Test.startTest();
        System.runAs(Usr){
            l = new Lead(FirstName='Test',LastName='Lead',Company='Testco');
            l.Phone='14444444';
            l.MobilePhone='14444444';
            l.Fax='14444444';
            l.Email='1test@email.com';
            l.Street='123 test';
            l.City='Atl';
            l.State='GA';
            l.PostalCode='30339';
            l.salutation='Mr';
            l.Title='CEO';
            l.website='http://www.ncr.com';
            l.Lead_Marketing_Notes__c='test';
            l.CardtronicsId__c='00000222313fakeid';
            l.LeadSource='Website';
            l.SubIndustry__c='Financial Institutions';
            l.Leadtype__c='Web';
            l.Lead_Marketing_Notes__c ='orig note';
            insert l;
            l.FirstName='Test2';
            l.Phone='4444444';
            l.MobilePhone='4444444';
            l.Fax='4444444';
            l.Email='test@email.com';
            l.Street='123 test st';
            l.Lead_Marketing_Notes__c='new note';
            update l;
            l.FirstName='Test3';
            update l;
        }
        Test.stopTest();
        Lead ld  = [Select Id, Lead_Marketing_Notes__c from Lead where Id = :l.Id];
        System.assertEquals('orig note\nnew note', ld.Lead_Marketing_Notes__c);
    }

    @isTest
    static void accountTest(){
        User Usr = [Select Id from User Where Name = 'Soup User'];
        insert new Automation_Setting__c(SetupOwnerId=Usr.Id, Skip_Flow__c=true,
            Skip_Outbound_Integration__c=true,Skip_Trigger__c=true,Skip_Validation_Rule__c=true);
        Opportunity o;
        Contract ct;
        Test.startTest();
        System.runAs(Usr){
            Account a = new Account(Name='Test Account');
            a.accountnumber='1';
            a.annualrevenue=100;
            a.billingcity='Atl';
            a.billingstate='GA';
            a.billingstreet='123 main';
            a.billingcountry='US';
            a.description='test';
            a.Fax='14444444';
            a.Phone='14444444';
            a.shippingcity='Atl';
            a.shippingstate='GA';
            a.shippingstreet='123 main';
            a.shippingcountry='US';
            a.tickersymbol='ABC';
            a.website='http://www.ncr.com';
            a.sic='1234';
            a.sicdesc='test';
            insert a;
            Contact c = new Contact(FirstName='Test',LastName='Contact');
            c.Phone='14444444';
            c.HomePhone='14444444';
            c.MobilePhone='14444444';
            c.Fax='14444444';
            c.Department='1Test';
            c.Email='1test@email.com';
            c.Active_Contact__c=true;
            c.assistantname='test';
            c.assistantphone='444444';
            c.description='test';
            c.MailingStreet='123 test';
            c.MailingCity='Atl';
            c.MailingState='GA';
            c.MailingPostalCode='30339';
            c.salutation='Mr';
            c.CardtronicsId__c='00000222314fakeid';
            c.accountid=a.id;
            insert c;
            a.Name='Test Account2';
            a.billingstreet='123 main st';
            a.shippingstreet='123 main st';
            update a;
            c.FirstName='Test2';
            c.Phone='4444444';
            c.HomePhone='4444444';
            c.MobilePhone='4444444';
            c.Fax='4444444';
            c.Department='Test';
            c.Email='test@email.com';
            c.MailingStreet='123 test dr';
            update c;
            o = new Opportunity(AccountId=a.id,ContactId=c.Id,Name='test',CloseDate=Date.parse('01/01/2025'),StageName='Prospecting');
            insert o;

            List<Product2> prodList = new List<Product2>();
            for(Integer i=0;i<2;i++) {
                Product2 p = new Product2();
                p.Name = 'Test Product Test Product'+i;
                p.pmdm_product_family__c ='Hardware like a GPU' +i;
                prodList.add(p);
            }
            insert prodList;
            
            List<PricebookEntry> peList = new List<PricebookEntry>();
            for(Product2 pr: prodList) {
                PricebookEntry pe = new PricebookEntry();
                pe = TestRecordsFactory.createPriceBookEntry(pr);
                peList.add(pe);
            }
            
            List<OpportunityLineItem> oliList1 = new List<OpportunityLineItem>();
            for(PricebookEntry pe: [select id, product2.product_category__c from PricebookEntry where pricebook2Id =: GlobalVariable.pricebookId]) {
                OpportunityLineItem oli = new OpportunityLineItem();
                oli.opportunityId = o.Id;
                oli.PriceBookEntryId= pe.Id;
                oli.Quantity=10;
                oli.TotalPrice=1000;
                oli.SW_Unattached_Code__c='Attached';
                oliList1.add(oli);                  
            }
            insert oliList1; // this will cause the OpportunityUpdateTempTrigger to run 
            ct = new Contract(AccountID = a.Id, Opportunity__c=o.Id, Status = 'Draft');
            insert ct;
        }
        Test.stopTest();
        Contract ctr  = [Select Id, Products__c from Contract where Id = :ct.Id];
        System.assertEquals('Test Product Test Product0, Test Product Test Product1', ctr.Products__c);
    }

    // @isTest
    // static void bulkTest(){
    //     User Usr = [Select Id from User Where Name = 'Soup User'];
    //     insert new Automation_Setting__c(SetupOwnerId=Usr.Id, Skip_Flow__c=true,
    //         Skip_Outbound_Integration__c=true,Skip_Trigger__c=true,Skip_Validation_Rule__c=true);
    //     Test.startTest();
    //     System.runAs(Usr){
    //         Account a = new Account(Name='Test Account');
    //         a.accountnumber='1';
    //         a.annualrevenue=100;
    //         a.billingcity='Atl';
    //         a.billingstate='GA';
    //         a.billingstreet='123 main';
    //         a.billingcountry='US';
    //         a.description='test';
    //         a.Fax='14444444';
    //         a.Phone='14444444';
    //         a.shippingcity='Atl';
    //         a.shippingstate='GA';
    //         a.shippingstreet='123 main';
    //         a.shippingcountry='US';
    //         a.tickersymbol='ABC';
    //         a.website='http://www.ncr.com';
    //         a.sic='1234';
    //         a.sicdesc='test';
    //         insert a;
    //         Contact c = new Contact(FirstName='Test',LastName='Contact');
    //         c.Phone='14444444';
    //         c.HomePhone='14444444';
    //         c.MobilePhone='14444444';
    //         c.Fax='14444444';
    //         c.Department='1Test';
    //         c.Email='1test@email.com';
    //         c.Active_Contact__c=true;
    //         c.assistantname='test';
    //         c.assistantphone='444444';
    //         c.description='test';
    //         c.MailingStreet='123 test';
    //         c.MailingCity='Atl';
    //         c.MailingState='GA';
    //         c.MailingPostalCode='30339';
    //         c.salutation='Mr';
    //         c.CardtronicsId__c='00000222314fakeid';
    //         c.accountid=a.id;
    //         insert c;
    //         List<Opportunity> opps = new List<Opportunity>();
    //         for(Integer i=0;i<200;i++){
    //             opps.add(new Opportunity(AccountId=a.id,ContactId=c.Id,Name='test'+i,CloseDate=Date.parse('01/01/2025'),StageName='Prospecting'));
    //         }
    //         insert opps;

    //         List<Product2> prodList = new List<Product2>();
    //         for(Integer i=0;i<2;i++) {
    //             Product2 p = new Product2();
    //             p.Name = 'Test Product Test Product'+i;
    //             p.pmdm_product_family__c ='Hardware like a GPU' +i;
    //             prodList.add(p);
    //         }
    //         insert prodList;
            
    //         List<PricebookEntry> peList = new List<PricebookEntry>();
    //         for(Product2 pr: prodList) {
    //             PricebookEntry pe = new PricebookEntry();
    //             pe = TestRecordsFactory.createPriceBookEntry(pr);
    //             peList.add(pe);
    //         }
            
    //         List<OpportunityLineItem> oliList1 = new List<OpportunityLineItem>();
    //         for (Opportunity o:opps){
    //             for(PricebookEntry pe: [select id, product2.product_category__c from PricebookEntry where pricebook2Id =: GlobalVariable.pricebookId]) {
    //                 OpportunityLineItem oli = new OpportunityLineItem();
    //                 oli.opportunityId = o.Id;
    //                 oli.PriceBookEntryId= pe.Id;
    //                 oli.Quantity=10;
    //                 oli.TotalPrice=1000;
    //                 oli.SW_Unattached_Code__c='Attached';
    //                 oliList1.add(oli);                  
    //             }
    //         }
    //         insert oliList1; // this will cause the OpportunityUpdateTempTrigger to run 
    //     }
    //     Test.stopTest();
    // }

}