force-app/main/default/objects/Account/fields/CATM_Region__c.field-meta.xml
<CustomField>
    <fullName>CATM_Region__c</fullName>
    <description>CATM</description>
    <label>Region</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Theater</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CATM_Record__c.field-meta.xml
<CustomField>
    <fullName>CATM_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CATM Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CPQ__c.field-meta.xml
<CustomField>
    <fullName>CPQ__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CPQ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Owner_Expiration_Notice_Date__c.field-meta.xml
<CustomField>
    <fullName>Owner_Expiration_Notice_Date__c</fullName>
    <description>CATM</description>
    <label>Last Day of Owner Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>CATM</description>
    <formula>Opportunity__r.Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CATM Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewal_Period_Months__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Period_Months__c</fullName>
    <description>CATM</description>
    <label>Renewal Period (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <description>CATM</description>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automatic Extension</fullName>
            </value>
            <value>
                <fullName>Fixed End Date</fullName>
            </value>
            <value>
                <fullName>Option to Extend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CATM_Region__c.field-meta.xml
<CustomField>
    <fullName>CATM_Region__c</fullName>
    <description>CATM</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LOB__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>CLA/BRAZIL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
            <value>
                <fullName>NAPAC</fullName>
            </value>
            <value>
                <fullName>SAPAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>IBG</fullName>
    </customValue>
    <customValue>
        <fullName>NABG</fullName>
    </customValue>
    <description>CATM</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractExpireUpdateCls_Test.cls
@isTest
public class ContractExpireUpdateCls_Test {
    
    @isTest
    public static void testdata(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Data Backup and Recovery Admin' Limit 1]; 
        User u = new User(Alias = 'standt', Email='standarduser@testorvjkhbvjhgejghwefg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          Quicklook_ID__c = '293103',
                          TimeZoneSidKey='America/New_York', UserName='standarduser@testorvjkhbvjhgejghwefg.com');
        insert u;
        
        
        
        System.runAs(u){
            List<Account> lstAccount = new List<Account>();
            for(Integer i=0; i<2; i++)
            {
                account acc = new Account();
                acc.BillingCity ='test';
                acc.Name = 'testing';
                acc.CATM_Region__c = 'NABG';
                lstAccount.add(acc);
            }
            insert lstAccount;
            
            List<Contract> lstContract = new List<Contract>();
            List<Contract> updContracts = new List<Contract>();
            for(Account acc:lstAccount)
            {
                Contract con =new Contract();
                //con.Status = 'Activated';
                con.AccountId = acc.Id;
                con.CATM_Record__c = true;
                con.Renewal_Type__c = 'Automatic Extension';
                //con.RecordTypeId= recordTypeId;
                con.Owner_Expiration_Notice_Date__c = system.Today();
                con.EndDate = system.Today();
                con.CPQ__c = FALSE;
                //con.Account.region__c ='NABG';
                lstContract.add(con);
            }
            
            insert lstContract;
            for(Contract con: lstContract){
                //con.RecordTypeId= recordTypeId;
                con.EndDate = system.today() + 30;
                con.Renewal_Period_Months__c = 1;
                
                con.Status = 'Activated';
                updContracts.add(con);
            }
            
            update updContracts;
            
            Test.startTest();
            
            //Database.executeBatch(new ContractExpireUpdateBatch());        
            ContractExpireUpdateCls sch = new ContractExpireUpdateCls();
            String cron = '0 0 6 1/1 * ? *';
            id job = System.schedule('UpdateContractEnddate' , cron, sch);
            
            ContractExpireUpdateBatch cb = New ContractExpireUpdateBatch();
            
            Database.QueryLocator ql = cb.start(null);
            cb.execute(null, updContracts);
            cb.Finish(null);
            
            Test.stopTest();
        }
    }
}