force-app/main/default/objects/Account/fields/cdm_Store_Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>cdm_Store_Branch_Number__c</fullName>
    <description>This field is only applicable for site record types and represent store number of particular site.</description>
    <label>Store/Branch Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <externalId>true</externalId>
    <label>Site Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site record type is used to represent Sites/Locations related to an Account.</description>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/JP_EndPoint__c/JP_EndPoint__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>JP EndPoint</label>
</CustomObject>

force-app/main/default/objects/JP_EndPoint__c/fields/EndPoint_URL__c.field-meta.xml
<CustomField>
    <fullName>EndPoint_URL__c</fullName>
    <label>EndPoint URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/NCR_Payments_Site__c/NCR_Payments_Site__c.object-meta.xml
<CustomObject>
    <label>NCR Payments Site</label>
    <nameField>
        <displayFormat>NCRPS-{000000}</displayFormat>
        <label>NCR Payments Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCR Payments  Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCR_Payments_Site__c/fields/Account_Sites__c.field-meta.xml
<CustomField>
    <fullName>Account_Sites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Sites</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3 AND 4) OR 5</booleanFilter>
        <errorMessage>Site needs to be a deliver to child site of the quote&apos;s account</errorMessage>
        <filterItems>
            <field>Account.Deliver_To__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Primary_Deliver_To__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.qtc_Account_Site_Parent__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.qtc_Multi_Site__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NCR Payments Sites</relationshipLabel>
    <relationshipName>NCR_Payments_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCR_Payments_Site__c/fields/InfiniceptApplicationId__c.field-meta.xml
<CustomField>
    <fullName>InfiniceptApplicationId__c</fullName>
    <label>InfiniceptApplicationId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Payments_Site__c/fields/NCR_Payments_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>NCR_Payments_Application_Status__c</fullName>
    <label>NCR Payments Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approve</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Submission successful.</fullName>
            </value>
            <value>
                <fullName>NewPend</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>AcquirerReview</fullName>
            </value>
            <value>
                <fullName>ApprovedAndBoarded</fullName>
            </value>
            <value>
                <fullName>FollowUp</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>RePend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCR_Payments_Site__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>NCR Payments  Sites</relationshipLabel>
    <relationshipName>NCR_Payments_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NCR_Payments_Site__c/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <formula>Billing_Account__r.ERPSiteNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPQ_InfiniCeptCalloutHelper.cls
public with sharing class CPQ_InfiniCeptCalloutHelper {
    final static String REJECT = 'Reject',
                        WITHDRAWN = 'Withdrawn';
    
    public static List <CPQ_InfiniCeptCallouts.CustomFieldWrapper> getTemplate(String accessToken) {
        try{
            CPQ_InfiniCeptCallouts.TemplateWrapper templateFields = new CPQ_InfiniCeptCallouts.TemplateWrapper();
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            HttpResponse resp = null; 
     System.debug('CPQ_InfiniCeptCalloutHelper > getTemplate > ' + accessToken);
            string endpointURL = getEndPointURL('JPTemplate');           
                      
            req.setEndpoint(endpointURL);
            req.setHeader('Authorization', 'Bearer ' + accessToken);
            req.setHeader('payos-application-key', '123');
            req.setHeader('x-app-name', 'pos-payos');
            req.setTimeout(120000);
            req.setMethod('GET');
            resp = http.send(req);
            System.debug('CPQ_InfiniCeptCalloutHelper > getTemplate > API Response ' + resp.getBody());
            if (resp.getStatusCode() != 200) {
                throw new CPQ_InfiniCeptCallouts.TemplateException('Template Called failed to retrieve fields');
            } else {
                templateFields = (CPQ_InfiniCeptCallouts.TemplateWrapper) JSON.deserialize(resp.getBody(), CPQ_InfiniCeptCallouts.TemplateWrapper.class);
            }
            return templateFields.CustomFields;
        }catch(Exception e){System.debug('CPQ_InfiniCeptCalloutHelper > getTemplate > catch > ' + e.getMessage());
            throw new CPQ_InfiniCeptCallouts.TemplateException(e);
        }
    }

    public static String getAccessToken() {
        String accessToken;
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:JetPay'+System.label.PayOs_oauth_relative_URL);
        req.setMethod('POST');
        Http h = new Http();
        HttpResponse res = h.send(req);
        Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
        accessToken = (String)m.get('access_token');
        return accessToken;
    }
    
    public static String getAccessTokenUsingJPAuthService() {
        String accessToken;
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:JPAuthService');
        req.setMethod('POST');
        Http h = new Http();
        HttpResponse res = h.send(req);
        Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
        accessToken = (String)m.get('access_token');
        return accessToken;
    }
    

    public static String getEndPointURL(String serviceName) {
        JP_EndPoint__c endpoint = null;
        endpoint = JP_EndPoint__c.getValues(serviceName);
        if (endpoint != null) {
            return endpoint.EndPoint_URL__c;
        } else {
            return '';
        }      
    }


    public static List<NCR_Payments_Site__c> getPaymentSites(String qteId) {
        return [ 
                SELECT Id, Quote__c, InfiniceptApplicationId__c, Account_Sites__c, Account_Sites__r.Site_Number__c,
                       Account_Sites__r.Name
                FROM NCR_Payments_Site__c
                WHERE Quote__c =: qteId AND (InfiniceptApplicationId__c = null
                    OR NCR_Payments_Application_Status__c = ''
                    OR NCR_Payments_Application_Status__c =: REJECT 
                    OR  NCR_Payments_Application_Status__c =: WITHDRAWN)
        ];
    }

    public static List<Account> getDeliverSites(Set<String> actIds) {
        return [
                SELECT 
                    Id, Name, Site_Number__c, BillingStreet, BillingCity, BillingState,BillingCountry,
                    BillingPostalCode, cdm_Store_Branch_Number__c
                FROM Account
                WHERE Id IN : actIds
        ];
    }  
    
    public static boolean checkDuplicateSites( List<NCR_Payments_Site__c> MultiQuotePaymentSites) {
        Set<String> sites=new Set<String>();
        for(NCR_Payments_Site__c site : MultiQuotePaymentSites){
            if(!(sites.add(site.Account_Sites__r.Site_Number__c))) {
                return true;
            }
        }
        return false;   
    }

    public static String getPaymentsFeature(String quoteId) {
        String paymentFeatures;
        
        List<SBQQ__QuoteLine__c> quoteLineItems = [ 
                SELECT qtc_Payments_Features__c 
                FROM SBQQ__QuoteLine__c 
                WHERE SBQQ__Quote__c =: quoteId 
                    AND SBQQ__ProductCode__c in ('SP1000000417', 'SP373060217965','SP1000000104','SP1000000105') 
                    AND SBQQ__Quantity__c = 1 LIMIT 1];
        
        if (! quoteLineItems.isEmpty()) {
            paymentFeatures = quoteLineItems[0].qtc_Payments_Features__c;
        }     
        return paymentFeatures;
    } 

}