force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Party Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Exception__c/Account_Exception__c.object-meta.xml
<CustomObject>
    <label>Customer Exception</label>
    <nameField>
        <displayFormat>AE -{000}</displayFormat>
        <label>Exception #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Exception__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Additional_Supporting_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Supporting_Information__c</fullName>
    <label>Additional Supporting Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Any_Current_Contract__c.field-meta.xml
<CustomField>
    <fullName>Any_Current_Contract__c</fullName>
    <inlineHelpText>Is there a current contract in place for services, solutions, SaaS?</inlineHelpText>
    <label>Any Current Contract</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_Comments__c</fullName>
    <label>Approver Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Channel_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Channel_Sales_Leader__c.field-meta.xml
<CustomField>
    <fullName>Channel_Sales_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Sales Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Exceptions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Channel_Sales_Leader_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Sales_Leader_Name__c</fullName>
    <formula>Channel_Sales_Leader__r.FirstName + &apos; &apos; + Channel_Sales_Leader__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel Sales Leader</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia*</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Current_Business_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Current_Business_Relationship__c</fullName>
    <inlineHelpText>Please describe the current business relationship between your company and End Customer entered above (NCR Named Account)?</inlineHelpText>
    <label>Current Business Relationship</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Current_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Current_Date_Time__c</fullName>
    <formula>NOW()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Customer</label>
    <referenceTo>Exception_Account__c</referenceTo>
    <relationshipName>Account_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Date_Of_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Expiration__c</fullName>
    <inlineHelpText>Mandatory if &quot;Any Current Contract&quot; is Yes</inlineHelpText>
    <label>Expiration Date(Mandatory if above:Yes)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Date_Of_Signing__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Signing__c</fullName>
    <inlineHelpText>Mandatory if &quot;Any Current Contract&quot; is Yes</inlineHelpText>
    <label>Signing Date(Mandatory if above:Yes)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Direct_Sales_Leader__c.field-meta.xml
<CustomField>
    <fullName>Direct_Sales_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direct Sales Leader</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Exceptions2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/End_Customer_MCN__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_MCN__c</fullName>
    <formula>Customer_Name__r.Master_Customer_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Customer MCN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/End_Customer_Region__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Region__c</fullName>
    <formula>Customer_Name__r.LOB__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Customer Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Expected_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Close_Date__c</fullName>
    <label>Expected Close Date/Expected Book Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/GDPR_Compliance_Policy__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Compliance_Policy__c</fullName>
    <defaultValue>&quot;www.ncr.com/privacy&quot;</defaultValue>
    <label>Our privacy policy is available at</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/How_long_has_this_existed__c.field-meta.xml
<CustomField>
    <fullName>How_long_has_this_existed__c</fullName>
    <label>How long has this existed?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/MCN__c.field-meta.xml
<CustomField>
    <fullName>MCN__c</fullName>
    <formula>Customer_Name__r.Master_Customer_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MCN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Name_the_Products_Provided__c.field-meta.xml
<CustomField>
    <fullName>Name_the_Products_Provided__c</fullName>
    <inlineHelpText>What are the products, solutions or services already provided by your company to this account or subsidiary?</inlineHelpText>
    <label>Name the Products Provided</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Opportunity_Value__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Value__c</fullName>
    <label>Opportunity Value/Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Other__c.field-meta.xml
<CustomField>
    <fullName>Other__c</fullName>
    <label>Other</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Partner_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Sales Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Account_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Postal_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Zip_Code__c</fullName>
    <label>Postal/Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Primary_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Competitor__c</fullName>
    <label>Primary Competitor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Primary_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Name__c</fullName>
    <label>End Customer Primary Contact</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Primary_Solution__c.field-meta.xml
<CustomField>
    <fullName>Primary_Solution__c</fullName>
    <label>Primary Solution/Offer Portfolio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Secondary_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Competitor__c</fullName>
    <label>Secondary Competitor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/Secondary_Solution__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Solution__c</fullName>
    <label>Secondary Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Exception__c/fields/State_Province_Region__c.field-meta.xml
<CustomField>
    <fullName>State_Province_Region__c</fullName>
    <label>State/Province/Region</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PRM_CustomerExceptionController.cls
public class PRM_CustomerExceptionController {
    
    @AuraEnabled
    public static List<Account_Exception__c> getCustomerException(String selectedView)
    {
        
        List<Account_Exception__c> lstCE;
        
        if(selectedView == 'All')
            lstCE =  [Select Id, Name, Account_Name__c, Additional_Supporting_Information__c, Any_Current_Contract__c, Approver_Comments__c, Channel_Account_Manager__r.Name, Channel_Sales_Leader__c,
                      Channel_Sales_Leader_Name__c, City__c, Country__c, Created_Date__c, Current_Business_Relationship__c, Current_Date_Time__c, Direct_Sales_Leader__c, Customer_Name__r.Name, End_Customer__c, End_Customer_MCN__c,
                      Primary_Contact_Name__c, End_Customer_Region__c, Expected_Close_Date__c, Expected_Start_Date__c, Date_Of_Expiration__c, How_long_has_this_existed__c, MCN__c, Name_the_Products_Provided__c, Opportunity_Value__c,
                      Other__c, GDPR_Compliance_Policy__c, Partner_Account_Name__r.Name, Partner_Contact__r.Name, Postal_Zip_Code__c, Primary_Competitor__c, Primary_Solution__c, Secondary_Competitor__c, Secondary_Solution__c, Date_Of_Signing__c,
                      State_Province_Region__c, Status__c, Street_Address__c, Submission_Approval_Date__c, Trigger_Time_05__c, What_are_your_own_value_added_products__c, Who_are_the_key_contacts__c
                      from Account_Exception__c order by CreatedDate ];
        else{
            String likeKey = '%' + selectedView + '%';
            lstCE =  [Select Id, Name, Account_Name__c, Additional_Supporting_Information__c, Any_Current_Contract__c, Approver_Comments__c, Channel_Account_Manager__r.Name, Channel_Sales_Leader__c,
                      Channel_Sales_Leader_Name__c, City__c, Country__c, Created_Date__c, Current_Business_Relationship__c, Current_Date_Time__c, Direct_Sales_Leader__c, Customer_Name__r.Name, End_Customer__c, End_Customer_MCN__c,
                      Primary_Contact_Name__c, End_Customer_Region__c, Expected_Close_Date__c, Expected_Start_Date__c, Date_Of_Expiration__c, How_long_has_this_existed__c, MCN__c, Name_the_Products_Provided__c, Opportunity_Value__c,
                      Other__c, GDPR_Compliance_Policy__c, Partner_Account_Name__r.Name, Partner_Contact__r.Name, Postal_Zip_Code__c, Primary_Competitor__c, Primary_Solution__c, Secondary_Competitor__c, Secondary_Solution__c, Date_Of_Signing__c,
                      State_Province_Region__c, Status__c, Street_Address__c, Submission_Approval_Date__c, Trigger_Time_05__c, What_are_your_own_value_added_products__c, Who_are_the_key_contacts__c
                      from Account_Exception__c where Status__c like :likeKey order by CreatedDate ];
        }
        return lstCE;
    }
    
    @AuraEnabled
    public static Account_Exception__c getCustomerExceptionDetail(String recId)
    {
        
        
        List<Account_Exception__c> lstCE;
        
        lstCE =  [Select Id, Name, Account_Name__c, Additional_Supporting_Information__c, Any_Current_Contract__c, Approver_Comments__c, Channel_Account_Manager__r.Name, Channel_Sales_Leader__c,
                  Channel_Sales_Leader_Name__c, City__c, Country__c, Created_Date__c, Current_Business_Relationship__c, Current_Date_Time__c, Direct_Sales_Leader__c, Customer_Name__r.Name, End_Customer__c, End_Customer_MCN__c,
                  Primary_Contact_Name__c, End_Customer_Region__c, Expected_Close_Date__c, Expected_Start_Date__c, Date_Of_Expiration__c, How_long_has_this_existed__c, MCN__c, Name_the_Products_Provided__c, Opportunity_Value__c,
                  Other__c, GDPR_Compliance_Policy__c, Partner_Account_Name__r.Name, Partner_Contact__r.Name, Postal_Zip_Code__c, Primary_Competitor__c, Primary_Solution__c, Secondary_Competitor__c, Secondary_Solution__c, Date_Of_Signing__c,
                  State_Province_Region__c, Status__c, Street_Address__c, Submission_Approval_Date__c, Trigger_Time_05__c, What_are_your_own_value_added_products__c, Who_are_the_key_contacts__c
                  from Account_Exception__c where Id =: recId ];
        
        if(!lstCE.isEmpty())
        {
            return lstCE[0];
        }
        
        return null;
    }
    
     @AuraEnabled
    public static List<Attachment> getCEAttachments(String recId)
    {
        return [Select Id, Name from Attachment where ParentId =: recId];
    }
    
    @AuraEnabled
    public static String saveCustomerException(Account_Exception__c objCE, String customerNameId)
    {
        objCE.Customer_Name__c = customerNameId;
        System.debug('-----------------objCE.Customer_Name__c----------------'+objCE.Customer_Name__c);
        System.debug('-----------------objCE----------------'+objCE);
        
        
        Account_Exception__c obj = new Account_Exception__c(Primary_Competitor__c = objCE.Primary_Competitor__c, 
                                                            Opportunity_Value__c = objCE.Opportunity_Value__c,
                                                            Customer_Name__c = objCE.Customer_Name__c, 
                                                            Primary_Contact_Name__c = objCE.Primary_Contact_Name__c, 
                                                            Primary_Solution__c = objCE.Primary_Solution__c, 
                                                            Expected_Close_Date__c = objCE.Expected_Close_Date__c,
                                                            Additional_Supporting_Information__c = objCE.Additional_Supporting_Information__c);
        insert obj;
        
        System.debug('--------------'+obj.Id);
        return obj.Id;
    }
    
    @AuraEnabled
    public static Account_Exception__c  getEditCustomerExceptionDetail(String recId)
    {
        List<Account_Exception__c> lstCE;
        
       /* lstCE =  [Select Id, Name, Customer_Name__cAccount_Name__c, Additional_Supporting_Information__c, Any_Current_Contract__c, Approver_Comments__c, Channel_Account_Manager__r.Name, Channel_Sales_Leader__c,
                  Channel_Sales_Leader_Name__c, City__c, Country__c, Created_Date__c, Current_Business_Relationship__c, Current_Date_Time__c, Direct_Sales_Leader__c, Customer_Name__r.Name, End_Customer__c, End_Customer_MCN__c,
                  Primary_Contact_Name__c, End_Customer_Region__c, Expected_Close_Date__c, Expected_Start_Date__c, Date_Of_Expiration__c, How_long_has_this_existed__c, MCN__c, Name_the_Products_Provided__c, Opportunity_Value__c,
                  Other__c, GDPR_Compliance_Policy__c, Partner_Account_Name__r.Name, Partner_Contact__r.Name, Postal_Zip_Code__c, Primary_Competitor__c, Primary_Solution__c, Secondary_Competitor__c, Secondary_Solution__c, Date_Of_Signing__c,
                  State_Province_Region__c, Status__c, Street_Address__c, Submission_Approval_Date__c, Trigger_Time_05__c, What_are_your_own_value_added_products__c, Who_are_the_key_contacts__c
                  from Account_Exception__c where Id =: recId ];
		*/
        lstCE =  [Select Id, Name, Primary_Competitor__c, Opportunity_Value__c, Customer_Name__c, Primary_Contact_Name__c, Primary_Solution__c, Expected_Close_Date__c, Additional_Supporting_Information__c,
                  Status__c, Customer_Name__r.Name
                  from Account_Exception__c where Id =: recId ];
        
        
        if(!lstCE.isEmpty())
        {
            return lstCE[0];
        }
        
        return null;
    }
    
  
    @AuraEnabled
    public static String saveEditedCustomerException(Account_Exception__c objCE, String customerNameId)
    {
        objCE.Customer_Name__c = customerNameId;
        System.debug('-----------------objCE.Customer_Name__c----------------'+objCE.Customer_Name__c);
        System.debug('-----------------objCE----------------'+objCE);
        
        
        Account_Exception__c obj = new Account_Exception__c(Id = objCE.Id, Primary_Competitor__c = objCE.Primary_Competitor__c, 
                                                            Opportunity_Value__c = objCE.Opportunity_Value__c,
                                                            Customer_Name__c = objCE.Customer_Name__c, 
                                                            Primary_Contact_Name__c = objCE.Primary_Contact_Name__c, 
                                                            Primary_Solution__c = objCE.Primary_Solution__c, 
                                                            Expected_Close_Date__c = objCE.Expected_Close_Date__c,
                                                            Additional_Supporting_Information__c = objCE.Additional_Supporting_Information__c);
        update obj;
        
        System.debug('--------------'+obj.Id);
        return obj.Id;
    }
    
    @AuraEnabled
    public static Id saveChunk(Id parentId, String fileName, String base64Data, String contentType, String fileId) 
    {      
        if (fileId == '') 
        {
            fileId = saveTheFile(parentId, fileName, base64Data, contentType);
        } 
        else {
            appendToFile(fileId, base64Data);
        }
 
        return Id.valueOf(fileId);
    }
 
    public static Id saveTheFile(Id parentId, String fileName, String base64Data, String contentType) 
    {
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
 
        Attachment oAttachment = new Attachment();
        oAttachment.parentId = parentId;
 
        oAttachment.Body = EncodingUtil.base64Decode(base64Data);
        oAttachment.Name = fileName;
        oAttachment.ContentType = contentType;
 
        insert oAttachment;
 
        return oAttachment.Id;
    }
 
    private static void appendToFile(Id fileId, String base64Data) 
    {
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
 
        Attachment a = [SELECT Id, Body FROM Attachment WHERE Id =: fileId];
 
        String existingBody = EncodingUtil.base64Encode(a.Body);
 
        a.Body = EncodingUtil.base64Decode(existingBody + base64Data);
 
        update a;
    }
    
    @AuraEnabled
    public static ProcessResult submitApprovalRequest(String recordId, String comment) 
    {
        List<Attachment> lstAttachment = [Select Id from Attachment where ParentId =: recordId];
        ProcessResult result ;
       
        
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest ();
            req.setComments(comment);
            req.setObjectId(Id.valueOf(recordId));
            
            try 
            {
                Approval.ProcessResult approvalResult = Approval.process(req);
                if(approvalResult.isSuccess()) 
                {
                    result = new ProcessResult('success','Record successfully submitted for Approval');
                } 
                else 
                {
                    result = new ProcessResult('error', String.valueOf(approvalResult.getErrors()));
                }
            }
            catch(Exception e) 
            {
                result =  new ProcessResult('error','Record cannot be submitted because of glitch in System. Contact IT support');
            }

       	return result;
    }
    
     public class ProcessResult {
        @AuraEnabled public String status = '';
        @AuraEnabled public String message = '';
        
        /*public processResult(){} commemted empty block */
        
        public processResult(String status, String message) {
            this.status = status;
            this.message = message;
        }
    }
    
    
}