force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Party Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attachment__c/Attachment__c.object-meta.xml
<CustomObject>
    <label>Attachment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/EULA_submission__c.object-meta.xml
<CustomObject>
    <label>EULA submissions</label>
    <nameField>
        <displayFormat>EULA-{0000}</displayFormat>
        <label>EULA submissions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EULA submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EULA_submission__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EULA_submission__c/fields/Date_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Agreement__c</fullName>
    <label>Date of Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/fields/End_Date_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>End_Date_of_Agreement__c</fullName>
    <label>End Date of Agreement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/fields/Solution_Name_or_Identifying_PID__c.field-meta.xml
<CustomField>
    <fullName>Solution_Name_or_Identifying_PID__c</fullName>
    <label>Solution Name or Identifying PID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EULA_submission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_EULASubmissionControllerTest.cls
@isTest
public class PRM_EULASubmissionControllerTest 
{
    static
    {
        createAcc();  
    }
    private static void createAcc(){
        List<Account> accounts = new List<Account>();
        accounts.add(new Account(Name = 'Unit Test Corp'));
        accounts.add(new Account(Name = 'Unit Test LLC'));
        accounts.add(new Account(Name = 'Parent Company Inc'));
        user u = [select id from user where name = 'Soup user'];
        System.runAs(u){
            insert accounts;}
    }
    
     private static void createContact(){
        Account acc = [SELECT Id FROM Account WHERE Name = 'Unit Test LLC' LIMIT 1];
        Contact con = new Contact(LastName ='testCon',AccountId = acC.Id);
        insert con;
    }  
    static testMethod void testPRM_EULASubmissionControllerTest() 
    {
        
        EULA_submission__c es = new EULA_submission__c();
        es.Customer_Name__c = 'ABC';
        es.Solution_Name_or_Identifying_PID__c ='XYZ';
        es.Country__c ='India';
        es.End_Date_of_Agreement__c = system.today();
        es.Address__c = 'Test';
        es.Date_of_Agreement__c = system.today();
        
       
        
        es.Status__c = 'Created';
        insert es;
        System.assertNotEquals(es,NULL,'EULA_submission__c should not be NULL');
        PRM_EULASubmissionController.getEULASubmission('All');
        PRM_EULASubmissionController.getEULASubmission('Created');
        update es;
        
        PRM_EULASubmissionController.getEULASubmissionDetail(es.Id);
        PRM_EULASubmissionController.getEditEULASubmissionDetail(es.Id);
        PRM_EULASubmissionController.saveEditedEULA(es);
        PRM_EULASubmissionController.getCBCAttachments(es.Id);
        
        EULA_submission__c objES = new EULA_submission__c();
        objES.Customer_Name__c = 'ABC';
        objES.Solution_Name_or_Identifying_PID__c ='XYZ';
        objES.Country__c ='India';
        objES.End_Date_of_Agreement__c = system.today();
        objES.Address__c = 'Test';
        objES.Date_of_Agreement__c = system.today();
        objES.Status__c = 'Created';
       
        PRM_EULASubmissionController.saveEULA(objES);
        
        
        
        PRM_EULASubmissionController.saveChunk(es.Id, 'Test', EncodingUtil.urlDecode('Testing', 'UTF-8'), 'txt', '');
        
        Attachment oAttachment = new Attachment();
        Blob b = Blob.valueOf('Test Data');
        oAttachment.parentId = es.Id;
        oAttachment.Name = 'Test Attachment for Parent';
        oAttachment.Body = b;
        insert oAttachment;
        PRM_EULASubmissionController.saveChunk(es.Id, 'Test', EncodingUtil.urlDecode('Testing', 'UTF-8'), 'txt', oAttachment.Id);
    }
    static testmethod void submitApprovalRequest()
    {
        Account acc = [SELECT Id FROM Account WHERE Name = 'Unit Test LLC' LIMIT 1];
        
        EULA_submission__c es = new EULA_submission__c();
        es.Customer_Name__c = 'ABC';
        es.Solution_Name_or_Identifying_PID__c ='XYZ';
        es.Country__c ='India';
        es.End_Date_of_Agreement__c = system.today();
        es.Address__c = 'Test';
        es.Date_of_Agreement__c = system.today();
        es.Status__c = 'Created';
        insert es;
     System.assertNotEquals(es,NULL,'EULA_submission__c should not be NULL');
        PRM_EULASubmissionController.submitApprovalRequest(es.id, 'Test');
        
   
        
        
           
        List<Attachment__c> esAttList = new List<Attachment__c>();
        
        Attachment__c obj = new Attachment__c();
        
        
        esAttList.add(obj);
        
       
        
        
        
        insert esAttList;
    }
    
    
}