force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Party Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Theater</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Geographical region where the account that a contact is aligned with is located.</description>
    <formula>if (TEXT( Account.Region__c ) = &quot;&quot;, &quot;Not Specified&quot;, TEXT( Account.Region__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Theater  value is populated from the corresponding Account record and cannot be edited.</inlineHelpText>
    <label>Theater</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Theater</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMEA</fullName>
            </value>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>JAPAN KOREA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Program__c/Demo_Program__c.object-meta.xml
<CustomObject>
    <label>Demo Program</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Demo Program #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Program__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <formula>TEXT(Partner_Account__r.Account_Country_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/LT__c.field-meta.xml
<CustomField>
    <fullName>LT__c</fullName>
    <label>LT</label>
    <length>252</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>MSRP</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Partner Account name who is requesting demo.</description>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demo Programs</relationshipLabel>
    <relationshipName>Demo_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demo Programs</relationshipLabel>
    <relationshipName>Demo_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/Product_Group_NCR_designation__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_NCR_designation__c</fullName>
    <label>Product Group [NCR designation]</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/QTY__c.field-meta.xml
<CustomField>
    <fullName>QTY__c</fullName>
    <label>QTY</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT(Partner_Account__r.Account_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_DemoCon.cls
public class PRM_DemoCon {
    
    /* Get List of the Demo Requests */
    @AuraEnabled
    public static List<Demo_Program__c> getFINDemoProgram()
    {
        
        List<Demo_Program__c> lstFDP =  [Select Id,Name, Partner_Contact__r.Name,Partner_Account__r.Name, Country_Code__c,Product_Group_NCR_designation__c,QTY__c,Status__c,Region__c,LT__c,MSRP__c	
                                         from Demo_Program__c order by CreatedDate desc];
        return lstFDP;
    }
    
    /* Get detail of the Demo Request */
    @AuraEnabled
    public static Demo_Program__c getDemoReq(String demoRecordId) {
        Demo_Program__c demoReq ;
        List<Demo_Program__c> demoReqList = [SELECT Id, Name, Partner_Account__c,Partner_Account__r.Name,Partner_Contact__c,Partner_Contact__r.Name,Country__c,
                                             Region__c, CreatedDate, Status__c, QTY__c, Product_Group_NCR_designation__c, Product_Description__c,
                                             MSRP__c, LT__c FROM Demo_Program__c WHERE Id =: demoRecordId LIMIT 1
                                            ];
        if(demoReqList.size() > 0) {
            demoReq = demoReqList[0];
        }
        return demoReq;
    }
    
    // Approval Process for the Demo Request
    @AuraEnabled
    public static approvalProcessResult submitRequest(String recId,  String comment) {
        approvalProcessResult appRes = new approvalProcessResult();
        Savepoint sp = Database.setSavepoint();
        try {
            // Validate attachement. If there is at least one attachement then only allow to submit the request.
            List<ContentDocument> attachedDocLst = getFiles(recId);
            if(!(attachedDocLst.size() > 0)){
                appRes.isSuccess = false;
                appRes.message = 'Please attach file before submitting the request.';
                return appRes;
            }
            // Submit request for approval.
            Approval.processSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setComments(comment);
            req.setObjectId(recId);
            Approval.ProcessResult result = Approval.process(req);
            if(result.isSuccess() != true) {
                appRes.isSuccess = false;
                appRes.message = 'Request could not submit for Approval. Please contact to System Administrator.';
                system.debug('***'+result.getErrors());
                Database.rollback(sp);
            } else {
                appRes.isSuccess = true;
                appRes.message = 'Record has been submitted successfully.';
            }
        } catch(Exception ex) {
            appRes.isSuccess = false;
            appRes.message = ex.getMessage();
            system.debug('***'+ex.getMessage());
            Database.rollback(sp);
        }
        
        return appRes;
    }
    
    
    // Find file attachment from the file
    @AuraEnabled
    public static List<ContentDocument> getFiles(String recId) {
        List<ContentDocumentLink> conDocLinkList = [SELECT Id, ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId =: recId];
        Set<Id> conDocIds = new Set<Id>();
        for (ContentDocumentLink conDocLink : conDocLinkList) {
            conDocIds.add(conDocLink.ContentDocumentId);
        }
        
        List<ContentDocument> conDocList = [SELECT Id, FileExtension, FileType, ContentSize, Title FROM ContentDocument WHERE Id IN: conDocIds];
        List<ContentVersion> conVersionLst = [SELECT Id, FileExtension, FileType, Title, ContentSize, ContentUrl
                                              FROM ContentVersion WHERE ContentDocumentId IN: conDocIds AND IsLatest = true];
        return conDocList;
        
    }
    
    //Deletion of Demo Request -- For future use --
    @AuraEnabled
    public static DataBaseOperation deleteDemoReq(String recId) {
        DataBaseOperation res = new DataBaseOperation();
        try {
            List<Demo_Program__c> demoReq = [SELECT Id FROM Demo_Program__c WHERE Id =: recId];
            if(demoReq.size()>0){
                DataBase.DeleteResult result = Database.delete(demoReq[0],true);
                if(result.isSuccess()){
                    res.isSuccess = true;
                    res.message = 'success';
                } else {
                    res.isSuccess = false;
                    res.message = result.getErrors()[0].getMessage();
                }
            }
        } catch(Exception ex){
            res.isSuccess = false;
            res.message = ex.getMessage();
        }
        return res;
    }
    
    public class DataBaseOperation {
        @AuraEnabled public Boolean isSuccess;
        @AuraEnabled public String message = '';
    }
    
    public class approvalProcessResult {
        @AuraEnabled public Boolean isSuccess;
        @AuraEnabled public String message = '';
    }
    
}