force-app/main/default/objects/Account/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Customer ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/DUNS__c.field-meta.xml
<CustomField>
    <fullName>DUNS__c</fullName>
    <externalId>true</externalId>
    <label>DUNS Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Enterprise.recordType-meta.xml
<RecordType>
    <fullName>Enterprise</fullName>
    <active>true</active>
    <description>Enterprise represent Legal Parent of Customer/Partner Account and same as Customer Party in CDM.</description>
    <label>Enterprise</label>
</RecordType>

force-app/main/default/objects/Hierarchy_Relation__c/Hierarchy_Relation__c.object-meta.xml
<CustomObject>
    <label>Hierarchy Relation</label>
    <nameField>
        <label>Hrchy Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarchy Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hierarchy_Relation__c/fields/From_Party_Number__c.field-meta.xml
<CustomField>
    <fullName>From_Party_Number__c</fullName>
    <label>From Party Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hierarchy_Relation__c/fields/IsProcessed__c.field-meta.xml
<CustomField>
    <fullName>IsProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Hierarchy_Relation__c/fields/Relationship_Code__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Code__c</fullName>
    <label>Relationship Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hierarchy_Relation__c/fields/Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Name__c</fullName>
    <label>Relationship Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hierarchy_Relation__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <label>Relationship Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hierarchy_Relation__c/fields/To_Party_Number__c.field-meta.xml
<CustomField>
    <fullName>To_Party_Number__c</fullName>
    <label>To Party Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateAccountGlobalUltimateTest.cls
@isTest
public class UpdateAccountGlobalUltimateTest {
    static testMethod void runTest(){
        Account acc1 =new Account();
        Account acc2 =new Account();
        Account childAcc =new Account();
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        User Usr = [Select Id from User Where Name = 'Soup User'];
        System.assertEquals(Usr.id!=null, true);
        System.runAs(Usr){
            List<Account> accList = new List<Account>(); 
            acc1.Name='Test Enterprise1';
            acc1.Customer_Number__c = 'Test1';
            acc1.DUNS__c = 'test1234';
            acc1.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            accList.add(acc1);
            
            acc2.Name='Test Enterprise2';
            acc2.Customer_Number__c = 'Test2';
            acc2.DUNS__c = 'test2345';
            acc2.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            accList.add(acc2);
            insert accList;  
            
            childAcc.Name='Child Enterprise';
            childAcc.Customer_Number__c = 'Test3';
            childAcc.parentId = acc1.Id;
            childAcc.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            insert childAcc;  
        }
        
        List<Hierarchy_Relation__c> hrlist = new List<Hierarchy_Relation__c>(); 
        Hierarchy_Relation__c hr = new Hierarchy_Relation__c(From_Party_Number__c = 'Test1' , To_Party_Number__c = 'Test2',
                                                             Relationship_Name__c = 'Enterprise Parent',IsProcessed__c = false, 
                                                             Relationship_Code__c = 'Enterprise Child of',Relationship_Status__c ='A',
                                                             Start_Date__c = Date.today(),End_Date__c = Date.today().addDays(10));
        Hierarchy_Relation__c hr1 = new Hierarchy_Relation__c(From_Party_Number__c = 'Test1' , To_Party_Number__c = 'Test2',
                                                             Relationship_Name__c = 'Enterprise Parent',IsProcessed__c = false, 
                                                             Relationship_Code__c = 'Enterprise Child of',Relationship_Status__c ='A',
                                                             Start_Date__c = Date.today(),End_Date__c = Date.today().addDays(-10));
        
        Hierarchy_Relation__c hr2 = new Hierarchy_Relation__c(From_Party_Number__c = 'Test3' , To_Party_Number__c = 'test1234',
                                                             Relationship_Name__c = 'Domestic Ultimate',IsProcessed__c = false);
        
        hrlist.add(hr);
        hrlist.add(hr1);
        hrlist.add(hr2);
        insert hrlist;
        
        Test.startTest();
            String TEST_CRON_EXP = '0 25 * * * ?';
        	System.schedule('Account Hierarchy Calculation',TEST_CRON_EXP , new ScheduleAccountGUUpdate());
            new UpdateAccountGlobalUltimate().processRelation();
            new UpdateAccountGlobalUltimate().processRelation();
        Test.stopTest();
    }
    
    
    static testMethod void runTest2() {
        Account acc1 =new Account();
        Account acc2 =new Account();
        Account childAcc =new Account();
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        User Usr = [Select Id from User Where Name = 'Soup User'];
         System.assertEquals(Usr.id!=null, true);
        System.runAs(Usr){
            List<Account> accList = new List<Account>(); 
            acc1.Name='Test Enterprise1';
            acc1.Customer_Number__c = 'Test1';
            acc1.DUNS__c = 'test1234';
            acc1.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            accList.add(acc1);
            
            acc2.Name='Test Enterprise2';
            acc2.Customer_Number__c = 'Test2';
            acc2.DUNS__c = 'test2345';
            acc2.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            accList.add(acc2);
            insert accList;  
            
            childAcc.Name='Child Enterprise';
            childAcc.Customer_Number__c = 'Test3';
            childAcc.parentId = acc1.Id;
            childAcc.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            insert childAcc;  
        }
        
         Test.startTest();
        List<Hierarchy_Relation__c> hrlist = new List<Hierarchy_Relation__c>(); 
        Hierarchy_Relation__c hr = new Hierarchy_Relation__c(From_Party_Number__c = 'Test1' , To_Party_Number__c = 'Test2',
                                                             Relationship_Name__c = 'Enterprise Parent',IsProcessed__c = false, 
                                                             Relationship_Code__c = 'Enterprise Child of',Relationship_Status__c ='A',
                                                             Start_Date__c = Date.today(),End_Date__c = Date.today().addDays(10));
        insert hr;
        
        Database.executeBatch(new HierarchyInitialSetup(), 1);
       
        Test.stopTest();
    }
    static testMethod void runTest3() {
     	Account acc1 =new Account();
        Account acc2 =new Account();
        Account childAcc =new Account();
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        User Usr = [Select Id from User Where Name = 'Soup User'];
         System.assertEquals(Usr.id!=null, true);
        
        System.runAs(Usr){
            List<Account> accList = new List<Account>(); 
            acc1.Name='Test Enterprise1';
            acc1.Customer_Number__c = 'Test1';
            acc1.DUNS__c = 'test1234';
            acc1.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            accList.add(acc1);
            
            acc2.Name='Test Enterprise2';
            acc2.Customer_Number__c = 'Test2';
            acc2.DUNS__c = 'test2345';
            acc2.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            accList.add(acc2);
            insert accList;  
            
            childAcc.Name='Child Enterprise';
            childAcc.Customer_Number__c = 'Test3';
            childAcc.parentId = acc1.Id;
            childAcc.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            insert childAcc;  
        }  
        
         Hierarchy_Relation__c hr1 = new Hierarchy_Relation__c(From_Party_Number__c = 'Test1' , To_Party_Number__c = 'Test2',
                                                             Relationship_Name__c = 'Enterprise Parent',IsProcessed__c = false, 
                                                             Relationship_Code__c = 'Enterprise Child of',Relationship_Status__c ='A',
                                                             Start_Date__c = Date.today(),End_Date__c = Date.today().addDays(-10));
        insert hr1;
        Database.executeBatch(new HierarchyInitialSetup(), 1);
    }
    
     static testMethod void runTest4() {
    	Account acc1 =new Account();
        Account acc2 =new Account();
        Account childAcc =new Account();
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        User Usr = [Select Id from User Where Name = 'Soup User'];
         System.assertEquals(Usr.id!=null, true);
        System.runAs(Usr){
            List<Account> accList = new List<Account>(); 
            acc1.Name='Test Enterprise1';
            acc1.Customer_Number__c = 'Test1';
            acc1.DUNS__c = 'test1234';
            acc1.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            accList.add(acc1);
            
            acc2.Name='Test Enterprise2';
            acc2.Customer_Number__c = 'Test2';
            acc2.DUNS__c = 'test2345';
            acc2.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            accList.add(acc2);
            insert accList;  
            
            childAcc.Name='Child Enterprise';
            childAcc.Customer_Number__c = 'Test3';
            childAcc.parentId = acc1.Id;
            childAcc.RecordTypeId = rtMapByName.get(Label.RT_Acc_Enterprise).getRecordTypeId();
            insert childAcc;  
        } 
         
        Hierarchy_Relation__c hr2 = new Hierarchy_Relation__c(From_Party_Number__c = 'Test3' , To_Party_Number__c = 'test1234',
                                                             Relationship_Name__c = 'Domestic Ultimate',IsProcessed__c = false);
        
        insert hr2;
        Database.executeBatch(new HierarchyInitialSetup(), 1);
    }
}