force-app/main/default/objects/Account/fields/Global_Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Global_Sales_Org_Code__c</fullName>
    <label>Global Sales Org Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDM_Data_Source_Code__c.field-meta.xml
<CustomField>
    <fullName>MDM_Data_Source_Code__c</fullName>
    <inlineHelpText>Data Source Code indicates the source application. NCR Sales Central (NSC) often carries the Data Source Code of ‘APOL’ which stands for ‘Apollo’ which was a predecessor application to NSC within NCR.</inlineHelpText>
    <label>Data Source Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSC_Support_Error_Notification__c/NSC_Support_Error_Notification__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NSC Support Error Notification</label>
</CustomObject>

force-app/main/default/objects/NSC_Support_Error_Notification__c/fields/ToEmailAddresses__c.field-meta.xml
<CustomField>
    <fullName>ToEmailAddresses__c</fullName>
    <label>ToEmailAddresses</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organization this opportunity is related to</description>
    <inlineHelpText>To find an org code search by your first or last name</inlineHelpText>
    <label>Sales Team Organization</label>
    <referenceTo>Sales_Org__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <formula>Sales_Org__r.Sales_Org_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Org Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <description>Contains all of the applicable NCR sales organizations</description>
    <label>Sales Org</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/Is_Active_in_RoR__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_in_RoR__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active in RoR?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateOppSalesOrgCodeTest.cls
@isTest
private class UpdateOppSalesOrgCodeTest {
    
     public static testMethod void myTest() {
        User Usr = [Select Id, profileId from User Where Name = 'Soup User'];
        system.assertNotEquals(Usr.Id,null);
        Id pr =NSCCommonInfoUtil.getIdOf('NSC_Admin');  //Change by saurav
        NSC_Support_Error_Notification__c nscNotification = new NSC_Support_Error_Notification__c (name='NSC Job Failure', ToEmailAddresses__c= 'test@ncr.com');
        insert nscNotification; 
         
   
        
        Account a;
        
        System.runAs(Usr) {
             a = new Account(name='Account-1');
             a.MDM_Data_Source_Code__c = 'CDM';
             a.Global_Sales_Org_Code__c = 'Test1234';
             insert a;
            
             Id includeInFunnelRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Include in Funnel').getRecordTypeId();
             Opportunity opp = TestRecordsFactory.createSimpleOpportunity(a);
          
             a.Global_Sales_Org_Code__c = '12345';
             update a;     
            
             Sales_Org__c org1 = new Sales_Org__c(name = 'test org', Is_Active_in_RoR__c = true, Sales_Org_Code__c='12345', ownerId= pr, isPrimary__c =true);
             insert org1;
         }
    }
    /*this will cover populateAccountOrgCode trigger*/
    public static testMethod void test2() {
        User Usr = [Select Id, profileId from User Where Name = 'Soup User'];
        system.assertNotEquals(Usr.Id,null);
          Id prf =NSCCommonInfoUtil.getIdOf('NSC_Admin'); //Change by saurav 00570000001N9kDAAS
        NSC_Support_Error_Notification__c nscNotification = new NSC_Support_Error_Notification__c (name='NSC Job Failure', ToEmailAddresses__c= 'test@ncr.com');
        insert nscNotification; 
         
   
        
        Account a;
        
        System.runAs(Usr) {
             a = new Account(name='Account-1');
             a.MDM_Data_Source_Code__c = 'CDM';
             a.Global_Sales_Org_Code__c = 'Test1234';
             insert a;
            
             Id includeInFunnelRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Include in Funnel').getRecordTypeId();
             Opportunity opp = TestRecordsFactory.createSimpleOpportunity(a);
          
             a.Global_Sales_Org_Code__c = '12345';
             update a;     
            
             Sales_Org__c org1 = new Sales_Org__c(name = 'test org', Is_Active_in_RoR__c = true, Sales_Org_Code__c='12345', ownerId=prf, isPrimary__c =true);
          
            insert org1;
            org1.isPrimary__c = false;
            try{
            update org1;
            }
            catch( exception ex){
                system.debug(ex.getMessage());
            }
            Sales_Org__c org2 = new Sales_Org__c(name = 'test org1', Is_Active_in_RoR__c = true, Sales_Org_Code__c='12345', ownerId=prf, isPrimary__c =false);
          
            insert org2;
            org2.isPrimary__c = true;
            try{
            update org2;
            }
            catch( exception ex){
                system.debug(ex.getMessage());
            }
            try{
             delete org1;
            }
            catch( exception ex){
                system.debug(ex.getMessage());
            }
           
         }
    }
         
}