force-app/main/default/objects/Account/fields/Interface_Type__c.field-meta.xml
<CustomField>
    <fullName>Interface_Type__c</fullName>
    <label>Interface Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Batch</fullName>
                <default>true</default>
                <label>Batch</label>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Real-Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/RequiredSPPCategory__c.field-meta.xml
<CustomField>
    <fullName>RequiredSPPCategory__c</fullName>
    <label>Required SPP Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Aggregation</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Application - Create Your Own Page SSO</fullName>
            </value>
            <value>
                <fullName>Application - Mobile SSO</fullName>
            </value>
            <value>
                <fullName>Application - Widget SSO</fullName>
            </value>
            <value>
                <fullName>BillPay</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Check Imaging</fullName>
            </value>
            <value>
                <fullName>Check Reorder</fullName>
            </value>
            <value>
                <fullName>Credit Cards</fullName>
            </value>
            <value>
                <fullName>Deposit Image</fullName>
            </value>
            <value>
                <fullName>Electronic Tax Payment</fullName>
            </value>
            <value>
                <fullName>FI Application</fullName>
            </value>
            <value>
                <fullName>Forms</fullName>
            </value>
            <value>
                <fullName>Funds Transfer</fullName>
            </value>
            <value>
                <fullName>IB Vendor</fullName>
            </value>
            <value>
                <fullName>Lender Application Interface</fullName>
            </value>
            <value>
                <fullName>Lender Doc Prep Interface</fullName>
            </value>
            <value>
                <fullName>Lender Servicing and Disbursement Interf</fullName>
            </value>
            <value>
                <fullName>Lender Servicing Interface</fullName>
            </value>
            <value>
                <fullName>Lending</fullName>
            </value>
            <value>
                <fullName>Online Statements</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>Remote Deposit</fullName>
            </value>
            <value>
                <fullName>Secure Support</fullName>
            </value>
            <value>
                <fullName>Statements &amp; Imaging</fullName>
            </value>
            <value>
                <fullName>To Be Classified</fullName>
            </value>
            <value>
                <fullName>Wire Transfer - Real Time</fullName>
            </value>
            <value>
                <fullName>Wireless</fullName>
            </value>
            <value>
                <fullName>Data Services-Agg API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/RequiredSPPInterfaceType__c.field-meta.xml
<CustomField>
    <fullName>RequiredSPPInterfaceType__c</fullName>
    <label>Required SPP Interface Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>SSO</fullName>
            </value>
            <value>
                <fullName>Lending</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solution_Provider__c/Solution_Provider__c.object-meta.xml
<CustomObject>
    <description>A company that provides service(s) that are integral to how our digital banking offerings operate.</description>
    <label>Solution Provider Account</label>
    <nameField>
        <label>Solution Provider Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solution Provider Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution_Provider__c/fields/Solution_Provider_Number__c.field-meta.xml
<CustomField>
    <fullName>Solution_Provider_Number__c</fullName>
    <description>V-prefixed four digit identification number - user friendly &quot;ID&quot; of Solution Provider</description>
    <label>Solution Provider Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution_Provider_Product__c/Solution_Provider_Product__c.object-meta.xml
<CustomObject>
    <label>Solution Provider Product</label>
    <nameField>
        <label>Solution Provider Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solution Provider Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution_Provider_Product__c/fields/Interface_Type__c.field-meta.xml
<CustomField>
    <fullName>Interface_Type__c</fullName>
    <description>Defines interface type to connect to DI product  (THIS MUST MATCH OF PICKLIST IN PRODUCT CATALOG)</description>
    <label>Interface Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>SSO</fullName>
            </value>
            <value>
                <fullName>Lending</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solution_Provider_Product__c/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <description>State of product from an Internal perspectiven - drives the ability to sell products &amp; associate to this DPV (can boil to Status).</description>
    <label>Internal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Beta Ready</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Not In Queue</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solution_Provider_Product__c/fields/Solution_Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>Solution_Provider_Id__c</fullName>
    <description>Which solution provider owns this product</description>
    <label>Solution Provider</label>
    <referenceTo>Solution_Provider__c</referenceTo>
    <relationshipLabel>Solution Provider Product</relationshipLabel>
    <relationshipName>Solution_Provider_Product</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution_Provider_Product__c/fields/Solution_Provider_Number__c.field-meta.xml
<CustomField>
    <fullName>Solution_Provider_Number__c</fullName>
    <label>Solution Provider Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution_Provider_Product__c/fields/Solution_Provider_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Solution_Provider_Product_Category__c</fullName>
    <description>&quot;Category&quot; - helps filter which solution provider product to choose when quoting (Matches picklist for FI_Vendor.Vendor_Type)</description>
    <label>Solution Provider Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Aggregation</fullName>
            </value>
            <value>
                <fullName>Account Switch</fullName>
            </value>
            <value>
                <fullName>ACH Originator</fullName>
            </value>
            <value>
                <fullName>Alternate Images</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Application – BMA SSO</fullName>
                <label>Application - BMA SSO</label>
            </value>
            <value>
                <fullName>Application - Create Your Own Page SSO</fullName>
            </value>
            <value>
                <fullName>Application - Mobile SSO</fullName>
            </value>
            <value>
                <fullName>Application - Widget SSO</fullName>
            </value>
            <value>
                <fullName>BillPay</fullName>
            </value>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Card Integration</fullName>
            </value>
            <value>
                <fullName>Card Management</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Check Imaging</fullName>
            </value>
            <value>
                <fullName>Check Reorder</fullName>
            </value>
            <value>
                <fullName>Credit Card Rewards</fullName>
            </value>
            <value>
                <fullName>Credit Cards</fullName>
            </value>
            <value>
                <fullName>Data Services-Agg API</fullName>
            </value>
            <value>
                <fullName>Deposit Image</fullName>
            </value>
            <value>
                <fullName>Electronic Tax Payment</fullName>
            </value>
            <value>
                <fullName>FI Application</fullName>
            </value>
            <value>
                <fullName>File Mover</fullName>
            </value>
            <value>
                <fullName>Forms</fullName>
            </value>
            <value>
                <fullName>Funds Transfer</fullName>
            </value>
            <value>
                <fullName>IB Vendor</fullName>
            </value>
            <value>
                <fullName>Interface</fullName>
            </value>
            <value>
                <fullName>Kids Banking</fullName>
            </value>
            <value>
                <fullName>Lender Application Interface</fullName>
            </value>
            <value>
                <fullName>Lender Doc Prep Interface</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateQuoteServiceTests.cls
// ===========================================================================
// Object: CreateQuoteServiceTests
// Company: Cloudware Connections, Inc.
// Author: Reid Beckett
// Purpose: Test coverage for the CreateQuoteService REST service
// ===========================================================================
// Changes: 2017-04-05 Reid Beckett
//           Class created
// ===========================================================================
@isTest(SeeAllData=true)
public class CreateQuoteServiceTests 
{
    Public Static User getUser(){        
        User Usr = [Select Id from User Where Name = 'Soup User'];
        return Usr;
    } 
    private static void setUp() {
        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.httpMethod = 'POST';
        RestContext.request.headers.put('Logging', 'document');

        Solution_Provider__c sp = new Solution_Provider__c(Name = 'Test SP', Solution_Provider_Number__c = '00001');
        insert sp;

        Solution_Provider_Product__c[] spProducts = new Solution_Provider_Product__c[]{
            new Solution_Provider_Product__c(Solution_Provider_Id__c = sp.Id, Name = 'Test SPP',
                Solution_Provider_Product_Category__c = 'IB Vendor',
                Interface_Type__c = 'Integrated', Internal_Status__c = 'Available')
        };
        insert spProducts;

    }
    
    @isTest static void test10_e1() {
        setUp();
        RestContext.request.headers.put('Logging', 'none');
        CreateQuoteService.createQuote();
        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(500, RestContext.response.statusCode);
    }

    @isTest static void test10_e2() {
        setUp();
        CreateQuoteModel.IncomingJSONBodyWrapper jsonBody = new CreateQuoteModel.IncomingJSONBodyWrapper();
        jsonBody.quoteInformation = new CreateQuoteModel.QuoteInformation();

        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));

        CreateQuoteService.createQuote();
        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(500, RestContext.response.statusCode);
    }

    @isTest static void test10_e3() {
        setUp();
        CreateQuoteModel.IncomingJSONBodyWrapper jsonBody = new CreateQuoteModel.IncomingJSONBodyWrapper();
        jsonBody.quoteInformation = new CreateQuoteModel.QuoteInformation();
        jsonBody.quoteInformation.opportunityId = 'abc123';
        jsonBody.quoteInformation.masterCustomerNumber = 'DI9999';
        jsonBody.quoteInformation.startDate = Date.today().addDays(1);
        jsonBody.quoteInformation.quoteType = 'Default';
        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));

        CreateQuoteService.createQuote();
        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(500, RestContext.response.statusCode);
    }

    @isTest static void test10_e4() {
        setUp();
        Account acct = new Account(Name = 'Test Account');
        System.runAs(getUser()){
            insert acct;
        }
        
        Opportunity opp = ZuoraTestUtil.createOpp(acct);

        CreateQuoteModel.IncomingJSONBodyWrapper jsonBody = new CreateQuoteModel.IncomingJSONBodyWrapper();
        jsonBody.quoteInformation = new CreateQuoteModel.QuoteInformation();
        jsonBody.quoteInformation.opportunityId = opp.Id;
        jsonBody.quoteInformation.billingAccountid = ZuoraTestUtil.generateGUID();
        jsonBody.quoteInformation.startDate = Date.today().addDays(1);
        jsonBody.quoteInformation.quoteType = 'BadQuoteType';
        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));

        CreateQuoteService.createQuote();
        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(500, RestContext.response.statusCode);
    }

    @isTest static void test10_e5() {
        setUp();
        Account acct = new Account(Name = 'Test Account');
        System.runAs(getUser()){
            insert acct;
        }
        
        
        Opportunity opp = ZuoraTestUtil.createOpp(acct);

        CreateQuoteModel.IncomingJSONBodyWrapper jsonBody = new CreateQuoteModel.IncomingJSONBodyWrapper();
        jsonBody.quoteInformation = new CreateQuoteModel.QuoteInformation();
        jsonBody.quoteInformation.opportunityId = opp.Id;
        jsonBody.quoteInformation.masterCustomerNumber = 'DI9999';
        jsonBody.quoteInformation.startDate = Date.today().addDays(1);
        jsonBody.quoteInformation.quoteType = 'Default';
        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));

        CreateQuoteService.createQuote();
        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(500, RestContext.response.statusCode);
    }

    @isTest static void test1_newSubscriptionQuote() {
        setUp();

        ZuoraTestUtil.ProductCatalog pcatalog = ZuoraTestUtil.createOneProductCatalog('SKU-99991','Recurring', 'Per Unit Pricing');
        update new Product2(Id = pcatalog.products[0].zqu__Product__c, RequiredSPPCategory__c = 'IB Vendor', RequiredSPPInterfaceType__c = 'Integrated');
        
        ZuoraTestUtil.ProductCatalog pcatalog2 = ZuoraTestUtil.createOneProductCatalog('SKU-99992', 'Recurring', 'Volume Pricing');

        Account acct = new Account(Name = 'Test Account');
        System.runAs(getUser()){
            insert acct;
        }
        
        String bilingAccountId = ZuoraTestUtil.generateGUID();
        Zuora__CustomerAccount__c billingAccount = new Zuora__CustomerAccount__c(
            Zuora__Account__c = acct.Id, BillToFlag__c = 'Yes',
            Zuora__External_Id__c = bilingAccountId, Zuora__Zuora_Id__c = bilingAccountId,
            MasterCustomerNumber__c = 'DI9999'
        );
        insert billingAccount;

        Opportunity opp = ZuoraTestUtil.createOpp(acct);
        
        CreateQuoteModel.IncomingJSONBodyWrapper jsonBody = new CreateQuoteModel.IncomingJSONBodyWrapper();
        jsonBody.quoteInformation = new CreateQuoteModel.QuoteInformation();
        jsonBody.quoteInformation.opportunityId = opp.Id;
        jsonBody.quoteInformation.masterCustomerNumber = 'DI9999';
        jsonBody.quoteInformation.startDate = Date.today().addDays(1);
        jsonBody.quoteInformation.quoteType = 'Default';
        jsonBody.quoteInformation.ownerFirstName = UserInfo.getFirstName();
        jsonBody.quoteInformation.ownerLastName = UserInfo.getLastName();
        
        jsonBody.ratePlans = new CreateQuoteModel.RatePlan[]{};
        CreateQuoteModel.RatePlan rp1 = new CreateQuoteModel.RatePlan();
        rp1.name = pcatalog.productRatePlans[0].Name;
        rp1.productRatePlanId = pcatalog.productRatePlans[0].zqu__ZuoraId__c;
        rp1.tpv = 'Test SPP';
        jsonBody.ratePlans.add(rp1);
        
        CreateQuoteModel.RatePlan rp2 = new CreateQuoteModel.RatePlan();
        rp2.name = pcatalog2.productRatePlans[0].Name;
        rp2.productRatePlanId = pcatalog2.productRatePlans[0].zqu__ZuoraId__c;
        rp2.tiers = new CreateQuoteModel.RatePlanTier[]{};
        CreateQuoteModel.RatePlanTier t1 = new CreateQuoteModel.RatePlanTier();           
        t1.tier = 1;
        t1.startingUnit = 0;
        t1.endingUnit = 99;
        t1.price = 100;
        rp2.tiers.add(t1);
        CreateQuoteModel.RatePlanTier t2 = new CreateQuoteModel.RatePlanTier();           
        t2.tier = 2;
        t2.startingUnit = 100;
        t2.endingUnit = null;
        t2.price = 90;
        rp2.tiers.add(t2);
        jsonBody.ratePlans.add(rp2);

        String jsonString = JSON.serializePretty(jsonBody);
        RestContext.request.requestBody = Blob.valueOf(jsonString);
        
        CreateQuoteService.createQuote();

        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        //system.assertEquals(200, RestContext.response.statusCode, RestContext.response.responseBody.toString());
        
        CreateQuoteModel.OutgoingJSONBodyWrapper responseJSON = (CreateQuoteModel.OutgoingJSONBodyWrapper)JSON.deserialize(RestContext.response.responseBody.toString(), CreateQuoteModel.OutgoingJSONBodyWrapper.class);
        system.assertNotEquals(null, responseJSON.quoteId);
        
        Test.startTest();
        update new zqu__Quote__c(Id = responseJSON.quoteId, RecordTypeId = Schema.SObjectType.zqu__Quote__c.getRecordTypeInfosByName().get('ReadOnly').getRecordTypeId());
        CreateQuoteServiceUtil.exportQuote(responseJSON.quoteId);
        Test.stopTest();
    }   

    @isTest static void test2_amendmentQuote_withUpdate() {
        setUp();

        ZuoraTestUtil.ProductCatalog pcatalog = ZuoraTestUtil.createOneProductCatalog('SKU-999991', 'Recurring', 'Per Unit Pricing');
        update new Product2(Id = pcatalog.products[0].zqu__Product__c, RequiredSPPCategory__c = 'IB Vendor', RequiredSPPInterfaceType__c = 'Integrated');
        ZuoraTestUtil.ProductCatalog pcatalogNew = ZuoraTestUtil.createOneProductCatalog('SKU-999992', 'One-Time', 'Flat Fee Pricing');
        
        Account acct = new Account(Name = 'Test Account');
        System.runAs(getUser()){
            insert acct;
        }
        
        Opportunity opp = ZuoraTestUtil.createOpp(acct);
        
        ZuoraClient.ZuoraMockClient mock = (ZuoraClient.ZuoraMockClient)ZuoraClient.getInstance();
        mock.addData('Account', ZuoraTestUtil.createZuoraObject('Account', new Map<String,Object>{
            'Name' => 'Test Account', 'CrmId' => acct.Id
        }));
        mock.addData('Subscription', ZuoraTestUtil.createZuoraObject('Subscription', new Map<String,Object>{
            'AccountId' => mock.getFirst('Account').getValue('Id'),
            'TermType' => 'TERMED',
            'InitialTerm' => 84,
            'RenewalTerm' => 24,
            'SubscriptionStartDate' => Date.today(),
            'SubscriptionEndDate' => Date.today().addMonths(84)
        }));
        String zuoraSubscriptionId = (String)mock.getFirst('Subscription').getValue('Id');
        mock.addData('RatePlan', ZuoraTestUtil.createZuoraObject('RatePlan', new Map<String,Object>{
            'SubscriptionId' => zuoraSubscriptionId,
            'ProductRatePlanId' => pcatalog.productRatePlans[0].zqu__ZuoraId__c
        }));
        String ratePlanId = (String)mock.getFirst('RatePlan').getValue('Id');
        mock.addData('RatePlanCharge', ZuoraTestUtil.createZuoraObject('RatePlanCharge', new Map<String,Object>{
            'RatePlanId' => ratePlanId,
            'ProductRatePlanChargeId' => pcatalog.productRatePlanCharges[0].zqu__ZuoraId__c,
            'Quantity' => 1, 'Price' => 1000
        }));


        CreateQuoteModel.IncomingJSONBodyWrapper jsonBody = new CreateQuoteModel.IncomingJSONBodyWrapper();
        jsonBody.quoteInformation = new CreateQuoteModel.QuoteInformation();
        jsonBody.quoteInformation.opportunityId = opp.Id;
        jsonBody.quoteInformation.billingAccountId = ZuoraTestUtil.generateGUID();
        jsonBody.quoteInformation.startDate = Date.today().addDays(1);
        jsonBody.quoteInformation.quoteType = 'Amendment';
        jsonBody.quoteInformation.subscriptionId = zuoraSubscriptionId;
        
        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));
        
        CreateQuoteService.createQuote();

        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(200, RestContext.response.statusCode);
        
        CreateQuoteModel.OutgoingJSONBodyWrapper out = (CreateQuoteModel.OutgoingJSONBodyWrapper)JSON.deserialize(RestContext.response.responseBody.toString(), CreateQuoteModel.OutgoingJSONBodyWrapper.class);
        system.assertNotEquals(null, out.quoteId);
        jsonBody.quoteInformation.id = out.quoteId;

        jsonBody.ratePlans = new CreateQuoteModel.RatePlan[]{};

        //UPDATED rate plan
        CreateQuoteModel.RatePlan rp1 = new CreateQuoteModel.RatePlan();
        rp1.name = pcatalog.productRatePlans[0].Name;
        rp1.productRatePlanId = pcatalog.productRatePlans[0].zqu__ZuoraId__c;
        rp1.subscriptionRatePlanId = ratePlanId;
        rp1.tpv = 'Test SPP';
        jsonBody.ratePlans.add(rp1);

        //NEW rate plan
        CreateQuoteModel.RatePlan rp2 = new CreateQuoteModel.RatePlan();
        rp2.name = pcatalogNew.productRatePlans[0].Name;
        rp2.productRatePlanId = pcatalogNew.productRatePlans[0].zqu__ZuoraId__c;
        jsonBody.ratePlans.add(rp2);

        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));

        Test.startTest();
        CreateQuoteServiceUtil.AllowMultipleQuotes = true;
        CreateQuoteService.createQuote();

        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(200, RestContext.response.statusCode, RestContext.response.responseBody.toString());
        Test.stopTest();
    }   

    @isTest static void test2_amendmentQuote_withRemove() {
        setUp();

        ZuoraTestUtil.ProductCatalog pcatalog = ZuoraTestUtil.createOneProductCatalog('SKU-999991', 'Recurring', 'Per Unit Pricing');
        ZuoraTestUtil.ProductCatalog pcatalogNew = ZuoraTestUtil.createOneProductCatalog('SKU-999992', 'One-Time', 'Flat Fee Pricing');
        
        Account acct = new Account(Name = 'Test Account');
        System.runAs(getUser()){
            insert acct;
        }
        
        Opportunity opp = ZuoraTestUtil.createOpp(acct);
        
        ZuoraClient.ZuoraMockClient mock = (ZuoraClient.ZuoraMockClient)ZuoraClient.getInstance();
        mock.addData('Account', ZuoraTestUtil.createZuoraObject('Account', new Map<String,Object>{
            'Name' => 'Test Account', 'CrmId' => acct.Id
        }));
        mock.addData('Subscription', ZuoraTestUtil.createZuoraObject('Subscription', new Map<String,Object>{
            'AccountId' => mock.getFirst('Account').getValue('Id'),
            'TermType' => 'TERMED',
            'InitialTerm' => 84,
            'RenewalTerm' => 24,
            'SubscriptionStartDate' => Date.today(),
            'SubscriptionEndDate' => Date.today().addMonths(84)
        }));
        String zuoraSubscriptionId = (String)mock.getFirst('Subscription').getValue('Id');
        mock.addData('RatePlan', ZuoraTestUtil.createZuoraObject('RatePlan', new Map<String,Object>{
            'SubscriptionId' => zuoraSubscriptionId,
            'ProductRatePlanId' => pcatalog.productRatePlans[0].zqu__ZuoraId__c
        }));
        String ratePlanId = (String)mock.getFirst('RatePlan').getValue('Id');
        mock.addData('RatePlanCharge', ZuoraTestUtil.createZuoraObject('RatePlanCharge', new Map<String,Object>{
            'RatePlanId' => ratePlanId,
            'ProductRatePlanChargeId' => pcatalog.productRatePlanCharges[0].zqu__ZuoraId__c,
            'Quantity' => 1, 'Price' => 1000
        }));


        CreateQuoteModel.IncomingJSONBodyWrapper jsonBody = new CreateQuoteModel.IncomingJSONBodyWrapper();
        jsonBody.quoteInformation = new CreateQuoteModel.QuoteInformation();
        jsonBody.quoteInformation.opportunityId = opp.Id;
        jsonBody.quoteInformation.billingAccountId = ZuoraTestUtil.generateGUID();
        jsonBody.quoteInformation.startDate = Date.today().addDays(1);
        jsonBody.quoteInformation.quoteType = 'Amendment';
        jsonBody.quoteInformation.subscriptionId = zuoraSubscriptionId;
        
        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));
        
        CreateQuoteService.createQuote();

        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(200, RestContext.response.statusCode);
        
        CreateQuoteModel.OutgoingJSONBodyWrapper out = (CreateQuoteModel.OutgoingJSONBodyWrapper)JSON.deserialize(RestContext.response.responseBody.toString(), CreateQuoteModel.OutgoingJSONBodyWrapper.class);
        system.assertNotEquals(null, out.quoteId);
        jsonBody.quoteInformation.id = out.quoteId;

        jsonBody.ratePlans = new CreateQuoteModel.RatePlan[]{};

        //REMOVED rate plan
        CreateQuoteModel.RatePlan rp1 = new CreateQuoteModel.RatePlan();
        rp1.name = pcatalog.productRatePlans[0].Name;
        rp1.productRatePlanId = pcatalog.productRatePlans[0].zqu__ZuoraId__c;
        rp1.subscriptionRatePlanId = ratePlanId;
        rp1.action = 'remove';
        jsonBody.ratePlans.add(rp1);

        //NEW rate plan
        CreateQuoteModel.RatePlan rp2 = new CreateQuoteModel.RatePlan();
        rp2.name = pcatalogNew.productRatePlans[0].Name;
        rp2.productRatePlanId = pcatalogNew.productRatePlans[0].zqu__ZuoraId__c;
        jsonBody.ratePlans.add(rp2);

        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));

        Test.startTest();
        CreateQuoteServiceUtil.AllowMultipleQuotes = true;
        CreateQuoteService.createQuote();

        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(200, RestContext.response.statusCode, RestContext.response.responseBody.toString());
        Test.stopTest();
    }       

    @isTest static void test2_renewalQuote_withUpdate() {
        setUp();

        ZuoraTestUtil.ProductCatalog pcatalog = ZuoraTestUtil.createOneProductCatalog('SKU-999991', 'Recurring', 'Per Unit Pricing');
        update new Product2(Id = pcatalog.products[0].zqu__Product__c, RequiredSPPCategory__c = 'IB Vendor', RequiredSPPInterfaceType__c = 'Integrated');
        ZuoraTestUtil.ProductCatalog pcatalogNew = ZuoraTestUtil.createOneProductCatalog('SKU-999992', 'One-Time', 'Flat Fee Pricing');
        
        Account acct = new Account(Name = 'Test Account');
        System.runAs(getUser()){
            insert acct;
        }
        
        Opportunity opp = ZuoraTestUtil.createOpp(acct);
        
        ZuoraClient.ZuoraMockClient mock = (ZuoraClient.ZuoraMockClient)ZuoraClient.getInstance();
        mock.addData('Account', ZuoraTestUtil.createZuoraObject('Account', new Map<String,Object>{
            'Name' => 'Test Account', 'CrmId' => acct.Id
        }));
        mock.addData('Subscription', ZuoraTestUtil.createZuoraObject('Subscription', new Map<String,Object>{
            'AccountId' => mock.getFirst('Account').getValue('Id'),
            'TermType' => 'TERMED',
            'InitialTerm' => 84,
            'RenewalTerm' => 24,
            'SubscriptionStartDate' => Date.today(),
            'SubscriptionEndDate' => Date.today().addMonths(84)
        }));
        String zuoraSubscriptionId = (String)mock.getFirst('Subscription').getValue('Id');
        mock.addData('RatePlan', ZuoraTestUtil.createZuoraObject('RatePlan', new Map<String,Object>{
            'SubscriptionId' => zuoraSubscriptionId,
            'ProductRatePlanId' => pcatalog.productRatePlans[0].zqu__ZuoraId__c
        }));
        String ratePlanId = (String)mock.getFirst('RatePlan').getValue('Id');
        mock.addData('RatePlanCharge', ZuoraTestUtil.createZuoraObject('RatePlanCharge', new Map<String,Object>{
            'RatePlanId' => ratePlanId,
            'ProductRatePlanChargeId' => pcatalog.productRatePlanCharges[0].zqu__ZuoraId__c,
            'Quantity' => 1, 'Price' => 1000
        }));


        CreateQuoteModel.IncomingJSONBodyWrapper jsonBody = new CreateQuoteModel.IncomingJSONBodyWrapper();
        jsonBody.quoteInformation = new CreateQuoteModel.QuoteInformation();
        jsonBody.quoteInformation.opportunityId = opp.Id;
        jsonBody.quoteInformation.billingAccountId = ZuoraTestUtil.generateGUID();
        jsonBody.quoteInformation.startDate = Date.today().addDays(1);
        jsonBody.quoteInformation.quoteType = 'New Renewal';
        jsonBody.quoteInformation.subscriptionId = zuoraSubscriptionId;
        
        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));
        
        CreateQuoteService.createQuote();

        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        system.assertEquals(200, RestContext.response.statusCode);
        
        CreateQuoteModel.OutgoingJSONBodyWrapper out = (CreateQuoteModel.OutgoingJSONBodyWrapper)JSON.deserialize(RestContext.response.responseBody.toString(), CreateQuoteModel.OutgoingJSONBodyWrapper.class);
        system.assertNotEquals(null, out.quoteId);
        jsonBody.quoteInformation.id = out.quoteId;

        jsonBody.ratePlans = new CreateQuoteModel.RatePlan[]{};

        //UPDATED rate plan
        CreateQuoteModel.RatePlan rp1 = new CreateQuoteModel.RatePlan();
        rp1.name = pcatalog.productRatePlans[0].Name;
        rp1.productRatePlanId = pcatalog.productRatePlans[0].zqu__ZuoraId__c;
        rp1.subscriptionRatePlanId = ratePlanId;
        rp1.tpv = 'Test SPP';
        jsonBody.ratePlans.add(rp1);

        //NEW rate plan
        CreateQuoteModel.RatePlan rp2 = new CreateQuoteModel.RatePlan();
        rp2.name = pcatalogNew.productRatePlans[0].Name;
        rp2.productRatePlanId = pcatalogNew.productRatePlans[0].zqu__ZuoraId__c;
        jsonBody.ratePlans.add(rp2);

        RestContext.request.requestBody = Blob.valueOf(JSON.serializePretty(jsonBody));

        Test.startTest();
        CreateQuoteServiceUtil.AllowMultipleQuotes = true;
        CreateQuoteService.createQuote();

        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
       // system.assertEquals(200, RestContext.response.statusCode, RestContext.response.responseBody.toString());
        Test.stopTest();
    }   
    
    @isTest static void test3_newSubscriptionQuote_multipleError() {
        setUp();

        ZuoraTestUtil.ProductCatalog pcatalog = ZuoraTestUtil.createOneProductCatalog('SKU-99991','Recurring', 'Per Unit Pricing');
        update new Product2(Id = pcatalog.products[0].zqu__Product__c, RequiredSPPCategory__c = 'IB Vendor', RequiredSPPInterfaceType__c = 'Integrated');
        
        ZuoraTestUtil.ProductCatalog pcatalog2 = ZuoraTestUtil.createOneProductCatalog('SKU-99992', 'Recurring', 'Volume Pricing');

        Account acct = new Account(Name = 'Test Account');
        System.runAs(getUser()){
            insert acct;
        }
        
        String bilingAccountId = ZuoraTestUtil.generateGUID();
        Zuora__CustomerAccount__c billingAccount = new Zuora__CustomerAccount__c(
            Zuora__Account__c = acct.Id, BillToFlag__c = 'Yes',
            Zuora__External_Id__c = bilingAccountId, Zuora__Zuora_Id__c = bilingAccountId,
            MasterCustomerNumber__c = 'DI9999'
        );
        insert billingAccount;

        Opportunity opp = ZuoraTestUtil.createOpp(acct);
        
        CreateQuoteModel.IncomingJSONBodyWrapper jsonBody = new CreateQuoteModel.IncomingJSONBodyWrapper();
        jsonBody.quoteInformation = new CreateQuoteModel.QuoteInformation();
        jsonBody.quoteInformation.opportunityId = opp.Id;
        jsonBody.quoteInformation.masterCustomerNumber = 'DI9999';
        jsonBody.quoteInformation.startDate = Date.today().addDays(1);
        jsonBody.quoteInformation.quoteType = 'Default';
        jsonBody.quoteInformation.ownerFirstName = UserInfo.getFirstName();
        jsonBody.quoteInformation.ownerLastName = UserInfo.getLastName();
        
        jsonBody.ratePlans = new CreateQuoteModel.RatePlan[]{};
        CreateQuoteModel.RatePlan rp1 = new CreateQuoteModel.RatePlan();
        rp1.name = pcatalog.productRatePlans[0].Name;
        rp1.productRatePlanId = pcatalog.productRatePlans[0].zqu__ZuoraId__c;
        rp1.tpv = 'Test SPP';
        jsonBody.ratePlans.add(rp1);
        
        CreateQuoteModel.RatePlan rp2 = new CreateQuoteModel.RatePlan();
        rp2.name = pcatalog2.productRatePlans[0].Name;
        rp2.productRatePlanId = pcatalog2.productRatePlans[0].zqu__ZuoraId__c;
        rp2.tiers = new CreateQuoteModel.RatePlanTier[]{};
        CreateQuoteModel.RatePlanTier t1 = new CreateQuoteModel.RatePlanTier();           
        t1.tier = 1;
        t1.startingUnit = 0;
        t1.endingUnit = 99;
        t1.price = 100;
        rp2.tiers.add(t1);
        CreateQuoteModel.RatePlanTier t2 = new CreateQuoteModel.RatePlanTier();           
        t2.tier = 2;
        t2.startingUnit = 100;
        t2.endingUnit = null;
        t2.price = 90;
        rp2.tiers.add(t2);
        jsonBody.ratePlans.add(rp2);

        String jsonString = JSON.serializePretty(jsonBody);
        RestContext.request.requestBody = Blob.valueOf(jsonString);
        
        CreateQuoteService.createQuote();

        system.debug(RestContext.response.statusCode);
        system.debug(RestContext.response.responseBody.toString());
        //system.assertEquals(200, RestContext.response.statusCode, RestContext.response.responseBody.toString());
        Test.startTest();
        CreateQuoteService.createQuote();
        system.assertEquals(500, RestContext.response.statusCode, RestContext.response.responseBody.toString());
        Test.stopTest();
    }   


}