force-app/main/default/objects/Account/fields/Interface_Type__c.field-meta.xml
<CustomField>
    <fullName>Interface_Type__c</fullName>
    <label>Interface Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Batch</fullName>
                <default>true</default>
                <label>Batch</label>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Real-Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <externalId>true</externalId>
    <label>Site Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>Site record type is used to represent Sites/Locations related to an Account.</description>
    <label>Site</label>
</RecordType>

force-app/main/default/objects/Customer_Document__c/Customer_Document__c.object-meta.xml
<CustomObject>
    <description>Track status&apos;s and other information that will be sent from DocuSign.</description>
    <label>CLM Document History</label>
    <nameField>
        <label>Customer Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLM Documents History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Document__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Executing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Ready to Send to Customer for Signature</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Ready for Preview</fullName>
            </value>
            <value>
                <fullName>Choose the Salesperson to email to</fullName>
            </value>
            <value>
                <fullName>Customer is Redlining Document</fullName>
            </value>
            <value>
                <fullName>Additional User is Approving</fullName>
            </value>
            <value>
                <fullName>Sales is reviewing Customer redlines</fullName>
            </value>
            <value>
                <fullName>Sales is Sending for Additional Review</fullName>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Customer is Redlining Other Documents, Order Form has not been sent</fullName>
            </value>
            <value>
                <fullName>Sales Review</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Signature Cancelled</fullName>
            </value>
            <value>
                <fullName>Signature Request Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Document__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Customer_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/Interface_Log__c.object-meta.xml
<CustomObject>
    <description>Custom object to capture Inbound/Outbound interfacing details between CPQ and other downstream application.</description>
    <label>Interface Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Interface Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interface Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interface_Log__c/fields/Fulfillment_Order__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fulfillment Order</label>
    <referenceTo>qtc_FulfillmentOrder__c</referenceTo>
    <relationshipLabel>Interface Logs</relationshipLabel>
    <relationshipName>Interface_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Interface_Type__c.field-meta.xml
<CustomField>
    <fullName>Interface_Type__c</fullName>
    <label>Interface Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Interface Logs</relationshipLabel>
    <relationshipName>Interface_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Interface Logs</relationshipLabel>
    <relationshipName>Interface_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>65536</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>66536</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Retry_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempt__c</fullName>
    <label>Retry Attempt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/qtc_Multi_Site__c.field-meta.xml
<CustomField>
    <fullName>qtc_Multi_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if an order&apos;s quote is Multi-Site</description>
    <label>Multi-Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/qtc_Multi_Site_Type__c.field-meta.xml
<CustomField>
    <fullName>qtc_Multi_Site_Type__c</fullName>
    <description>specifies the type of multi-site deal being configured. All quotes in the child/parent relationship should share the same value</description>
    <label>Multi-Site Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE+PP</fullName>
            </value>
            <value>
                <fullName>AE Only</fullName>
            </value>
            <value>
                <fullName>PP Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrder__c/qtc_FulfillmentOrder__c.object-meta.xml
<CustomObject>
    <label>Fulfillment Order</label>
    <nameField>
        <label>Fulfillment Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/qtc_FulfillmentOrder__c/fields/qtc_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>qtc_Sequence_Number__c</fullName>
    <description>First time quote is submitted to ERP it is sent with number 0, Next time when same quote is submitted its sequence will increase by 1 each time it&apos;s resubmitted.</description>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrder__c/fields/Retry_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempt__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Attempt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CPQ_Util.cls
public with sharing class CPQ_Util {
    
    private static final String QUOTE_TYPE_AMENDEMENT = 'Amendment';
    private static final String QUOTE_TYPE_QUOTE = 'Quote';
    // Retrun value if String variable is not null else return empty string.
    public static String safeString(String val) {
        String returnVal = '';
        if (val != null) {
            returnVal = val;
        }
        return returnVal;
    }
    
    // MCN account information
    public static Account getAccount(String masterCustomerNumber) {
        Account act;
        
        if (String.isBlank(masterCustomerNumber)) {
            return null;
        } else {
            List<Account> actLst = [SELECT Id, Name, Master_Customer_Number__c 
                                    FROM Account WHERE Master_Customer_Number__c =: masterCustomerNumber];
            if (!actLst.isEmpty()) {
                act = actLst[0];
            }
        }
        return act;
    }
    
    // Returns bill to site information based on site number.
    public static Account getSite(String siteNumber) {
        Account act;
        
        if (String.isBlank(siteNumber)) {
            return null;
        } else {
            List<Account> actLst = [SELECT Id, Name, Site_Number__c, ParentId 
                                    FROM Account WHERE Site_Number__c =: siteNumber];
            if (!actLst.isEmpty()) {
                act = actLst[0];
            }
        }
        return act;
    }
    
    
    // This method is to capture Interface Log
    public boolean createLog(String transactionID,String status, String interfaceMessage,  String request, 
                             String response,String requestType, qtc_FulfillmentOrder__c  fo,
                             Id quote,Id opp, String interfaceType) {
                                 Interface_Log__c obj=  new Interface_Log__c();
                                 obj.Request__c = request;
                                 obj.Response__c = response;
                                 obj.RequestType__c	 = requestType;
                                 obj.Status__c = status;
                                 obj.Transaction_ID__c = transactionID;
                                 if( fo != null){
                                     
                                     obj.Sequence_Number__c	= fo.qtc_Sequence_Number__c	;
                                     obj.Retry_Attempt__c = fo.Retry_Attempt__c;
                                     obj.Fulfillment_Order__c = fo.id;
                                     
                                 }
                                 obj.Quote__c = quote;
                                 obj.Opportunity__c = opp;
                                 obj.Message__c = interfaceMessage;
                                 obj.Interface_Type__c = interfaceType;
                                 
                                 try{
                                     
                                     Insert obj; 
                                     return true;
                                     
                                 }catch(Exception e){
                                     return false;
                                 }
                                 
                                 
                             } 
    
    public String getRequestJSONAsString(RestRequest request){
        if(request!=null){
            return request.requestBody.toString();
        }else{
            return request.toString();
        }
    }
    
    public String getResponseJSONAsString(RestResponse response){
        return response.responseBody.toString();
    }
    public String getRequestJSONAsString(HttpRequest request){
        if(request!=null){
            return String.valueOf(request.getBody());
        }else{
            return String.valueOf(request);
        }
    }
    
    public String getResponseJSONAsString(HttpResponse response){
        return String.valueOf(response);
    }
    
    public string dateString(Datetime dt) {
        if(dt!=null){
            String myDatetime;
            string day;
            string month;
            string year;
            integer i;
            myDatetime = String.valueOfGmt(dt);
            string[] dttime = myDatetime.split('-');
            year = dttime[0];
            i = Integer.valueOf(dttime[1]);//month
            day = dttime[2].split(' ')[0];
            if(i==1){
                month = 'JAN';
            }else if(i==2){
                month = 'FEB';
            }
            else if(i==3){
                month = 'MAR';
            }
            else if(i==4){
                month = 'APR';
            }
            else if(i==5){
                month = 'MAY';
            }
            else if(i==6){
                month = 'JUN';
            }
            else if(i==7){
                month = 'JUL';
            }
            else if(i==8){
                month = 'AUG';
            }
            else if(i==9){
                month = 'SEP';
            }
            else if(i==10){
                month = 'OCT';
            }
            else if(i==11){
                month = 'NOV';
            }
            else if(i==12){
                month = 'DEC';
            }
            return (day+'-'+month+'-'+year);
        } Else {
            return '';
        }
    }
    
    public static Boolean getQulifiedQuotesForAlert(ID quoteID) {
             
        // Start
        SBQQ__Quote__c quoteRec = getQuotesWithCLMDoc(quoteId);
        if(quoteRec != null){
            return true;
        }else{
            return false;
        }
        
        
    }
    
    public static  SBQQ__Quote__c getQuotesWithCLMDoc(Id qid){   
        
        List<SBQQ__QuoteLine__c> qlines = [Select id,SBQQ__quote__r.qtc_Multi_Site__c,SBQQ__quote__r.qtc_Multi_Site_Type__c,SBQQ__quote__r.SBQQ__Type__c from SBQQ__QuoteLine__c where Revenue_Type__c = 'Payments Processing' and Product_Type__c = 'Sub-Package' and SBQQ__RequiredBy__c = null and SBQQ__Quote__c=:qid ];
        if (qlines.size() == 0 ) {
            SBQQ__Quote__c quote = CPQMSQuoteForAmendmentDocument.getQuoteDetailById(qid);
            if(quote.SBQQ__Type__c == QUOTE_TYPE_QUOTE){
                return [Select Name,(Select Id, Document_Status__c,Document_Type__c From Customer_Documents__r 
                                              Where Document_Type__c = 'AE Order Form'  order by LastModifiedDate desc limit 1 )
                                 From SBQQ__Quote__c where id =: qid];
                
            }else if (quote.SBQQ__Type__c == QUOTE_TYPE_AMENDEMENT){
                return [Select Name,(Select Id, Document_Status__c,Document_Type__c From Customer_Documents__r 
                                              Where Document_Type__c = 'AE Amendment'  order by LastModifiedDate desc limit 1 )
                                 From SBQQ__Quote__c where id =: qid];
            }
            return null;
        }else{
            return null;
        }
        
        
        
    }
    
}