force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>End-user Customer account that is in a RoR country</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/CADDDoNotReply__c/CADDDoNotReply__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CADD Do Not Reply</label>
</CustomObject>

force-app/main/default/objects/Deming__c/Deming__c.object-meta.xml
<CustomObject>
    <label>CADD Management</label>
    <nameField>
        <displayFormat>CADD-{0000}</displayFormat>
        <label>CADD Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CADD Management</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deming__c/fields/Customer_Country_code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Country_code__c</fullName>
    <description>Customer Country Code</description>
    <label>Customer Country code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_No__c</fullName>
    <description>Customer MCN Number</description>
    <label>MCN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/EditShareWithUser__c.field-meta.xml
<CustomField>
    <fullName>EditShareWithUser__c</fullName>
    <label>EditShareWithUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Max_Promise_Date__c.field-meta.xml
<CustomField>
    <fullName>Max_Promise_Date__c</fullName>
    <label>Arrival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <label>Order Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Order_number__c.field-meta.xml
<CustomField>
    <fullName>Order_number__c</fullName>
    <externalId>true</externalId>
    <label>Order number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CADD Management</relationshipLabel>
    <relationshipName>CADD_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/SalesOrdCode__c.field-meta.xml
<CustomField>
    <fullName>SalesOrdCode__c</fullName>
    <label>SalesOrgCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/SalesPerson_Global_Id__c.field-meta.xml
<CustomField>
    <fullName>SalesPerson_Global_Id__c</fullName>
    <description>Sales Person Gobal Id</description>
    <label>Salesperson Global Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/ERP_Orders_Backlog__c.object-meta.xml
<CustomObject>
    <label>ERP Orders</label>
    <nameField>
        <displayFormat>EOB-{00000000}</displayFormat>
        <label>ERP Orders Backlog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <label>Master Customer Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/Order_Line_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Line Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ERP_Orders_Backlog__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/NCR_Employee_Detail__c.object-meta.xml
<CustomObject>
    <description>This object stores the details of all NCR employees.</description>
    <label>NCR Employee Detail</label>
    <nameField>
        <label>NCR Employee Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCR Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_ID__c</fullName>
    <label>Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/InActive__c.field-meta.xml
<CustomField>
    <fullName>InActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/Sales_Org_Temp__c.object-meta.xml
<CustomObject>
    <description>This Objects receives the data from iPaaS.</description>
    <label>Sales Org Temp</label>
    <nameField>
        <label>Sales Org Temp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Temps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Hierarchy_2__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_2__c</fullName>
    <label>Hierarchy 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_ID__c</fullName>
    <label>User Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SynkCSM_To_CADDTest.cls
@isTest 
private class SynkCSM_To_CADDTest {
    static testMethod void Method1() {
        /* CADDDoNotReply__c TargetObjectIdEmial = new CADDDoNotReply__c();
TargetObjectIdEmial.UserID__c='0050g000006HbDe';
TargetObjectIdEmial.Name='Do Not Reply User For CADD';
insert TargetObjectIdEmial;*/
        UserRole role = [Select Id, Name FROM UserRole LIMIT 1];
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = '04 NSC UI Administrator' Limit 1];
        User u2 = new User();
        u2.Username = 'sysAdmin@ncr.com';
        u2.UserRole= role ;
        u2.ProfileId = adminProfile.Id;
        u2.Alias = 'admin123';
        u2.Email = 'sm245977@gmail.com';
        u2.EmailEncodingKey = 'UTF-8';
        u2.LastName = 'systemAdmin';
        u2.CommunityNickname = 'adminUser';
        u2.TimeZoneSidKey = 'America/Los_Angeles';
        u2.LocaleSidKey = 'en_US';
        u2.LanguageLocaleKey = 'en_US';
        u2.FederationIdentifier = 'admin333';
        u2.Quicklook_ID__c = 'admin330';
        insert u2;
          system.assert(u2.Id!=null);
        Account a = TestRecordsFactory.createAccount('7392826','FINANCIAL:BANKING MAJOR','INDIA');
        
        Deming__c DemObj1= new Deming__c();
        DemObj1.Order_Id__c='47593451';                                      //Select id,Order_Number__c,Order_Line_Id__c from ERP_Orders_Backlog__c          208395648
        //DemObj1.SalesPerson_Global_Id__c='14200124419-201100959';           //Select id,Global_ID__c,Quicklook_ID__c,InActive__c from NCR_Employee_Detail__c  41477033784-20110098
        DemObj1.SalesOrdCode__c='201100959';                               //Select id,Sales_Org_Code__c,Hierarchy_2__c from Sales_Org_Temp__c
        DemObj1.Customer_No__c='8511908';
        DemObj1.Order_number__c='5340549';
        DemObj1.Customer_Country_code__c= 'US'; //Select id,Name,Master_Customer_Number__c,Owner.Email from Account  8533019PH
        DemObj1.Max_Promise_Date__c=System.today();
        DemObj1.EditShareWithUser__c=u2.id;
        DemObj1.RelatedAccount__c=a.id;
        Insert DemObj1;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId=a.id;
        atm.UserId=u2.id;
        atm.TeamMemberRole='Customer Success Manager';
        atm.AccountAccessLevel='Read';
        insert atm;  
        
        atm.TeamMemberRole='Account Manager';
        update atm;
        atm.TeamMemberRole='Customer Success Manager';
        update atm;
        Delete atm; 
        
        AccountTeamMember atm1 = new AccountTeamMember();
        atm1.AccountId=a.id;
        atm1.UserId=u2.id;
        atm1.TeamMemberRole='Implementation Coordinator';
        atm1.AccountAccessLevel='Read';
        
        insert atm1;  
        
        atm1.TeamMemberRole='Account Manager';
        update atm1;
        atm1.TeamMemberRole='Customer Success Manager';
        update atm1;
        Delete atm1;
        system.assertEquals(atm1.TeamMemberRole,'Customer Success Manager');
       
      
    }
    
}