force-app/main/default/objects/Account/fields/Master_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Master Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tab_Access__c/Tab_Access__c.object-meta.xml
<CustomObject>
    <label>Tab Access</label>
    <nameField>
        <label>Tab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tab Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tab_Access__c/fields/Daily_View_Count__c.field-meta.xml
<CustomField>
    <fullName>Daily_View_Count__c</fullName>
    <label>Daily View Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tab_Access__c/fields/Metrics_Date__c.field-meta.xml
<CustomField>
    <fullName>Metrics_Date__c</fullName>
    <label>Metrics Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tab_Access__c/fields/PageName__c.field-meta.xml
<CustomField>
    <fullName>PageName__c</fullName>
    <label>Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tab_Access__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tab_Access__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <externalId>true</externalId>
    <label>UniqueId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tab_Access__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tab_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InactiveLeadAndContactEmail</label>
</CustomObject>

force-app/main/default/classes/ContractActionCntrl.cls
/*
##################################################################################################
# Project Name..........: CLM
# File............................: ContractActionCntrl.cls                                                        
# Created by................: Varsha Pal                                                                   
# Created Date...........: 27/08/2021 (MM/DD/YYYY)                                                                             
# Last Modified by......:  Varsha Pal
# Last Modified Date..: 31/08/2021 (MM/DD/YYYY)
# Description...............: This class will track the history of contract actions button usage per user per day limit and
it will be called from two flows(Contract Action) and Contract Action on Account(EBA_SF-1481)
History #
LastModifiedBy         LastModifiedDate                  Story#
Varsha                 03/10/2022(MM/DD/YYYY)            
##################################################################################################
*/
public class ContractActionCntrl {
    public PageReference urlRedirection() {
       //Changes done by Yogesh - EBA_SF-1732
        /*	String obj = apexpages.currentpage().getparameters().get('obj');
        String  pName = apexpages.currentpage().getparameters().get('page');
        System.debug('object'+obj);
        system.debug('pname'+pName);
        string url = apexpages.currentpage().getparameters().get('url');
        System.debug('url'+url);*/
        String obj = String.escapeSingleQuotes(apexpages.currentpage().getparameters().get('obj'));
        String  pName = String.escapeSingleQuotes(apexpages.currentpage().getparameters().get('page'));
        string url = String.escapeSingleQuotes(apexpages.currentpage().getparameters().get('url'));  
       	String aid = String.escapeSingleQuotes(apexpages.currentpage().getparameters().get('acid'));  
        //End Changes 
        if(obj!=null&&pName!=null) {
            String tabAccssUniqueId = pName + obj + Userinfo.getUserId() + String.valueOf(Datetime.now().format('yyMMdd'));
            
            List<Tab_Access__c > tabAccList = [Select UniqueId__c, Daily_View_Count__c  from Tab_Access__c where UniqueId__c = :tabAccssUniqueId LIMIT 1];
            
            Tab_Access__c ta;
            if (tabAccList != null && tabAccList.size() > 0) {
                ta =  tabAccList.get(0);
                ta.Daily_View_Count__c  = ta.Daily_View_Count__c + 1;    
            } else {
                ta = new Tab_Access__c(Name = 'Contract Action', Source_Object__c=obj,PageName__c = pName, Metrics_Date__c = Date.today(), User__c= Userinfo.getUserId(), UniqueId__c= tabAccssUniqueId, Daily_View_Count__c  = 1);        
            }
           	upsert ta UniqueId__c; 
            
        }
        PageReference page = null;
        if(url!=null){
            url = EncodingUtil.urlDecode(url,'UTF-8');
            if(aid!=null){
                Account a = [Select Name, Master_Customer_Number__c from Account where id =:aid];
                url = url.replace('accName',EncodingUtil.urlEncode(a.Name,'UTF-8'));
                url = url.replace('accMCN',EncodingUtil.urlEncode(a.Master_Customer_Number__c,'UTF-8'));
            }
           	page = new PageReference(url);
            System.debug('final url'+EncodingUtil.urlDecode(url,'UTF-8'));
            page.setRedirect(true);
        }
        return page;
    }
    
}