force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.SuspendProcessing_Contact__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Contact</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/NCR_CPQBLG_Email__c/NCR_CPQBLG_Email__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NCR CPQBLG Email</label>
</CustomObject>

force-app/main/default/objects/Order/fields/Deliver_To_Site__c.field-meta.xml
<CustomField>
    <fullName>Deliver_To_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Twinned from Quote</description>
    <label>Deliver To Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Deliver To Site)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrder__c/qtc_FulfillmentOrder__c.object-meta.xml
<CustomObject>
    <label>Fulfillment Order</label>
    <nameField>
        <label>Fulfillment Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/qtc_FulfillmentOrder__c/fields/qtc_OrderStartDate__c.field-meta.xml
<CustomField>
    <fullName>qtc_OrderStartDate__c</fullName>
    <label>Order Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/qtc_FulfillmentOrder__c/fields/qtc_Quote__c.field-meta.xml
<CustomField>
    <fullName>qtc_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Fulfillment Orders</relationshipLabel>
    <relationshipName>Fulfillment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FulfillmentOrderReport.cls
global class FulfillmentOrderReport implements Schedulable{
    public Id partnerId{get;set;}
    public String getInstanceURL(){
        return System.URL.getSalesforceBaseURL().toExternalForm();
    }
    private DateTime getOrderStartDateUpperLimit(){
        DateTime dt1 = DateTime.now();
		DateTime dt2= DateTime.newInstance(dt1.year(), dt1.month()+1, 1, dt1.hour(),dt1.minute(),dt1.second());
        return dt2;
    }
    public String getAlohaBusinessEmail(){
        return NCR_CPQBLG_Email__c.getValues('Order Management').Email__c;
    } 
    
    public List<qtc_FulfillmentOrder__c> getFulfillmentOrders() {
        List<qtc_FulfillmentOrder__c> fulfillmentOrders;
		String qry='SELECT Id, Name,qtc_Quote__r.Name, qtc_Quote__r.SBQQ__Partner__r.Name, qtc_Quote__r.SBQQ__Account__r.Name, qtc_Quote__r.Deliver_To_Site__r.Name,qtc_OrderStartDate__c FROM qtc_FulfillmentOrder__c WHERE qtc_Quote__r.SBQQ__Partner__c= :partnerId AND qtc_Quote__r.SBQQ__Ordered__c = false AND qtc_OrderStartDate__c <= ' +getOrderStartDateUpperLimit().format('yyyy-MM-dd');
        fulfillmentOrders = Database.query(qry);        
        return fulfillmentOrders;
    }
    
    global void execute(SchedulableContext sc){
        List<Messaging.SingleEmailMessage> lstMessages = new List<Messaging.SingleEmailMessage>();
        
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'salesforce.donotreply@ncr.com'];
        
        EmailTemplate et = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where DeveloperName ='Fulfillment_Order_Reports_For_Channel'];
		List<qtc_FulfillmentOrder__c> fOrders;
        String qry2 ='SELECT qtc_Quote__r.SBQQ__Partner__r.Primary_Contact__c, qtc_Quote__r.SBQQ__Partner__r.Primary_Contact__r.Email FROM qtc_FulfillmentOrder__c Where qtc_Quote__r.qtc_Channel_Local_Office_Record_Type__c = \'PARTNER\' AND qtc_Quote__r.SBQQ__Ordered__c = false AND qtc_OrderStartDate__c <= '+ getOrderStartDateUpperLimit().format('yyyy-MM-dd')+ ' ORDER BY qtc_Quote__r.SBQQ__Partner__c';
        fOrders = Database.query(qry2);        
        Id prevPartnerId = null;
        String prevEmail = null;
        Id currentPartnerId = null;
        String currentEmail = null;
        Set<Account> partners = new Set<Account>();
        for(qtc_FulfillmentOrder__c fo : fOrders){
            Id oid = fo.qtc_Quote__r.SBQQ__Partner__r.Primary_Contact__c;
            if(oid == null){
                System.debug('Error > No primary contact of partner account');
                continue;
            }
            partners.add(fo.qtc_Quote__r.SBQQ__Partner__r);
            }
        sendEmail(owea, et, partners);
        
    }
    
    @TestVisible private void sendEmail(OrgWideEmailAddress[] owea, EmailTemplate et, Set<Account> partners){
        try{
            List<Messaging.SingleEmailMessage> lstMessages = new List<Messaging.SingleEmailMessage>();
            for(Account partner : partners){
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setSaveAsActivity(false);
            if ( owea.size() > 0 ) {
                    Message.setOrgWideEmailAddressId(owea.get(0).Id);
                }
            message.setTemplateId(et.Id);
            message.setTargetObjectId(partner.Primary_Contact__c);
            message.setTreatTargetObjectAsRecipient(false);
            message.setWhatId(partner.Id);
            
            message.toAddresses = new List<String> {partner.Primary_Contact__r.Email};
                lstMessages.add(message);
            }
            List<Messaging.SendEmailResult> lstResults = Messaging.sendEmail(lstMessages);
        } catch (Exception ex) {
            system.debug('***'+ex.getLineNumber());
            system.debug('***'+ex.getMessage());
            system.debug('***'+ex.getCause());
            system.debug('***'+ex.getStackTraceString());
        }
    }
}