force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Theater</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CATM_Record__c.field-meta.xml
<CustomField>
    <fullName>CATM_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CATM Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_End_Date_Override__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CATM</description>
    <label>Contract End Date Override?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Owner_Expiration_Notice__c.field-meta.xml
<CustomField>
    <fullName>Owner_Expiration_Notice__c</fullName>
    <description>CATM</description>
    <label>Owner Expiration Notice (Days)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>135</fullName>
            </value>
            <value>
                <fullName>180</fullName>
            </value>
            <value>
                <fullName>210</fullName>
            </value>
            <value>
                <fullName>270</fullName>
            </value>
            <value>
                <fullName>360</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Owner_Expiration_Notice_Date__c.field-meta.xml
<CustomField>
    <fullName>Owner_Expiration_Notice_Date__c</fullName>
    <description>CATM</description>
    <label>Last Day of Owner Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>CATM</description>
    <formula>Opportunity__r.Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CATM Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewal_Period_Months__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Period_Months__c</fullName>
    <description>CATM</description>
    <label>Renewal Period (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <description>CATM</description>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automatic Extension</fullName>
            </value>
            <value>
                <fullName>Fixed End Date</fullName>
            </value>
            <value>
                <fullName>Option to Extend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractExpireUpdateBatch.cls
global class ContractExpireUpdateBatch implements Database.Batchable<sObject> {
    // Start Method
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //Id recordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('FI Contract').getRecordTypeId();
        String query = 'SELECT Id, AccountId, OwnerExpirationNotice, Account.region__c, StartDate, EndDate,Renewal_Type__c,'+
            'Owner_Expiration_Notice__c, Owner_Expiration_Notice_Date__c,Renewal_Period_Months__c,  Contract_End_Date_Override__c '+
            ' FROM Contract where Renewal_Type__c=\'Automatic Extension\' AND Status = \'Activated\' AND Contract_End_Date_Override__c = true '+
            'AND Account.region__c =\'NABG\' AND Owner_Expiration_Notice_Date__c = today AND catm_record__c = true';
        System.debug('qry '+query);
        return Database.getQueryLocator(query);   
    }
    //Execute Method
    global void execute(Database.BatchableContext BC, List<Contract> scope) {
        if(scope!=null && scope.size()>0){
            List<Contract> upplistContract = new List<Contract>();
            for(Contract con : scope)
            {
                if(con.CATM_Record__c) {
                    integer dt = Integer.valueOf(con.Renewal_Period_Months__c);
                    
                    con.EndDate = con.EndDate.addMonths(dt);
                    upplistContract.add(con);
                    system.debug('upplistContract 1'+upplistContract); 
                }

            }
            try{
                if(!upplistContract.isEmpty() && upplistContract!=null){
                    update upplistContract;
                    system.debug('upplistContract'+upplistContract);
                }
                
            }
            catch(Exception ex){
                System.debug(' stack trace  '+ex.getStackTraceString());
                System.debug(' excetion  '+ex);
            }
        }
        
    }
    // Finish Method
    global void finish(Database.BatchableContext BC) {
        
    }
    
}