force-app/main/default/objects/Account/fields/Service_Partner__c.field-meta.xml
<CustomField>
    <fullName>Service_Partner__c</fullName>
    <inlineHelpText>The Service Partner ID is the unique identifier of the Partner Account for Diagnostic Dongle Key Issuance/Renewal. First 2 letters are country abbreviation followed by 2 numbers</inlineHelpText>
    <label>Service Partner ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Engineers__c/Engineers__c.object-meta.xml
<CustomObject>
    <description>For NCR Partner Channel - Partner Portal.  Will track all partner engineers and registrations.</description>
    <label>Engineer</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Engineers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engineers__c/fields/Active_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Active_Engineer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Engineer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <defaultValue>null</defaultValue>
    <label>First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Account Name that you are employed by</inlineHelpText>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Account.Partner_Type__c</field>
            <operation>equals</operation>
            <value>Dealer, Deployer, Distributor, Master VAR, Solution Provider</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engineers</relationshipLabel>
    <relationshipName>Engineers</relationshipName>
    <trackHistory>false</trueHistory>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PrometricVoucherRequest.cls
public class PrometricVoucherRequest{
    public ApexPages.standardController controller {get; set;}
    public Engineers__c engineers{ get; set; }
    public boolean mailcontent{get; set;}
    public boolean errorcontent{get; set;}
    public String mailBody {get; set;}
    public PrometricVoucherRequest(ApexPages.StandardController stdController) {
        controller = stdController;
        engineers = [Select Id, Owner.Name, Partner_Account__r.Name, First_Name__c, Last_Name__c, Active_Engineer__c from Engineers__c where id = :stdController.getid() limit 1].get(0);
        //Partner_Account__r.Service_Partner__c -Removed From select query due to EBA_SF-688
        if(engineers.Active_Engineer__c == false){
            errorcontent = true;
            mailcontent = false;
        }
        else{
            mailcontent = true;
            errorcontent = false;
        }
    }
    public PageReference sendMail(){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddress = new String[]{'pa230005@ncr.com'};
        mail.setToAddresses(toAddress);
        mail.setSubject('Prometric Voucher Request');
        mail.setBccSender(false);
        mail.setUseSignature(false);
        mail.setHTMLBody('Engineer Name : '+engineers.First_Name__c+' '+engineers.Last_Name__c+'<br/> Account Name : '+ engineers.Partner_Account__r.Name +'<br/>SalesForce ID : '+engineers.id+'<br/>Additional Information:<table><tr><td>&nbsp;</td><td><pre style="font-family:Times New Roman;font-size:12pt">'+mailBody+'</pre></td></tr></table>Thank You,<br/>NCR SalesCentral Administration');
        //Service Partner ID : '+engineers.Partner_Account__r.Service_Partner__c+'<br/> removed due to EBA_SF-688
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        PageReference pageref = new PageReference('/'+engineers.id);
        return pageref;
    }
    public PageReference cancel(){
        PageReference pageref = new PageReference('/'+engineers.id);
        return pageref;
    }
}