force-app/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <externalId>true</externalId>
    <label>Site Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/Is_Processed_By_Contract_End_Batch__c.field-meta.xml
<CustomField>
    <fullName>Is_Processed_By_Contract_End_Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag is set to TRUE by CPQ_ProcessContractEndBatch batch class. This class picks the Contract which are Ended or Terminated and process them and set this flag to true.</description>
    <label>Is Processed By Contract End Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/qtc_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>qtc_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be set on account creation from the Order. The user can then update this field to update Bill To Site on related Orders.</description>
    <label>Bill To Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Bill_To__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/qtc_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>qtc_Termination_Date__c</fullName>
    <description>Date, when the contract is terminated.</description>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CPQ_ProcessContractEndBatch.cls
public with sharing class CPQ_ProcessContractEndBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    
    public Database.QueryLocator  start(Database.BatchableContext bc) {
        String query = 'SELECT Id, SBQQ__Quote__c, qtc_Bill_To_Account__r.Site_Number__c, Is_Processed_By_Contract_End_Batch__c FROM Contract WHERE (EndDate <= Today OR qtc_Termination_Date__c <= Today) AND (Is_Processed_By_Contract_End_Batch__c = false)';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, list<Contract> contracts) {
        List<Contract> contractToUpdate = new List<Contract>();
        for (Contract contractRec : contracts) {
            if (contractRec.qtc_Bill_To_Account__c != null) {
                GenerateLegalDocumentService.myNcrCallout(contractRec.SBQQ__Quote__c, contractRec.qtc_Bill_To_Account__r.Site_Number__c);
                contractRec.Is_Processed_By_Contract_End_Batch__c = true;
                contractToUpdate.add(contractRec);
            }
        }

        if (!contractToUpdate.isEmpty()) {
            update contractToUpdate;
        }
    }

    public void finish(Database.BatchableContext bc){
        // Not yet decided anything for final block
    }
}