force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/SFDC_MDF__c/SFDC_MDF__c.object-meta.xml
<CustomObject>
    <description>Track MDF request details including partner account, requested amount, activity type and date, and approval status.</description>
    <label>Fund Request</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF__c/fields/Claim_Paid_Year__c.field-meta.xml
<CustomField>
    <fullName>Claim_Paid_Year__c</fullName>
    <label>Reimbursed Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/No_of_Submitted_Claims__c.field-meta.xml
<CustomField>
    <fullName>No_of_Submitted_Claims__c</fullName>
    <label>No. of Submitted Claims</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Released_Amount__c.field-meta.xml
<CustomField>
    <fullName>Released_Amount__c</fullName>
    <label>Released Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Released_Funds__c.field-meta.xml
<CustomField>
    <fullName>Released_Funds__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is the replica of  &quot;Released Funds&quot; of claim. This field value come from &quot;Released Funds&quot; field of Claim.</description>
    <label>Released Funds</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Released_Year__c.field-meta.xml
<CustomField>
    <fullName>Released_Year__c</fullName>
    <label>Released Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Request_ID__c.field-meta.xml
<CustomField>
    <fullName>Request_ID__c</fullName>
    <description>A unique id assigned to the fund request. Optionally useful for the partner as a means to identify the specific fund request record.</description>
    <displayFormat>FR-{YY}{MM}{DD}-{0000}</displayFormat>
    <label>Request ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund request approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request Created</fullName>
                <default>true</default>
                <label>Request Created</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Level 1 Review</fullName>
            </value>
            <value>
                <fullName>Level 2 Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Transaction_Reference__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Reference__c</fullName>
    <label>Transaction Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/SFDC_MDF_Claim__c.object-meta.xml
<CustomObject>
    <description>A set of claims tied to a specific fund request.</description>
    <label>Fund Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Accrual_Balance__c.field-meta.xml
<CustomField>
    <fullName>Accrual_Balance__c</fullName>
    <description>Accrual balance is the difference between the remaining accrual and the released funds.</description>
    <formula>Fund_Request__r.Remaining_Accrual__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accrual Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Claim_ID_Txt__c.field-meta.xml
<CustomField>
    <fullName>Claim_ID_Txt__c</fullName>
    <description>Claim I number should be same as Fund Request Number.</description>
    <label>Claim ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Claim_Paid_Month__c.field-meta.xml
<CustomField>
    <fullName>Claim_Paid_Month__c</fullName>
    <label>Reimbursed Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sept</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Fund_Request__c.field-meta.xml
<CustomField>
    <fullName>Fund_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Note: This cannot be a master detail relationship if you plan to use approval workflow as the fund request will be locked (during approval and most likely post approval) and therefore any child claims cannot be saved</description>
    <label>Fund Request</label>
    <referenceTo>SFDC_MDF__c</referenceTo>
    <relationshipLabel>Fund Claims</relationshipLabel>
    <relationshipName>R00N30000002DjDcEAK</relationshipName>
    <trackHistory>false</trueHistory>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Released_Funds__c.field-meta.xml
<CustomField>
    <fullName>Released_Funds__c</fullName>
    <description>Released Funds is manually entered.</description>
    <label>Released Funds</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Released_Month__c.field-meta.xml
<CustomField>
    <fullName>Released_Month__c</fullName>
    <label>Released Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>Jun</fullName>
            </value>
            <value>
                <fullName>Jul</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sep</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Released_Year__c.field-meta.xml
<CustomField>
    <fullName>Released_Year__c</fullName>
    <label>Released Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund claim approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_MdfClaimHandler.cls
/*************************************************************************************************
*   ClassName   : PRM_MdfClaimHandler
*   Description :   
*   Author      :   
# Modification History.: 
Story No         Date           DevName         Description
EBA_SF-1948     20-10-2022      KAVYA SREE      Technical Debt - Apex sharing violation part 2 -PRM 
*************************************************************************************************/
public without sharing class PRM_MdfClaimHandler {
    
    
    /* Update information on MDF request that How many claim is submitted for the request. */ 
    public void totalClaimCount(List<SFDC_MDF_Claim__c> claimList) {
        Set<Id> SFDCMDFIdSet = new Set<Id>();
        for (SFDC_MDF_Claim__c claim : claimList) {
            SFDCMDFIdSet.add(claim.Fund_Request__c);   
        }
        
        Map<Id,SFDC_MDF__c> idToMdfReqMap = new Map<Id,SFDC_MDF__c>([SELECT Id, No_of_Submitted_Claims__c FROM SFDC_MDF__c WHERE Id IN : SFDCMDFIdSet ]);
        
        AggregateResult[] agResultList =  [SELECT  COUNT(ID) submittedClaims,Fund_Request__c from SFDC_MDF_Claim__c WHERE Fund_Request__c IN : SFDCMDFIdSet AND (Status__c = 'Submitted' OR Status__c =  'Approved' OR Status__c = 'Rejected' OR Status__c = 'Paid')  GROUP BY Fund_Request__c ];
        
        Map<Id,AggregateResult> mdfReqIdToAggRes = new Map<Id,AggregateResult>();
        
        for(AggregateResult agResult : agResultList) {
            mdfReqIdToAggRes.put((Id)agResult.get('Fund_Request__c'),agResult);
        } 
        
        List<SFDC_MDF__c> MDFReqList = new List<SFDC_MDF__c>();
        
        for (SFDC_MDF__c fundReq : idToMdfReqMap.values()) {
            if (mdfReqIdToAggRes.get(fundReq.Id) != null) {
                if (fundReq.No_of_Submitted_Claims__c != (Decimal)(mdfReqIdToAggRes.get(fundReq.Id)).get('submittedClaims')) {
                    fundReq.No_of_Submitted_Claims__c = (Decimal)(mdfReqIdToAggRes.get(fundReq.Id)).get('submittedClaims');
                    MDFReqList.add(fundReq);
                } 
            } else if(fundReq.No_of_Submitted_Claims__c != 0) {
                fundReq.No_of_Submitted_Claims__c = 0;
                MDFReqList.add(fundReq);
            }
        }
        
        if (MDFReqList.size() > 0) { 
            update MDFReqList;
        }
    }
    
    public void creatClaimId(List<SFDC_MDF_Claim__c> newList) {
        /* Update information on MFF request that How many claim is submitted for the request. */  
        
        /* This Trigger creates claim Id based on MDF Request Id */
        Set<Id> FundReqIds = new Set<Id>();
        
        
        for(SFDC_MDF_Claim__c claim : newList) {
            
            FundReqIds.add(claim.Fund_Request__c);
        }
        
        Map<Id,SFDC_MDF__c> idToMDFReq = new Map<Id,SFDC_MDF__c>([SELECT id, Request_ID__c FROM SFDC_MDF__c WHERE Id IN: FundReqIds]);
        
        for(SFDC_MDF_Claim__c claim : newList) {
            if (idToMDFReq.get(claim.Fund_Request__c) != null && idToMDFReq.get(claim.Fund_Request__c).Request_ID__c != null) {
                String str = idToMDFReq.get(claim.Fund_Request__c).Request_ID__c;
                claim.Claim_Id_Txt__c = 'FC'+str.remove('FR');
            }
        }
    }
    
    
    
    public void updateClaimInfoOnMDF(List<SFDC_MDF_Claim__c> newList) {
        List<SFDC_MDF__c> fundRequesList = new List<SFDC_MDF__c>();
        // Map<Id, SFDC_MDF__c> FundCklaiMap =new Map<Id, SFDC_MDF__c>();
        
        for(SFDC_MDF_Claim__c  claim : newList) {
            SFDC_MDF__c  sfdcRequest = new SFDC_MDF__c();
            sfdcRequest.Id  = claim.Fund_Request__c;
            If(claim.Claim_Paid_Month__c != null || claim.Claim_Paid_Year__c != null){
                sfdcRequest.Claim_Paid_Month__c = Claim.Claim_Paid_Month__c;
                sfdcRequest.Claim_Paid_year__c = Claim.Claim_Paid_year__c;
                fundRequesList.add(sfdcRequest);
            }
            
        }
        If (fundRequesList != null && !fundRequesList .isEmpty()) {
            database.update(fundRequesList,false);
        }
    }
    
    public void updateTrasactionRefOnMDFReq (List<SFDC_MDF_Claim__c> newList) {
        Set<Id> mdfReqIds = new Set<Id>();
        Set<Id> claimIds  = new Set<Id>();
        
        Map<Id,SFDC_MDF_Claim__c> mdfReqIdToClaimRec = new Map<Id,SFDC_MDF_Claim__c>();
        
        List<SFDC_MDF__c> mdfReqs = new List<SFDC_MDF__c>();
        
        for (SFDC_MDF_Claim__c claim : newList) {
            //claimIds.add(claim.Id);
            mdfReqIdToClaimRec.put(claim.Fund_Request__c,claim);
        }
        
        for (SFDC_MDF__c mdfReq : [SELECT Id, Transaction_Reference__c FROM SFDC_MDF__c WHERE Id IN : mdfReqIdToClaimRec.keySet()]) {
            if (mdfReqIdToClaimRec.get(mdfReq.Id) != null && mdfReqIdToClaimRec.get(mdfReq.Id).Transaction_Reference__c != null && mdfReq.Transaction_Reference__c == null) {
                mdfReq.Transaction_Reference__c  = mdfReqIdToClaimRec.get(mdfReq.Id).Transaction_Reference__c;
                mdfReqs.add(mdfReq);
            }
        }
        
        if (mdfReqs.size() > 0) {
            update mdfReqs;
        }
    }
    
    public void updateAccrualBalanceAIAU(List<SFDC_MDF_Claim__c> newList) {
        // This trigger has been written to full fill below requirments
        // "Accrual Balance" on the REQUEST page should be reflective of the "Accrual Balance" on the CLAIM page.
        Set<Id> claimIds = new Set<Id>();
        Set<Id> mdfReqIds = new Set<Id>();
        
        
        for (SFDC_MDF_Claim__c claim : newList) {
            if (claim.Fund_Request__c != null) {
                claimIds.add(claim.Id);
                mdfReqIds.add(claim.Fund_Request__c);
            }
            
        }
        List<SFDC_MDF_Claim__c> claims = [SELECT Id, Name, Fund_Request__c, Accrual_Balance__c, Released_Funds__c FROM SFDC_MDF_Claim__c WHERE Id IN: claimIds];
        
        
        // Find MDF Request Ids on which we needs to update Accrual Balance
        for(SFDC_MDF_Claim__c claim : claims) {
            if (claim.Fund_Request__c != null)
                mdfReqIds.add(claim.Fund_Request__c);
        }
        
        Map<Id,SFDC_MDF__c> idToMdfMap = new Map<Id,SFDC_MDF__c>([SELECT ID, Released_Funds__c FROM SFDC_MDF__c WHERE Id IN: mdfReqIds]);
        
        List<SFDC_MDF__c> mdfReqToUpdate = new List<SFDC_MDF__c>();
        
        for(SFDC_MDF_Claim__c claim : claims) {
            if (claim.Fund_Request__c != null) {
                if (claim.Released_Funds__c != idToMdfMap.get(claim.Fund_Request__c).Released_Funds__c) {
                    idToMdfMap.get(claim.Fund_Request__c).Released_Funds__c = claim.Released_Funds__c; 
                    mdfReqToUpdate.add(idToMdfMap.get(claim.Fund_Request__c));
                }
            }
        }
        
        if (mdfReqToUpdate.size() > 0) {
            update mdfReqToUpdate;
        }
    }
    
    public void updateFundClaimChannelManager(List<SFDC_MDF_Claim__c> newList){
        /**
*   Update the Partner Owner field when the record is owned by a partner
*
*/
        
        Set<Id> ownerIds = new Set<Id>();
        
        
        //Loop through each fund claim and create a Set of all the UserIds for the fund claim owners 
        for (SFDC_MDF_Claim__c fundClaim : newList) {
            //Figure out the owner ids of the fund claims 
            ownerIds.add(fundClaim.OwnerId);
        }
        
        //Create a map of the owernids to their partner accounts
        Map<Id,User> partnerAccts = new Map<Id,User>([Select Id, Contact.Account.OwnerId from User where id in :ownerIds]);
        
        //Now loop through each fund claim to set the Partner Account Id on the claim
        for (SFDC_MDF_Claim__c fundClaim : newList) {
            //Update the partner account manager 
            if ((partnerAccts.get(fundClaim.OwnerId).Contact.Account.OwnerId != NULL) && (fundClaim.Partner_Owner__c == NULL)) {
                fundClaim.Partner_Owner__c = partnerAccts.get(fundClaim.OwnerId).Contact.Account.OwnerId;
            }
        }
    }
    
    //Local Mehtod resposible to populate Claim month and year on Associated Fund Request record.
    public void populateFundRequestReleasedMonthAndYear(Map<Id, SFDC_MDF_Claim__c> mapNewIdToFundClaim, Map<Id, SFDC_MDF_Claim__c> mapOldIdToFundClaim)
    {
        List<SFDC_MDF__c> lstUpdateFundRequest = new List<SFDC_MDF__c>();
        
        List<SFDC_MDF_Claim__c> lstNewFundClaim = new List<SFDC_MDF_Claim__c>();
        
        //Insert New Fund Claim 
        if(mapOldIdToFundClaim == null)
        {
            lstNewFundClaim.addAll(mapNewIdToFundClaim.values());
        }
        else //Update Fund Claim 
        {
            for(SFDC_MDF_Claim__c objNewFundClaim : mapNewIdToFundClaim.values())
            {
                SFDC_MDF_Claim__c objOldFundClaim = mapOldIdToFundClaim.get(objNewFundClaim.Id);
                if((objNewFundClaim.Fund_Request__c != null && 
                    ((objOldFundClaim.Released_Funds__c != objNewFundClaim.Released_Funds__c) || 
                     (objOldFundClaim.Released_Month__c != objNewFundClaim.Released_Month__c) || 
                     (objOldFundClaim.Released_Year__c != objNewFundClaim.Released_Year__c))))
                {
                    lstNewFundClaim.add(objNewFundClaim);
                }
            }
        }
        
        for(SFDC_MDF_Claim__c objNewFundClaim : lstNewFundClaim)
        {   
            if(String.isNotBlank(objNewFundClaim.Fund_Request__c))
            {
                SFDC_MDF__c objFundRequest = new SFDC_MDF__c(Id = objNewFundClaim.Fund_Request__c);
                objFundRequest.Released_Month__c = objNewFundClaim.Released_Month__c;
                objFundRequest.Released_Year__c = objNewFundClaim.Released_Year__c;
                
                if(mapOldIdToFundClaim != null)
                {
                    SFDC_MDF_Claim__c objOldFundClaim = mapOldIdToFundClaim.get(objNewFundClaim.Id);
                    if(objOldFundClaim.Released_Funds__c != objNewFundClaim.Released_Funds__c)
                        objFundRequest.Released_Amount__c = objNewFundClaim.Released_Funds__c;
                }
                else
                    objFundRequest.Released_Amount__c = objNewFundClaim.Released_Funds__c;
                lstUpdateFundRequest.add(objFundRequest);
            }
        }
        
        //Update Fund Request
        if(!lstUpdateFundRequest.isEmpty())
        {
            update lstUpdateFundRequest;
        }
    }
}