force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JPLogs__c/JPLogs__c.object-meta.xml
<CustomObject>
    <label>JPLog</label>
    <nameField>
        <label>JPLogs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JPLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JPLogs__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <label>Opportunity Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JPLogs__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JPLogs__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OutBound</fullName>
            </value>
            <value>
                <fullName>InBound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NCR_Payments_Site__c/NCR_Payments_Site__c.object-meta.xml
<CustomObject>
    <label>NCR Payments Site</label>
    <nameField>
        <displayFormat>NCRPS-{000000}</displayFormat>
        <label>NCR Payments Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCR Payments  Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCR_Payments_Site__c/fields/InfiniceptApplicationId__c.field-meta.xml
<CustomField>
    <fullName>InfiniceptApplicationId__c</fullName>
    <label>InfiniceptApplicationId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Payments_Site__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>NCR_Payments_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Generates a number for the opportunity</description>
    <displayFormat>{000000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/groomNcrPaymentSiteRecordsTest.cls
@isTest
public class groomNcrPaymentSiteRecordsTest {
	public static testMethod void Test_PopulateOCRBookDateFieldsSecondMethod(){
        Account act=TestRecordsFactory.createAccount('Test456');
        Opportunity opp = TestRecordsFactory.createSimpleOpportunity(act);
        
        NCR_Payments_Site__c PaySite= new NCR_Payments_Site__c();
        PaySite.InfiniceptApplicationId__c='123';
        PaySite.Opportunity__c = opp.Id;        
        insert PaySite;
        
        Opportunity Opp1 = [Select Id, Opportunity_Number__c from Opportunity where id=:opp.Id LIMIT 1];
        String response = '[{"merchantClaimURL":"https://merchantapp.io:443/ncralohapfintegration/Merchant/Claim/758cb569-aeb0-4370-ba03-a48ca9a62043","administratorURL":"https://merchantapp.io:443/ncralohapfintegration/CoBrands/MerchantUW?applicationId=136396","merchantApplicationId":"136396","externalMerchantApplicationId":"e2d83032f3ea4250841c521d7e18a070/790ce820ea974c308caefbcb4bf2f4e5","infiniceptApplicationId":"c40f4dbf-ba35-4237-a8c2-1dd8de4af385","status":30,"statusMessage":"Submission successful.","organizationId":"e2d83032-f3ea-4250-841c-521d7e18a070","siteId":"790ce820-ea97-4c30-8cae-fbcb4bf2f4e5","externalMerchantId":"ATL864","externalStoreId":"1234","cobrand":"ncralohapfintegration"}]';
        JPLogs__c jplog = new JPLogs__c(name=opp1.Opportunity_Number__c + '-OutBound',Type__c ='OutBound', Status__c='Success', Response__c = response);
        insert jplog;
        
        Test.startTest();
       		Database.executeBatch(new groomNcrPaymentSiteRecords(),1); 
        Test.stopTest();
        
    }
}