force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>End-user Customer account that is in a RoR country</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Business_Function__c.field-meta.xml
<CustomField>
    <fullName>Business_Function__c</fullName>
    <label>Business Function</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>C-Level</fullName>
            </value>
            <value>
                <fullName>CPI</fullName>
            </value>
            <value>
                <fullName>Customer Support/Service</fullName>
            </value>
            <value>
                <fullName>Digital Commerce</fullName>
            </value>
            <value>
                <fullName>Finance/Accounting</fullName>
            </value>
            <value>
                <fullName>Fraud Management</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NCR Ambassador</fullName>
            </value>
            <value>
                <fullName>NCR Champion</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Other: (please specify)</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Project Management</fullName>
            </value>
            <value>
                <fullName>Quality/Improvement</fullName>
            </value>
            <value>
                <fullName>Research &amp; Development</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Vendor Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Decision_Maker__c.field-meta.xml
<CustomField>
    <fullName>Decision_Maker__c</fullName>
    <inlineHelpText>Contacts labeled as Not Involved will not be surveyed</inlineHelpText>
    <label>Decision Maker</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>Not involved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Entry-Level Manager</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Individual Contributor</fullName>
            </value>
            <value>
                <fullName>Middle Manager</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Project/Team Leader</fullName>
            </value>
            <value>
                <fullName>Sr. Exec/CXO</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Vice President/Director</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Login_Status__c.field-meta.xml
<CustomField>
    <fullName>Portal_Login_Status__c</fullName>
    <inlineHelpText>PRM Services</inlineHelpText>
    <label>Portal Login Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_User__c.field-meta.xml
<CustomField>
    <fullName>Portal_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Status__c.field-meta.xml
<CustomField>
    <fullName>Profile_Status__c</fullName>
    <inlineHelpText>PRM Services</inlineHelpText>
    <label>Profile Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_Flag__c.field-meta.xml
<CustomField>
    <fullName>Survey_Flag__c</fullName>
    <label>Relationship Survey</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No-Prospect</fullName>
            </value>
            <value>
                <fullName>No-Customer Policy</fullName>
            </value>
            <value>
                <fullName>No-Customer Opt Out</fullName>
            </value>
            <value>
                <fullName>No-Customer Contract</fullName>
            </value>
            <value>
                <fullName>No-Account Request</fullName>
            </value>
            <value>
                <fullName>No-Indirect Customer</fullName>
            </value>
            <value>
                <fullName>No-Per CX Team</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <label>Deal Registration</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Registration__c/fields/Channel_Partner_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Channel_Partner_Key_Contact__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_Key_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner Key Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deal Registrations</relationshipLabel>
    <relationshipName>Deal_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/End_Customer_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Company_Name__c</fullName>
    <label>Customer Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/End_Customer_Key_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>End_Customer_Key_Contact_Name__c</fullName>
    <label>Key Contact Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Estimated_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Close_Date__c</fullName>
    <label>Expected Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Name_of_Account_Financial_Institution__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Account_Financial_Institution__c</fullName>
    <label>Name of Account/Financial Institution</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Partner_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Partner&apos;s account name.</description>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registrations (Partner Company Name)</relationshipLabel>
    <relationshipName>Deal_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of Deal Registration Request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <color>#F3D904</color>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <color>#FF6600</color>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#33CC00</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Converted to an Opportunity</fullName>
                <color>#419249</color>
                <label>Converted to an Opportunity</label>
            </value>
            <value>
                <fullName>Closed Booked</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Partner Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engineers__c/Engineers__c.object-meta.xml
<CustomObject>
    <description>For NCR Partner Channel - Partner Portal.  Will track all partner engineers and registrations.</description>
    <label>Engineer</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Engineers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engineers__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <defaultValue>null</defaultValue>
    <label>First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Account Name that you are employed by</inlineHelpText>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Account.Partner_Type__c</field>
            <operation>equals</operation>
            <value>Dealer, Deployer, Distributor, Master VAR, Solution Provider</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engineers</relationshipLabel>
    <relationshipName>Engineers</relationshipName>
    <trackHistory>false</trueHistory>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Portal Access Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ModalPopUpApexController.cls
/*
##################################################################################################
# Class Name............................:ModalPopUpApexController.cls                                                                                                                                  
# Last Modified by......:  Monika
# Last Modified Date..:    19-12-2022
BA_SF-2491 JDK Locale impact - Upgrade API Part 5 
                               
################################################################################################
*/
public class ModalPopUpApexController {
    
Public static Engineers__c eng{get;set;} 
public static ProcessInstanceStep work;
public static Deal_Registration__c dealreg;
      
    @AuraEnabled
    public static void getAccountupdatedlist(Account newAcc){
        insert newAcc ;
    }
        
    @AuraEnabled
    public static String getPopUpAvailablity(Id recordId){
        return null;
    }
        
    @AuraEnabled
    public static String fetchUrl(Id processId){
        return null;
    }
        
    @AuraEnabled
    public static String engineerToContact(Id recordId ,String engineerId ,String portalLogin){
        return null;
    }
           
    public static Id createContact(Engineers__c engineer){
    
        Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Partner Contact').getRecordTypeId();
        //Create contact
        Contact contactInstannce = new Contact();
        contactInstannce.recordtypeId =devRecordTypeId ;
        contactInstannce.FirstName = engineer.First_name__c;
        contactInstannce.Lastname = engineer.Last_Name__c;
        contactInstannce.Email = engineer.Email_Address__c;
        contactInstannce.AccountId = engineer.Partner_Account__c;
        contactInstannce.Title ='Engineer';
        contactInstannce.Decision_Maker__c ='Not involved';
        contactInstannce.Level__c ='Individual Contributor';
        contactInstannce.Business_Function__c ='Customer Support/Service';
        contactInstannce.Portal_User__c = true;
        contactInstannce.Profile_Status__c ='Active';
        contactInstannce.Portal_Login_Status__c ='Active';
        contactInstannce.Survey_Flag__c ='No-Customer Opt Out';
        contactInstannce.Reason__c ='Channel directive';
    
        try{
            Insert contactInstannce;
        } catch(exception e){
            System.debug('Exception Caught'+e.getMessage());
        } 
        return contactInstannce.Id;
    }
    
    @AuraEnabled
    public static String sendEmail(String selectedReason,String comment,Id recordId){ 
        return null;
    }
        
    @AuraEnabled
    public static String sendEmailDealReg(String selectedReason,Id recordId){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    
        work = [Select id,ProcessInstance.TargetObjectId from ProcessInstanceStep WHERE Id =: recordId];
        dealReg   =[Select id, Name,Owner.name,Name_of_Account_Financial_Institution__c,Channel_Partner_Company_Name__c,Channel_Partner_Key_Contact__c,OwnerID,owner.email,End_Customer_Company_Name__c,End_Customer_Key_Contact_Name__c,
                   Estimated_Close_Date__c,Is_this_part_of_an_RFP__c,Status__c,NCR_Account_Manager__c,Partner_Company_Name__c,Partner_Contact__c,Primary_Contact_Name__c,Primary_Contact_NameText__c,Projected_Opportunity_Value__c From Deal_Registration__c Where id =: work.ProcessInstance.TargetObjectId ]    ;
    
        If(selectedReason !='' && selectedReason !=null && dealReg != null){
            dealreg.VisualTemplate__c = selectedReason;
            update dealreg;
        }
        //Query Email
        List<EmailTemplate> emailtemp =[Select id from EmailTemplate Where Name ='Deal Registration Rejection Email Template'];
    
        //Set list of people who should get the email
        List<String> sendTo = new List<String>();
        sendTo.add(Dealreg.owner.email);
        mail.setToAddresses(sendTo); 
    
        //Set who the email is sent from
        
        mail.setTemplateID(emailtemp[0].Id); 
        mail.setSaveAsActivity(false);
        mail.setWhatId(dealreg.id);
        mail.setTargetObjectId(dealReg.OwnerId);
    
        // (Optional) Set list of people who should be CC'ed
        List<String> ccTo = new List<String>();
        //  Set email contents - you can use variables!
        System.debug('mail'+ mail);
        List<Messaging.SingleEmailMessage> mails=
        new List<Messaging.SingleEmailMessage>();
        mails.add(mail);
        System.debug('mails'+ mails);
        // Messaging.SendEmailResult[] results = 
        Messaging.sendEmail(mails);
        return dealReg.id;
    }

}