force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner account who is in a country that is RoR compliant</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Demo_Program__c/Demo_Program__c.object-meta.xml
<CustomObject>
    <label>Demo Program</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Demo Program #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Program__c/fields/LT__c.field-meta.xml
<CustomField>
    <fullName>LT__c</fullName>
    <label>LT</label>
    <length>252</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>MSRP</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/Product_Group_NCR_designation__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_NCR_designation__c</fullName>
    <label>Product Group [NCR designation]</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/QTY__c.field-meta.xml
<CustomField>
    <fullName>QTY__c</fullName>
    <label>QTY</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demo_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_DemoProgramApprovalHistoryTest.cls
@isTest
public class PRM_DemoProgramApprovalHistoryTest 
{
	@isTest public static void testDemoCon ()
    {
        // Create Partner user
        Account act = PRM_TestRecordsFactory.createPartnerAccount('test',null);
         System.runAs(TestRecordsFactory.getUser()){
           insert act;
        }
        Contact con = PRM_TestRecordsFactory.createPartnerContact(act.Id, 'test', null);
        insert con;
        User u = PRM_TestRecordsFactory.createPartnerUser(con.Id, 'test', null);
        insert u;
        
        // Create Demo Request
        Demo_Program__c rec = new Demo_Program__c();
        rec.QTY__c = 50;
        rec.MSRP__c = 10000;
        rec.Product_Description__c = 'Description';
        rec.Product_Group_NCR_designation__c = 'Product Group';
        rec.LT__c = 'LT';
        rec.Status__c = 'Draft';
        insert rec;
                System.assertNotEquals(rec, null,'Demo_Program__c should not be null');

        Approval.processSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setComments('Test');
        req.setObjectId(rec.id);
        Approval.ProcessResult result = Approval.process(req);
        
        PRM_DemoProgramApprovalHistory.getApprovalHistory(rec.id);
        
        List<ProcessInstance> allPIList = new List<ProcessInstance>();
        allPIList = [Select Id,CompletedDate , (Select Id, OriginalActorId,OriginalActor.Name, ActorId, Actor.Name, CreatedDate From Workitems ORDER BY CreatedDate DESC)
                     From ProcessInstance p WHERE TargetObjectId =: rec.id ORDER BY CreatedDate DESC ];
        
        String workItemId ;
        
        for(ProcessInstance pi: allPIList)
        {            
            if(pi.Workitems.size() > 0)
            {
                workItemId = pi.Workitems[0].Id;
            }
        }
        
        PRM_DemoProgramApprovalHistory.rejectDemoProgram('Test', 'Test', rec.id, workItemId);
        
        // Create Demo Request
        Demo_Program__c rec2 = new Demo_Program__c();
        rec2.QTY__c = 50;
        rec2.MSRP__c = 10000;
        rec2.Product_Description__c = 'Description';
        rec2.Product_Group_NCR_designation__c = 'Product Group';
        rec2.LT__c = 'LT';
        rec2.Status__c = 'Draft';
        insert rec2;
        
        allPIList = [Select Id,CompletedDate , (Select Id, OriginalActorId,OriginalActor.Name, ActorId, Actor.Name, CreatedDate From Workitems ORDER BY CreatedDate DESC)
                     From ProcessInstance p WHERE TargetObjectId =: rec2.id ORDER BY CreatedDate DESC ];
        
        for(ProcessInstance pi: allPIList)
        {            
            if(pi.Workitems.size() > 0)
            {
                workItemId = pi.Workitems[0].Id;
            }
        }
        
        PRM_DemoProgramApprovalHistory.approveDemoProgram(rec2, 'Test', rec2.id, workItemId, false) ;
        
        PRM_DemoProgramApprovalHistory.saveChunk(rec2.Id, 'Test' , 'Test', 'text', '') ;
    }
}