force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Activity__c/Campaign_Activity__c.object-meta.xml
<CustomObject>
    <description>Custom Task related to existent  Account/Contact. Once a task is qualified need to create an opportunity.</description>
    <label>Campaign Activity</label>
    <nameField>
        <displayFormat>CA - {0000000}</displayFormat>
        <label>Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Activity__c/fields/Assign_to__c.field-meta.xml
<CustomField>
    <fullName>Assign_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Gives information about the user to whom task is assigned.</description>
    <label>Assign to</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Activities</relationshipName>
    <trackHistory>false</trueHistory>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Activity__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <description>Name of the campaign.</description>
    <label>Primary Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the task.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Activity__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Subject of the task.</description>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validate this Contact</fullName>
            </value>
            <value>
                <fullName>Validate this Account</fullName>
            </value>
            <value>
                <fullName>Validate this Lead/Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/updateCampaignActivityOwnerUtilTest.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
@isTest
private class updateCampaignActivityOwnerUtilTest {
    
    static testMethod void campActOwnerChangeTest() {
        
        
        //Fetch Profile
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        //Creat a user
        User us =  new User();
        us.Profileid = p.id;
        us.Email = 's.mahla@ncr.com';
        us.Alias= 'sm250665';
        us.Username = 's@ncr.com';
        us.FirstName ='Fname';
        us.LastName = 'lname';
        us.LocaleSidKey= 'ar';
        us.LanguageLocaleKey= 'de';
        us.TimeZoneSidKey= 'Africa/Cairo';
        us.EmailEncodingKey = 'Big5';
        us.CurrencyIsoCode= 'AUD';
        us.Quicklook_ID__c='sz250665';
        insert us;
        
        List<Campaign_Activity__c> campList = new List<Campaign_Activity__c>();
        //Create Campaign activity under that.
        Campaign_Activity__c campAct = new Campaign_Activity__c();
        campAct.Assign_to__c = us.Id ;
        campAct.Campaign_Name__c = 'campaign3031';
        campAct.Status__c = 'Open';
        campAct.Subject__c='Validate this Account';
        
        campList.add(campAct);
        insert campList;
        updateCampaignActivityOwnerUtil.updateOwner(null,null,campList);
        Campaign_Activity__c caObj = [select OwnerId,Assign_to__c from Campaign_Activity__c where id=:campAct.id];
        System.assert(caObj.Assign_to__c==caObj.OwnerId);
    }      
}