force-app/main/default/objects/Account/fields/Subscription_Group__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Group__c</fullName>
    <label>Subscription Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality Hosted Solutions</fullName>
            </value>
            <value>
                <fullName>Customer Billing Hold</fullName>
            </value>
            <value>
                <fullName>Digital Insight</fullName>
            </value>
            <value>
                <fullName>Enterprise Ticketing</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Finance eMarketing</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Retail eMarketing</fullName>
            </value>
            <value>
                <fullName>Retail Connected Payment and Services</fullName>
            </value>
            <value>
                <fullName>PCR Cloud</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Retail NSS</fullName>
            </value>
            <value>
                <fullName>Digital Insight- Billing Hold</fullName>
            </value>
            <value>
                <fullName>Retail Omnichannel Decision Service Platform</fullName>
            </value>
            <value>
                <fullName>Hospitality Partnerships</fullName>
            </value>
            <value>
                <fullName>Do Not Bill Hospitality On Hold</fullName>
            </value>
            <value>
                <fullName>Do Not Bill Retail On Hold</fullName>
            </value>
            <value>
                <fullName>Digital Insight - Customer Watchlist</fullName>
            </value>
            <value>
                <fullName>Retail Optic</fullName>
            </value>
            <value>
                <fullName>Zipscene</fullName>
            </value>
            <value>
                <fullName>As-A-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Classification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Classification__c</fullName>
    <description>CATM - This field is used to differentiate Digital Insight Opportunities</description>
    <inlineHelpText>This field is used to differentiate Digital Insight Opportunities</inlineHelpText>
    <label>Opportunity Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Alaric</fullName>
            </value>
            <value>
                <fullName>Digital Insight</fullName>
            </value>
            <value>
                <fullName>CATM - FI</fullName>
            </value>
            <value>
                <fullName>CATM - IBG (Core)</fullName>
            </value>
            <value>
                <fullName>CATM - Retail (Corporate)</fullName>
            </value>
            <value>
                <fullName>CATM - atmAd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Solution_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Solution_Portfolio__c</fullName>
    <label>Offer Portfolio</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DIGITAL BANKING</fullName>
            </value>
            <value>
                <fullName>FINANCIAL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>GAMING</fullName>
            </value>
            <value>
                <fullName>GEMS</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>IPS</fullName>
            </value>
            <value>
                <fullName>PC / ELS</fullName>
            </value>
            <value>
                <fullName>RETAIL ASSISTED SERVICE</fullName>
            </value>
            <value>
                <fullName>RETAIL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>RETALIX</fullName>
            </value>
            <value>
                <fullName>SERVICES</fullName>
            </value>
            <value>
                <fullName>TRAVEL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>SYSTEMS MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>CHECK &amp; IMAGE</fullName>
            </value>
            <value>
                <fullName>SELF-SERVICE REINVENTION</fullName>
            </value>
            <value>
                <fullName>BRANCH TRANSFORMATION</fullName>
            </value>
            <value>
                <fullName>ENTERPRISE FRAUD AND SECURITY</fullName>
            </value>
            <value>
                <fullName>TRANSACTION PROCESSING</fullName>
            </value>
            <value>
                <fullName>CASH MANAGEMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RenewalQuoteRedirectController.cls
// ===========================================================================
// Object: RenewalQuoteRedirectController
// Company: Cloudware Connections, Inc.
// Author: Reid Beckett
// Purpose: Serves the redirect page - to redirect renewals to use the standard quote flow
// ===========================================================================
// Changes: 2016-04-26 Reid Beckett
//           Class created
// ===========================================================================
public with sharing class RenewalQuoteRedirectController 
{
    public zqu__Quote__c quoteSobject {get;set;}
    
    public RenewalQuoteRedirectController(ApexPages.StandardController stdController) 
    {
        quoteSobject = (zqu__Quote__c)stdController.getRecord();
    }

    public PageReference init()
    {
        String subscriptionId = ApexPages.currentPage().getParameters().get('subscriptionId');
        String url = Page.zqu__CreateQuote.getUrl();
        Id oppId = ApexPages.currentPage().getParameters().get('oppId');
        Opportunity opp = [select Id, Name, Opportunity_Classification__c,Account.Subscription_Group__c,/* Solution_Portfolio__c,*/
         AccountId from Opportunity where Id = :oppId];
        if(!DIQuoteUtil.isDigitalInsight(opp))
        {
            //just redirect to the next page in the renewal wizard
            url += '?stepNumber=3&subscriptionId='+subscriptionId;
            return new PageReference(url);
        }else {
            
            ZuoraSubscription zuoraSub = ZuoraClient.getInstance().findZuoraSubscription(subscriptionId);
            ZuoraSubscriptionState zss = new ZuoraSubscriptionState(zuoraSub);

            //create the quote...
            String billingAccountId = ApexPages.currentPage().getParameters().get('billingAccountId');
            Id quoteId = DIQuoteUtil.createRenewalQuote(billingAccountId, subscriptionId, oppId);
            String crmAccountId = opp.AccountId;

            //redirect to the next page in the renewal wizard
            //DI 1105 pass the billingAccountId it will make the Bill To & Sold To Read-only
            url += '?id='+quoteId+'&billingAccountId='+billingAccountId+'&crmAccountId='+crmAccountId+'&subscriptionId='+subscriptionId+'&stepNumber=2&quoteType=Subscription&retURL='+
                EncodingUtil.urlEncode('/'+oppId, 'UTF-8') + '&oppId='+oppId;
            return new PageReference(url).setRedirect(true);
        }
    }
}