force-app/main/default/objects/Account/fields/Subscription_Group__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Group__c</fullName>
    <label>Subscription Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality Hosted Solutions</fullName>
            </value>
            <value>
                <fullName>Customer Billing Hold</fullName>
            </value>
            <value>
                <fullName>Digital Insight</fullName>
            </value>
            <value>
                <fullName>Enterprise Ticketing</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Finance eMarketing</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Retail eMarketing</fullName>
            </value>
            <value>
                <fullName>Retail Connected Payment and Services</fullName>
            </value>
            <value>
                <fullName>PCR Cloud</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Retail NSS</fullName>
            </value>
            <value>
                <fullName>Digital Insight- Billing Hold</fullName>
            </value>
            <value>
                <fullName>Retail Omnichannel Decision Service Platform</fullName>
            </value>
            <value>
                <fullName>Hospitality Partnerships</fullName>
            </value>
            <value>
                <fullName>Do Not Bill Hospitality On Hold</fullName>
            </value>
            <value>
                <fullName>Do Not Bill Retail On Hold</fullName>
            </value>
            <value>
                <fullName>Digital Insight - Customer Watchlist</fullName>
            </value>
            <value>
                <fullName>Retail Optic</fullName>
            </value>
            <value>
                <fullName>Zipscene</fullName>
            </value>
            <value>
                <fullName>As-A-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Classification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Classification__c</fullName>
    <description>CATM - This field is used to differentiate Digital Insight Opportunities</description>
    <inlineHelpText>This field is used to differentiate Digital Insight Opportunities</inlineHelpText>
    <label>Opportunity Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Alaric</fullName>
            </value>
            <value>
                <fullName>Digital Insight</fullName>
            </value>
            <value>
                <fullName>CATM - FI</fullName>
            </value>
            <value>
                <fullName>CATM - IBG (Core)</fullName>
            </value>
            <value>
                <fullName>CATM - Retail (Corporate)</fullName>
            </value>
            <value>
                <fullName>CATM - atmAd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Solution_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Solution_Portfolio__c</fullName>
    <label>Offer Portfolio</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DIGITAL BANKING</fullName>
            </value>
            <value>
                <fullName>FINANCIAL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>GAMING</fullName>
            </value>
            <value>
                <fullName>GEMS</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY</fullName>
            </value>
            <value>
                <fullName>IPS</fullName>
            </value>
            <value>
                <fullName>PC / ELS</fullName>
            </value>
            <value>
                <fullName>RETAIL ASSISTED SERVICE</fullName>
            </value>
            <value>
                <fullName>RETAIL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>RETALIX</fullName>
            </value>
            <value>
                <fullName>SERVICES</fullName>
            </value>
            <value>
                <fullName>TRAVEL SELF SERVICE</fullName>
            </value>
            <value>
                <fullName>SYSTEMS MANAGEMENT</fullName>
            </value>
            <value>
                <fullName>CHECK &amp; IMAGE</fullName>
            </value>
            <value>
                <fullName>SELF-SERVICE REINVENTION</fullName>
            </value>
            <value>
                <fullName>BRANCH TRANSFORMATION</fullName>
            </value>
            <value>
                <fullName>ENTERPRISE FRAUD AND SECURITY</fullName>
            </value>
            <value>
                <fullName>TRANSACTION PROCESSING</fullName>
            </value>
            <value>
                <fullName>CASH MANAGEMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NCRDefaultValuePlugin.cls
// ===========================================================================
// Object: NCRDefaultValuePlugin
// Company: Cloudware Connections, Inc.
// Author: Reid Beckett
// Purpose: The controller implementation of zqu.CreateQuoteController.PopulateDefaultFieldValuePlugin, set in Component Registration of Z-Quotes config
//    This default implementation will delegate to division-specific implementation of INCRDefaultValuePlugin
// ===========================================================================
// Changes: 2016-03-17 Reid Beckett
//           Class created
// ===========================================================================
global class NCRDefaultValuePlugin extends zqu.CreateQuoteController.PopulateDefaultFieldValuePlugin implements zqu.PropertyComponentController.IPopulateValuePlugin
{
  global override void populateDefaultFieldValue(SObject record, zqu.PropertyComponentController.ParentController pcc)
  {   
    if(!Test.isRunningTest()){
        super.populateDefaultFieldValue(record,pcc);
        system.debug('NCRDefaultValuePlugin called');
    }

    Opportunity[] opps;
    Id oppId = ApexPages.currentPage().getParameters().get('oppId');
    if(!String.isBlank(oppId))
    {
      opps = [select Id, AccountId, Opportunity_Classification__c,Account.Subscription_Group__c /*Solution_Portfolio__c*/ from Opportunity where Id = :oppId];
    }else{
      oppId = (Id)record.get(zqu__Quote__c.fields.zqu__Opportunity__c.getDescribe().getName());
      if(!String.isBlank(oppId)) opps = [select Id, AccountId, Opportunity_Classification__c,Account.Subscription_Group__c /*Solution_Portfolio__c*/ from Opportunity where Id = :oppId];
    }

    if(opps != null && !opps.isEmpty())
    {
      //get the default value plugin from the /*Solution_Portfolio__c*/ Account's subscription group  value
      INCRDefaultValuePlugin defaultPluginImpl = (INCRDefaultValuePlugin)NCRZuoraCustomizationPluginFactory.getImpl('INCRDefaultValuePlugin',/*opps[0].Solution_Portfolio__c*/ opps[0].Account.Subscription_Group__c);
      if(defaultPluginImpl != null) defaultPluginImpl.populateDefaultFieldValue(opps[0], (zqu__Quote__c)record, pcc);
    }
    /* Modified By [29-Sept-2016] : AS251035 - Regarding User Stroy no. 1499 of SCA
       Set the Logic in else if part becuase there are some case where Sales person can
       create the Quote from the Account directly and set the Defaulted value of
       Solution Portfolio to CRM Account.
    */
    if (String.isBlank(oppId)){
        INCRDefaultValuePlugin defaultPluginImpl = (INCRDefaultValuePlugin)NCRZuoraCustomizationPluginFactory.getImpl('INCRDefaultValuePlugin', 'CRM Account');
        if(defaultPluginImpl != null) defaultPluginImpl.populateDefaultFieldValue(null, (zqu__Quote__c)record, pcc);
    }
  }
}