force-app/main/default/objects/Account/fields/Subscription_Group__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Group__c</fullName>
    <label>Subscription Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality Hosted Solutions</fullName>
            </value>
            <value>
                <fullName>Customer Billing Hold</fullName>
            </value>
            <value>
                <fullName>Digital Insight</fullName>
            </value>
            <value>
                <fullName>Enterprise Ticketing</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Finance eMarketing</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Retail eMarketing</fullName>
            </value>
            <value>
                <fullName>Retail Connected Payment and Services</fullName>
            </value>
            <value>
                <fullName>PCR Cloud</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Retail NSS</fullName>
            </value>
            <value>
                <fullName>Digital Insight- Billing Hold</fullName>
            </value>
            <value>
                <fullName>Retail Omnichannel Decision Service Platform</fullName>
            </value>
            <value>
                <fullName>Hospitality Partnerships</fullName>
            </value>
            <value>
                <fullName>Do Not Bill Hospitality On Hold</fullName>
            </value>
            <value>
                <fullName>Do Not Bill Retail On Hold</fullName>
            </value>
            <value>
                <fullName>Digital Insight - Customer Watchlist</fullName>
            </value>
            <value>
                <fullName>Retail Optic</fullName>
            </value>
            <value>
                <fullName>Zipscene</fullName>
            </value>
            <value>
                <fullName>As-A-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel_Office__c.field-meta.xml
<CustomField>
    <fullName>Channel_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel/Local Office</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(5 AND ((1 OR 4) AND 2) OR 3) AND (6 AND 7) AND 8</booleanFilter>
        <filterItems>
            <field>Account.CDM_Account_Type__c</field>
            <operation>equals</operation>
            <value>PARTNER, LOCAL OFFICE</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Country_Code__c</field>
            <operation>equals</operation>
            <value>US</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>C9 Administration, 02 NSC Administrator, 04 NSC UI Administrator,HOSP Inside Sales, 50 Hospitality Account Director, 55 Hosted Solutions Sales, iPaas Administration, Soup Integration</value>
        </filterItems>
        <filterItems>
            <field>Account.CDM_Sub_Account_Type__c</field>
            <operation>equals</operation>
            <value>CHANNEL</value>
        </filterItems>
        <filterItems>
            <field>Account.Active_Account__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Enterprise</value>
        </filterItems>
        <filterItems>
            <field>Account.LOB__c</field>
            <operation>equals</operation>
            <value>HOSPITALITY, RETAIL</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Channel Office)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ACVEstimatedUsageControllerTest.cls
@isTest(SeeAllData=true)
public class ACVEstimatedUsageControllerTest
{
    private static zqu__Quote__c qt;
    
	Public Static User getUser(){
		User Usr = [Select Id from User Where Name = 'Soup User'];
		return Usr;
	}   
    public static testMethod void testInit()
    {
        
        Account acct = new Account(Name = 'Test Account', Subscription_Group__c = 'Test',industry = 'HOSPITALITY:CHANNEL');
        
        System.runAs(getUser()){
	insert acct;
	}
        
        //Opportunity opp = ZuoraTestUtil.createOpp(acct);
        //ZuoraTestUtil.ProductCatalog pcatalog = ZuoraTestUtil.createProductCatalog();
		
        Opportunity opp = new Opportunity();
        opp.accountid = acct.id;
        opp.name = 'test';
        opp.closedate = system.today();
        opp.stagename = 'Analyzing';
        opp.Channel_Office__c = acct.id;
        insert opp;
        
        qt = ZuoraTestUtil.createQuote(opp, 'Default');
    
        Test.setCurrentPage(Page.ACVEstimatedUsage);
        ApexPages.currentPage().getParameters().put('stepNumber', '4');
        ACVEstimatedUsageController c = new ACVEstimatedUsageController(new ApexPages.StandardController(qt));
        test.startTest();
        System.assertNotEquals(null,c.init());
        System.assertNotEquals(null,c.Save());
        System.assertNotEquals(null,c.Next());
        System.assertEquals(null,c.Back());
        System.assertNotEquals(null,c.Done());        
        
        ApexPages.currentPage().getParameters().put('stepNumber', null);
        System.assertNotEquals(null,c.back());
        System.assertNotEquals(null,c.Next());

        test.stopTest();    
    }    
    

}