force-app/main/default/objects/Account/fields/Subscription_Group__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Group__c</fullName>
    <label>Subscription Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality Hosted Solutions</fullName>
            </value>
            <value>
                <fullName>Customer Billing Hold</fullName>
            </value>
            <value>
                <fullName>Digital Insight</fullName>
            </value>
            <value>
                <fullName>Enterprise Ticketing</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Finance eMarketing</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Retail eMarketing</fullName>
            </value>
            <value>
                <fullName>Retail Connected Payment and Services</fullName>
            </value>
            <value>
                <fullName>PCR Cloud</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Retail NSS</fullName>
            </value>
            <value>
                <fullName>Digital Insight- Billing Hold</fullName>
            </value>
            <value>
                <fullName>Retail Omnichannel Decision Service Platform</fullName>
            </value>
            <value>
                <fullName>Hospitality Partnerships</fullName>
            </value>
            <value>
                <fullName>Do Not Bill Hospitality On Hold</fullName>
            </value>
            <value>
                <fullName>Do Not Bill Retail On Hold</fullName>
            </value>
            <value>
                <fullName>Digital Insight - Customer Watchlist</fullName>
            </value>
            <value>
                <fullName>Retail Optic</fullName>
            </value>
            <value>
                <fullName>Zipscene</fullName>
            </value>
            <value>
                <fullName>As-A-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestBillingAccountNotificationTrigger.cls
@isTest(SeeallData = true)
public class TestBillingAccountNotificationTrigger {
    
    static testmethod void Test() { 
         Profile pf= [Select Id from profile where Name='Soup Integration']; 
        System.assert(pf.Id!=null);
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+RandomId; 
        User uu=new User(firstname = 'ABC', 
                         lastName = 'XYZ', 
                         email = uniqueName + '@test' + orgId + '.org', 
                         Username = uniqueName + '@test' + orgId + '.org', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = uniqueName.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US', 
                         Quicklook_ID__c= '57665765',
                         ProfileId = pf.Id
                        );   
        insert uu; 
        System.assert(uu.Id!=null);
        system.assertEquals('ABC',uu.firstname);
        system.assertNotEquals('ISO-8859-9',uu.EmailEncodingKey);
        System.runAs(uu){
        
        Account a = new Account();
        a.Name = 'Test';
        a.Subscription_Group__c = 'Digital Insight';
        insert a;
        System.assert(a.Id!=null);
        system.assertEquals('Test',a.Name);
        system.assertNotEquals('Digital',a.Subscription_Group__c);
            
        Zuora__CustomerAccount__c acc = new Zuora__CustomerAccount__c();
        acc.Zuora__Account__c = a.Id;
        
        insert acc; 
        System.assert(acc.Id!=null);    
        }
    }
}