force-app/main/default/objects/Credit_Detail__c/Credit_Detail__c.object-meta.xml
<CustomObject>
    <description>This object stores the Credit data information. The Data is coming from EDW via iPaaS.</description>
    <label>AR Detail</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Credit Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Detail__c/fields/Dues_Notification_Status__c.field-meta.xml
<CustomField>
    <fullName>Dues_Notification_Status__c</fullName>
    <label>Dues Notification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Notification Cycle Reset</fullName>
            </value>
            <value>
                <fullName>Stage 1 Notification Sent</fullName>
            </value>
            <value>
                <fullName>Stage 2 Notification Sent</fullName>
            </value>
            <value>
                <fullName>Stage 3 Notification Sent</fullName>
            </value>
            <value>
                <fullName>Stage 4 Notification Sent</fullName>
            </value>
            <value>
                <fullName>Notification not required</fullName>
                <isActive>false</isActive>
                <label>Notification not required</label>
            </value>
            <value>
                <fullName>Qualified for Stage 1 Notification Evaluation</fullName>
                <isActive>false</isActive>
                <label>Qualified for Stage 1 Notification Evaluation</label>
            </value>
            <value>
                <fullName>Qualified for Stage 2 Notification Evaluation</fullName>
                <isActive>false</isActive>
                <label>Qualified for Stage 2 Notification Evaluation</label>
            </value>
            <value>
                <fullName>Qualified for Stage 3 Notification Evaluation</fullName>
                <isActive>false</isActive>
                <label>Qualified for Stage 3 Notification Evaluation</label>
            </value>
            <value>
                <fullName>Qualified for Stage 4 Notification Evaluation</fullName>
                <isActive>false</isActive>
                <label>Qualified for Stage 4 Notification Evaluation</label>
            </value>
            <value>
                <fullName>Qualified for Stage 4 Reporting</fullName>
                <isActive>false</isActive>
                <label>Qualified for Stage 4 Reporting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Is_Record_freeze_for_Notification__c.field-meta.xml
<CustomField>
    <fullName>Is_Record_freeze_for_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to stop any type of overdue notification alert for next 15 days. Don&apos;t change the value of it.</description>
    <inlineHelpText>This field is used to stop any type of overdue notification alert for next 15 days. Don&apos;t change the value of it.</inlineHelpText>
    <label>Is Record freeze for Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Last_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Notification_Date__c</fullName>
    <label>Last Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Prior_Value_of_Dues_Notification_Status__c.field-meta.xml
<CustomField>
    <fullName>Prior_Value_of_Dues_Notification_Status__c</fullName>
    <label>Prior Value of Dues Notification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Notification Cycle Reset</fullName>
            </value>
            <value>
                <fullName>Stage 1 Notification Sent</fullName>
            </value>
            <value>
                <fullName>Stage 2 Notification Sent</fullName>
            </value>
            <value>
                <fullName>Stage 3 Notification Sent</fullName>
            </value>
            <value>
                <fullName>Qualified for Stage 4 Reporting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Stage_1_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_1_Notification_Date__c</fullName>
    <label>Stage 1 Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Stage_2_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_2_Notification_Date__c</fullName>
    <label>Stage 2 Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Stage_3_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_3_Notification_Date__c</fullName>
    <label>Stage 3 Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Detail__c/fields/Stage_4_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_4_Notification_Date__c</fullName>
    <label>Stage 4 Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AR_NotificationBatch.cls
public class AR_NotificationBatch implements Database.Batchable<sObject>{
    /* This batch class un-freeze the records which are locked from last 15 days from the previous notification.*/
    public Integer successCounter = 0;
    public Integer failureCounter = 0; 
    public String Status = '';
    public Exception[] errorslist = new Exception[0];
    public integer totalSizeRecords=0;
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Dues_Notification_Status__c,Last_Notification_Date__c,Prior_Value_of_Dues_Notification_Status__c, Is_Record_freeze_for_Notification__c,Stage_1_Notification_Date__c,Stage_2_Notification_Date__c,Stage_3_Notification_Date__c,Stage_4_Notification_Date__c FROM Credit_Detail__c WHERE Is_Record_freeze_for_Notification__c = true';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Credit_Detail__c> creditDetails = new List<Credit_Detail__c>();
        try {
            for (sObject rec : scope) {
                Credit_Detail__c cd = (Credit_Detail__c)rec;
                if (cd.Last_Notification_Date__c != null) {
                    if (cd.Last_Notification_Date__c.daysBetween(System.today()) >= 15) {
                        cd.Is_Record_freeze_for_Notification__c = false;
                        creditDetails.add(cd);
                    }
                } else {
                    cd.Is_Record_freeze_for_Notification__c = false;
                    creditDetails.add(cd);
                }
                
            }
        
            update creditDetails;
            successCounter++;
        } catch(Exception ex) {
            failureCounter++;
            errorslist.add(ex);
        }
    }
    
    public void finish(Database.BatchableContext BC){
        //Id batchJobId = Database.executeBatch(new AR_NotificationBatch(), 200);
        //AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :bc.getJobId()];
        string emailBodytoReplaced = 'Total number of records ==> '+totalSizeRecords
                +'<Br/>Number of batch completed ==> '+successCounter
                +'<Br/>Number of batch failed ==> '+failureCounter;
            
            string emailHeader = 'Batch Job Succeeded';
            
            if(failureCounter!=0) {
                emailHeader='Batch Job Failed'; 
                emailBodytoReplaced += '<Br/><Br/> Fix the record and re-run the batch by using below command <Br/> <p style="color:blue">AR_NotificationBatch batch = new AR_NotificationBatch ();<Br/>database.executebatch(batch, 200);</p>';
                integer n=1;
                for(Exception e : errorslist) {  
                    emailBodytoReplaced += n+'.'+' '+'Exception Occured:' + e.getMessage() + '<Br/>' + e.getStackTraceString()+'<Br/>';
                    n++;
                    
                }
            }
            
            string emailSubject = emailHeader+' For AR_NotificationBatch ';
            string emailSubHeader = emailHeader+' For AR_NotificationBatch ';
            EmailTemplate template = [Select id, Body, HtmlValue, Subject from EmailTemplate where name = 'NCR Standard'];
            String EmailBody=template.HtmlValue;
            
            CommonUtility.sendEmail(emailSubject,emailHeader,emailSubHeader,emailBodytoReplaced,EmailBody,(Label.BatchClassEmailNotification).split(',')); 
    }
}