force-app/main/default/objects/Sales_org_Code_Mapping__c/Sales_org_Code_Mapping__c.object-meta.xml
<CustomObject>
    <description>Business will provide a mapping between Sales Org Code and Account. 
When the compensation team is being entered for an account, only the sales org codes that apply to the master customer account will be available as choices</description>
    <label>Sales org Code Mapping</label>
    <nameField>
        <label>Sales org Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales org Code Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/blockDeletionTest.cls
@isTest
public class blockDeletionTest{
    public static testMethod void myTest(){
          Profile p = [SELECT id from Profile WHERE name = 'iPaas Administration'];
        User u = new User(alias = 'standt', email='standarduser11@ncr.com',
                          emailencodingkey='UTF-8', lastname='Testing4',Quicklook_Id__c='ValProfl', languagelocalekey='en_US',
                          localesidkey='en_US',/*profileid = p.Id*/ profileid=p.Id,timezonesidkey='America/Los_Angeles',
                          username='standarduser1@.ncr.com'+System.now().getTime()+'.com');
        system.runAs(u){
            Sales_org_Code_Mapping__c  sm = new Sales_org_Code_Mapping__c();
            sm.Name='Test';
            insert sm;
            List<Sales_org_Code_Mapping__c  > myList = new List<Sales_org_Code_Mapping__c  >();
            myList =[Select Id from Sales_org_Code_Mapping__c  where Id =:sm.Id LIMIT 1];
            try{
                delete myList ; 
                List<Sales_org_Code_Mapping__c> smObj = [select id from Sales_org_Code_Mapping__c where id=:sm.id];
                System.assert(smObj.size()==0);
            }
            catch(Exception e){
                System.assert(e.getMessage()!=null);
            }
           
        }
    }
}