force-app/main/default/objects/All_profie_config__c/All_profie_config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>All profile config</label>
</CustomObject>

force-app/main/default/objects/All_profie_config__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <label>Profile Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CCAD_Dispute_Nbr__c.field-meta.xml
<CustomField>
    <fullName>CCAD_Dispute_Nbr__c</fullName>
    <description>This is the dispute number assigned when a dispute is created in CCAD.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the dispute number assigned when a dispute is created in CCAD.</inlineHelpText>
    <label>CCAD Dispute Nbr</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country Code of the customer that is assigned to the invoices on a dispute.</description>
    <label>Country Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_Analyst_Email__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Analyst_Email__c</fullName>
    <description>The email of the dispute analyst assigned to the dispute.</description>
    <inlineHelpText>The email of the dispute analyst assigned to the dispute.</inlineHelpText>
    <label>Dispute Analyst Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_Analyst_Name__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Analyst_Name__c</fullName>
    <description>The name of the dispute analyst assigned to the dispute.  Note if not assigned it is assigned to the queue.</description>
    <inlineHelpText>The name of the dispute analyst assigned to the dispute.  Note if not assigned it is assigned to the queue.</inlineHelpText>
    <label>Dispute Analyst Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ab251082</fullName>
                <label>Abhijit Bhattacharjee</label>
            </value>
            <value>
                <fullName>am185511</fullName>
                <label>Amirah Aqilah Mahfiz</label>
            </value>
            <value>
                <fullName>al185173</fullName>
                <label>Andrzej Lesiczka</label>
            </value>
            <value>
                <fullName>AB251081</fullName>
                <label>Anja Bjegovic</label>
            </value>
            <value>
                <fullName>Assigned to Queue</fullName>
                <default>true</default>
                <label>Assigned to Queue</label>
            </value>
            <value>
                <fullName>BS185321</fullName>
                <label>Barbara Stefanski</label>
            </value>
            <value>
                <fullName>bi250023</fullName>
                <label>Brian Ivy</label>
            </value>
            <value>
                <fullName>Charlyn Sanchez</fullName>
            </value>
            <value>
                <fullName>dm185051</fullName>
                <label>Damanjeet Puri</label>
            </value>
            <value>
                <fullName>dl185147</fullName>
                <label>Dorota Lisowska</label>
            </value>
            <value>
                <fullName>ej185034</fullName>
                <label>Emil Jackson</label>
            </value>
            <value>
                <fullName>Ferai Mberi</fullName>
            </value>
            <value>
                <fullName>gr185126</fullName>
                <label>Gajender Rathore</label>
            </value>
            <value>
                <fullName>hg185061</fullName>
                <label>Harsh Gurav</label>
            </value>
            <value>
                <fullName>Hiralkumar Ahir</fullName>
            </value>
            <value>
                <fullName>Jackie Watson</fullName>
            </value>
            <value>
                <fullName>jr185287</fullName>
                <label>Janeese Robinson</label>
            </value>
            <value>
                <fullName>John Benitez</fullName>
            </value>
            <value>
                <fullName>kj185072</fullName>
                <label>Kamil Jablonowski</label>
            </value>
            <value>
                <fullName>ke185017</fullName>
                <label>Kathrina Saranillo</label>
            </value>
            <value>
                <fullName>LM185205</fullName>
                <label>Liliia Mohyrova</label>
            </value>
            <value>
                <fullName>MP185225</fullName>
                <label>Magdalena Pankowska</label>
            </value>
            <value>
                <fullName>ms250789</fullName>
                <label>Manikanta Shekar</label>
            </value>
            <value>
                <fullName>ms185544</fullName>
                <label>Maria Sieluzycka</label>
            </value>
            <value>
                <fullName>MJ250395</fullName>
                <label>Marko Josipovic</label>
            </value>
            <value>
                <fullName>ma185260</fullName>
                <label>Marta Abramek</label>
            </value>
            <value>
                <fullName>Mary Pearl Luzada</fullName>
            </value>
            <value>
                <fullName>Mary Precilla</fullName>
            </value>
            <value>
                <fullName>mt185092</fullName>
                <label>Mehul Thakkar</label>
            </value>
            <value>
                <fullName>Mequia Quiachon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_Created_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Created_By_Name__c</fullName>
    <label>Dispute Created By Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_CreatedBy_Qlook__c.field-meta.xml
<CustomField>
    <fullName>Dispute_CreatedBy_Qlook__c</fullName>
    <label>Dispute CreatedBy Qlook</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_Updated_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Updated_By_Name__c</fullName>
    <label>Dispute Updated By Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_UpdatedBy_Qlook__c.field-meta.xml
<CustomField>
    <fullName>Dispute_UpdatedBy_Qlook__c</fullName>
    <label>Dispute UpdatedBy Qlook</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Master_Customer_Nbr__c.field-meta.xml
<CustomField>
    <fullName>Master_Customer_Nbr__c</fullName>
    <label>Master Customer Nbr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Dispute.recordType-meta.xml
<RecordType>
    <fullName>Dispute</fullName>
    <active>true</active>
    <businessProcess>CADD Dispute Case</businessProcess>
    <description>This type is used for creating cases against Invoices that are in Dispute by the customer</description>
    <label>Dispute</label>
</RecordType>

force-app/main/default/classes/TEST_updateCommnetAndAttachmentService.cls
/****************************************************************************************************
* Author        :   Santosh  
* Date          :   18-01-2022
* Description   :   This is the Test Class for updateCommnetAndAttachmentService.
*************************************************************************************************/

@isTest
public class TEST_updateCommnetAndAttachmentService {
    
    
    static testmethod void UpdateDispute()
    {
        Id DisputeRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Dispute').getRecordTypeId();
        All_profie_config__c setting = new All_profie_config__c();       
        setting.Name = 'CCAD Service Ignored Profile';
        setting.Profile_Id__c = '00eZ0000000NhsBIAS';
        insert setting;
        
        
        Case caseObj = new Case();
        caseObj.RecordTypeId = DisputeRecordTypeId;
        caseObj.Master_Customer_Nbr__c='12345';
        caseObj.Country_Code__c='IT';
        caseObj.Currency_Code__c='USD'; 
        caseObj.Dispute_UpdatedBy_Qlook__c='12345';
        caseObj.Dispute_CreatedBy_Qlook__c='54321';  
        caseObj.Dispute_Updated_By_Name__c='77379';
        caseObj.Dispute_Analyst_Email__c='test@test.com';     
        caseObj.Status='New';
        caseObj.Dispute_Created_By_Name__c='Test';
        caseObj.Dispute_Analyst_Name__c='testing';
        caseObj.CCAD_Dispute_Nbr__c = '100';
        system.debug('@@Case: '+caseObj );
        insert caseObj; 
        
        
        
        
        
        
        //Construct HTTP request and response
        RestRequest  req = new RestRequest ();
        RestResponse  res = new RestResponse ();
        DisputeUtil dspUtil = new DisputeUtil();
        
        
        updateCommentAndAttachmentService.RequestHeader requestheader = new updateCommentAndAttachmentService.RequestHeader(); 
        requestheader.TransactionID = '123e4567-e89b-12d3-a456-426655440003';
        requestheader.Timestamp ='2021-08-02T12:36:08.370-04:00';
        requestheader.SourceSystem = 'MyNCR';
        requestheader.TargetSystem = 'NSC';
        
        
        updateCommentAndAttachmentService.Attachment attachment = new updateCommentAndAttachmentService.Attachment();
        attachment.Source = 'bwali tred';
        attachment.Description = 'bawali tred';
        attachment.URL = 'www.google.com';
        
        
        updateCommentAndAttachmentService.Dispute dispute = new updateCommentAndAttachmentService.Dispute();  
        dispute.DisputeID =  caseObj.CCAD_Dispute_Nbr__c;
        dispute.CreatedBy = 'sj185091';
        dispute.SubmitterName = 'santosh jha';
        dispute.Comment = 'santosh jha';
        list<updateCommentAndAttachmentService.Attachment> ss = new list<updateCommentAndAttachmentService.Attachment>();
        ss.add(attachment);
        dispute.Attachment = ss;
        
        
        
        
        updateCommentAndAttachmentService.InvoiceDisputeRequest invoicedisputerequest = new updateCommentAndAttachmentService.InvoiceDisputeRequest() ;
        invoicedisputerequest.Dispute = dispute;
        
        
        updateCommentAndAttachmentService.MainHeader mainheader = new updateCommentAndAttachmentService.MainHeader();
        mainheader.RequestHeader = requestheader;
        mainheader.InvoiceDisputeRequest = invoicedisputerequest;
        
        
        
        
        
        
        
        req.requestURI = '/services/apexrest/invoiceDispute/updateCommentAndAttachment';
        req.httpMethod = 'PUT';
        //req.requestBody = Blob.valueOf('"{\n\t\"RequestHeader\": {\n\t\t\"TransactionID\": \"123e4567-e89b-12d3-a456-426655440003\",\n\t\t\"Timestamp\": \"2021-08-02T12:36:08.370-04:00\",\n\t\t\"SourceSystem\": \"MyNCR\",\n\t\t\"TargetSystem\": \"NSC\"\n\t},\n\t\"InvoiceDisputeRequest\": {\n\t\t\"Dispute\": {\n\t\t\t\"DisputeID\": \"00254471\",\n\t\t\t\"CreatedBy\": \"\",\n\t\t\t\"SubmitterName\": \"santosh jha\",\n\t\t\t\"Comment\": \"testing on friday\",\n\t\t\t\"Attachment\": [{\n\t\t\t\t\t\"Source\": \"\",\n\t\t\t\t\t\"Description\": \"\",\n\t\t\t\t\t\"URL\": \"\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"Source\": \"\",\n\t\t\t\t\t\"Description\": \"\",\n\t\t\t\t\t\"URL\": \"\"\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t}\n}"');
        
        // res.responseBody = Blob.valueOf('"{\n\"ResponseHeader\":{\n\"TransactionID\":\"123e4567-e89b-12d3-a456-426655440003\",\n\"Timestamp\":\"2021-08-02T12:36:08.370-04:00\",\n\"Status\":\"FAILURE\"\n},\n\"InvoiceDisputeResponse\":{\n\"Dispute\":{\n\"Result\":\"Existing Case not found\",\n\"InvoiceCount\":1,\n\"DisputeID\":\"00254471\"\n}\n}\n}"');
        req.requestBody= blob.valueOf(json.serializePretty(mainheader));
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        updateCommentAndAttachmentService.UpdateDispute();
        Test.stopTest();
        
        
        
        
    }
}