force-app/main/default/objects/CEC__c/CEC__c.object-meta.xml
<CustomObject>
    <description>This is the Primary object for MKT - Customer Experience Centre Enhancements which holds the basic details about the CEC meetings scheduled by the team.</description>
    <label>CEC Meeting</label>
    <nameField>
        <label>CEC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEC Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEC__c/fields/Meeting_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CEC Meeting</relationshipLabel>
    <relationshipName>CEC_Meeting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEC_Attendees__c/CEC_Attendees__c.object-meta.xml
<CustomObject>
    <description>This is the child object of CEC meeting which hold the details about the attendees who will be part of a specific CEC meeting like Name, phone number, email id, title etc.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>Attendee - {000}</displayFormat>
        <label>CEC Attendees Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEC Attendees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CEC_Attendees__c/fields/Attendee_Name_Contact__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Name_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacts in Salesforce</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CEC Attendees</relationshipLabel>
    <relationshipName>CEC_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEC_Attendees__c/fields/CEC_Meeting__c.field-meta.xml
<CustomField>
    <fullName>CEC_Meeting__c</fullName>
    <label>CEC Meeting</label>
    <referenceTo>CEC__c</referenceTo>
    <relationshipName>CEC_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityAndCECObject__c/OpportunityAndCECObject__c.object-meta.xml
<CustomObject>
    <label>CEC Opportunity Relationship</label>
    <nameField>
        <label>Opportunites Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEC Opportunity Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityAndCECObject__c/fields/CEC_Meeting__c.field-meta.xml
<CustomField>
    <fullName>CEC_Meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEC Meeting</label>
    <referenceTo>CEC__c</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityAndCECObject__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CECMeetingTriggerHandler.cls
/*##################################################################################################
# Description...........: This class is for CEC functionality.
# Created by......: Sushant, Saurav, Yogesh, Monika 
# Created Date....: Nov 2021.  
# Story Number ......: EBA_SF-1607 , EBA_SF-1606 , EBA_SF-1605 , EBA_SF-1554
##################################################################################################*/
public class CECMeetingTriggerHandler {
    public static boolean isFlag=true;
    public static void updateStatus(List<Cec__c> cecLst){
        Set<Id> cecLstOpp = new Set<Id>();
        boolean flagCec=false;
        Id oppId;
        Id campId = NSCCommonInfoUtil.getIdOf('CEC_Campaign_id');
        for(CEC__c cecObj:cecLst){
            if(cecObj.Meeting_Status__c =='Cancelled' || cecObj.Meeting_Status__c =='Declined'){
                cecLstOpp.add(cecObj.id);
                oppId=cecObj.Opportunity__c;
            }
        }
        Set<Id> oppCECLst = new Set<Id>();
        for(OpportunityAndCECObject__c Obj : [Select id,CEC_Meeting__c,Opportunity__c from OpportunityAndCECObject__c where Opportunity__c=:oppId]){
            oppCECLst.add(obj.CEC_Meeting__c);
        }
        for(CEC__c cecObj : [Select id, Opportunity__c,Meeting_Status__c from CEC__c where id IN: oppCECLst]){
            if(!cecLstOpp.contains(cecObj.Id)){
                if(cecObj.Meeting_Status__c =='Cancelled' || cecObj.Meeting_Status__c =='Declined'){
                    flagCec=false;
                }else{
                    flagCec=true;
                    break;
                }
            }
        }
        List<Opportunity> oppLst = new List<Opportunity>();
        if(flagCec==false){
            for(Opportunity opp :[Select id,CampaignId from Opportunity where Id=:oppId and CampaignId =:campId]){
                Opportunity objOpp = new Opportunity();
                if(opp.CampaignId!=null){
                    objOpp.Id = opp.id;
                    if(flagCec==false){
                        objOpp.CampaignId = null;
                        oppLst.add(objOpp);
                    }
                }
            }
        }
        if(!oppLst.isEmpty()){
            update oppLst;
        }
        List<campaignMember> camMemLst = new List<campaignMember>();
        Map<id, Id> conCecMettingMap = new Map<Id,Id>();
        System.debug('@@@@'+cecLstOpp);
        Set<Id> conIdsSet = new Set<Id>();
        for(CEC_Attendees__c obj :[Select id, CEC_Meeting__c,Attendee_Name_Contact__c  from CEC_Attendees__c where CEC_Meeting__c IN:cecLstOpp]){
            conIdsSet.add(obj.Attendee_Name_Contact__c);
        }
        System.debug('@@@@'+conIdsSet);
        if(!conIdsSet.isEmpty()){
            for(CampaignMember camObj : [Select ContactId,CEC_Meeting__c, CampaignId,Id from CampaignMember where  ContactId IN:conIdsSet and CampaignId =:campId]){
                conCecMettingMap.put(camObj.ContactId, camObj.CEC_Meeting__c);
                camMemLst.add(camObj);
            }
        }
        system.debug('@@@@@'+camMemLst);
        if(!camMemLst.isEmpty()){
            delete camMemLst;
        }
        
    }
    
}