force-app/main/default/objects/CEC__c/CEC__c.object-meta.xml
<CustomObject>
    <description>This is the Primary object for MKT - Customer Experience Centre Enhancements which holds the basic details about the CEC meetings scheduled by the team.</description>
    <label>CEC Meeting</label>
    <nameField>
        <label>CEC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEC Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CEC__c/fields/Bypass_Val__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Val__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is created to bypass the validation rule - Set_the_min_and_max_length_for_fields, on CEC Meeting Object .</description>
    <label>Bypass Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Customer_Competitors__c.field-meta.xml
<CustomField>
    <fullName>Customer_Competitors__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer&apos;s competitors in which are aligned to the Account.  This is autopopulated and can be more than 1.</description>
    <label>Who are NCR Competitors?</label>
    <referenceTo>Competitors__c</referenceTo>
    <relationshipLabel>CEC Meeting</relationshipLabel>
    <relationshipName>CEC_Meeting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Customer_Expectations__c.field-meta.xml
<CustomField>
    <fullName>Customer_Expectations__c</fullName>
    <inlineHelpText>What is the customer hoping to achieve?</inlineHelpText>
    <label>Customer Expectations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Customer_Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Customer_Time_Zone__c</fullName>
    <label>Customer Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+14:00) Line Is. Time (Pacific/Kiritimati)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Phoenix Is.Time (Pacific/Enderbury)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Tonga Time (Pacific/Tongatapu)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:45) Chatham Standard Time (Pacific/Chatham)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) New Zealand Standard Time (Pacific/Auckland)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Fiji Time (Pacific/Fiji)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Petropavlovsk-Kamchatski Time (Asia/Kamchatka)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:30) Norfolk Time (Pacific/Norfolk)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Lord Howe Standard Time (Australia/Lord_Howe)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Solomon Is. Time (Pacific/Guadalcanal)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:30) Australian Central Standard Time ((South Australia) Australia/Adelaide)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Australian Eastern StandardTime (New South Wales) (Australia/Sydney)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Australian Eastern Standard Time (Queensland) (Australia/Brisbane)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Australian Central Standard Time (Northern Territory) (Australia/Darwin)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Korea Standard Time (Asia/Seoul)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Japan Standard Time (Asia/Tokyo)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Hong Kong Time (Asia/Hong_Kong)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Malaysia Time (Asia/Kuala_Lumpur)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Philippines Time (Asia/Manila)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) China Standard Time (Asia/Shanghai)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Singapore Time (Asia/Singapore)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) China Standard Time (Asia/Taipei)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Australian Western Standard Time (Australia/Perth)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Bangkok)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Ho_Chi_Minh)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) West Indonesia Time (Asia/Jakarta)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:30) Myanmar Time (Asia/Rangoon)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:00) Bangladesh Time (Asia/Dhaka)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:45) Nepal Time (Asia/Kathmandu)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Colombo)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Experience_Center__c.field-meta.xml
<CustomField>
    <fullName>Experience_Center__c</fullName>
    <label>Experience Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Belgrade</fullName>
            </value>
            <value>
                <fullName>Dundee</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Ideal_Meeting_Duration__c.field-meta.xml
<CustomField>
    <fullName>Ideal_Meeting_Duration__c</fullName>
    <label>Ideal Meeting Duration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>15 Minutes</fullName>
            </value>
            <value>
                <fullName>30 Minutes</fullName>
            </value>
            <value>
                <fullName>1 Hours</fullName>
            </value>
            <value>
                <fullName>1 Hours 30 Minutes</fullName>
            </value>
            <value>
                <fullName>2 Hours</fullName>
                <label>2 hours</label>
            </value>
            <value>
                <fullName>2 Hours 30 Minutes</fullName>
            </value>
            <value>
                <fullName>3 Hours</fullName>
                <label>3 hours</label>
            </value>
            <value>
                <fullName>3Hours 30 Minutes</fullName>
            </value>
            <value>
                <fullName>4 Hours</fullName>
                <label>4 hours</label>
            </value>
            <value>
                <fullName>4 Hours 30 Minutes</fullName>
            </value>
            <value>
                <fullName>5 Hours</fullName>
            </value>
            <value>
                <fullName>5 Hours 30 Minutes</fullName>
            </value>
            <value>
                <fullName>6 Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Meeting_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Purpose__c</fullName>
    <label>Meeting Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Top-to-Top Meeting or Introduction</fullName>
            </value>
            <value>
                <fullName>Close Opportunity/Win Back</fullName>
            </value>
            <value>
                <fullName>Prospect with Key Decision Makers in Attendance</fullName>
            </value>
            <value>
                <fullName>Customer at Risk</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Name_of_company_for_meeting_materials__c.field-meta.xml
<CustomField>
    <fullName>Name_of_company_for_meeting_materials__c</fullName>
    <inlineHelpText>Exact organization/company name as it should appear on digital signage and meeting materials</inlineHelpText>
    <label>Name of company for meeting materials</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/NCR_Expectations__c.field-meta.xml
<CustomField>
    <fullName>NCR_Expectations__c</fullName>
    <inlineHelpText>What is NCR’s goal for the meeting?</inlineHelpText>
    <label>NCR Expectations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/NCR_solutions__c.field-meta.xml
<CustomField>
    <fullName>NCR_solutions__c</fullName>
    <inlineHelpText>What NCR solutions would you like to cover?</inlineHelpText>
    <label>NCR solutions to be covered?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Personal_Customer_Considerations__c.field-meta.xml
<CustomField>
    <fullName>Personal_Customer_Considerations__c</fullName>
    <description>Any special touches we can consider to make the customer experience more personalized?  Examples:  customer success or partnership milestones, birthday, religious, food considerations, etc.</description>
    <inlineHelpText>Customer success milestones, partnership milestones, favorite foods/beverages, birthday, religious considerations, etc.</inlineHelpText>
    <label>Special requests for personalization?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Presenters_already_secured__c.field-meta.xml
<CustomField>
    <fullName>Presenters_already_secured__c</fullName>
    <description>What presenters have you secured.</description>
    <label>Presenters already secured?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/RFP_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>RFP_Affiliation__c</fullName>
    <description>Is this briefing affiliated with an active or Upcoming RFP?</description>
    <inlineHelpText>Is this briefing affiliated with an active or upcoming RFP?</inlineHelpText>
    <label>Briefing part of active/upcoming RFP?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEC__c/fields/RFP_Name__c.field-meta.xml
<CustomField>
    <fullName>RFP_Name__c</fullName>
    <label>If yes, what is the name of the RFP?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/RVP_Aware__c.field-meta.xml
<CustomField>
    <fullName>RVP_Aware__c</fullName>
    <description>Is your Regional Vice President (RVP) aware of this meeting?  Note that, RVP&apos;s receive a weekly summary of all upcoming meetings each Friday.</description>
    <inlineHelpText>Regional Vice President. RVPs receive a weekly summary of all upcoming briefings each Friday</inlineHelpText>
    <label>Is your RVP aware of this briefing?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEC__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <inlineHelpText>Anticipated meeting tone</inlineHelpText>
    <label>Temperature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEC__c/fields/X1st_Potential_Meeting_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>X1st_Potential_Meeting_Date_Time__c</fullName>
    <inlineHelpText>Please provide three dates below to discuss with core teams on our intake call to align calendars quickly and prioritize with leaders.

CEC team supports highly collaborative, cross-industry customer briefings. We work with sales teams, subject matter experts and NCR leaders to drive an outcomes-focused approach to hosting customers, prospects and partners.</inlineHelpText>
    <label>1st Preferred Meeting Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CEC__c/fields/X2nd_Potential_Meeting_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Potential_Meeting_Date_Time__c</fullName>
    <inlineHelpText>Please provide three dates below to discuss with core teams on our intake call to align calendars quickly and prioritize with leaders.

CEC team supports highly collaborative, cross-industry customer briefings. We work with sales teams, subject matter experts and NCR leaders to drive an outcomes-focused approach to hosting customers, prospects and partners.</inlineHelpText>
    <label>2nd Preferred Meeting Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CEC__c/recordTypes/CEC_Visit.recordType-meta.xml
<RecordType>
    <fullName>CEC_Visit</fullName>
    <active>true</active>
    <label>CEC Visit</label>
</RecordType>

force-app/main/default/classes/cecMeetingTest.cls
/*############################################################################################################
# Description...........: This test class is for CEC functionality.It covers cECGetPickListValueController,
MultiSelectLookupController,CECMeetingTrigger, CECMeetingTriggerHandler
# Created by......: Sushant, Saurav, Yogesh, Monika 
# Created Date....: Nov 2021.  
# Story Number ......: EBA_SF-1607 , EBA_SF-1606 , EBA_SF-1605 , EBA_SF-1554
##############################################################################################################*/
@isTest
private class cecMeetingTest {
    @isTest static void myTest() {       
        CEC__c cecObj1 = new CEC__c();        
        cecObj1.Experience_Center__c = 'Dundee';
        cecObj1.Name = 'cecTest1';
        cecObj1.Meeting_Purpose__c = 'Customer at Risk';
        cecObj1.Customer_Expectations__c ='test';
        cecObj1.NCR_Expectations__c ='test';
        cecObj1.Ideal_Meeting_Duration__c = '15 Minutes';
        cecObj1.Customer_Time_Zone__c = '(GMT+14:00) Line Is. Time (Pacific/Kiritimati)';
        cecObj1.X1st_Potential_Meeting_Date_Time__c = system.today();
        cecObj1.X2nd_Potential_Meeting_Date_Time__c = system.today();
        cecObj1.Temperature__c = 'Red';
        cecObj1.Bypass_Val__c = true;

        cecObj1.RFP_Affiliation__c= 'No';
        cecObj1.RFP_Name__c= 'Testt';
        cecObj1.RVP_Aware__c= 'Yes';
        cecObj1.NCR_solutions__c='Test';
        cecObj1.Customer_Competitors__c= TestRecordsFactory.createCompetitor().id;
        cecObj1.Name_of_company_for_meeting_materials__c= 'Test';
        cecObj1.Personal_Customer_Considerations__c = 'Test';
        cecObj1.Presenters_already_secured__c= 'Test';
        cecObj1.Special_notes_requests__c= 'Test';
        List<String> ContactIds = new List<String>();
        List<String> UserIds = new List<String>();
        List<String> OppIds = new List<String>();
        List<CEC_Attendees__c> ExtUserList = new List<CEC_Attendees__c>();
        List<CEC_Attendees__c> UserNotInSF = new List<CEC_Attendees__c>();
        List<Account> acc = TestRecordsFactory.createAccounts(1);
        Opportunity opp  = TestRecordsFactory.createSimpleOpportunity(acc[0]);
        ID idOpp = opp.id;
        ID idAcc = acc[0].id;
        
        //Add contact Attendee
        Contact cn = TestRecordsFactory.createContact(acc[0]);
        ContactIds.add(cn.id);
        
       //Add internal Attendee 
        User us = TestRecordsFactory.getUser();
        UserIds.add(us.id);
        
        //Add external Attendee
        CEC_Attendees__c Attnd= new CEC_Attendees__c();
        Attnd.Attendee_Name_External__c='test';
        Attnd.Email__c='test@test.com';
        Attnd.Role__c='test';
        ExtUserList.add(Attnd);
        
        //Add internal Attendee not in SF
        CEC_Attendees__c Att= new CEC_Attendees__c();
        Att.Non_Sf_NCR__c='test not in SF';
        Att.Is_Non_Sf_NCR__c = True;
        Att.Email__c='test@test.com';
        Att.Role__c='test';
        UserNotInSF.add(Att);
        
        //add opportunity to be influenced
        Opportunity op = TestRecordsFactory.createSimpleOpportunity();
        
        //add the some random campaign other then CEC_Visit to the opportunity
        OppIds.add(op.Id);
        OppIds.add(idOpp);     
        
        String str1 = 'Opportunity' ;
        String str2 = opp.id; 
        
        insert new BPM_Configuration__c(Name='BPMContactIdForNotifyActionOwner',values__C=cn.id);               
        cECGetPickListValueController controller = new cECGetPickListValueController();
        
        CEC__c cecObj2 = new CEC__c();        
        cecObj2.Experience_Center__c = 'Dundee';
        cecObj2.Name = 'cecTest2';
        cecObj2.Meeting_Purpose__c = 'Customer at Risk';
        cecObj2.Customer_Expectations__c ='test';
        cecObj2.NCR_Expectations__c ='test';
        cecObj2.Ideal_Meeting_Duration__c = '15 Minutes';
        cecObj2.Customer_Time_Zone__c = '(GMT+14:00) Line Is. Time (Pacific/Kiritimati)';
        cecObj2.X1st_Potential_Meeting_Date_Time__c = system.today();
        cecObj2.X2nd_Potential_Meeting_Date_Time__c = system.today();
        cecObj2.Temperature__c = 'Red';
        cecObj2.Bypass_Val__c = true;
        cecObj2.RFP_Affiliation__c= 'Yes';
        cecObj2.RFP_Name__c= 'Test';
 
        cecObj2.RVP_Aware__c= 'Yes';
        cecObj2.NCR_solutions__c='Test';
        cecObj2.Customer_Competitors__c= TestRecordsFactory.createCompetitor().id;
       
        cecObj2.Name_of_company_for_meeting_materials__c= 'Test';
        cecObj2.Personal_Customer_Considerations__c = 'Test';
        cecObj2.Presenters_already_secured__c= 'Test';
        cecObj2.Special_notes_requests__c= 'Test';
      
        
        Test.startTest(); 
        ID cecId1 = cECGetPickListValueController.start(cecObj1,ContactIds,UserIds,UserNotInSF,OppIds,ExtUserList,str1,str2).id;
         System.assert(cecId1 != null,'CEC record not created');
        CEC__c cecObj =[Select id,Meeting_Status__c from CEC__c where id=:cecId1];
                                           
        ID cecId2 = cECGetPickListValueController.start(cecObj2,ContactIds,UserIds,UserNotInSF,OppIds,ExtUserList,str1,str2).id;
        System.assert(cecId2 != null,'CEC record not createdl');
        CEC__c cecOb =[Select id,Meeting_Status__c from CEC__c where id=:cecId2];
                                   

        cecOb.Meeting_Status__c ='Cancelled';
        CECMeetingTriggerHandler.isFlag=true;
        update cecOb; 
        

        cecObj.Meeting_Status__c ='Cancelled';
        CECMeetingTriggerHandler.isFlag=true;
        update cecObj; 
        
        //This line covers the MultiSelectLookupController class
         MultiSelectLookupController.retrieveRecords('Opportunity','Name,Opportunity_Number__c,AccountId','Name,Opportunity_Number__c','Opp',idOpp);
         MultiSelectLookupController.retrieveRecords('User','Id,Name,Email','Name','Monika Ma',idOpp);  
        
        //This line covers the cECGetPickListValueController class
        cECGetPickListValueController.pickListValueDynamically(new cec__c(),'Meeting_Purpose__c');
        Test.stopTest();

        
    }
}