force-app/main/default/objects/Sales_Compensation_Notification__c/Sales_Compensation_Notification__c.object-meta.xml
<CustomObject>
    <description>Sales Compensation</description>
    <label>Sales Compensation Notification</label>
    <nameField>
        <label>Sales Compensation Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Compensation Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New NSC SCP Associate</fullName>
            </value>
            <value>
                <fullName>New SCP Associate</fullName>
            </value>
            <value>
                <fullName>Role Changed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <label>Job Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Manager_Name__c</fullName>
    <description>Stores sales persons manager name</description>
    <label>Manager Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Manager_QuicklookID__c.field-meta.xml
<CustomField>
    <fullName>Manager_QuicklookID__c</fullName>
    <label>Manager QuicklookID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Notified__c.field-meta.xml
<CustomField>
    <fullName>Notified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Notified_On__c.field-meta.xml
<CustomField>
    <fullName>Notified_On__c</fullName>
    <description>Date/Time will be stored for Notifications sent.</description>
    <label>Notified On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Previous_ARCS_Job_Family__c.field-meta.xml
<CustomField>
    <fullName>Previous_ARCS_Job_Family__c</fullName>
    <label>Previous ARCS Job Family</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Previous_Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Previous_Job_Code__c</fullName>
    <label>Previous Job Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/QuicklookId_Action__c.field-meta.xml
<CustomField>
    <fullName>QuicklookId_Action__c</fullName>
    <description>Quick look Id and job code make a unique key which is used for data upsert from interface.</description>
    <externalId>true</externalId>
    <label>QuicklookId Action</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Role_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Role_Change_Date__c</fullName>
    <label>Role Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Sales_Person__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person__c</fullName>
    <label>Sales Person</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Sales_Person_Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Sales_Person_Quicklook_ID__c</fullName>
    <label>Sales Person Quicklook ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Compensation_Notification__c/fields/Sales_Persons_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Persons_Country_Code__c</fullName>
    <label>Sales Persons Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Country CodeA2</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DJ</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/compensationHelper.cls
/*
##################################################################################################
# Project Name..........: ARCS 2013
# File............................: compensationHelper.cls
# Version.....................: 23.0
# Created by................: Darshan Singh Farswan
# Created Date...........: 11-12-2012
# Last Modified by......: Darshan Singh Farswan
# Last Modified Date..: 02-01-2013
# Description...............: Class that checks for record duplicacy.
# Modification History.: 
Story No#       Date            DevName            Description
EBA_SF-1909     12-08-2022      Monika      Technical Debt - Apex sharing violation part 1 
################################################################################################
*/

public without sharing class compensationHelper{
	public static Map<Id, Boolean> errorMap = new Map<Id, Boolean>();
    public static Boolean checkDuplicate(Map<String, List<List<Date>>>datesMap, String currentOPID,  Date startDate, Date endDate){
        Boolean Flag = FALSE;
        for(String role : datesMap.KeySet()){
            if(role == currentOPID ||currentOPID == 'All' || role == 'ALL'){
                for(Integer i=0; i<datesMap.get(role).size(); i++){
                    if(!((datesMap.get(role).get(i).get(1) == null && endDate < datesMap.get(role).get(i).get(0))|| (datesMap.get(role).get(i).get(1) != null &&  endDate < datesMap.get(role).get(i).get(0)) || (datesMap.get(role).get(i).get(1) != null &&  startDate > datesMap.get(role).get(i).get(1)))){
                        Flag = TRUE;
                    }   
                }
            }
        }
        return Flag;
    }

    @future
    public static void createRecords(List<String> recordDetails){
    	List<Sales_Compensation_Notification__c> insertRecords = new List<Sales_Compensation_Notification__c>();
    	for(String record : recordDetails){
    		String[] details = record.split(':', -1);
    		String ManagerQLID = details.get(3);
    		String managerName = details.get(4);
    		String oldJobCode = details.get(5);
    		String newJobCode = details.get(6);
    		String oldJobRole = details.get(7);
    		String newJobRole = details.get(8);
    		if(ManagerQLID == null || ManagerQLID.equalsIgnoreCase('null')){
    			ManagerQLID = '';
    		}
    		if(managerName == null || managerName.equalsIgnoreCase('null')){
    			managerName = '';
    		}
    		if(oldJobCode == null || oldJobCode.equalsIgnoreCase('null')){
    			oldJobCode = '';
    		}
    		if(newJobCode == null || newJobCode.equalsIgnoreCase('null')){
    			newJobCode = '';
    		}
    		if(oldJobRole == null || oldJobRole.equalsIgnoreCase('null')){
    			oldJobRole = '';
    		}
    		if(newJobRole == null || newJobRole.equalsIgnoreCase('null')){
    			newJobRole = '';
    		}
    		Sales_Compensation_Notification__c SCM = new Sales_Compensation_Notification__c (
    			Action__c = details.get(0),
    			Sales_Person_Quicklook_ID__c = details.get(1),
    			Sales_Person__c = details.get(2),
    			Manager_QuicklookID__c = ManagerQLID,
    			Manager_Name__c = managerName,
    			Previous_Job_Code__c = oldJobCode,
    			Job_Code__c = newJobCode,
    			Previous_ARCS_Job_Family__c = oldJobRole,
    			ARCS_Job_Family__c = newJobRole,
    			Role_Change_Date__c = System.Today(),
    			Sales_Persons_Country_Code__c = details.get(9),
    			Notified__c = FALSE,
    			Notified_On__c = null,
    			QuicklookId_Action__c = details.get(1) + details.get(0));
    			
    		insertRecords.add(SCM);
    	}
    	upsert insertRecords QuicklookId_Action__c;
    	List<Sales_Compensation_Notification__c> notifications = [SELECT Id, Action__c, Sales_Person_Quicklook_ID__c, Sales_Person__c, Previous_Job_Code__c, Job_Code__c, Previous_ARCS_Job_Family__c, ARCS_Job_Family__c, Role_Change_Date__c, Notified__c, Manager_Name__c, Manager_QuicklookID__c, Sales_Persons_Country_Code__c from Sales_Compensation_Notification__c where Notified__c = FALSE];
        System.debug('darshan'+notifications);
    }
}