force-app/main/default/objects/QuBy_Detail__c/QuBy_Detail__c.object-meta.xml
<CustomObject>
    <label>All QuBy Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>All QuBy Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuBy_Detail__c/fields/Annuity_Modification_Date__c.field-meta.xml
<CustomField>
    <fullName>Annuity_Modification_Date__c</fullName>
    <label>Recurring Revenue Modification Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Annuity_Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Annuity_Quote_Status__c</fullName>
    <label>Recurring Revenue Quote Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/MCN__c.field-meta.xml
<CustomField>
    <fullName>MCN__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>All QuBy Quotes</relationshipLabel>
    <relationshipName>All_QuBy_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Solution_Modification_Date__c.field-meta.xml
<CustomField>
    <fullName>Solution_Modification_Date__c</fullName>
    <label>Orders Funnel Modification Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/QuBy_TESTQuoteRelatedList.cls
/*##################################################################################################
# Project Name..........: QuBy
# File..................: QuBy_TESTQuoteRelatedList.cls                                                        
# Version...............: 32.0 
# Created by............: Mudit Saxena                                                                 
# Created Date..........: 28-08-2016                                                                               
# Last Modified by......: Mudit Saxena 
# Last Modified Date....: 28-08-2016
# Description...........: This is test class for QuBy_QuoteRelatedList class.                          
##################################################################################################*/
@isTest
private class QuBy_TESTQuoteRelatedList{
    
    static testMethod void UnittestFirst() {
        Opportunity opp = TestRecordsFactory.createSimpleOpportunity();
        
        QuBy_Detail__c QD = new QuBy_Detail__c();
        QD.Name = 'TESTQD';
        QD.Annuity_Quote_Status__c = 'ACKNOWLEDGED';
        Qd.Quote_Number__c='390000222';
        QD.MCN__c = 'TEST000012';
        QD.Country_Code__c='US';
        QD.Opportunity__c = opp.id;
        insert QD;
        
        
        QuBy_QuoteRelatedList.isDisabled( );
        QuBy_QuoteRelatedList.getRecords( opp.id );
        QuBy_QuoteRelatedList.getAvailableQuotes( opp.id );
        QuBy_QuoteRelatedList.search( opp.id,'390000222' );
        QuBy_QuoteRelatedList.searchAvailableQuotes( opp.id,'390000222' );
        QuBy_QuoteRelatedList.disAssociateQuote( new List <String> { QD.id },opp.id );
        //QuBy_QuoteRelatedList.associateQuote( new List <String> { QD.id },opp.id );
        
        try{ 
             QuBy_QuoteRelatedList.associateQuote( new List <String> { QD.id },opp.id );
            
        }catch(DMLException e){
           system.assertEquals(e.getMessage(), e.getMessage()); 
        }
        QuBy_QuoteRelatedList.availableQuotesInBatches( opp.id ,10,10);
        QuBy_QuoteRelatedList.dataWrapper DW = new QuBy_QuoteRelatedList.dataWrapper( QD );
        QD.Annuity_Modification_Date__c = System.today() ;
        
        QuBy_QuoteRelatedList.dataWrapper DW1 = new QuBy_QuoteRelatedList.dataWrapper( QD );
        QD.Annuity_Modification_Date__c = null ;
        QD.Solution_Modification_Date__c = System.today() +1  ;
        QuBy_QuoteRelatedList.dataWrapper DW2 = new QuBy_QuoteRelatedList.dataWrapper( QD );
        QD.Annuity_Modification_Date__c = System.today() ;
        QuBy_QuoteRelatedList.dataWrapper DW3 = new QuBy_QuoteRelatedList.dataWrapper( QD );
        QD.Annuity_Modification_Date__c = System.today() + 5 ;
        QuBy_QuoteRelatedList.dataWrapper DW4 = new QuBy_QuoteRelatedList.dataWrapper( QD );
        QuBy_QuoteRelatedList.lightningTableWrapper lwrapper1 = new QuBy_QuoteRelatedList.lightningTableWrapper() ;
        lwrapper1.page = 1 ;
        lwrapper1.total = 2;

    }
  
}