force-app/main/default/objects/QuBy_Detail__c/QuBy_Detail__c.object-meta.xml
<CustomObject>
    <label>All QuBy Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>All QuBy Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuBy_Detail__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>550</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/MCN__c.field-meta.xml
<CustomField>
    <fullName>MCN__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>All QuBy Quotes</relationshipLabel>
    <relationshipName>All_QuBy_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/QuickLook_ID__c.field-meta.xml
<CustomField>
    <fullName>QuickLook_ID__c</fullName>
    <label>Assigned Salesperson QILD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Solution_Quote_Amount__c.field-meta.xml
<CustomField>
    <fullName>Solution_Quote_Amount__c</fullName>
    <label>Orders Funnel  Quote Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Solution_Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Solution_Quote_Status__c</fullName>
    <label>Orders Funnel Quote Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/X24_hour_Notification__c.field-meta.xml
<CustomField>
    <fullName>X24_hour_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>24 hour Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuBy_TESTDetailTrigger.cls
/*##################################################################################################
# Project Name..........: QuBy
# File..................: QuBy_TESTDetailTrigger
# Version...............: 32.0 
# Created by............: Mudit Saxena                                                                 
# Created Date..........: 18-07-2016                                                                               
# Last Modified by......: Mudit Saxena 
# Last Modified Date....: 18-07-2016
# Description...........: This is test class for QuBy_DetailTrigger Trigger.
# Status................: Active    
##################################################################################################*/
@isTest( seeAllData = true )
private class QuBy_TESTDetailTrigger{
    
    static testMethod void runUnitTest() {
        Opportunity opp=TestRecordsFactory.createSimpleOpportunity();
        test.startTest();
        QuBy_Detail__c QD = new QuBy_Detail__c();
        QD.Name = 'TEST Quote';
        QD.Quote_Number__c = '125';
        QD.Country_Code__c = 'US';
        QD.MCN__C = '25721';
        QD.Quicklook_ID__c = 'ms250942';
        QD.Solution_Quote_Amount__c=11000;
        QD.CurrencyIsoCode='USD';
        QD.Solution_Quote_Status__c='Acknowledged';
        QD.Description__c = 'TEST NAME';
        insert QD;
        
        Delete QD;
        Undelete QD;
        
        QD.Country_Code__c = 'US';
        QD.X24_hour_Notification__c=true;        
        QD.Description__c = 'TEST NAME';
        update QD;
        
        QD.Opportunity__c=opp.id;
        QD.Description__c = 'TEST NAME';
        update QD;
        
        // delete
        Delete QD;
        Undelete QD;
        System.assert(QD.Description__c=='TEST NAME');
        
        test.stopTest();
    }

}