force-app/main/default/objects/Subscription_only_products__c/Subscription_only_products__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Subscription only Products</label>
</CustomObject>

force-app/main/default/objects/Subscription_only_products__c/fields/Product_Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Revenue_Type__c</fullName>
    <label>Product Revenue Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InactiveLeadAndContactEmail</label>
</CustomObject>

force-app/main/default/objects/User_Favorite_Products__c/User_Favorite_Products__c.object-meta.xml
<CustomObject>
    <label>User Favorite Products</label>
    <nameField>
        <label>Favourite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Favorite Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Favorite_Products__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>User Favorite Products</relationshipLabel>
    <relationshipName>User_Favorite_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Favorite_Products__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Favorite_Products_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ScrollComponentConreoller.cls
public class ScrollComponentConreoller {

    @AuraEnabled
    public static String addFavourite(String ProductId){
        string Message; 
        try{
            User_Favorite_Products__c FavObj = new User_Favorite_Products__c();
            FavObj.Products__c=ProductId;
            FavObj.User__c=UserInfo.getUserId(); 
            insert FavObj; 
        }
        catch(DmlException e) 
        { 
            Message= e.getMessage();
        }
        return Message;
    }
    
     @AuraEnabled
     Public static String RemoveFavourite(String ProductId){
       system.debug('>>>>'+ProductId);  
        string Message; 
        try{
            if(String.isNotBlank(ProductId)){
                 User_Favorite_Products__c FavObj =[Select Id,Name from User_Favorite_Products__c where Products__c = : ProductId AND User__c=:UserInfo.getUserId()];
                 Delete FavObj;
            }
           
        }
        catch(DmlException e) 
        { 
            Message= e.getMessage();
        }
        return Message;   
     }  
     @AuraEnabled
    public static SubsProductWrapper getSubsOnlyProd(){     
         Set<String> SubsProdSet= new Set<String>(); 
       	 Set<String> SubsRevenueSet= new Set<String>();
        
        SubsProductWrapper subsProdWrapObj= new subsProductWrapper();
     	List<Subscription_only_products__c> subsProdList=  Subscription_only_products__c.getall().values();
       
        if(subsProdList.size()>0){            
        if(String.isNotBlank(subsProdList[0].Product_Name__c)){
             for(String prodName : subsProdList[0].Product_Name__c.split(',')){
            SubsProdSet.add(prodname);            
       			 }
            if(String.isNotBlank(subsProdList[0].Product_Revenue_Type__c)){
             for(String revenueType : subsProdList[0].Product_Revenue_Type__c.split(',')){
            SubsRevenueSet.add(revenueType);               
       			 }
           	 }
    		}
            
            subsProdWrapObj.ProductNames = SubsProdSet;
            subsProdWrapObj.RevenueTypes = SubsRevenueSet;
                    
                
        }
        return subsProdWrapObj;
    } 
    
     public class SubsProductWrapper{
        @AuraEnabled public Set<String> ProductNames{get;set;}
        @AuraEnabled public Set<String> RevenueTypes{get;set;}
           }
}