force-app/main/default/objects/Co_Op_Supporting_Document__c/Co_Op_Supporting_Document__c.object-meta.xml
<CustomObject>
    <label>Co Op Supporting Document</label>
    <nameField>
        <label>Co Op Supporting Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supporting Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <description>Reference for the attachment associated with co op.</description>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Co_Op_Request__c.field-meta.xml
<CustomField>
    <fullName>Co_Op_Request__c</fullName>
    <description>Reference to co op request.</description>
    <label>Co Op</label>
    <referenceTo>Co_Op__c</referenceTo>
    <relationshipLabel>Supporting Documents</relationshipLabel>
    <relationshipName>Supporting_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/coOpExtension.cls
/*
*********************************************************
Apex Class Name    : coOpExtension
Test Class Name    : coOpExtensionTest
Created Date       : 3/15/2017 11:24 AM
@author            : Shiv Mahla
Modification Log:
Date                       Modified by                      Modification
1/18/2022 3:58 AM          Simran Grewal                    EBA_SF-1734 -Technical Debt - Security- Apex Class -ApexXSSFromURLParam Part 3 
                                                   
*********************************************************
*/
public class coOpExtension {
    public String coOpId {get;set;}
    public Attachment att {get;set;}
    public Co_Op_Supporting_Document__c supportingDoc {get;set;}
    //public Map<String,String> params {get;set;}
    String retUrl;
    
    public coOpExtension(ApexPages.StandardController sc) {
        att = new Attachment();
        supportingDoc = new Co_Op_Supporting_Document__c();
        //EBA_SF-1734-Technical Debt - Security- Apex Class -ApexXSSFromURLParam Part 3
       // coOpId  = ApexPages.currentPage().getParameters().get('coOpid');
        coOpId = String.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('coOpid'));
        //retUrl = ApexPages.currentPage().getParameters().get('retURL');
        //List<String> temp = retUrl.split('/');
        //if (temp.size() > 0)
           //coOpId =  temp[temp.size()-1];
    }
    
    public PageReference saveSupportingDoc() {
        if (att.Body == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error,'Please choose a file to attach.'));
            return null;
        }
        Savepoint sp = Database.setSavepoint();
        PageReference pageRef = Page.ipt_co_op_view;
        pageRef.getParameters().put('id',coOpId);
        try {
            // Insert attachment
            att.ParentId = coOpId;
            insert att;
            // Insert Supporting Doc record
            supportingDoc.Name = att.Name;
            supportingDoc.Attachment_Id__c = att.Id;
            supportingDoc.Co_Op_Request__c = coOpId;
            insert supportingDoc;
            
        } catch (Exception ex) {
            Database.rollback(sp);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error,ex.getMessage()));
            return null;
        }
        return pageRef;
    }

}