force-app/main/default/objects/Co_Op_Supporting_Document__c/Co_Op_Supporting_Document__c.object-meta.xml
<CustomObject>
    <label>Co Op Supporting Document</label>
    <nameField>
        <label>Co Op Supporting Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supporting Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <description>Reference for the attachment associated with co op.</description>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Invoice amount.</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of invoice and Proof of payment.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description about the attachment.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Co_Op_Supporting_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed reimbursement request form</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Proof of payment</fullName>
            </value>
            <value>
                <fullName>Other required supporting documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/coOpEditExtension.cls
public class coOpEditExtension {
    public String coOpId {get;set;} // co op Id is a co op document id here.
    public Attachment att {get;set;}
    public Co_Op_Supporting_Document__c supportingDoc {get;set;}
    public Map<String,String> params {get;set;}
    String retUrl;
    Attachment existingAtt;
        
    public coOpEditExtension (ApexPages.StandardController sc) {
        String coOpId = ApexPages.currentPage().getParameters().get('id');
        List<Co_Op_Supporting_Document__c> supportingDocs;
        
        if (! String.isBlank(coOpId)) {
            supportingDocs = [SELECT Id, Name, Attachment_Id__c, Cost__c, Date__c,Type__c, Description__c FROM Co_Op_Supporting_Document__c 
                             WHERE Id =: coOpId LIMIT 1
                            ];
            if (supportingDocs.size() > 0) {
                supportingDoc = supportingDocs[0];
            }
            
            if (! String.isBlank(supportingDoc.Attachment_Id__c)) {
                List<Attachment> attachments = [SELECT Id, Name, Body FROM Attachment WHERE Id =: supportingDoc.Attachment_Id__c LIMIT 1];
                if (attachments.size() > 0) {
                    existingAtt = attachments[0];
                }
            }
        } else {
            supportingDoc = new Co_Op_Supporting_Document__c();
        }
        
        
        att = new Attachment();
    }
    
    public PageReference saveSupportingDoc() {
        Savepoint sp = Database.setSavepoint();
        String retUrl = ApexPages.currentPage().getParameters().get('retURL');
        PageReference pageRef = new PageReference(retUrl);
        try {
            // Insert attachment
            if (att.Name != null)
                existingAtt.Name = att.Name;
            if (att.Body != null)
                existingAtt.Body = att.Body;
            if (att.Name != null || att.Body != null)
                update existingAtt;
            // Insert Supporting Doc record
            if (att.Name != null)
            supportingDoc.Name = att.Name;
            update supportingDoc;
            
        } catch (Exception ex) {
            Database.rollback(sp);
        }
        return pageRef;
    }

}