force-app/main/default/objects/SyncOLI_Config__c/SyncOLI_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncOLI Config</label>
</CustomObject>

force-app/main/default/objects/SyncOLI_Config__c/fields/LastRun_Datetime__c.field-meta.xml
<CustomField>
    <fullName>LastRun_Datetime__c</fullName>
    <label>LastRun Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SyncOliScheduler.cls
public Class SyncOliScheduler implements Schedulable {
    public void execute (SchedulableContext sc) { 
       SyncOLI_Config__c cnfg = SyncOLI_Config__c.getValues('Org_Config');
       Datetime lastRunDatetime = cnfg.LastRun_Datetime__c; 
        
       if(lastRunDatetime != null) {
           BatchSyncOliTrigger syncOli = new BatchSyncOliTrigger(lastRunDatetime);
       	   Database.executeBatch(syncOli);          
       } else {
       		BatchSyncOliTrigger syncOli = new BatchSyncOliTrigger();
     		Database.executeBatch(syncOli);         
       }
                   
    }
}