force-app/main/default/objects/File__c/File__c.object-meta.xml
<CustomObject>
    <label>File</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/File__c/fields/Attachment_ID__c.field-meta.xml
<CustomField>
    <fullName>Attachment_ID__c</fullName>
    <description>Id of the attachment.</description>
    <label>Attachment ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/File__c/fields/CP_Is_Cloned__c.field-meta.xml
<CustomField>
    <fullName>CP_Is_Cloned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by the system to track either file record is cloned from MDF request to Claim or not.</description>
    <label>CP Is Cloned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/File__c/fields/Fund_Request__c.field-meta.xml
<CustomField>
    <fullName>Fund_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Request</label>
    <referenceTo>SFDC_MDF__c</referenceTo>
    <relationshipLabel>Files</relationshipLabel>
    <relationshipName>Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File__c/fields/Pre_Approval_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Pre_Approval_Document_Type__c</fullName>
    <description>Describes Pre-Approval Document Type.</description>
    <label>Pre-Approval Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Event Agenda</fullName>
            </value>
            <value>
                <fullName>Employment Offer Letter</fullName>
            </value>
            <value>
                <fullName>Print/Graphics Proofs</fullName>
            </value>
            <value>
                <fullName>Quotes/Estimates</fullName>
            </value>
            <value>
                <fullName>Rate Cards</fullName>
            </value>
            <value>
                <fullName>Event Registration Form</fullName>
            </value>
            <value>
                <fullName>Resume/CV</fullName>
            </value>
            <value>
                <fullName>Incentive Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/File__c/fields/Proof_of_Performance_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Performance_Document_Type__c</fullName>
    <description>Document type which partner need to upload while claim submission.</description>
    <label>Proof of Performance Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agenda</fullName>
            </value>
            <value>
                <fullName>List of Attendees</fullName>
            </value>
            <value>
                <fullName>Pay Stub</fullName>
            </value>
            <value>
                <fullName>Photos</fullName>
            </value>
            <value>
                <fullName>Proofs</fullName>
            </value>
            <value>
                <fullName>Receipts</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/SFDC_MDF__c.object-meta.xml
<CustomObject>
    <description>Track MDF request details including partner account, requested amount, activity type and date, and approval status.</description>
    <label>Fund Request</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <description>The date the activity is planned. Optionally incorporate a validation rule to ensure that there is ample lead time to approve the request before the planned activity.</description>
    <inlineHelpText>This is the day of the event or the date the activity begins.</inlineHelpText>
    <label>Activity Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Description__c.field-meta.xml
<CustomField>
    <fullName>Activity_Description__c</fullName>
    <label>Activity Description</label>
    <length>90000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <description>A list of available activity types. Customize as needed.</description>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E-marketing Digital Campaign</fullName>
            </value>
            <value>
                <fullName>E-marketing - Video</fullName>
            </value>
            <value>
                <fullName>Event - Campaign in a box</fullName>
            </value>
            <value>
                <fullName>Event - Conference / Tradeshow only</fullName>
            </value>
            <value>
                <fullName>Event - Customer Briefing Center (CBC) Visit</fullName>
            </value>
            <value>
                <fullName>Event – Partner Seminar / Roadshow</fullName>
            </value>
            <value>
                <fullName>Event - Tradeshow in a box including event</fullName>
            </value>
            <value>
                <fullName>Event – Training</fullName>
            </value>
            <value>
                <fullName>Event – Webinar</fullName>
            </value>
            <value>
                <fullName>NCR defined Sales Program – Funded Head Count Distributor Only</fullName>
            </value>
            <value>
                <fullName>Print – Business case driven</fullName>
            </value>
            <value>
                <fullName>Sales Program - Incentive</fullName>
            </value>
            <value>
                <fullName>Sales Program - Telesales/Telemarketing</fullName>
            </value>
            <value>
                <fullName>Search Engine Marketing/Social Media/PR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Activity End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <label>Estimated Number of Leads</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Other_Vendors_Represented__c.field-meta.xml
<CustomField>
    <fullName>Other_Vendors_Represented__c</fullName>
    <description>Other Vendors Represented in the Activity.</description>
    <inlineHelpText>Other Vendors Represented in the Activity.</inlineHelpText>
    <label>Other Vendors Represented</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fujitsu</fullName>
            </value>
            <value>
                <fullName>Zebra Technologies</fullName>
            </value>
            <value>
                <fullName>Micros</fullName>
            </value>
            <value>
                <fullName>Datalogic</fullName>
            </value>
            <value>
                <fullName>Epson</fullName>
            </value>
            <value>
                <fullName>Cognitive TPG</fullName>
            </value>
            <value>
                <fullName>Elo Touch Solutions</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
            <value>
                <fullName>HP ( Hewlett Packard)</fullName>
            </value>
            <value>
                <fullName>SII (Seiko Instruments)</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Payleven</fullName>
            </value>
            <value>
                <fullName>Motorola solutions</fullName>
            </value>
            <value>
                <fullName>Intermec (by Honeywell)</fullName>
            </value>
            <value>
                <fullName>APG Cash Drawer</fullName>
            </value>
            <value>
                <fullName>Applied Data Corp</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Epicor Retail Solutions</fullName>
            </value>
            <value>
                <fullName>JDA Software</fullName>
            </value>
            <value>
                <fullName>LOC Software</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund request approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request Created</fullName>
                <default>true</default>
                <label>Request Created</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Level 1 Review</fullName>
            </value>
            <value>
                <fullName>Level 2 Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/SFDC_MDF_Claim__c.object-meta.xml
<CustomObject>
    <description>A set of claims tied to a specific fund request.</description>
    <label>Fund Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Fund_Request__c.field-meta.xml
<CustomField>
    <fullName>Fund_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Note: This cannot be a master detail relationship if you plan to use approval workflow as the fund request will be locked (during approval and most likely post approval) and therefore any child claims cannot be saved</description>
    <label>Fund Request</label>
    <referenceTo>SFDC_MDF__c</referenceTo>
    <relationshipLabel>Fund Claims</relationshipLabel>
    <relationshipName>R00N30000002DjDcEAK</relationshipName>
    <trackHistory>false</trueHistory>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund claim approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MDFListViewCmpControllerTest.cls
@istest(SeeAllData=true)
public class MDFListViewCmpControllerTest 
{
    public static testmethod void testMDFDetails() 
    {
        List<SFDC_MDF__c> lstMDF = new List<SFDC_MDF__c>();
        
        for(Integer i = 0 ; i <50 ; i++)
        {
            SFDC_MDF__c mdfReq= new SFDC_MDF__c();
            mdfReq.Name= 'Test Activity' + i;
            mdfReq.Activity_Date__c= Date.today()+ 60;
            mdfReq.End_Date__c= mdfReq.Activity_Date__c.addDays(1);
            mdfReq.Activity_Type__c= 'Event – Webinar';
            mdfReq.Other_Vendors_Represented__c='Micros';
            mdfReq.Activity_Description__c='TestDescription';
            mdfReq.Number_of_Leads__c= 1000;
            mdfReq.Status__c= 'Approved'; 
            lstMDF.add(mdfReq);
        }
        
        insert lstMDF;
        List<SFDC_MDF_Claim__c> lstMDFClaim = new List<SFDC_MDF_Claim__c>();
        for(Integer i = 0 ; i < 50 ; i++)
        {
            
            SFDC_MDF_Claim__c mdfClaim = new SFDC_MDF_Claim__c();
            mdfClaim.Name = lstMDF[i].Name + ' - Claim' ;
            mdfClaim.Fund_Request__c = lstMDF[i].Id;
            
            lstMDFClaim.add(mdfClaim);
        }
        insert  lstMDFClaim;
        
        MDFListViewCmpController.getMDFRequestController(false, false, 0, '');
        MDFListViewCmpController.getMDFRequestController(true, false, 5, '');
        MDFListViewCmpController.getMDFRequestController(false, true, 15, ''); 
        
        string oldString;// String.escapeSingleQuotes('Approved');
        MDFListViewCmpController.getMDFRequestController(false, false, 0,null);
        //MDFListViewCmpController.getMDFRequestController(false, false, 0, ' where Status__c =:'+oldString);
        //MDFListViewCmpController.getMDFRequestController(false, false, 0, ' where Status__c =:'+oldString); 
           
        Test.startTest();
        MDFListViewCmpController.deleteMDFRequest(false, false, 20, lstMDF[21].Id);
        
        MDFListViewCmpController.getMDFDetailInformation(lstMDF[0].Id);
        MDFListViewCmpController.submitMdfRequestForApproval(lstMDF[0], 'Test');
      
        Test.stopTest();
    }
    
    public static testmethod void testMDFDetails2() 
    {
        List<SFDC_MDF__c> lstMDF = new List<SFDC_MDF__c>();
        
        for(Integer i = 0 ; i <50 ; i++)
        {
            SFDC_MDF__c mdfReq= new SFDC_MDF__c();
            mdfReq.Name= 'Test Activity' + i;
            mdfReq.Activity_Date__c= Date.today()+ 60;
            mdfReq.End_Date__c= mdfReq.Activity_Date__c.addDays(1);
            mdfReq.Activity_Type__c= 'Event – Webinar';
            mdfReq.Other_Vendors_Represented__c='Micros';
            mdfReq.Activity_Description__c='TestDescription';
            mdfReq.Number_of_Leads__c= 1000;
            mdfReq.Status__c= 'Approved'; 
            lstMDF.add(mdfReq);
        }
        
        insert lstMDF;
        List<SFDC_MDF_Claim__c> lstMDFClaim = new List<SFDC_MDF_Claim__c>();
        for(Integer i = 0 ; i < 50 ; i++)
        {
            
            SFDC_MDF_Claim__c mdfClaim = new SFDC_MDF_Claim__c();
            mdfClaim.Name = lstMDF[i].Name + ' - Claim' ;
            mdfClaim.Fund_Request__c = lstMDF[i].Id;
            
            lstMDFClaim.add(mdfClaim);
        }
        insert lstMDFClaim;
        
        Test.startTest();
        MDFListViewCmpController.submitMdfClaimForApproval(lstMDFClaim[0], 'Test');
        Test.stopTest();       
    }
    
    public static testmethod void testMDFDetails3() 
    {
        List<SFDC_MDF__c> lstMDF = new List<SFDC_MDF__c>();
        
        for(Integer i = 0 ; i <50 ; i++)
        {
            SFDC_MDF__c mdfReq= new SFDC_MDF__c();
            mdfReq.Name= 'Test Activity' + i;
            mdfReq.Activity_Date__c= Date.today()+ 60;
            mdfReq.End_Date__c= mdfReq.Activity_Date__c.addDays(1);
            mdfReq.Activity_Type__c= 'Event – Webinar';
            mdfReq.Other_Vendors_Represented__c='Micros';
            mdfReq.Activity_Description__c='TestDescription';
            mdfReq.Number_of_Leads__c= 1000;
            mdfReq.Status__c= 'Approved'; 
            lstMDF.add(mdfReq);
        }
        
        insert lstMDF;
        List<SFDC_MDF_Claim__c> lstMDFClaim = new List<SFDC_MDF_Claim__c>();
        for(Integer i = 0 ; i < 50 ; i++)
        {
            
            SFDC_MDF_Claim__c mdfClaim = new SFDC_MDF_Claim__c();
            mdfClaim.Name = lstMDF[i].Name + ' - Claim' ;
            mdfClaim.Fund_Request__c = lstMDF[i].Id;
            
            lstMDFClaim.add(mdfClaim);
        }
        insert lstMDFClaim;
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Approved');
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Request Pending for Approvals');
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Rejected');
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Created Today');
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Pending');
        MDFListViewCmpController.changeViewSelection(false, false, 5, '');
        MDFListViewCmpController.saveActivityResult(lstMDF[0]);
        
        MDFListViewCmpController.saveChunk('Fund Request', 'Test', 'Test', lstMDF[0].Id, 'Test', EncodingUtil.urlDecode('Testing', 'UTF-8'), 'txt', '');
        MDFListViewCmpController.saveChunk('Fund Claim', 'Test', 'Test', lstMDFClaim[0].Id, 'Test', EncodingUtil.urlDecode('Testing', 'UTF-8'), 'txt', '');
        
        Attachment oAttachment = new Attachment();
        Blob b = Blob.valueOf('Test Data');
        oAttachment.parentId = lstMDF[0].Id;
        oAttachment.Name = 'Test Attachment for Parent';
        oAttachment.Body = b;
        insert oAttachment;
        
        Test.startTest();
        MDFListViewCmpController.saveChunk('Fund Request', 'Test', 'Test', lstMDF[0].Id, 'Test', EncodingUtil.urlDecode('Testing', 'UTF-8'), 'txt', oAttachment.Id);
        
        File__c objFile = new File__c();
        objFile.Name = 'Test';
        objFile.CP_Is_Cloned__c = false;
        objFile.Fund_Request__c = lstMDF[0].Id;
        objFile.Attachment_ID__c = oAttachment.Id;
        insert objFile;
        
        MDFListViewCmpController.preAppFileList(lstMDF[0].Id);
        
        File__c objFile2 = new File__c();
        objFile2.Name = 'Test';
        objFile2.CP_Is_Cloned__c = false;
        objFile2.Fund_Request__c = lstMDF[0].Id;
        objFile2.Attachment_ID__c = oAttachment.Id;
        objFile2.Claim__c = true;
        insert objFile2;
        MDFListViewCmpController.updatePreAppFileList(new List<File__c> {objFile2}, lstMDFClaim[0].Id);
        MDFListViewCmpController.getRefreshedFiles(null, lstMDFClaim[0].Id);
        MDFListViewCmpController.getRefreshedFiles(lstMDF[0].Id, null);
        MDFListViewCmpController.getRefreshedFiles(lstMDF[0].Id, lstMDFClaim[0].Id);
        Test.stopTest();
    }
    
    public static testmethod void testMDFDetails4() { {
        List<SFDC_MDF__c> lstMDF = new List<SFDC_MDF__c>();
        
        for(Integer i = 0 ; i <50 ; i++)
        {
            SFDC_MDF__c mdfReq= new SFDC_MDF__c();
            mdfReq.Name= 'Test Activity' + i;
            mdfReq.Activity_Date__c= Date.today()+ 60;
            mdfReq.End_Date__c= mdfReq.Activity_Date__c.addDays(1);
            mdfReq.Activity_Type__c= 'Event – Webinar';
            mdfReq.Other_Vendors_Represented__c='Micros';
            mdfReq.Activity_Description__c='TestDescription';
            mdfReq.Number_of_Leads__c= 1000;
            mdfReq.Status__c= 'Approved'; 
            lstMDF.add(mdfReq);
        }
        
        insert lstMDF;
        List<SFDC_MDF_Claim__c> lstMDFClaim = new List<SFDC_MDF_Claim__c>();
        for(Integer i = 0 ; i < 50 ; i++)
        {
            
            SFDC_MDF_Claim__c mdfClaim = new SFDC_MDF_Claim__c();
            mdfClaim.Name = lstMDF[i].Name + ' - Claim' ;
            mdfClaim.Fund_Request__c = lstMDF[i].Id;
            
            lstMDFClaim.add(mdfClaim);
        }
        insert lstMDFClaim;
        
        MDFListViewCmpController.getMDFRequestController(false, false, 0, '');
        MDFListViewCmpController.getMDFRequestController(true, false, 5, '');
        MDFListViewCmpController.getMDFRequestController(false, true, 15, ''); 
        
        MDFListViewCmpController.getMDFRequestController(false, false, 0, ' where Status__c = \'Approved\'');
        MDFListViewCmpController.getMDFRequestController(true, false, 5, ' where Status__c = \'Approved\'');
        MDFListViewCmpController.getMDFRequestController(false, true, 15, ' where Status__c = \'Approved\''); 
        Test.startTest();
        MDFListViewCmpController.deleteMDFRequest(false, false, 20, lstMDF[21].Id);
        
        MDFListViewCmpController.getMDFDetailInformation(lstMDF[0].Id);
        MDFListViewCmpController.submitMdfRequestForApproval(lstMDF[0], 'Test');
        MDFListViewCmpController.deletePreApprovalDoc('Test','Approved');
       //MDFListViewCmpController.saveActivityResult('mdfReq');
        Test.stopTest();
    }
                                                     
  }
   /* public static testmethod void testMDFDetails6() 
    {
        string Agenda;
        string Agenda1;
        List<SFDC_MDF__c> lstMDF = new List<SFDC_MDF__c>();
        
        for(Integer i = 0 ; i <50 ; i++)
        {
            SFDC_MDF__c mdfReq= new SFDC_MDF__c();
            mdfReq.Name= 'Test Activity' + i;
            mdfReq.Activity_Date__c= Date.today()+ 60;
            mdfReq.End_Date__c= mdfReq.Activity_Date__c.addDays(1);
            mdfReq.Activity_Type__c= 'Event – Webinar';
            mdfReq.Other_Vendors_Represented__c='Micros';
            mdfReq.Activity_Description__c='TestDescription';
            mdfReq.Number_of_Leads__c= 1000;
            mdfReq.Status__c= 'Approved'; 
            lstMDF.add(mdfReq);
        }
        
        insert lstMDF;
        List<SFDC_MDF_Claim__c> lstMDFClaim = new List<SFDC_MDF_Claim__c>();
        for(Integer i = 0 ; i < 50 ; i++)
        {
            
            SFDC_MDF_Claim__c mdfClaim = new SFDC_MDF_Claim__c();
            mdfClaim.Name = lstMDF[i].Name + ' - Claim' ;
            mdfClaim.Fund_Request__c = lstMDF[i].Id;
            
            lstMDFClaim.add(mdfClaim);
        }
        insert lstMDFClaim;
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Approved');
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Request Pending for Approvals');
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Rejected');
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Created Today');
        MDFListViewCmpController.changeViewSelection(false, false, 5, 'Pending');
        MDFListViewCmpController.changeViewSelection(false, false, 5, '');
        MDFListViewCmpController.saveActivityResult(lstMDF[0]);
        
        MDFListViewCmpController.saveChunk('Fund Request', 'Test', 'Test', lstMDF[0].Id, 'Test', EncodingUtil.urlDecode('Testing', 'UTF-8'), 'txt', '');
        MDFListViewCmpController.saveChunk('Fund Claim', 'Test', 'Test', lstMDFClaim[0].Id, 'Test', EncodingUtil.urlDecode('Testing', 'UTF-8'), 'txt', '');
        
        Attachment oAttachment = new Attachment();
        Blob b = Blob.valueOf('Test Data');
        oAttachment.parentId = lstMDF[0].Id;
        oAttachment.Name = 'Test Attachment for Parent';
        oAttachment.Body = b;
        insert oAttachment;
        
                 

        
        Test.startTest();
 File__c objFile = new File__c();
        objFile.Name = 'Test4';
        objFile.CP_Is_Cloned__c = false;
        objFile.Fund_Request__c = lstMDF[0].Id;
        objFile.Attachment_ID__c = oAttachment.Id;
        objFile.Proof_of_Performance_Document_Type__c = 'Agenda';

        insert objFile;
        
        MDFListViewCmpController.preAppFileList(lstMDF[0].Id);
       
        File__c objFile2 = new File__c();
        objFile2.Name = 'Test8';
        objFile2.CP_Is_Cloned__c = false;
        objFile2.Fund_Request__c = lstMDF[0].Id;
        objFile2.Attachment_ID__c = oAttachment.Id;
        objFile2.Claim__c = true;
        objFile2.Proof_of_Performance_Document_Type__c = Agenda1;

        insert objFile2;
       
     MDFListViewCmpController.saveEditChunk(objFile2, '0060g0000111MB0AAM', 'Test5',EncodingUtil.urlDecode('Testing5', 'UTF-8'), 'txt', 'Fund Request', Agenda);
      // MDFListViewCmpController.updateFileProcess(objFile2, 'testing',EncodingUtil.urlDecode('Testing8', 'UTF-8'), 'txt', 'Request', Agenda );

       
        MDFListViewCmpController.updatePreAppFileList(new List<File__c> {objFile2}, lstMDFClaim[0].Id);
        MDFListViewCmpController.getRefreshedFiles(null, lstMDFClaim[0].Id);
        MDFListViewCmpController.getRefreshedFiles(lstMDF[0].Id, null);
        MDFListViewCmpController.getRefreshedFiles(lstMDF[0].Id, lstMDFClaim[0].Id);
        Test.stopTest();
    }*/
    
   public static testmethod void testMDFDetails8() 
   { string Agenda;
        List<SFDC_MDF__c> lstMDF = new List<SFDC_MDF__c>();
        
        for(Integer i = 0 ; i <50 ; i++)
        {
            SFDC_MDF__c mdfReq= new SFDC_MDF__c();
            mdfReq.Name= 'Test Activity' + i;
            mdfReq.Activity_Date__c= Date.today()+ 60;
            mdfReq.End_Date__c= mdfReq.Activity_Date__c.addDays(1);
            mdfReq.Activity_Type__c= 'Event – Webinar';
            mdfReq.Other_Vendors_Represented__c='Micros';
            mdfReq.Activity_Description__c='TestDescription';
            mdfReq.Number_of_Leads__c= 1000;
            mdfReq.Status__c= 'Approved'; 
            lstMDF.add(mdfReq);
        }
        
        insert lstMDF;
       Attachment oAttachment = new Attachment();
        Blob b = Blob.valueOf('Test Data');
        oAttachment.parentId = lstMDF[0].Id;
        oAttachment.Name = 'Test Attachment for Parent';
        oAttachment.Body = b;
        insert oAttachment;
       
         File__c objFile = new File__c();
        objFile.Name = 'Test';
        objFile.CP_Is_Cloned__c = false;
        objFile.Fund_Request__c = lstMDF[0].Id;
        objFile.Attachment_ID__c = oAttachment.Id;
       objFile.Proof_of_Performance_Document_Type__c = 'Request';
       objFile.Pre_Approval_Document_Type__c = 'Agenda';
       
        insert objFile;
Test.startTest();
 MDFListViewCmpController.updateFileProcess(objFile, 'testing',EncodingUtil.urlDecode('Testing8', 'UTF-8'), 'txt', 'Request', Agenda );
 Test.stopTest();
   }


}