force-app/main/default/objects/Message_Center__c/Message_Center__c.object-meta.xml
<CustomObject>
    <description>Using this object to populate messages on partner screen based on their creteria</description>
    <label>Message Center</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Message Center</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_Center__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>User for maintain criteria</description>
    <inlineHelpText>Please select  at-least  one</inlineHelpText>
    <label>Industry</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>FINANCIAL:BANKING CFI</fullName>
            </value>
            <value>
                <fullName>FINANCIAL:BANKING MAJOR</fullName>
            </value>
            <value>
                <fullName>FINANCIAL:OTHER</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY:QSR</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY:T&amp;E</fullName>
            </value>
            <value>
                <fullName>HOSPITALITY:TSR</fullName>
            </value>
            <value>
                <fullName>RETAIL:CFR</fullName>
            </value>
            <value>
                <fullName>RETAIL:DSR</fullName>
            </value>
            <value>
                <fullName>RETAIL:FDMM</fullName>
            </value>
            <value>
                <fullName>T&amp;T:TECHNOLOGY</fullName>
            </value>
            <value>
                <fullName>T&amp;T:TELECOM</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Message_Center__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>set true for active data</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message_Center__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Help to maintain logic based on criteria</description>
    <inlineHelpText>Please select at-least one</inlineHelpText>
    <label>Region</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>APJ</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>CLA</fullName>
            </value>
            <value>
                <fullName>CLA BRAZIL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EUROPE</fullName>
            </value>
            <value>
                <fullName>EUROPE EXC RUSSIA</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDIA &amp; SEA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>NAMER</fullName>
            </value>
            <value>
                <fullName>NAMER CFI</fullName>
            </value>
            <value>
                <fullName>NAMER DIRECT</fullName>
            </value>
            <value>
                <fullName>NAMER MAJORS</fullName>
            </value>
            <value>
                <fullName>NAMER SMB</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA</fullName>
            </value>
            <value>
                <fullName>NORTH ASIA &amp; SPA</fullName>
            </value>
            <value>
                <fullName>SAPAC</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Message_Center__c/fields/Tier_Level__c.field-meta.xml
<CustomField>
    <fullName>Tier_Level__c</fullName>
    <description>Use to show messages for  partner community</description>
    <inlineHelpText>Please select at-least one</inlineHelpText>
    <label>Tier Level</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
                <isActive>false</isActive>
                <label>Advanced</label>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
            <value>
                <fullName>Elite</fullName>
                <isActive>false</isActive>
                <label>Elite</label>
            </value>
            <value>
                <fullName>Premier</fullName>
                <isActive>false</isActive>
                <label>Premier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MCenterDupCheckerHelper.cls
/*
 * Class:	MCenterDupCheckerHelper
 * Description:	This class is using as helper class for MessageCenter DupChecker trigger to pevent from Duplicacy.
 * Date:	18/9/2019
 * DeveloperName:	Deeksharth Sriwastava
*/
public  class MCenterDupCheckerHelper {
    public static void DupChecker(List<Message_Center__c> msgCentr,List<Message_Center__c> msgCentrOld){
        Set<Id> MsgIds = new Set<Id>();
        if(msgCentrOld != NUll && msgCentrOld.size()>0){
            for(Message_Center__c msg : msgCentr){
            	MsgIds.add(msg.Id);
        	}
        }
        Map<Id,Message_Center__c> msgExistLst = New Map<Id,Message_Center__c>([SELECT Id,Industry__c,Region__c,Tier_Level__c FROM Message_Center__c where Is_Active__c =: true limit 50]);
        If(msgExistLst.size()>0 && msgExistLst != NULL){
            for(Message_Center__c msgExst : msgExistLst.values()){
                for(Message_Center__c msg : msgCentr){
                    if(!MsgIds.contains(msgExst.id)){
                        if(msg.Industry__c == msgExst.Industry__c && msg.Region__c == msgExst.Region__c && msg.Tier_Level__c == msgExst.Tier_Level__c){
                            msg.addError(system.label.MCntrDup1);//lRecord with the same combination was already exist.
                        }
                    }
                }
            }
        }
    }
}