force-app/main/default/objects/SFDC_MDF__c/SFDC_MDF__c.object-meta.xml
<CustomObject>
    <description>Track MDF request details including partner account, requested amount, activity type and date, and approval status.</description>
    <label>Fund Request</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund request approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request Created</fullName>
                <default>true</default>
                <label>Request Created</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Level 1 Review</fullName>
            </value>
            <value>
                <fullName>Level 2 Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_MDF_Claim__c/SFDC_MDF_Claim__c.object-meta.xml
<CustomObject>
    <description>A set of claims tied to a specific fund request.</description>
    <label>Fund Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund claim approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRM_MdfClaimTrigger_Test.cls
@isTest
public class PRM_MdfClaimTrigger_Test {
    @isTest
    static void mdfClaimTest() {
        // create MDF request
        SFDC_MDF__c mdfReq=PrepareMDFTestDataUtil.prepareMDFRecord();
        // Create claim 
        SFDC_MDF_Claim__c mdfClaim =  PrepareMDFTestDataUtil.prepareMDFClaimRecord(mdfReq.Id);
        // Update Claim Status
        mdfClaim.status__c = 'Submitted';
        update mdfClaim ;
        system.assertEquals( mdfClaim.status__c , 'Submitted');
    }
}