force-app/main/default/objects/SFDC_MDF__c/SFDC_MDF__c.object-meta.xml
<CustomObject>
    <description>Track MDF request details including partner account, requested amount, activity type and date, and approval status.</description>
    <label>Fund Request</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_MDF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The fund request approval status. This should be updated through an approval process rather than changing through the user interface</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request Created</fullName>
                <default>true</default>
                <label>Request Created</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Level 1 Review</fullName>
            </value>
            <value>
                <fullName>Level 2 Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MDFUtil.cls
global class MDFUtil {
  webservice static String cancelMDFRequest(String requestId) {
  	
  	// First check either user is having the permission to cancel the request or not, if not gave him error message.
  	
  	// Find Permission Set Ids who has the permission to Cancel the request.
  	Set<String> permissionSetAPIs = new Set<String>();
  	permissionSetAPIs.add('Channel_Operation_Team');
  	
  	Set<Id> permissionSetIds = new Set<Id>();
  	
  	for (PermissionSet pSet : [SELECT Id, Name FROM PermissionSet WHERE Name IN: permissionSetAPIs]) {
  	  permissionSetIds.add(pSet.Id);
  	}
  	
  	List<PermissionSetAssignment> pSetAssList = [SELECT AssigneeId, PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId=: UserInfo.getUserId() AND PermissionSetId IN: permissionSetIds];
  	
  	if (! (pSetAssList.size() > 0)) {
  	  return 'No_Permission';
  	}
  	
    List<SFDC_MDF__c> MDFRequestList = [SELECT Id, Status__c FROM SFDC_MDF__c WHERE Id =: requestId LIMIT 1];
    
    if (MDFRequestList.size() > 0) {
      SFDC_MDF__c mdfRequest = MDFRequestList[0];
      if (mdfRequest.Status__c == 'Cancelled'){
      	return 'already_cancelled';
      }
      mdfRequest.Status__c = 'Cancelled';
      Database.SaveResult result = DataBase.update(mdfRequest);
      if (result.isSuccess()) {
      	return 'true';
      } else {
          return 'false';
      }
    }
    return 'error';
  }
}