force-app/main/default/objects/ASM_Role_Hierarchy__c/ASM_Role_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Account Point of Contacts</label>
    <nameField>
        <displayFormat>APOC{000000}</displayFormat>
        <label>APOC ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Point of Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/NCR_Employee_Detail__c.field-meta.xml
<CustomField>
    <fullName>NCR_Employee_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to associate NCR Employee Detail so that we can assign the roles to the users.</description>
    <label>NCR Employee Detail</label>
    <referenceTo>NCR_Employee_Detail__c</referenceTo>
    <relationshipLabel>Account Point of Contacts</relationshipLabel>
    <relationshipName>Account_Point_of_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/QuickLook_ID__c.field-meta.xml
<CustomField>
    <fullName>QuickLook_ID__c</fullName>
    <label>Role User QuickLook ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Role_Name__c.field-meta.xml
<CustomField>
    <fullName>Role_Name__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Director</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>Account Services Manager</fullName>
                <isActive>false</isActive>
                <label>Account Services Manager</label>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Support Analyst</fullName>
            </value>
            <value>
                <fullName>Account Support Manager</fullName>
            </value>
            <value>
                <fullName>Channel Account Manager</fullName>
            </value>
            <value>
                <fullName>CMS Account Manager</fullName>
            </value>
            <value>
                <fullName>COA</fullName>
            </value>
            <value>
                <fullName>COE</fullName>
            </value>
            <value>
                <fullName>COL</fullName>
            </value>
            <value>
                <fullName>Collector</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Customer Advocate</fullName>
            </value>
            <value>
                <fullName>Customer Delivery Partner (CDP)</fullName>
            </value>
            <value>
                <fullName>Customer Project Manager (CPM)</fullName>
            </value>
            <value>
                <fullName>Customer Relationship Manager</fullName>
            </value>
            <value>
                <fullName>Customer Success Analyst</fullName>
            </value>
            <value>
                <fullName>Customer Success Leader</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
            <value>
                <fullName>Executive Service Manager</fullName>
            </value>
            <value>
                <fullName>Executive Services Manager</fullName>
                <isActive>false</isActive>
                <label>Executive Services Manager</label>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Field Operations</fullName>
            </value>
            <value>
                <fullName>Field Service Coordinator</fullName>
            </value>
            <value>
                <fullName>Field Training</fullName>
            </value>
            <value>
                <fullName>Global Account Manager</fullName>
            </value>
            <value>
                <fullName>Inside Sales Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Role_User_Name__c.field-meta.xml
<CustomField>
    <fullName>Role_User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Point_of_Contacts_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/Role_User_Qlook_Id__c.field-meta.xml
<CustomField>
    <fullName>Role_User_Qlook_Id__c</fullName>
    <formula>If(Role_User_Name__c != null,Role_User_Name__r.Quicklook_ID__c, NCR_Employee_Detail__r.Quicklook_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User QuicklookId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASM_Role_Hierarchy__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <formula>If(Role_User_Name__c!=null,Role_User_Name__r.FirstName + &apos; &apos; + Role_User_Name__r.LastName, NCR_Employee_Detail__r.User_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Role User Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BPM_Configuration__c/BPM_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BPM Configuration</label>
</CustomObject>

force-app/main/default/objects/CA_Hierarchy__c/CA_Hierarchy__c.object-meta.xml
<CustomObject>
    <description>This is to store customer advocate hierarchy which is different from salesforce(NCR) Hierarchy for APOC system</description>
    <label>CA Hierarchy</label>
    <nameField>
        <displayFormat>CA{00000}</displayFormat>
        <label>CA Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CA_Hierarchy__c/fields/CA_QuicklookId__c.field-meta.xml
<CustomField>
    <fullName>CA_QuicklookId__c</fullName>
    <label>CA QuicklookId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CA_Hierarchy__c/fields/Manager1_Name__c.field-meta.xml
<CustomField>
    <fullName>Manager1_Name__c</fullName>
    <label>Manager1 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CA_Hierarchy__c/fields/Manager1_Quicklookid__c.field-meta.xml
<CustomField>
    <fullName>Manager1_Quicklookid__c</fullName>
    <label>Manager1 Quicklookid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CA_Hierarchy__c/fields/Manager2_Quicklookid__c.field-meta.xml
<CustomField>
    <fullName>Manager2_Quicklookid__c</fullName>
    <label>Manager2 Quicklookid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CA_Hierarchy__c/fields/Manager3_Quicklookid__c.field-meta.xml
<CustomField>
    <fullName>Manager3_Quicklookid__c</fullName>
    <label>Manager3 Quicklookid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CA_Hierarchy__c/fields/Manager4_Name__c.field-meta.xml
<CustomField>
    <fullName>Manager4_Name__c</fullName>
    <label>Manager4 Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CA_Hierarchy__c/fields/Manager4_Quicklookid__c.field-meta.xml
<CustomField>
    <fullName>Manager4_Quicklookid__c</fullName>
    <label>Manager4 Quicklookid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/NCR_Employee_Detail__c.object-meta.xml
<CustomObject>
    <description>This object stores the details of all NCR employees.</description>
    <label>NCR Employee Detail</label>
    <nameField>
        <label>NCR Employee Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCR Employee Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Contingent_Manager__c.field-meta.xml
<CustomField>
    <fullName>Contingent_Manager__c</fullName>
    <label>Contingent Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_ID__c</fullName>
    <label>Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/InActive__c.field-meta.xml
<CustomField>
    <fullName>InActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Manager_Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Manager_Global_ID__c</fullName>
    <label>Manager Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NCR_Employee_Detail__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>User Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Global_ID__c</fullName>
    <label>User Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Manager_Global_ID__c.field-meta.xml
<CustomField>
    <fullName>Manager_Global_ID__c</fullName>
    <label>Manager Global ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CalculateContingentHierarchy.cls
/*
####################################################################################################################
# Project Name..........: BPM Automation                                                                                                                      
# File............................:CalculateContingentHierarchy.cls                                                             
# Created by................: Varsha Pal                                                                      
# Created Date...........: 09-02-2021                                                                                
# Last Modified by......: Varsha Pal                                                                           
# Last Modified Date..: 09-02-2021                                                                               
# Description...............: This class calculates Contingent Manager Hierarchy of all Contingent workers and store
							  it in CA Hierarchy Object.
####################################################################################################################
*/

public class CalculateContingentHierarchy implements Database.Batchable < sObject > , Database.Stateful, schedulable {
    Map <String,String> EmpMap = new Map <String,String> (); // Map -> Key = Global_Id__c of User : Value = Contingent_Manager__c of user(global id of contingent hierachy) - Both values are coming from workday(NIAM team) on NCR_Employee_Detail__c object
    Map <String,String> empNameMap = new Map <String,string> (); // Map -> Key = Global_Id__c from NCR_Employee_Detail__c : Value = User_name__c from NCR_Employee_Detail__c
    Map<String,String> empQlMap = new Map<String,String>(); // Map -> Key = Global_Id__c from NCR_Employee_Detail__c : Value = Quicklook_ID__c from NCR_Employee_Detail__c
    String msgBody='Contingent Manager Hierarchy Batch Failed. Please check Apex Jobs.';
   
    public Database.QueryLocator start(Database.BatchableContext BC) {
        for (NCR_Employee_Detail__c emp: [Select Id, User_Name__c, Quicklook_ID__c, Global_ID__c, Contingent_Manager__c,Manager_Global_ID__c from NCR_Employee_Detail__c where inactive__c = false and Employee_type__c!=null limit 50000]) {
            empNameMap.put(emp.global_id__c, emp.User_Name__c);
            empQlMap.put(emp.Global_ID__c,emp.Quicklook_ID__c);
            if (emp.Contingent_Manager__c!=null){
                EmpMap.put(emp.global_id__c, emp.Contingent_Manager__c);
            }else if(emp.global_id__c!=emp.Manager_Global_ID__c) {
               EmpMap.put(emp.global_id__c, emp.Manager_Global_ID__c); 
            }
        }
        return Database.getQueryLocator([Select Role_User_Qlook_Id__c,User_Name__c from ASM_Role_hierarchy__c where Role_User_Name__r.isactive=true and Role_Name__c='Customer Advocate']);
    }

    public void execute(Database.BatchableContext BC, List<ASM_Role_hierarchy__c> CAList) {
        try{
            Map<String,List <String>> qlIdHrchyMap = new Map<String,List <String>>();//Map -> Key = Quicklook_ID__c from User :Value = reporting hierarchy of the user    
            Set<String> qlSet = new Set<String>();
            Map<String,String> actvUsr = new Map<String,String>();
            for(ASM_Role_hierarchy__c a: CAList){
                actvUsr.put(a.Role_User_Qlook_Id__c.toLowerCase(),a.User_Name__c);
            }
            for (NCR_Employee_Detail__c u: [Select Id, Quicklook_ID__c, Global_ID__c  from NCR_Employee_Detail__c where inactive__c = false and Quicklook_ID__c in:actvUsr.keyset()]) {
                List <String> hrchy = new List < String > ();
                String H = u.global_id__c;
                hrchy.add(H);
                while (EmpMap.get(H) != null && String.isNotEmpty(EmpMap.get(H)) && !(hrchy.size()>5)){
                    hrchy.add(EmpMap.get(H));
                    H = EmpMap.get(H);
                }
                if (hrchy != null && hrchy.size() > 0) {
                    qlIdHrchyMap.put(u.Quicklook_ID__c.toLowerCase(),hrchy);
                }
            }
            List<CA_Hierarchy__c> caLst = new List<CA_Hierarchy__c>();
            List<CA_Hierarchy__c> caLst1 = new List<CA_Hierarchy__c>();
            Set<String> qlids = new Set<String>();
            for(CA_Hierarchy__c ca : [Select id,CA_QuicklookId__c from CA_Hierarchy__c where CA_QuicklookId__c in: qlIdHrchyMap.keyset() ]){
                String ql = ca.CA_QuicklookId__c.toLowerCase(); 
                qlids.add(ql);
                if(actvUsr.get(ql)!=null){
                    if(qlIdHrchyMap.get(ql)!=null){
                        List<String> hrchy= qlIdHrchyMap.get(ql);
                        CA_Hierarchy__c c = ca;
                        caLst.add(setHierarchy(ql,c,hrchy));
                    }
                }else{
                    caLst1.add(ca);
                }
            }
            for(String ql: actvUsr.keyset()) {
                if(!qlids.contains(ql)){
                    if(qlIdHrchyMap.get(ql)!=null){
                        List<String> hrchy= qlIdHrchyMap.get(ql);
                        CA_Hierarchy__c c = new CA_Hierarchy__c();
                        c.CA_Name__c = actvUsr.get(ql);
                        c.CA_QuicklookId__c = ql;
                        caLst.add(setHierarchy(ql,c,hrchy));
                    }
                }
            }
            System.debug('caLst'+caLst);
            if(!caLst.isEmpty()){
                upsert caLst;    
            }
            if(!caLst1.isEmpty()){
                delete caLst1;
            }
            msgBody = 'SUCCESS';
        }catch(Exception ex){
            msgBody = 'Contingent Manager Hierarchy Batch Process has failed due to '+ex.getMessage()+' at Line number '+ex.getLineNumber();
        }
    }

    public void finish(Database.BatchableContext BC) {
        if(!msgBody.contains('failed')){
            delete [Select id,CA_QuicklookId__c from CA_Hierarchy__c where lastmodifieddate !=today];
        }
       	if(msgBody.contains('failed')||Test.isRunningTest()){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(BPM_Configuration__c.getValues('CAHierarchyJobReciever').values__c.split(','));
            //Changes done by Yogesh - related to Story EBA_SF-1919
            //ail.setOrgWideEmailAddressId('0D270000000XZHr');
             Id OrgId= NSCCommonInfoUtil.getIdOf('CCH_OrgId');
            //End changes by Yogesh
            mail.setOrgWideEmailAddressId(OrgId);
            mail.setPlainTextBody(msgBody);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {
                mail
                    });
        }
    }
    public void execute(SchedulableContext SC) {
        database.executebatch(new CalculateContingentHierarchy());
    }
    public CA_Hierarchy__c setHierarchy(String qlId,CA_Hierarchy__c c, List<String> hrchy){
        Integer hsize = hrchy.size();
        if(hsize>=5){
            c.Manager1_Name__c = empNameMap.get(hrchy.get(1));
            c.Manager2_Name__c = empNameMap.get(hrchy.get(2));
            c.Manager3_Name__c = empNameMap.get(hrchy.get(3));
            c.Manager4_Name__c = empNameMap.get(hrchy.get(4));
            
            c.Manager1_Quicklookid__c = empQlMap.get(hrchy.get(1));
            c.Manager2_Quicklookid__c = empQlMap.get(hrchy.get(2));
            c.Manager3_Quicklookid__c = empQlMap.get(hrchy.get(3));
            c.Manager4_Quicklookid__c = empQlMap.get(hrchy.get(4));
        }
        if(hsize==4){
            c.Manager1_Name__c = empNameMap.get(hrchy.get(1));
            c.Manager2_Name__c = empNameMap.get(hrchy.get(2));
            c.Manager3_Name__c = empNameMap.get(hrchy.get(3));
            
            c.Manager1_Quicklookid__c = empQlMap.get(hrchy.get(1));
            c.Manager2_Quicklookid__c = empQlMap.get(hrchy.get(2));
            c.Manager3_Quicklookid__c = empQlMap.get(hrchy.get(3));
        }
        if(hsize==3){
            c.Manager1_Name__c = empNameMap.get(hrchy.get(1));
            c.Manager2_Name__c = empNameMap.get(hrchy.get(2));
            
            c.Manager1_Quicklookid__c = empQlMap.get(hrchy.get(1));
            c.Manager2_Quicklookid__c = empQlMap.get(hrchy.get(2));
        }
        if(hsize==2){
            c.Manager1_Name__c = empNameMap.get(hrchy.get(1));
            c.Manager1_Quicklookid__c = empQlMap.get(hrchy.get(1));
        }
        return c;
    }
}