force-app/main/default/objects/Opportunity/fields/CAM_TAM_Confirm_Net_New_Customer__c.field-meta.xml
<CustomField>
    <fullName>CAM_TAM_Confirm_Net_New_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CAM/TAM Confirm Net New Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Linked_Special_Bid_Registration__c.field-meta.xml
<CustomField>
    <fullName>Linked_Special_Bid_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Deal Registration</label>
    <referenceTo>Deal_Registration__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Net_New_Customer__c.field-meta.xml
<CustomField>
    <fullName>Net_New_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This checkbox states this customer is a Net New Customer as specified within the Deal Registration Program Guide, located in Seismic.</inlineHelpText>
    <label>Net New Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PRM_Opp_Net_New_Customer_PopUP_Contoller.cls
public class PRM_Opp_Net_New_Customer_PopUP_Contoller {
    
    @AuraEnabled
    public static Opportunity getOpportunityDetail(String oppId ){        
        Opportunity opportunityInfo = [SELECT Id,Net_New_Customer__c, CAM_TAM_Confirm_Net_New_Customer__c, Linked_Special_Bid_Registration__c 
                                       FROM Opportunity 
                                       WHERE Id =: oppId 
                                       LIMIT 1];
        return opportunityInfo;
    } 
    
    @AuraEnabled
    public static void setConfrimNetNewCustomer(String oppId ,Boolean netNewCustomerConfirm){        
        Opportunity opportunityInfo = [SELECT Id,Net_New_Customer__c, CAM_TAM_Confirm_Net_New_Customer__c, Linked_Special_Bid_Registration__c 
                                       FROM Opportunity 
                                       WHERE Id =: oppId 
                                       LIMIT 1];
		opportunityInfo.CAM_TAM_Confirm_Net_New_Customer__c = netNewCustomerConfirm;
        opportunityInfo.Net_New_Customer__c = true;
        Update opportunityInfo;
    }
}