force-app/main/default/objects/Opportunity/fields/CAM_TAM_Confirm_Net_New_Customer__c.field-meta.xml
<CustomField>
    <fullName>CAM_TAM_Confirm_Net_New_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CAM/TAM Confirm Net New Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Net_New_Customer__c.field-meta.xml
<CustomField>
    <fullName>Net_New_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This checkbox states this customer is a Net New Customer as specified within the Deal Registration Program Guide, located in Seismic.</inlineHelpText>
    <label>Net New Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PRM_Opp_Net_New_Customer_PopUP_Ctrl_Test.cls
@isTest
public class PRM_Opp_Net_New_Customer_PopUP_Ctrl_Test {

    @isTest
    public static void getOpportunityDetailTest(){
        Opportunity opportunityTestRecord = new Opportunity();
        opportunityTestRecord.Name='Test Opportunity';
        opportunityTestRecord.CAM_TAM_Confirm_Net_New_Customer__c = false;
        opportunityTestRecord.Net_New_Customer__c = true;
        opportunityTestRecord.StageName='Analyzing';
        opportunityTestRecord.CloseDate = Date.today()+10;
        Insert opportunityTestRecord;
                System.assertNotEquals(opportunityTestRecord,NULL,'opportunityTestRecord not be NULL');

        Test.startTest();
        PRM_Opp_Net_New_Customer_PopUP_Contoller.getOpportunityDetail(opportunityTestRecord.id);
        Test.stopTest();
        
    }
    
     @isTest
    public static void setConfrimNetNewCustomerTest(){
        Opportunity opportunityTestRecord = new Opportunity();
        opportunityTestRecord.Name='Test Opportunity';
        opportunityTestRecord.CAM_TAM_Confirm_Net_New_Customer__c = true;
        opportunityTestRecord.Net_New_Customer__c = true;
        opportunityTestRecord.StageName='Analyzing';
        opportunityTestRecord.CloseDate = Date.today()+10;
        Insert opportunityTestRecord;
        System.assertNotEquals(opportunityTestRecord,NULL,'opportunityTestRecord not be NULL');
        Test.startTest();
        PRM_Opp_Net_New_Customer_PopUP_Contoller.setConfrimNetNewCustomer(opportunityTestRecord.id,true);
        Test.stopTest();
        
    }
	
}