force-app/main/default/objects/Opportunity/fields/Linked_Partner_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Linked_Partner_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Reseller Opportunity</label>
    <referenceTo>Partner_Opportunity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Opportunity__c/Partner_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Partner Opportunity</label>
    <nameField>
        <displayFormat>CPO -{0000}</displayFormat>
        <label>Partner Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Opportunity__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <label>Quote Number</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/QuBy_Detail__c.object-meta.xml
<CustomObject>
    <label>All QuBy Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>All QuBy Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuBy_Detail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>All QuBy Quotes</relationshipLabel>
    <relationshipName>All_QuBy_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuBy_Detail__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <externalId>true</externalId>
    <label>Quote Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PRM_QuBY_DetailTriggerHandler.cls
public class PRM_QuBY_DetailTriggerHandler {
    public static void updateQuoteNumOnPartnerOpp (List<QuBy_Detail__c> QuByDetailList ) {
        Set<Id> oppIds = new Set<Id>();
        
        for (QuBy_Detail__c qbDetail : QuByDetailList) {
            oppIds.add(qbDetail.Opportunity__c);
        }
        
        Map<Id,String> partnerOppIdToQuoterNumMap = new Map<Id,String>();
        
        if (oppIds.size() > 0) {
            
            for (Opportunity op : [SELECT Id,Linked_Partner_Opportunity__c, (SELECT Id,Quote_Number__c FROM All_QuBy_Quotes__r)  FROM Opportunity WHERE Id IN: oppIds AND Linked_Partner_Opportunity__c != null]) {
                String quoteNumbers = '';
                for (QuBy_Detail__c qd : op.All_QuBy_Quotes__r) {
                    quoteNumbers = (quoteNumbers != '') ? quoteNumbers +'; ' + qd.Quote_Number__c : qd.Quote_Number__c;
                }
                if (quoteNumbers != '') {
                    partnerOppIdToQuoterNumMap.put(op.Linked_Partner_Opportunity__c,quoteNumbers);
                }
                
            }
            
        }
        
        if (partnerOppIdToQuoterNumMap.keySet().size() > 0) {
            List<Partner_Opportunity__c> partnerOpportunity = [SELECT Id, Quote_Number__c FROM Partner_Opportunity__c WHERE Id IN: partnerOppIdToQuoterNumMap.keySet()];
            for (Partner_Opportunity__c po : partnerOpportunity ) {
                po.Quote_Number__c = partnerOppIdToQuoterNumMap.get(po.Id);
            }
            update partnerOpportunity ;
        }
    }
}