force-app/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>CATM</description>
    <label>Product Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Service_Offer_Category__c.field-meta.xml
<CustomField>
    <fullName>Service_Offer_Category__c</fullName>
    <label>Revenue Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Annuity_product__c.field-meta.xml
<CustomField>
    <fullName>Annuity_product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurring Revenue product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Professional Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Offer_Category__c.field-meta.xml
<CustomField>
    <fullName>Service_Offer_Category__c</fullName>
    <label>Revenue Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/synchUSMOnOppUpdt_Test.cls
@isTest
public class synchUSMOnOppUpdt_Test {
     
    public static testMethod void SynkUSMQueUpdate(){
       List<Product2> products = new List<Product2>(); 
       Product2 HWMProduct1 = new Product2( Name='Orderman', CurrencyIsoCode='USD',  Service_Offer_Category__c = 'HWM',Product_Category__c ='CS',isactive=true, Annuity_product__c = true, CanUseQuantitySchedule = true);
        products.add(HWMProduct1) ;
       insert products;
        
       List<Opportunity>  Opportunities = TestRecordsFactory.returnOpportunities(1);
       Opportunity opp = Opportunities[0]; 
       insert opp;
       List<Id> Opplist = new List<Id>(); 
       Opplist.add(Opp.Id);	
       OpportunityLineItem lstOLI = TestRecordsFactory.createOpportunityLineItem(opp, TestRecordsFactory.createPriceBookEntry(HWMProduct1));
       synchUSMOnOppUpdateQueueable QueableObj = new synchUSMOnOppUpdateQueueable(Opplist); 
       synchUSMOnOppLinkQueueable QueableLinkObj = new synchUSMOnOppLinkQueueable(Opplist);
        Test.startTest();
           Id job1= System.enqueueJob(QueableObj);
            System.enqueueJob(QueableLinkObj);
        system.assert(job1 !=null);
        Test.stopTest();
    }
}