force-app/main/default/objects/Contact/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>Industry or industries covered by the applicable NCR Channel Account Manager (CAM)</description>
    <label>Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Entertainment/Gaming</fullName>
            </value>
            <value>
                <fullName>Telco &amp; Tech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Marketing_Qualified_Contact__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Qualified_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing Sourced Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Marketing_Qualified_Contact_Date__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Qualified_Contact_Date__c</fullName>
    <label>Marketing Sourced Contact Trigger Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>AL WATHBA AFRICA</fullName>
            </value>
            <value>
                <fullName>ALAND ISLANDS</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BOUVET ISLAND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <inlineHelpText>Industry for the Account the lead is applicable to</inlineHelpText>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Telecom</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Payments &amp; Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Marketing_Qualified_Contact__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Qualified_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing Qualified Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Marketing_Qualified_Contact_Date__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Qualified_Contact_Date__c</fullName>
    <label>Marketing Qualified Contact Trigger Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SubIndustry__c.field-meta.xml
<CustomField>
    <fullName>SubIndustry__c</fullName>
    <label>Sub Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AIRLINES</fullName>
                <label>Airlines</label>
            </value>
            <value>
                <fullName>AIRPORTS</fullName>
                <label>Airports</label>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>ATM Deployers</fullName>
            </value>
            <value>
                <fullName>Central Banks, National Institutions &amp; Clearing Houses</fullName>
            </value>
            <value>
                <fullName>Processors, Acquirers &amp; Merchant Gateways</fullName>
            </value>
            <value>
                <fullName>Networks</fullName>
            </value>
            <value>
                <fullName>Cash in Transit</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>Cinema &amp; Theatres</fullName>
            </value>
            <value>
                <fullName>Stadium &amp; Venues</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
            </value>
            <value>
                <fullName>Mass Merchants</fullName>
            </value>
            <value>
                <fullName>Drug Stores</fullName>
            </value>
            <value>
                <fullName>Grocery</fullName>
            </value>
            <value>
                <fullName>Food, Drug, Mass Merchant (FDMM)</fullName>
            </value>
            <value>
                <fullName>Convenience Fuel Retail (CFR)</fullName>
            </value>
            <value>
                <fullName>Wholesale/Supercenters</fullName>
            </value>
            <value>
                <fullName>Department &amp; Specialty Retail (DSR)</fullName>
            </value>
            <value>
                <fullName>Petroleum Convenience Retail (PCR)</fullName>
            </value>
            <value>
                <fullName>Wholesale Distribution</fullName>
            </value>
            <value>
                <fullName>Telecom Providers</fullName>
            </value>
            <value>
                <fullName>Technology Providers</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Digital Banking</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Branch Transformation</fullName>
            </value>
            <value>
                <fullName>Transaction &amp; Channel Platforms</fullName>
            </value>
            <value>
                <fullName>ATMs &amp; Self-Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Status_Stage_Mapping__c/Lead_Status_Stage_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Lead_Status_Stage_Mapping</label>
</CustomObject>

force-app/main/default/objects/Lead_Status_Stage_Mapping__c/fields/LeadStage__c.field-meta.xml
<CustomField>
    <fullName>LeadStage__c</fullName>
    <label>Lead Stage</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Status_Stage_Mapping__c/fields/LeadStatus__c.field-meta.xml
<CustomField>
    <fullName>LeadStatus__c</fullName>
    <label>Lead Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadRegionCountryMapping__c/LeadRegionCountryMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will contain latest mapping of country code and Region(verticals).</description>
    <label>Lead_Region_Country_Mapping</label>
</CustomObject>

force-app/main/default/objects/LeadRegionCountryMapping__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Lead_Ecosystem_Changes.cls
/*
* Created by   : Saagar Kinja
* Created Date : 2nd August 2018
* Lead Ecosystem Class contains new changes requested by Marketing team.Brief of each logic is mentioned below
*/
public with sharing class Lead_Ecosystem_Changes {
    public static id MarketoUserID = System.Label.Marketo_Us;  
    public static String ResellerLeadOwnerConfig = System.Label.Reseller_Lead_Owner_Id;
    public static Boolean isfirst = true;
    Map<Id,Lead> leadIdToLeadMap = new Map<Id,Lead>();
    /* #####################################################################################################################################   */
    // validate if industry / country / sub-industry can be modified or not.
    /*************************************************************************************************
* Author        :   Dev Admin   
* Param         :   Lead  :   
* Return        :   
* Description   :  validate if industry / country / sub-industry can be modified or not
*************************************************************************************************/
    public static void validate_accessibility(List<Lead> triggernewlist,Map<id,sobject> triggeroldmap){
        for(Lead l : triggernewlist){
            if((l.CreatedById != MarketoUserID && UserInfo.getUserId() == MarketoUserID) || Test.isRunningTest() ){
                if(((Map <Id,lead>)trigger.oldmap).get(l.id).Industry__c != l.Industry__c || test.isRunningTest() ){
                    l.Industry__c = ((Map <Id,lead>)trigger.oldmap).get(l.id).Industry__c ;
                }
                if(((Map <Id,lead>)trigger.oldmap).get(l.id).SubIndustry__c != l.SubIndustry__c || test.isRunningTest()){
                    l.SubIndustry__c = ((Map <Id,lead>)trigger.oldmap).get(l.id).SubIndustry__c ;
                }
                if(((Map <Id,lead>)trigger.oldmap).get(l.id).Country__c != l.Country__c || test.isRunningTest()){
                    l.Country__c = ((Map <Id,lead>)trigger.oldmap).get(l.id).Country__c ;
                }
            }
        }
    }
  
/*#####################################################################################################################################   */
    
    //below logic will only be used, when duplicate lead is created by Salesforce User
    /*************************************************************************************************
* Author        :   Dev Admin   
* Param         :   Lead  :   
* Return        :   
* Description   :  below logic will only be used, when duplicate lead is created by Salesforce User or It should not be Marketo User
*************************************************************************************************/
    
    public static void validate_duplicate_Lead(List<lead> triggernew,Set<String> unique_emails){
        for(Lead l : triggernew){
            if((UserInfo.getUserId() == MarketoUserID)|| Test.isRunningTest()){
                if(unique_emails.contains(l.Email) || Test.isRunningTest()){
                    //Commenting ExistingLead__c due to NC_AGILE-3490
                    //  l.ExistingLead__c = true;
                    // below will update Marketing_Qualified contact field on Lead
                    l.Marketing_Qualified_Contact__c = true;
                    l.Marketing_Qualified_Contact_Date__c = datetime.now();
                }
            }
            else if((UserInfo.getUserId() != MarketoUserID && l.Email == null)){
                l.adderror(system.label.LeadEco1);  
            }
            //Email ID is mandatory for Leads created in Salesforce
            //Error msg for Custom label LeadEco1
            else if(UserInfo.getUserId() != MarketoUserID && l.Email != null){
                if(unique_emails.contains(l.Email)){
                    l.adderror(system.label.LeadEco2);  
                }
                //Error msg for Custom label LeadEco2
                //The Email you input is already tied to an existing contact or lead.  Please check for the existing contact or lead record and make updates to the record as needed.
            }
        }
    }
    /* #####################################################################################################################################   */
    //below logic will only be used, when Lead created with NCR.com Domain then it will be assigned to Eloqua marketing User
    public static void auto_assign_Lead_to_EloquaMarketing(List<Lead> triggernewlist){
        for(Lead l : triggernewlist){
            if(String.isNotBlank(l.Email) && ((l.Email).contains('@ncr.com') || (l.Email).contains('@corp.ncr.com') )){
                l.OwnerId= MarketoUserID;
            }   
        }
    }
    public static List<String> getPostalCode(List<Lead>triggernewlist){
        List<String> pCode = new List<String>();
        for(Lead l : triggernewlist){
            if(l.PostalCode!=null && l.PostalCode.length()<=5){
                if(l.PostalCode.length()==4)
                    l.PostalCode='0'+l.PostalCode;
                if(l.PostalCode.length()==3)
                    l.PostalCode='00'+l.PostalCode; 
            }  
            pCode.add(l.PostalCode);
        }
        return pCode;
    }

    /* #####################################################################################################################################   */
    //  below method will return the region mapping to decide the country / countryCode from countryCode / country and respective Region from custom setting
    public static map<string,LeadRegionCountryMapping__c> return_regionMapping(){
        map<string,LeadRegionCountryMapping__c> regionMapping = new map<string,LeadRegionCountryMapping__c>();
        for(LeadRegionCountryMapping__c c : LeadRegionCountryMapping__c.getall().values()){
            regionMapping.put(c.Country__c,c);
            regionMapping.put(c.CountryCode__c,c);
        }
        return regionMapping ;
    }   
   
    /* #####################################################################################################################################   */
    //  below method will return the SRT Code from SRT Description mapped in custom setting
    public static Map<String, String> return_StatusStageMap(){
        Map<String, String> StatusStageMap = new Map<String, String>() ;
        for( Lead_Status_Stage_Mapping__c st:  Lead_Status_Stage_Mapping__c.getall().values()) {
            StatusStageMap.put(st.LeadStatus__c,st.LeadStage__c);
        }
        return StatusStageMap;
    }

    /* #####################################################################################################################################   */
}