force-app/main/default/objects/Deming__c/Deming__c.object-meta.xml
<CustomObject>
    <label>CADD Management</label>
    <nameField>
        <displayFormat>CADD-{0000}</displayFormat>
        <label>CADD Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CADD Management</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deming__c/fields/Acceptance_Time__c.field-meta.xml
<CustomField>
    <fullName>Acceptance_Time__c</fullName>
    <label>Customer Contact Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Cadd_Status__c.field-meta.xml
<CustomField>
    <fullName>Cadd_Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Customer Approval</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Customer_Acceptance_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Acceptance_Date__c</fullName>
    <label>Customer Accepted  Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Person Who Accepted the new Promise Date</description>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/isCustomerContacted__c.field-meta.xml
<CustomField>
    <fullName>isCustomerContacted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCustomerContacted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Ncr_Associate__c.field-meta.xml
<CustomField>
    <fullName>Ncr_Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCR Associate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Demings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <label>Order Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Order_number__c.field-meta.xml
<CustomField>
    <fullName>Order_number__c</fullName>
    <externalId>true</externalId>
    <label>Order number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deming__c/fields/Reason_Of_Rejection__c.field-meta.xml
<CustomField>
    <fullName>Reason_Of_Rejection__c</fullName>
    <label>Rejection Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distressed Stores</fullName>
            </value>
            <value>
                <fullName>Grand Opening</fullName>
            </value>
            <value>
                <fullName>Pilot</fullName>
            </value>
            <value>
                <fullName>High Impact Store</fullName>
            </value>
            <value>
                <fullName>Tech Refresh for Compliance</fullName>
            </value>
            <value>
                <fullName>Tech Refresh</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Soup_Username__mdt/Soup_Username__mdt.object-meta.xml
<CustomObject>
    <label>Soup_Username</label>
    <pluralLabel>Soup_Usernames</pluralLabel>
</CustomObject>

force-app/main/default/objects/Soup_Username__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soup_Username__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soup_Username__mdt/fields/User_name__c.field-meta.xml
<CustomField>
    <fullName>User_name__c</fullName>
    <label>User_name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Nsc_Soup_Integration.cls
public class Nsc_Soup_Integration {
    
    
    final static string SUCCESS_STATUS='SUCCESS';
    final static string FAILURE_STATUS='FAILURE';
    static Soup_Username__mdt   soup_cred;
    
    public static  void synchLOS_OM(list<id> dmgId){
        
        list<Deming__c>deminglist=new list<Deming__c>();
        // deminglist=[select Order_Id__c,Order_number__c,Customer_Acceptance_Date__c,Customer_Name__c,Ncr_Associate__c,isCustomerContacted__c,Customer_Contact_Name__c,Cadd_Status__c,Acceptance_time__c from deming__c where id=:dmgId];     
        deminglist=[select Order_Id__c,Order_number__c,Customer_Acceptance_Date__c,Customer_Name__c,Ncr_Associate__c,isCustomerContacted__c,Customer_Contact_Name__c,Cadd_Status__c,Acceptance_time__c,Reason_Of_Rejection__c from deming__c where id=:dmgId];
        
        //system.debug('@@@@@@'+deminglist);       
        // soup_cred=[select user_name__c,password__c, EndPoint__c from Soup_Username__mdt where DeveloperName='header'];
        //String userID=string.valueof(soup_cred.user_name__c);
        //String password=soup_cred.password__c;
        // String EndPoint=soup_cred.EndPoint__c;
        //system.debug('@@@@@@'+userID+'>>>>>>><<<<<<<'+password+'!!!!!'+EndPoint);
        //String jsonBody ='userID='+userID+'&password='+password; 
        
        try{
            for(deming__c dmg : deminglist){
                if(dmg.Order_Id__c!=null && dmg.Cadd_Status__c!=null  ){
                    
                    
                    
                    
                    
                    
                    
                    String bdy=generateRequestBody(new Uuid().getValue(), 'NSC', string.valueof(Datetime.now().format()), 'ERP', string.valueof(dmg.Order_Id__c),string.valueof(dmg.Order_number__c) ,string.valueof(dmg.Customer_Acceptance_Date__c), string.valueof(dmg.Customer_Contact_Name__c), NSCCommonInfoUtil.getIdOf('AtmPrcsUserId') ,string.valueof(dmg.isCustomerContacted__c), string.valueof(dmg.Cadd_Status__c), string.valueof(dmg.Acceptance_Time__c),string.valueOf(dmg.Reason_Of_Rejection__c));          
                    
                    system.debug('bdy@@@>>>' + bdy);
                    
                    HttpRequest req=new HttpRequest();
                    
                    HttpResponse res= new HttpResponse() ;
                    //Blob headerValue = Blob.valueOf(userID + ':' + password);
                    //String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
                    Http h = new Http();
                    req.setBody(bdy);
                    req.setMethod('POST');
                   // req.setHeader('Authorization', authorizationHeader);
                    // req.setEndpoint('https://osbcert-ha.ncr.com/ext/EA/NSC/Services/NSCOrderHeaderUpdatePS?wsdl');
                    req.setEndpoint('callout:NSC_SOUP_Header');
                        // req.setEndpoint(EndPoint);
                        if(!Test.isRunningTest()) {
                            res = h.send(req);
                            System.debug(res.getStatus());
                            //system.debug('<><><><><'+res);
                            
                            
                            
                            if(res.getStatus()==SUCCESS_STATUS){
                                System.debug('Deming Record successfully synced with ERP');
                                // String respStr = parseXMLResponse(res.getBody());
                                
                                
                            }
                        } 
                    
                }
            }  
        }
        
        catch(Exception ex){
            system.debug('error occured'+ex.getMessage());
        }
        
        
    }
    @future(callout=true)
    public static  void synchLOS_OM_With_Future(list<id> dmgId){
        synchLOS_OM(dmgId);
    }
    
    
    
    
    
    private static String generateRequestBody(String transactionID, String sourceSystem, String timestamp, String targetSystem, String OrderID, String OrderNumber, string CustomerAcceptanceDate, string CustomerName,string NCRAssociate, string isCustomerContacted, string Status,string AcceptanceDate,string rejectionOfCode){
        String QuickLook;
        user usr=[select Quicklook_ID__c from user where id=:NCRAssociate];
        
        if(usr!=null)
            QuickLook =usr.Quicklook_ID__c;
        
        QuickLook='';
        AcceptanceDate='';
        isCustomerContacted='';
        
        
        
        if(String.isBlank(CustomerAcceptanceDate)) CustomerAcceptanceDate = '';
        
        if(string.isBlank(status)) status='';
        String ReasonOfRejct='Other';
        
        // if(Status=='Reject'){
        //   CustomerAcceptanceDate=string.valueof(system.today());
        
        //   }
        
        //  if(Status==null){
        //   CustomerAcceptanceDate=string.valueof(system.today());
        //  Status='';
        
        //   }
        
        String  SoupRequest='<?xml version=\"1.0\" encoding=\"utf-8\"?>'+
            '<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">'+
            '<Body>'+
            '<OrderHeaderUpdateRequestABM xmlns="http://xmlns.ncr.com/SOUP/ABM/NSC/OrderHeaderUpdate/V1">' +
            '<RequestHeader>'+ 
            '<TransactionID xmlns="http://xmlns.ncr.com/SOUP/Common/2.0">'+transactionID+'</TransactionID>' +
            '<SourceSystem xmlns="http://xmlns.ncr.com/SOUP/Common/2.0">'+sourceSystem+'</SourceSystem>' +
            '<Timestamp xmlns="http://xmlns.ncr.com/SOUP/Common/2.0">'+timestamp+'</Timestamp>' +
            '<TargetSystem xmlns="http://xmlns.ncr.com/SOUP/Common/2.0">'+targetSystem+'</TargetSystem>' +
            '</RequestHeader>'+  
            '<OrderHeaderUpdateRequest>' +
            '<OrderID>'+OrderID+'</OrderID>'+
            '<OrderNumber>'+OrderNumber+'</OrderNumber>'+
            '<CustomerAcceptanceDate>'+CustomerAcceptanceDate+'</CustomerAcceptanceDate>'+
            '<CustomerName>'+CustomerName+'</CustomerName>'+
            '<NCRAssociate>'+NCRAssociate+'</NCRAssociate>'+
            '<isCustomerContacted>'+isCustomerContacted+'</isCustomerContacted>'+
            '<Status>'+Status+'</Status>'+
            '<CADDAcceptanceTimestamp>'+CustomerAcceptanceDate+'</CADDAcceptanceTimestamp>'+
            '<CADDRejectionReason>'+rejectionOfCode+'</CADDRejectionReason>'+
            '</OrderHeaderUpdateRequest>'+
            '</OrderHeaderUpdateRequestABM>'+
            ' </Body>'+
            '</Envelope>'; 
        
        return SoupRequest; 
        
    }
    
    
    
    public static list<Deming__c> generateData(){
        
        list<Deming__c> demList=new list<Deming__c>();
        
        
        return  demList  ;
    }
    /* public HttpResponse GenerateRequest( String bdy ){
HttpRequest req1=new HttpRequest();

HttpResponse res1= new HttpResponse() ;
// Blob headerValue = Blob.valueOf(userID + ':' + password);
// String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
Http h = new Http();
req1.setBody(bdy);
req1.setMethod('POST');
// req1.setHeader('Authorization', authorizationHeader);
req1.setEndpoint('https://osbdev-ha.ncr.com/ext/EA/NSC/Services/NSCOrderHeaderUpdatePS?wsdl');
res1 = h.send(req1);
system.debug('@@@@@Response'+res1);
return res1;

}*/
    
}