force-app/main/default/objects/Marketing_Concierge__c/Marketing_Concierge__c.object-meta.xml
<CustomObject>
    <label>Marketing Concierge</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Marketing Concierge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Concierges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Concierge__c/fields/Partner_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Partner_Email_Address__c</fullName>
    <label>Partner Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Marketing_Concierge__c/fields/Partner_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Partner_Phone_Number__c</fullName>
    <label>Partner Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Marketing_Concierge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarketingConciergeTriggerTest.cls
@isTest
private class MarketingConciergeTriggerTest{

    static testmethod  void MarketingConciergeTest() {
            Test.startTest(); //denote testing context
            Marketing_Concierge__c mc = new Marketing_Concierge__c();
            mc.Partner_Email_Address__c ='abc@xyz.com';
            mc.Partner_Phone_Number__c ='999999';
            Insert mc;
            mc.Status__c = 'Approved';
            Update mc;
        	system.assertEquals(mc.Status__c,'Approved');
            Test.stopTest(); //rev
     
    }
   }