force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <description>Contains all of the applicable NCR sales organizations</description>
    <label>Sales Org</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/Corporate_Name__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Name__c</fullName>
    <description>RoR sales org code name from Trident</description>
    <label>Corporate Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Functional_Group__c.field-meta.xml
<CustomField>
    <fullName>Functional_Group__c</fullName>
    <label>Functional Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Hierarchy_10__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_10__c</fullName>
    <label>Hierarchy 10</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Hierarchy_3__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_3__c</fullName>
    <label>Hierarchy 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Hierarchy_4__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_4__c</fullName>
    <label>Hierarchy 4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Hierarchy_7__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_7__c</fullName>
    <label>Hierarchy 7</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Is_Active_in_RoR__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_in_RoR__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active in RoR?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/RoR_Update_Date__c.field-meta.xml
<CustomField>
    <fullName>RoR_Update_Date__c</fullName>
    <description>Date this record was updated by the interface</description>
    <label>RoR Update Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Solution_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Solution_Portfolio__c</fullName>
    <label>Offer Portfolio</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/Sales_Org_Temp__c.object-meta.xml
<CustomObject>
    <description>This Objects receives the data from iPaaS.</description>
    <label>Sales Org Temp</label>
    <nameField>
        <label>Sales Org Temp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Temps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Corporate_Name__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Name__c</fullName>
    <description>RoR sales org code name from DRM</description>
    <label>Corporate Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Hierarchy_1__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_1__c</fullName>
    <label>Hierarchy 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Hierarchy_2__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_2__c</fullName>
    <label>Hierarchy 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Hierarchy_5__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_5__c</fullName>
    <label>Hierarchy 5</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Hierarchy_6__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_6__c</fullName>
    <label>Hierarchy 6</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Hierarchy_8__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_8__c</fullName>
    <label>Hierarchy 8</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Hierarchy_9__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_9__c</fullName>
    <label>Hierarchy 9</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Is_Active_in_RoR__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_in_RoR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active in RoR?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/fields/Org_Code_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Org_Code_Country_Code__c</fullName>
    <label>Org Code Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Org_Temp__c/fields/RoR_Update_Date__c.field-meta.xml
<CustomField>
    <fullName>RoR_Update_Date__c</fullName>
    <label>RoR Update Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/updateSalesOrgTableTest.cls
/*
####################################################################################################################
# Project Name..........: NSC CRM 2016                                                                                                                            
# File............................:updateSalesOrgTableTest.cls                                                             
# Created by................: Mudasir Rashid                                                                       
# Created Date...........: 23-12-2016                                                                                  
# Last Modified by......: Mudasir Rashid                                                                             
# Last Modified Date..: 23-12-2016                                                                                 
# Description...............: This is the test class of trigger updateSalesOrgTable.trigger
# Jira Story Number.........: NSCI_AGILE-2810   
####################################################################################################################
*/
@isTest
Private Class updateSalesOrgTableTest{
    Private static testmethod void myTest(){
        Sales_Org_Temp__c  sotemp =new Sales_Org_Temp__c();
            sotemp.Name = 'Test';
            sotemp.Sales_Org_Code__c = '123456789';
            sotemp.Corporate_Name__c  = 'Test';
            sotemp.Functional_Group__c = 'Test';
            sotemp.Org_Code_Country_Code__c = 'US';
            sotemp.RoR_Update_Date__c = system.today();
            sotemp.Is_Active_in_RoR__c = true;
            sotemp.solution_Portfolio__c = 'RT';
            sotemp.Hierarchy_1__c = 'Test Hierarchy';
            sotemp.Hierarchy_2__c = 'Test Hierarchy';
            sotemp.Hierarchy_3__c = 'Test Hierarchy';
            sotemp.Hierarchy_4__c = 'Test Hierarchy';
            sotemp.Hierarchy_5__c = 'Test Hierarchy';
            sotemp.Hierarchy_6__c = 'Test Hierarchy';
            sotemp.Hierarchy_7__c = 'Test Hierarchy';
            sotemp.Hierarchy_8__c = 'Test Hierarchy';
            sotemp.Hierarchy_9__c = 'Test Hierarchy';
            sotemp.Hierarchy_10__c = 'Test Hierarchy';
            insert sotemp;
            
          Sales_Org_Temp__c  sotemp2 = [Select Id,Corporate_Name__c,Functional_Group__c,Org_Code_Country_Code__c,RoR_Update_Date__c,Sales_Org_Code__c,Solution_Portfolio__c,Hierarchy_1__c,Hierarchy_2__c,Hierarchy_3__c,Hierarchy_4__c,Hierarchy_5__c,Hierarchy_6__c,Hierarchy_7__c,Hierarchy_8__c,Hierarchy_9__c,Hierarchy_10__c from Sales_Org_Temp__c  where Sales_Org_Code__c = :sotemp.Sales_Org_Code__c ];
            sotemp2.Corporate_Name__c  = 'Test2';
            sotemp2.Functional_Group__c = 'Test2';
            sotemp2.Org_Code_Country_Code__c = 'CA';
            sotemp2.RoR_Update_Date__c = system.today();
            sotemp2.Is_Active_in_RoR__c = true;
            sotemp2.solution_Portfolio__c = 'FN';
            sotemp2.Hierarchy_1__c = 'Test Hierarchy1';
            sotemp2.Hierarchy_2__c = 'Test Hierarchy2';
            sotemp2.Hierarchy_3__c = 'Test Hierarchy3';
            sotemp2.Hierarchy_4__c = 'Test Hierarchy4';
            sotemp2.Hierarchy_5__c = 'Test Hierarchy5';
            sotemp2.Hierarchy_6__c = 'Test Hierarchy6';
            sotemp2.Hierarchy_7__c = 'Test Hierarchy7';
            sotemp2.Hierarchy_8__c = 'Test Hierarchy8';
            sotemp2.Hierarchy_9__c = 'Test Hierarchy9';
            sotemp2.Hierarchy_10__c = 'Test Hierarchy10';
            update sotemp2;
        
        Sales_Org__c salesOrgObj = [select id,solution_Portfolio__c from Sales_Org__c limit 1];
        System.assert(salesOrgObj.solution_Portfolio__c=='FN');
    }
}