force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <description>Contains all of the applicable NCR sales organizations</description>
    <label>Sales Org</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/Is_Active_in_RoR__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_in_RoR__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active in RoR?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalculateRegionHierarchyTest.cls
/*
##################################################################################################
# Project Name..........: Sales Reporting                                                                     
# File..................: CalculateRegionHierarchyTest.cls                                                        
# Version...............: 41.0 
# Created by............: Ravikant Maurya                                                                   
# Created Date..........: 15-01-2018                                                                               
# Last Modified by......: Ravikant Maurya
# Last Modified Date....: 15-01-2018 
# Description...........: The test class is written to test the CalculateRegionHierarchy Trigger.
################################################################################################
*/
@isTest
public class CalculateRegionHierarchyTest {
     static testMethod void runUnitTest() {
         String orgId = UserInfo.getOrganizationId();
    String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
    Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
    String uniqueName = orgId + dateString + randomInt;
         Sales_Org__c s = new Sales_Org__c(name = 'test org', Is_Active_in_RoR__c = true, Sales_Org_Code__c='126232');
         insert s;
         
         String profileName = '04 NSC UI Administrator';
         Profile userProfile;
         List<Profile> profiles = [SELECT Id, Name FROM Profile WHERE Name =: profileName LIMIT 1];
            if (profiles.size() > 0) {
               userProfile = profiles[0];
            }
         String usrname = uniqueName + '@test' + orgId + '.org';
         User us              =  new User();
         us.Profileid         = userProfile.Id;
         us.Username          = usrname;
         us.Email             = usrname;
         us.Alias             = 'alias';           
         us.FirstName         = 'Fname';
         us.LastName          = 'lname';
         us.LocaleSidKey      = 'ar';
         us.LanguageLocaleKey = 'de';
         us.TimeZoneSidKey    = 'Africa/Cairo';
         us.EmailEncodingKey  = 'Big5';
         us.CurrencyIsoCode   = 'AUD';
         us.Quicklook_ID__c   = 'sm25066';
         us.Sales_Org_Code__c   = '126232';    
         insert us;
         
         User u = [select id from user where Username = :usrname ];
         System.assert(u.Id!=null);
     }    
}