force-app/main/default/objects/Sales_Org__c/Sales_Org__c.object-meta.xml
<CustomObject>
    <description>Contains all of the applicable NCR sales organizations</description>
    <label>Sales Org</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Org__c/fields/Is_Active_in_RoR__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_in_RoR__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active in RoR?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Org__c/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tableau__c/Tableau__c.object-meta.xml
<CustomObject>
    <description>This object will contain all the roles id in salesforce and list of users who have access to these roles</description>
    <label>Tableau RLS Query</label>
    <nameField>
        <displayFormat>TRLS-{00000}</displayFormat>
        <label>Tableau Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tableau RLS Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tableau__c/fields/RoleID__c.field-meta.xml
<CustomField>
    <fullName>RoleID__c</fullName>
    <label>Role ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tableau_SalesOrg__c/Tableau_SalesOrg__c.object-meta.xml
<CustomObject>
    <label>Tableau_SalesOrg</label>
    <nameField>
        <displayFormat>TSOrg-{0000000}</displayFormat>
        <label>Auto-Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tableau_SalesOrgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tableau_SalesOrg__c/fields/SalesOrgID__c.field-meta.xml
<CustomField>
    <fullName>SalesOrgID__c</fullName>
    <label>SalesOrgID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TableauSubRoleIDs__c/TableauSubRoleIDs__c.object-meta.xml
<CustomObject>
    <label>Tableau Sub Role ID</label>
    <nameField>
        <displayFormat>SUBROLEID-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tableau Sub Role IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TableauSubRoleIDs__c/fields/RoleID__c.field-meta.xml
<CustomField>
    <fullName>RoleID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Role ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TableauUser__c/TableauUser__c.object-meta.xml
<CustomObject>
    <description>Object contains list of users who have access to tableau</description>
    <label>Tableau User</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Tableau User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tableau Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TableauUser__c/fields/IfSFDCUser__c.field-meta.xml
<CustomField>
    <fullName>IfSFDCUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>If SFDC User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/InteractorPublisher__c.field-meta.xml
<CustomField>
    <fullName>InteractorPublisher__c</fullName>
    <label>Interactor/Publisher</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interactor</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If User is active in Tableau and have access to workbooks</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/OwnershipAccess__c.field-meta.xml
<CustomField>
    <fullName>OwnershipAccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OwnershipAccess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/RoleID__c.field-meta.xml
<CustomField>
    <fullName>RoleID__c</fullName>
    <formula>TableauRLSQuery__r.RoleID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Role ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/RoleLevelAccess__c.field-meta.xml
<CustomField>
    <fullName>RoleLevelAccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RoleLevelAccess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/SalesOrgAccess__c.field-meta.xml
<CustomField>
    <fullName>SalesOrgAccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SalesOrg Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/TRole1__c.field-meta.xml
<CustomField>
    <fullName>TRole1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>T_Role1</label>
    <referenceTo>Tableau__c</referenceTo>
    <relationshipLabel>Tableau Users (T_Role1)</relationshipLabel>
    <relationshipName>Tableau_Users1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/TRole2__c.field-meta.xml
<CustomField>
    <fullName>TRole2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>T_Role2</label>
    <referenceTo>Tableau__c</referenceTo>
    <relationshipLabel>Tableau Users (T_Role2)</relationshipLabel>
    <relationshipName>Tableau_Users2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/TRole3__c.field-meta.xml
<CustomField>
    <fullName>TRole3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>T_Role3</label>
    <referenceTo>Tableau__c</referenceTo>
    <relationshipLabel>Tableau Users (T_Role3)</relationshipLabel>
    <relationshipName>Tableau_Users3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/User18digitID__c.field-meta.xml
<CustomField>
    <fullName>User18digitID__c</fullName>
    <label>User 18 digit ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauUser__c/fields/UserQlookID__c.field-meta.xml
<CustomField>
    <fullName>UserQlookID__c</fullName>
    <label>User Qlook ID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/TableauWorkbookURL__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TableauWorkbookURL</label>
</CustomObject>

force-app/main/default/objects/TableauWorkbookURL__c/fields/TableauServerAddress__c.field-meta.xml
<CustomField>
    <fullName>TableauServerAddress__c</fullName>
    <label>Tableau Server Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/VisualforcePageURL__c.field-meta.xml
<CustomField>
    <fullName>VisualforcePageURL__c</fullName>
    <label>VisualforcePageURL</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook1Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook1Name__c</fullName>
    <label>Workbook_1_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook1URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook1URL__c</fullName>
    <label>Workbook_1_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook2Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook2Name__c</fullName>
    <label>Workbook_2_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook2URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook2URL__c</fullName>
    <label>Workbook_2_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook3Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook3Name__c</fullName>
    <label>Workbook_3_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook3URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook3URL__c</fullName>
    <label>Workbook_3_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook4Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook4Name__c</fullName>
    <label>Workbook_4_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook4URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook4URL__c</fullName>
    <label>Workbook_4_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook5Name__c.field-meta.xml
<CustomField>
    <fullName>Workbook5Name__c</fullName>
    <label>Workbook_5_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TableauWorkbookURL__c/fields/Workbook5URL__c.field-meta.xml
<CustomField>
    <fullName>Workbook5URL__c</fullName>
    <label>Workbook_5_URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Org_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Code__c</fullName>
    <label>Sales Org Code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_Tableau_QueryObject.cls
@isTest(SeeAllData=false)
public class Test_Tableau_QueryObject{
    
    /* ########################################################################################################## */ 
    public static String CRON_EXP = '0 0 0 15 8 ? 2023';
    
    @testSetup 
    static void create_tableau_Records(){
        
        Test.startTest();
        ID currentuserroleid =  UserInfo.getUserRoleId() ;
        
        //create tableau sub-roleid object object
        TableauSubRoleIDs__c tsrls = new TableauSubRoleIDs__c() ;
        tsrls.RoleID__c = currentuserroleid ;
        insert tsrls ;
        
        //create tableau rls query object
        Tableau__c trls = new Tableau__c() ;
        trls.RoleID__c = currentuserroleid ;
        insert trls ;
        //create tableau user object object
        TableauUser__c tableauuserobject = new TableauUser__c() ;
        tableauuserobject.UserQlookID__c = 'sk250817' ;
        tableauuserobject.InteractorPublisher__c = 'Interactor' ; 
        tableauuserobject.IfSFDCUser__c= True ;
        tableauuserobject.IsActive__c= True ;   
        tableauuserobject.TRole1__c = trls.id ;
        tableauuserobject.TRole2__c = trls.id ;
        tableauuserobject.TRole3__c = trls.id ;
        tableauuserobject.OwnershipAccess__c = true ;
        tableauuserobject.RoleLevelAccess__c = true ;
        tableauuserobject.SalesOrgAccess__c = true ;
        tableauuserobject.User18digitID__c = userInfo.getUserId() ;
        insert tableauuserobject ;
        
        //create tableau sub role id object
        Sales_Org__c salesorg = new Sales_Org__c(name = 'sk250817', Is_Active_in_RoR__c = true, Sales_Org_Code__c='126232');
        insert salesorg;
        Tableau_SalesOrg__c tsorls = new Tableau_SalesOrg__c();
        tsorls.SalesOrgID__c = salesorg.id ;
        insert tsorls;
    }
    @isTest 
    static void update_tableauRecords(){
        ID currentuserroleid =  UserInfo.getUserRoleId() ;
        ID SalesOrgId = [select id from Sales_Org__c where name=:'sk250817'].id ;
        TableauSubRoleIDs__c tsrls = [select id,RoleID__c from TableauSubRoleIDs__c where RoleID__c =: currentuserroleid];
        Tableau__c trls = [select id,RoleID__c from Tableau__c where RoleID__c =: currentuserroleid];
        TableauUser__c tableauuserobject = [select id,SalesOrgAccess__c from TableauUser__c  ];
        System.assertEquals(tableauuserobject.id!=null, true);
        Tableau_SalesOrg__c tsorls = [select id,SalesOrgID__c from Tableau_SalesOrg__c where SalesOrgID__c=: SalesOrgId];
        
        // update above objects statements
        tableauuserobject.SalesOrgAccess__c = false; 
        update tableauuserobject;
        update tsrls ;
        update trls ;
        update tsorls;

    }
    @isTest
    static void test_pageControllers(){
        
        ID currentuserroleid =  UserInfo.getUserRoleId() ;
        
        TableauSubRoleIDs__c tsrls = [select id from TableauSubRoleIDs__c where RoleID__c =: currentuserroleid];
        System.assertEquals(tsrls.id!=null, true);
        Tableau__c trls = [select id from Tableau__c where RoleID__c =: currentuserroleid];
        TableauUser__c tableauuserobject = [select id,SalesOrgAccess__c from TableauUser__c  ];
        // Tableau_SalesOrg__c tsorls = [select id,SalesOrgID__c from Tableau_SalesOrg__c where salesorg.id];
        
        
        Test.startTest();
        //test case for tableau admin screen
        Controller_Tableau_Admin_Page.checkaccess(); 
        Controller_Tableau_Admin_Page.cgetusertable(); 
        Controller_Tableau_Admin_Page.cgetroletable(); 
        Controller_Tableau_Admin_Page.cgetsaleorgtable(); 
        //Controller_Tableau_Admin_Page.ctableauuserreadonly();
        //Controller_Tableau_Admin_Page.cgetroledetails();
        Controller_Tableau_Admin_Page.searchsalesorgg('sk250817');
        Controller_Tableau_Admin_Page.gettabuser('sk250817'); 
        Controller_Tableau_Admin_Page.validateifuserexist('sk250817');
        Controller_Tableau_Admin_Page.validateifuserexist('sk250820');
        Controller_Tableau_Admin_Page.checkifuserisfdc('sk250817'); 
        Controller_Tableau_Admin_Page.checkifuserisfdc('sk250820'); 
        Controller_Tableau_Admin_Page.getrolename(''); 
        Controller_Tableau_Admin_Page.gettuserrecord(tableauuserobject.id); 
        Controller_Tableau_Admin_Page.udpdatetabrecord(tableauuserobject);
        Controller_Tableau_Admin_Page.createtabrecord(new TableauUser__c(UserQlookID__c = 'sk250819',InteractorPublisher__c = 'Interactor',IfSFDCUser__c= True,IsActive__c= True,RoleLevelAccess__c = true));
        Controller_Tableau_Admin_Page.createtabrecordd('sk250818','sk250818',false,false,true,true,true,'interactor',trls.id,trls.id,trls.id);
        
        List<STRING> st = new LIST<STRING>();st.add('sk250818');
        Controller_Tableau_Admin_Page_Batch.roleidset_updateroleidset();
        Controller_Tableau_Admin_Page_Batch.update_sub_role_id(st);
        //Controller_Tableau_Admin_Page_Batch.update_role_id(st);
        Controller_Tableau_Admin_Page_Batch.returnsize(st);
        Controller_Tableau_Admin_Page_Batch.updateallsubrole(st);
        Controller_Tableau_Admin_Page_Batch.updateallrole(st);
        
         //test method for executing the batch classes
        Tableau_Batch_GenScript oSCR = new Tableau_Batch_GenScript();
        Database.executeBatch(oSCR);
        
        
        Test.StopTest();
        
        
    }
    /* ########################################################################################################## */ 
    @isTest
    static void test_batches(){
        
        ID currentuserroleid =  UserInfo.getUserRoleId() ;
        
        TableauSubRoleIDs__c tsrls = [select id from TableauSubRoleIDs__c where RoleID__c =: currentuserroleid];
        Tableau__c trls = [select id from Tableau__c where RoleID__c =: currentuserroleid];
        
        TableauUser__c tableauuserobject = [select id,SalesOrgAccess__c from TableauUser__c];
        
     
        Test.startTest(); 
        String jobId = System.schedule('ScheduledApexTest',
                                       CRON_EXP, new Tableau_Scheduler()); 
     
        // test method for executing the batch classes
        Tableau_Batch_getNewRole nSCR = new Tableau_Batch_getNewRole();
        Database.executeBatch(nSCR,1);
       
        Test.StopTest();
        
        
        
    }
    /* ########################################################################################################## */   
    static testMethod void test_controller_tableau_uipage(){
        TableauWorkbookURL__c testobj =new TableauWorkbookURL__c ();
        
        testobj.TableauServerAddress__c = '';
        testobj.VisualforcePageURL__c = '';
        testobj.Workbook1Name__c = '';
        testobj.Workbook2Name__c = '';
        testobj.Workbook3Name__c = '';
        testobj.Workbook4Name__c = '';
        testobj.Workbook5Name__c = '';
        
        testobj.Workbook1URL__c = '';
        testobj.Workbook2URL__c = '';
        testobj.Workbook3URL__c = '';
        testobj.Workbook4URL__c = '';
        testobj.Workbook5URL__c = '';
       
        
        insert testobj;
        
        Test.startTest();
        
        PageReference myVfPage = Page.Tableau_Workbooks_HomePage;
         System.assertEquals(myVfPage!=Null, True);
        Test.setCurrentPage(myVfPage);
        System.currentPageReference().getParameters().put('id',testobj.id);
        Tableaupagecontroller testController = new Tableaupagecontroller();
        
        // test method for executing the batch classes
        Tableau_Batch_GenRoleId uSCR = new Tableau_Batch_GenRoleId();
        Database.executeBatch(uSCR);
        
        Test.StopTest();
        /* ########################################################################################################## */ 
    }
}