force-app/main/default/objects/EBDEDDSetting__c/EBDEDDSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Turning Feature it EDSD to keep readonly and changing schedule with change in Close Date</description>
    <label>EBDEDDSetting</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Are_we_the_Incumbent__c.field-meta.xml
<CustomField>
    <fullName>Are_we_the_Incumbent__c</fullName>
    <label>Are we the Incumbent?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Yes, exclusive</fullName>
            </value>
            <value>
                <fullName>Yes, multi-vendor</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CLM_Sales_Acknowledgment__c.field-meta.xml
<CustomField>
    <fullName>CLM_Sales_Acknowledgment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CLM Sales Acknowledgment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closed_Lost_Comments__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Comments__c</fullName>
    <label>Closed Lost Comments</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Delivery_Date__c</fullName>
    <label>Expected Delivery Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lose_to_a_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Lose_to_a_Competitor__c</fullName>
    <label>Lose to a Competitor?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Variance__c.field-meta.xml
<CustomField>
    <fullName>Price_Variance__c</fullName>
    <inlineHelpText>Enter the selection that best represents NCR&apos;s price compared to the competitors involved in this opportunity</inlineHelpText>
    <label>Price Variance</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>NCR above 5%</fullName>
            </value>
            <value>
                <fullName>NCR within 5%</fullName>
            </value>
            <value>
                <fullName>NCR under 5%</fullName>
            </value>
            <value>
                <fullName>Unknown/Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Loss_Reason__c</fullName>
    <label>Primary Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lose_to_a_Competitor__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>HW Lead Times</fullName>
            </value>
            <value>
                <fullName>Solution Differentiation</fullName>
            </value>
            <value>
                <fullName>Relationship Health</fullName>
            </value>
            <value>
                <fullName>Support Quality</fullName>
            </value>
            <value>
                <fullName>Price Sensitivity</fullName>
            </value>
            <value>
                <fullName>Migration Simplicity</fullName>
            </value>
            <value>
                <fullName>Lost Funding</fullName>
            </value>
            <value>
                <fullName>Project Cancelled not due to Funding</fullName>
            </value>
            <value>
                <fullName>Merger/Acquisition/Divestiture</fullName>
            </value>
            <value>
                <fullName>Qualified Out by NCR</fullName>
            </value>
            <value>
                <fullName>Non Responsive</fullName>
            </value>
            <value>
                <fullName>Opportunity created in error or Administrative purposes</fullName>
            </value>
            <value>
                <fullName>Not Ready to Upgrade</fullName>
            </value>
            <value>
                <fullName>Potential of Closing</fullName>
            </value>
            <value>
                <fullName>Quote Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Type__c</fullName>
    <label>Primary Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HW</fullName>
            </value>
            <value>
                <fullName>SW</fullName>
            </value>
            <value>
                <fullName>PS</fullName>
            </value>
            <value>
                <fullName>TS</fullName>
            </value>
            <value>
                <fullName>HWM</fullName>
            </value>
            <value>
                <fullName>SWM</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Managed Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Quicklook_ID__c.field-meta.xml
<CustomField>
    <fullName>Quicklook_ID__c</fullName>
    <externalId>true</externalId>
    <label>Quicklook ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Test_PS_ChangeSchedule.cls
/****************************************************************************************************************
//Name          :   Test_PS_ChangeSchedule.cls
//Author        :   Mudit Saxena
//Date          :   2 March 2017
//Version       :   Initial
//Description   :   This is test class for trigger "PS_ChangeSchedule".
****************************************************************************************************************/
@isTest
private class Test_PS_ChangeSchedule{
    public static testMethod void runUnitTest() {
       
        EBDEDDSetting__c ebdedd = new EBDEDDSetting__c();
        ebdedd.Name = 'EDSD_Calc';
        ebdedd.isActive__c = true;
        insert ebdedd; 
        System.assertNotEquals(ebdedd.id, null,'ebdedd List Should not be null');
        //Admin User
            User u1 = new User(alias = 'standt', email='standarduser2@ncr.com',
                emailencodingkey='UTF-8', lastname='Testing1',Quicklook_Id__c='AdmProfl', languagelocalekey='en_US',
                localesidkey='en_US', profileid = NSCCommonInfoUtil.getIdOf('NSC_Admin_04_UI_Profile'),timezonesidkey='America/Los_Angeles',
                username='standarduser2@ncr.com'+System.now().getTime()+'.com'); 
        system.runas(u1){ 
            opportunity opp = TestRecordsFactory.createOpportunityWithLineItemSchedule();        
           //opp.Expected_Delivery_Date__c = System.TODAY().addDays(90);
            opp.closeDate = Date.valueOf('2019-04-20');
            update opp;
            //Boolean check = Recursionblocker.flag;
            //opp.closeDate = System.TODAY().addMonths(5);    
            //update opp;
        }
    }
    
     public static testMethod void runUnitTest1() {
       
        
       
       opportunity opp = TestRecordsFactory.createOpportunityWithLineItemSchedule();        
        //opp.Expected_Delivery_Date__c = System.TODAY().addDays(90);
        opp.closeDate = Date.valueOf('2018-08-20');
        opp.stagename = 'Closed/Lost';
        opp.Price_Variance__c = 'NCR above 5%';
         opp.Are_we_the_Incumbent__c='NO';
         opp.Closed_Lost_Comments__c='Test';
         opp.Lose_to_a_Competitor__c='Test';
         opp.CLM_Sales_Acknowledgment__c=true;
         opp.Primary_Loss_Reason__c='Test';
         opp.Primary_Product_Type__c='HW';
        update opp; 
        System.assertNotEquals(opp.id, null,'Opp List Should not be null');
        
        
    }
}