force-app/main/default/objects/Attachment__c/Attachment__c.object-meta.xml
<CustomObject>
    <label>Attachment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment__c/fields/Engineer_Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Attachment_Type__c</fullName>
    <label>Engineer Attachment Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment__c/fields/Engineers__c.field-meta.xml
<CustomField>
    <fullName>Engineers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineers</label>
    <referenceTo>Engineers__c</referenceTo>
    <relationshipName>Engineer_Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engineers__c/Engineers__c.object-meta.xml
<CustomObject>
    <description>For NCR Partner Channel - Partner Portal.  Will track all partner engineers and registrations.</description>
    <label>Engineer</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Engineers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Engineers__c/fields/Active_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Active_Engineer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Engineer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <defaultValue>null</defaultValue>
    <label>First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Portal Access Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engineers__c/fields/Type_of_Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Portal_Access__c</fullName>
    <label>Request for</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diagnostics</fullName>
            </value>
            <value>
                <fullName>Portal Access</fullName>
                <default>true</default>
                <label>Portal Access</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UploadAttachmentControllerLtngTest.cls
@isTest
private class UploadAttachmentControllerLtngTest {

    static testMethod void testUploadAttachmentControllerLtng() {
       	Engineers__C eng = new Engineers__C();
    	eng.First_name__c ='ABC';
	    eng.Last_Name__c ='XYZ';
	    eng.Active_Engineer__c =true;
	    eng.Email_Address__c ='xyz@ncr.com';
	    eng.City__c='noWhere';
	    eng.Type_of_Portal_Access__c ='Portal Access';
	    eng.Status__c = 'Created';
	    insert eng;
	    
	    Attachment__c obj1 = new Attachment__c();
        obj1.Engineer_Attachment_Type__c='IPP Order Form';
        obj1.Engineers__c =eng.id;
        insert obj1;
        
        ApexPages.currentPage().getParameters().put('id', eng.Id);
        
        
        UploadAttachmentControllerLtng controller = new UploadAttachmentControllerLtng();
        controller.fileBody = Blob.valueOf('Test body');
        controller.fileName = 'test';
        controller.selectedType = 'IPP Order Form';
        controller.processUpload();
        controller.back();
        system.assertEquals(controller.message,'File uploaded successfully.');
        UploadAttachmentControllerLtng controller1 = new UploadAttachmentControllerLtng();
     
        controller1.selectedType = 'IPP Order Form';
        controller1.processUpload();
              
    }
}