force-app/main/default/objects/Attachment__c/Attachment__c.object-meta.xml
<CustomObject>
    <label>Attachment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <label>Attachment Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetUploadAttachmentController.cls
public with sharing class GetUploadAttachmentController {

  
    
    public String fileName {get;set;}
    public  transient Blob fileBody {get;set;}
    public Id recordId;
    
    
     public GetUploadAttachmentController () {
          //Changes done by Yogesh - EBA_SF-1732
       // recordId=  ApexPages.currentPage().getParameters().get('id');
          recordId = String.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('id')); 
          System.debug('recordid'+ recordId);
         //End Changes 
     }

    
    // creates a new Engineer_Attachment__c record
    private Database.SaveResult saveCustomAttachment() {
      Attachment__c obj = new Attachment__c();
        obj.Case__c= recordId;
           
        
        // fill out cust obj fields
        return Database.insert(obj);
        }
    
    // create an actual Attachment record with the Contact_Attachment__c as parent
    private Database.SaveResult saveStandardAttachment(Id recordId) {
        Database.SaveResult result;
        Attachment attachment = new Attachment();
        attachment.body = this.fileBody;
        attachment.name = this.fileName;
        attachment.parentId = recordId;
        // inser the attahcment
        result = Database.insert(attachment);
        // reset the file for the view state
        fileBody = Blob.valueOf(' ');
        return result;
    }
    
    /**
    * Upload process is:
    *  1. Insert new Engineer_Attachment__c record
    *  2. Insert new Attachment with the new Engineer_Attachment__c record as parent
    *  3. Update the Engineer_Attachment__c record with the ID of the new Attachment
    **/
    public PageReference processUpload() {
     //   try {
            Database.SaveResult customAttachmentResult = saveCustomAttachment();
        
            if (customAttachmentResult == null || !customAttachmentResult.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Could not save attachment.'));  return null;
            }
            
            System.debug('--->'+customAttachmentResult.getId());
            
        
            Database.SaveResult attachmentResult = saveStandardAttachment(customAttachmentResult.getId());
        
            if (attachmentResult == null || !attachmentResult.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Could not save attachment.'));  return null;
            } else {
                // update the custom attachment record with some attachment info
                Attachment__c customAttachment = [select id from Attachment__c where id = :customAttachmentResult.getId()];
                customAttachment.Attachment_Name__c = this.fileName;
                customAttachment.Attachment__c = attachmentResult.getId();
                update customAttachment;
            }
        
      /*  } catch (Exception e) {
            ApexPages.AddMessages(e);
            return null;
        } */
        
       
        return new PageReference('/'+recordId );
    }
    
    public PageReference back() {
        return new PageReference('/'+recordId );
    }   

}