force-app/main/default/objects/Attachment__c/Attachment__c.object-meta.xml
<CustomObject>
    <label>Attachment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attachment__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attachment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetHelpInlineMessageController.cls
public with sharing class GetHelpInlineMessageController 
{
    public Boolean isDisplayAttachment {get;set;}
    
    public GetHelpInlineMessageController(ApexPages.StandardController stdController)
    {
        isDisplayAttachment = false; 
        System.debug('-------------------stdController.getId()---------------'+stdController.getId());
        List<Attachment__c> lstAttachment = [Select Id, CreatedDate from Attachment__c where Case__c =: stdController.getId() order by CreatedDate desc limit 1];
        
        System.debug('---------------lstAttachment------------'+lstAttachment);
        if(!lstAttachment.isEmpty())
        {
            System.debug('---------------(Datetime.now().getTime() - lstAttachment[0].CreatedDate.getTime())------------'+(Datetime.now().getTime() - lstAttachment[0].CreatedDate.getTime()));
            System.debug('---------------(Datetime.now().getTime() - lstAttachment[0].CreatedDate.getTime())/ 1000----'+((Datetime.now().getTime() - lstAttachment[0].CreatedDate.getTime())/ 1000));
            Decimal sec = (Datetime.now().getTime() - lstAttachment[0].CreatedDate.getTime())/ 1000;
            
            isDisplayAttachment = sec <= 6.0;
        }                   
    }
    
}